const fs=require('fs'),assert=require('assert/strict'),I=require('../../assets/coach-intake.js'),Q=require('../../assets/coach-programming-v4.js'),cases=require('./cases.cjs');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const rows=[],out=__dirname+'/results';fs.mkdirSync(out,{recursive:true});const check=(n,v)=>{assert(v,n);rows.push(n);};
const training=cases.B.training,proposal={schema_version:1,name:'Basic · rutina inicial',description:Q.instruction(training),days:training.weekdays.map((id,i)=>({name:I.weekdays.find(d=>d.id===id).label,exercises:(i%2?['db_rdl','knee_pushup','dead_bug']:['goblet','db_row','floor_press']).map(id=>({name:Q.byId.get(id).name,sets:2,reps_min:8,reps_max:10,rir:3,rest_seconds:60}))}))};
(async()=>{for(const engine of ['chromium','webkit']){const browser=await(engine==='chromium'?chromium:webkit).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});const p=await browser.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));try{
 await p.goto('http://127.0.0.1:4198/demo',{waitUntil:'domcontentloaded',timeout:30000});await p.waitForFunction(()=>window.previewReady);
 await p.evaluate(({proposal,training})=>{window.qualityFixture={proposal,training};coachShell(coachProposalMarkup(proposal,'basic-initial-v4')+reviewerProgramming({proposal,prompt_version:'basic-initial-v4'},training));},{proposal,training});
 check(engine+' deterministic per-side label',await p.locator('.coach-day').filter({hasText:'Remo con mancuerna'}).first().textContent().then(s=>s.includes('reps por lado')));
 check(engine+' reviewer hamstrings, secondary and warning visible',await p.locator('.coach-quality').textContent().then(s=>s.includes('Femorales')&&s.includes('participación secundaria')&&s.includes('series directas')));
 check(engine+' legacy markup unaltered by v4 labels',await p.evaluate(()=>!coachProposalMarkup(qualityFixture.proposal,'basic-initial-v3').includes('por lado')));
 for(const width of [320,360,390,430,1280])for(const theme of ['light','dark']){await p.setViewportSize({width,height:844});await p.evaluate(t=>simpleTheme.set(t),theme);await p.waitForTimeout(180);check(engine+' '+width+' '+theme+' content fits',await p.locator('#coachDialog').evaluate(d=>d.scrollWidth<=d.clientWidth+1));if(engine==='chromium'&&[390,1280].includes(width))await p.screenshot({path:out+'/quality-'+width+'-'+theme+'.png'});}
 await p.evaluate(()=>{simpleCoach.granted=true;coachStartQuestionnaire();simpleCoach.wizard.step=6;coachRenderQuestionnaire();});check(engine+' exclusions clarification',await p.locator('#coachForm').textContent().then(t=>t.includes('Excluir este ejercicio no excluye automáticamente otras variantes.')));
 check(engine+' no new browser errors',errors.length===0);
 }finally{await browser.close();}}fs.writeFileSync(out+'/quality-ui.json',JSON.stringify({passed:rows.length,rows},null,2));console.log(rows.length+'/'+rows.length+' quality UI checks');})().catch(e=>{console.error(e);process.exitCode=1;});
