// Loopback-only internal preview. No private files or credentials served.
const http=require('http'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'../..'),port=Number(process.env.PREMIUM_PORT||4231),live=process.env.PREMIUM_LIVE_FIXTURE==='1';
const I=require('../../assets/coach-intake.js');let state={intake:I.emptyPremium(),row_version:1,allowed:false};
const fixture=live?JSON.parse(fs.readFileSync(path.join(__dirname,'private/fixture.json'))):null;
const sessions=live?JSON.parse(fs.readFileSync(path.join(__dirname,'private/sessions.json'))):null;
const type={'.js':'application/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'};
async function rpc(name,args){if(!fixture||fixture.ref!=='dmqjexigdnfzobarhnib')throw Error('Staging only');const r=await fetch('https://'+fixture.ref+'.supabase.co/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:fixture.key,Authorization:'Bearer '+sessions.mock.access_token,'Content-Type':'application/json'},body:JSON.stringify(args)});const d=await r.json();if(!r.ok)throw Error('La solicitud de staging fue rechazada ('+r.status+').');return d;}
async function read(table,query){if(!live||fixture.ref!=='dmqjexigdnfzobarhnib')throw Error('Staging only');const r=await fetch('https://'+fixture.ref+'.supabase.co/rest/v1/'+table+'?'+query,{headers:{apikey:fixture.key,Authorization:'Bearer '+sessions.mock.access_token}});if(!r.ok)throw Error('No se pudo leer la fixture ('+r.status+').');return r.json();}
http.createServer(async(req,res)=>{const u=new URL(req.url,'http://127.0.0.1');res.setHeader('Cache-Control','no-store');try{
 if(u.pathname==='/premium-api'&&req.method==='POST'){
  if(req.headers.origin!==`http://127.0.0.1:${port}`)throw Error('Origin rejected');let body='';for await(const chunk of req){body+=chunk;if(body.length>20000)throw Error('Payload too large');}const {action,data}=JSON.parse(body);let v;
  if(action==='state'){if(live){const [m]=await read('coach_mesocycles','id=eq.'+fixture.ui_mesocycle+'&select=intake,row_version');state={...state,...m};}v=state;}
  else if(action==='save'){if(I.premiumErrors(data.training,!!data.submit).length||data.expected!==state.row_version)throw Error('Revisa las respuestas o vuelve a abrir el borrador.');if(live){const r=await rpc('premium_save_intake',{p_mesocycle:fixture.ui_mesocycle,p_expected:data.expected,p_training:data.training,p_submit:!!data.submit});state={...state,intake:r.intake,row_version:r.row_version};}else state={...state,intake:structuredClone(data.training),row_version:state.row_version+1};v=state;}
  else if(action==='permission'){if(live)await rpc('premium_permission',{p_mesocycle:fixture.ui_mesocycle,p_allow:!!data.allow});state.allowed=!!data.allow;v={allowed:state.allowed};}
  else if(action==='history'){if(!state.allowed)throw Error('Falta autorización de historial.');v=live?await rpc('premium_training_history',{p_mesocycle:fixture.ui_mesocycle}):{exercises:[{name:'Remo con mancuerna',metrics:{exposures:4,trend:'reps_increasing_comparable'},exposures:[{date:'Semana reciente',sets:[{kg:20,reps:11,rir:2}]}]}]};}
  else if(action==='mesocycle'){if(live){const [m]=await read('coach_mesocycles','id=eq.'+fixture.ui_mesocycle+'&select=number,state,planned_weeks');const weeks=await read('coach_mesocycle_weeks','mesocycle_id=eq.'+fixture.ui_mesocycle+'&select=week_number,revision_id&order=week_number');const revisions=await read('routine_revisions','routine_id=eq.'+fixture.ui_routine+'&select=id,revision_no');v={...m,weeks:weeks.map(w=>({...w,revision_no:revisions.find(r=>r.id===w.revision_id)?.revision_no}))};}else v={number:1,state:'active',planned_weeks:7,weeks:Array.from({length:7},(_,i)=>({week_number:i+1,revision_no:i<3?1:2}))};}
  else if(action==='recommendations')v=live?await read('coach_recommendations','mesocycle_id=eq.'+fixture.ui_mesocycle+'&select=kind,state,facts,interpretation,patches'):[{kind:'KEEP',state:'ready',facts:['Aumentan las repeticiones con la misma carga y RIR.'],interpretation:'Mantener. Estos datos no justifican atribuir una causa.',patches:[]},{kind:'REVIEW',state:'pending_review',facts:['Solo consta una exposición.'],interpretation:'Evidencia insuficiente. Revisión humana.',patches:[]}];
  else throw Error('Action unavailable');res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(v));
 }
 if(req.method!=='GET'){res.writeHead(405);return res.end();}
 if(u.pathname==='/review'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(`<!doctype html><html lang="es"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SIMPLE Premium · Phase 1</title><style>body{margin:0;font:14px system-ui;background:#f7f5f1;color:#252929}header{padding:12px 18px}button{min-height:44px}iframe{border:0;display:block;width:100%;height:calc(100dvh - 130px)}</style><header><b>SIMPLE Premium · Phase 1</b><p>${live?'Fixture controlada en staging; sin OpenAI.':'Demostración ficticia local; sin Supabase ni OpenAI.'} Premium comercial cerrado.</p><button id="open">Abrir Premium</button></header><iframe title="SIMPLE Premium interno" src="/demo"></iframe><script>document.querySelector('#open').onclick=()=>document.querySelector('iframe').contentWindow.postMessage('premium-phase1',location.origin)</script></html>`);}
 if(u.pathname==='/demo-sdk.js'){res.setHeader('Content-Type',type['.js']);return res.end(['tests/interior/mock-sdk.js','tests/coach/demo-sdk.js','tests/coach-v2/preview-sdk.js','tests/coach-intake-v2/preview-sdk.js'].map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n'));}
 if(u.pathname==='/demo-seed.js'){res.setHeader('Content-Type',type['.js']);return res.end(fs.readFileSync(path.join(root,'tests/coach-v2/preview-seed.js')));}
 if(u.pathname==='/demo'){res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; form-action 'none'; object-src 'none'; base-uri 'none'");res.setHeader('Content-Type','text/html;charset=utf-8');let html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.115.0','/demo-sdk.js').replace('https://yvguatdqncadkwewlepe.supabase.co','https://dmqjexigdnfzobarhnib.supabase.co').replace('</head>','<link rel="stylesheet" href="/assets/coach-premium-phase1.css"></head>').replace('</body>','<script src="/demo-seed.js"></script><script src="/assets/coach-premium-phase1.js"></script></body>');return res.end(html);}
 if(!/^\/assets\/[a-zA-Z0-9._/-]+$/.test(u.pathname)||u.pathname.includes('..')){res.writeHead(404);return res.end();}const f=path.join(root,u.pathname);if(!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',type[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));
 }catch(e){res.writeHead(400,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}));}
}).listen(port,'127.0.0.1',()=>console.log('Internal '+(live?'staging fixture':'offline')+' preview http://127.0.0.1:'+port+'/review'));
