const fs=require('fs'),path=require('path'),assert=require('assert/strict');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.join(__dirname,'results'),rows=[],base=process.env.PREMIUM_PREVIEW_URL||'http://127.0.0.1:4231',live=process.env.PREMIUM_UI_LIVE==='1',readonly=process.env.PREMIUM_UI_READONLY==='1';fs.mkdirSync(out,{recursive:true});
const check=(name,pass)=>{rows.push({name,pass:!!pass});assert(pass,name);};
(async()=>{for(const engine of live?['chromium']:['chromium','webkit']){const browser=await(engine==='chromium'?chromium:webkit).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});const p=await browser.newPage({viewport:{width:390,height:844}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 try{await p.goto(base+'/review');const f=p.frameLocator('iframe');await f.locator('body').evaluate(()=>new Promise(resolve=>{const timer=setInterval(()=>{if(window.previewReady){clearInterval(timer);resolve();}},50);}));await p.locator('#open').click();await f.locator('.premium-nav').first().waitFor();
  check(engine+' unchanged Premium question title',await f.locator('#coachQuestion').textContent().then(x=>x.includes('¿Cuánto tiempo llevas entrenando')));
  await f.locator('body').evaluate(()=>{const w=simpleCoach.wizard;w.data.experience='lt6';coachRenderQuestionnaire();});check(engine+' beginner no weak points',await f.locator('body').evaluate(()=>!coachWizardSteps().includes('weak_points')));
  await f.locator('body').evaluate(()=>{const w=simpleCoach.wizard;w.data.experience='y2_4';w.data.effort='habitual';coachRenderQuestionnaire();});check(engine+' conditional weak points and confidence',await f.locator('body').evaluate(()=>coachWizardSteps().includes('weak_points')&&coachWizardSteps().includes('confidence')));
  if(!readonly){await f.locator('body').evaluate(()=>{const I=coachIntake,w=simpleCoach.wizard;w.data={...I.emptyPremium(),experience:'y2_4',pause:false,goal:'balanced',days:2,weekdays:['mon','thu'],minutes_by_day:{mon:60,thu:45},weak_points:['upper_back'],effort:'confident',confidence:'medium',activity:{type:'none',weekdays:[],minutes:null,intensity:null},recovery:'mostly',sleep:'h7_8',stress:'low',distribution:'coach',inventory:{equipment:['dumbbells','bench'],custom:[]}};w.step=coachWizardSteps().length-1;coachRenderQuestionnaire();});await f.locator('#coachNext').click();await f.locator('#premiumSubmit').click();await f.locator('#coachError').filter({hasText:'Anamnesis guardada'}).waitFor();check(engine+' review save successful',true);}
  for(const page of ['Anamnesis','Historial autorizado','Mesociclo','Recomendaciones']){
   await f.getByRole('button',{name:page,exact:true}).click();
   if(page==='Historial autorizado'){await f.locator('#premiumPermission').click();await f.getByRole('button',{name:'Revocar permiso',exact:true}).waitFor();}
   if(page==='Mesociclo')await f.locator('.premium-weeks').waitFor();
   if(live&&page==='Mesociclo')check('UI reads actual five-week mesocycle',await f.locator('.premium-weeks li').count()===5);
   if(live&&page==='Recomendaciones'){await f.locator('#coachProposal').filter({hasText:'No hay recomendaciones'}).waitFor();check('UI reads actual empty recommendation list',true);}
   for(const width of [320,390,1280])for(const theme of ['light','dark']){await p.setViewportSize({width,height:900});await f.locator('body').evaluate((body,t)=>simpleTheme.set(t),theme);await f.locator('#coachDialog').evaluate(async d=>{d.getAnimations({subtree:true}).forEach(a=>{if(a.effect.getTiming().iterations!==Infinity)a.finish();});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});
    const fit=await f.locator('#coachDialog').evaluate(d=>({fit:d.scrollWidth<=d.clientWidth+1,touch:[...d.querySelectorAll('.premium-nav button')].filter(b=>b.getClientRects().length).every(b=>b.getBoundingClientRect().height>=44),width:d.clientWidth,scroll:d.scrollWidth}));if(!fit.fit||!fit.touch){await p.screenshot({path:path.join(out,'layout-failure.png')});console.log(JSON.stringify(fit));}check(engine+' '+page+' '+width+' '+theme+' fit/touch',fit.fit&&fit.touch);
    const color=await f.locator('#coachDialog').evaluate(d=>{const bg=getComputedStyle(d).backgroundColor;return {theme:document.documentElement.dataset.theme,bg};});if(color.theme!==theme||color.bg!==(theme==='dark'?'rgb(42, 47, 45)':'rgb(255, 255, 255)'))console.log(JSON.stringify({expected:theme,actual:color}));assert(color.theme===theme&&color.bg===(theme==='dark'?'rgb(42, 47, 45)':'rgb(255, 255, 255)'),engine+' actual theme colors');
    if(engine==='chromium'&&(width===390||width===1280)){await f.locator('#coachDialog').evaluate(d=>d.scrollTop=0);await p.screenshot({path:path.join(out,(live?'live-':'')+page.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll(' ','-')+'-'+width+'-'+theme+'.png')});}
   }
  }
  await f.getByRole('button',{name:'Historial autorizado',exact:true}).click();await f.locator('#premiumPermission').click();await f.getByRole('button',{name:'Autorizar historial',exact:true}).waitFor();check(engine+' revocation feedback persists',await f.locator('#premiumHistory').textContent().then(s=>s.includes('Sin permiso')));
  check(engine+' no payment or model action',await f.locator('#coachDialog').textContent().then(s=>!s.includes('12,99')&&!s.includes('Enviar y generar propuesta')));
  if(!live){let release;const delayed=new Promise(r=>release=r);await p.route('**/premium-api',async route=>{const body=route.request().postDataJSON();if(body.action==='mesocycle'){await delayed;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({number:999,state:'active',planned_weeks:1,weeks:[]})});}else await route.continue();});await f.getByRole('button',{name:'Mesociclo',exact:true}).click();await f.getByRole('button',{name:'Recomendaciones',exact:true}).click();await f.locator('.premium-row').first().waitFor();release();await f.locator('body').evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));check(engine+' late response cannot replace new page',await f.locator('#premiumHeading').textContent()==='Recomendaciones'&&!await f.locator('#coachProposal').textContent().then(s=>s.includes('999')));await p.unroute('**/premium-api');await p.route('**/premium-api',async route=>route.request().postDataJSON().action==='recommendations'?route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'No se pudo leer. Puedes reintentar.'})}):route.continue());await f.getByRole('button',{name:'Recomendaciones',exact:true}).click();await f.locator('#coachError').filter({hasText:'Puedes reintentar'}).waitFor();check(engine+' request error visible and accessible',await f.locator('#coachError').getAttribute('role')==='alert');await p.unroute('**/premium-api');}
  check(engine+' no browser errors',errors.length===0);
 }finally{await browser.close();}}
})().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(()=>{fs.writeFileSync(path.join(out,(live?(readonly?'ui-live-readback':'ui-live'):'ui')+'.json'),JSON.stringify({completed:!process.exitCode,total:rows.length,rows},null,2));console.log(rows.filter(x=>x.pass).length+'/'+rows.length+' '+(live?'staging UI':'offline UI')+' checks');});
