// Real renderer and adapter, synthetic offline projection. All non-local traffic blocked.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {fixture}=require('../premium-upgrade/preview.cjs'),root=path.resolve(__dirname,'../..'),out=path.join(__dirname,'results');let base='http://127.0.0.1:0';
const scripts=['coach-intake.js','coach-programming-v4.js','coach-programming-v5.js','coach-questionnaire.js','coach-premium-weekly.js','coach-premium-chat.js','coach-premium-adapter.js','coach-premium-app.js'];
const ss=(max,rest)=>[1,2].map(set_number=>({set_number,reps_min:10,reps_max:max,rir:3,rest_seconds:rest}));
const row={id:'10000000-0000-4000-8000-000000000099',kind:'MODIFY',state:'pending_review',base_revision_id:'10000000-0000-4000-8000-000000000003',patches:[{field:'replace_exercise',target_id:'old',from:'old',exercise_name:'Dead bug',before_prescription:{name:'Dead bug',scheme:'straight',planned_sets:ss(12,60)},to:{catalogue_id:'cable_crunch',source_catalogue_id:'dead_bug',scheme:'straight',planned_sets:ss(15,120)}}],quality_warnings:['multiple_changes_require_review']};
const server=http.createServer((req,res)=>{const u=new URL(req.url,base);if(u.pathname.startsWith('/assets/')&&!u.pathname.includes('..')){const f=path.join(root,u.pathname);res.setHeader('Content-Type',f.endsWith('.css')?'text/css;charset=utf-8':'application/javascript;charset=utf-8');return res.end(fs.readFileSync(f));}const v=fixture(u.searchParams.get('actor')==='reviewer'?'reviewer':'normal');v.recommendations=[];if(v.actor==='reviewer')v.days=[];res.setHeader('Content-Type','text/html;charset=utf-8');res.end('<!doctype html><html lang="es" data-theme="'+(u.searchParams.get('theme')==='dark'?'dark':'light')+'"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/theme.css"><link rel="stylesheet" href="/assets/coach-premium-app.css"></head><body><div id="host"></div>'+scripts.map(s=>'<script src="/assets/'+s+'"></script>').join('')+'<script>const view='+JSON.stringify(v)+';view.recommendations=[PremiumAdapter.recommendation('+JSON.stringify(row)+')];window.ui=PremiumApp.mount(document.getElementById("host"),{adapter:async()=>structuredClone(view),initialState:view});</script></body></html>');});
const rows=[];async function run(){fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;try{for(const [engine,type]of [['chromium',chromium],['webkit',webkit]]){const browser=await type.launch(engine==='chromium'?{channel:'msedge'}:{});try{for(const actor of ['athlete','reviewer'])for(const theme of ['light','dark']){const p=await browser.newPage({viewport:{width:theme==='light'?390:1280,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await p.goto(base+'/?actor='+actor+'&theme='+theme);try{await p.getByRole('button',{name:'Análisis',exact:true}).click({timeout:5000});}catch(e){console.error(JSON.stringify({errors,body:await p.locator('body').innerText()}));throw e;}await p.getByRole('button',{name:'Ver propuesta',exact:true}).click();const dd=p.locator('dl dd');assert((await dd.nth(0).innerText()).includes('10–12 reps, RIR 3, 1 min'));assert((await dd.nth(1).innerText()).includes('10–15 reps, RIR 3, 2 min'));assert.equal(await p.getByRole('button',{name:'Aprobar propuesta',exact:true}).count(),actor==='reviewer'?1:0);assert((await p.locator('main').innerText()).includes('multiple_changes_require_review'));assert.equal(errors.length,0);rows.push({engine,actor,theme,before_exact:true,after_exact:true,review_controls_correct:true,warnings_retained:true});await p.screenshot({path:path.join(out,'before-projection-'+engine+'-'+actor+'-'+theme+'.png'),fullPage:true});await p.close();}}finally{await browser.close();}}}finally{server.close();}fs.writeFileSync(path.join(out,'before-ui.json'),JSON.stringify({scenarios:rows,provider_calls:0,auth_calls:0,remote_writes:0},null,2));console.log(rows.length+'/'+rows.length+' before/after UI scenarios, Chromium/WebKit, athlete/reviewer, light/dark, mobile/desktop');}
run().catch(e=>{console.error(e.message);process.exitCode=1;server.close();});
