const fs=require('fs'),assert=require('assert/strict'),path=require('path');const read=f=>JSON.parse(fs.readFileSync(path.join(__dirname,f)));const blocks=[];
for(const [name,file] of [['Basic/Premium schema and adaptivity','unit.json'],['v3 provider contract (synthetic)','provider-v3.json'],['staging JWT legacy/security','live-negative.json'],['staging JWT new questionnaire/reviewer','live-v2.json'],['browser matrix','ui.json'],['interaction, contrast and stale requests','ui-delta.json']]){const r=read('results/'+file),n=r.total??r.checks;assert.equal(r.passed,n);assert.notEqual(r.completed,false);blocks.push({name,passed:n});}
const old=read('../coach-ai/results/unit.json');assert(old.every(x=>x.pass));blocks.push({name:'legacy provider compatibility',passed:old.length});
const quality=['quality2','quality3','quality4','quality5'].map(k=>read('results/real-quality-'+k+'.json'));assert(quality.every(r=>r.passed&&r.checks.every(c=>c.pass)));blocks.push({name:'real staging generations (4 calls)',passed:quality.reduce((n,r)=>n+r.checks.length,0)});
const regressions=read('../coach-v2/results/regressions.json'),archived=['tests/interior/contracts.cjs','tests/polish/contracts.cjs'];assert(regressions.every(r=>r.pass||archived.includes(r.name)));const general=regressions.filter(r=>r.pass).map(r=>{const m=[...r.output.matchAll(/"passed"\s*:\s*(\d+)/g)];assert(m.length);return {name:r.name,passed:Number(m.at(-1)[1])};});blocks.push({name:'general passing regression suites',passed:general.reduce((n,r)=>n+r.passed,0)});
const audit=read('results/legacy-contract-audit.json');assert(audit.comparisons.every(x=>x.sameFailureSet));const excluded=audit.comparisons.reduce((n,r)=>n+r.candidate.failed.length,0);
const invariants=read('results/final-contract.json');blocks.push({name:'final scope/integrity invariants',passed:invariants.passed});const total=blocks.reduce((n,b)=>n+b.passed,0);
const ledger=read('private/openai-budget.json');assert.equal(ledger.calls.length,4);assert(ledger.budget_used_usd<=.5);const report={scope:'Coach intake v2',checks:total,passed:total,blocks,general,excluded:{archivedExpectations:excluded,reason:'Identical failure set on base 57a4008 and candidate. Neither counted nor changed.'},realCalls:ledger.calls.length,estimatedCostUsd:ledger.budget_used_usd};fs.writeFileSync(__dirname+'/results/consolidated.json',JSON.stringify(report,null,2));
let md='\n## Pruebas finales\n\n**'+total.toLocaleString('es-ES')+' comprobaciones pertinentes superadas**, sin sumar reejecuciones.\n\n| Bloque | Resultado |\n|---|---:|\n';for(const b of blocks)md+='| '+b.name+' | '+b.passed+'/'+b.passed+' |\n';md+='\nNueve expectativas archivadas de interior/polish fallan idénticamente en la base y el candidato. No se han debilitado ni contado como éxitos. La comparación está en results/legacy-contract-audit.json. Los dos archivos que las contienen no se declaran íntegramente verdes.\n\nLa primera ejecución general necesitó recuperar la copia local ya existente del SDK público para cuatro suites. Se ejecutaron después solo las pendientes. Un test de igualdad JSON se corrigió para ignorar el orden de claves de jsonb; un test de anon aceptaba solo el mensaje de la función y ahora comprueba el rechazo HTTP 401/403. La prueba de límite de dos grupos hace clic y verifica el rechazo, sin exigir que el tercer checkbox quede marcado. Nada de ello altera los valores esperados del producto.\n\nDurante la revisión se corrigió un defecto real: al pasar de otra actividad a «No» y volver, los checks ocultos conservaban marcas visuales. Ahora datos y controles se limpian juntos; hay un caso específico en ambos motores. La interfaz también bloquea antes de generar una combinación de material/exclusiones que el validador de backend considera inviable; muestra cómo revisar esas respuestas.\n';const file=__dirname+'/README.md';let prior=fs.readFileSync(file,'utf8');prior=prior.split('\n## Pruebas finales')[0];fs.writeFileSync(file,prior+md);console.log(total+'/'+total+' applicable checks; '+excluded+' unchanged archived assertions excluded');
