const I=require('../../assets/coach-intake.js'),assert=require('assert/strict'),fs=require('fs');
let n=0;const check=(name,fn)=>{try{fn();n++;}catch(e){throw Error(name+': '+e.message);}};
const valid=()=>({...I.emptyBasic(),experience:'lt6',goal:'balanced_mass',days:3,weekdays:['mon','wed','fri'],minutes:60,effort:'unknown',activity:{type:'none',weekdays:[]},inventory:{equipment:['dumbbells','bands'],custom:[]}});
(async()=>{
check('empty draft',()=>assert.deepEqual(I.basicErrors(I.emptyBasic(),false),[]));check('empty not submitted',()=>assert(I.basicErrors(I.emptyBasic()).length));check('complete basic',()=>assert.deepEqual(I.basicErrors(valid()),[]));
for(const [key,value] of Object.entries({days:7,weekdays:['mon','mon','fri'],minutes:20,experience:'expert',goal:'strength',effort:'always_failure',excluded:['unknown'],activity:{type:'none',weekdays:['mon']},inventory:{equipment:['gym'],custom:[]},preferred:['goblet']}))check('reject '+key,()=>assert(I.basicErrors({...valid(),[key]:value}).length));
for(const days of [2,3,4,5,6])check('frequency '+days,()=>assert.deepEqual(I.basicErrors({...valid(),days,weekdays:I.weekdays.slice(0,days).map(d=>d.id)}),[]));
for(const e of I.experience)for(const effort of I.effort){const p={...I.emptyPremium(),experience:e.id,goal:'balanced',pause:false,days:3,weekdays:['mon','wed','fri'],minutes_by_day:{mon:30,wed:60,fri:90},effort:effort.id,confidence:effort.id==='unknown'?null:'high',activity:{type:'none',weekdays:[],minutes:null,intensity:null},recovery:'mostly',sleep:'h7_8',stress:'low',distribution:'coach',weak_points:['y2_4','gt4'].includes(e.id)?['unsure']:[]};
check('Premium '+e.id+' '+effort.id,()=>{assert.deepEqual(I.premiumErrors(p),[]);const steps=I.premiumSteps(p);assert(steps.length>=13&&steps.length<=15);assert.equal(steps.includes('weak_points'),['y1_2','y2_4','gt4'].includes(e.id));assert.equal(steps.includes('confidence'),effort.id!=='unknown');});}
check('no mixed unsure',()=>{const p={...I.emptyPremium(),experience:'gt4',weak_points:['unsure','chest']};assert(I.premiumErrors(p,false).includes('weak_points'));});
check('adaptive clears stale',()=>{const p={...I.emptyPremium(),experience:'lt6',weak_points:['chest'],effort:'unknown',confidence:'high',weekdays:['mon'],minutes_by_day:{mon:60,tue:90}};I.normalizePremium(p);assert.deepEqual(p.weak_points,[]);assert.equal(p.confidence,null);assert.equal(p.minutes_by_day.tue,undefined);});
check('catalogue identities unique',()=>{assert.equal(new Set(I.equipment.map(e=>e.id)).size,I.equipment.length);assert.equal(new Set(I.exercises.map(e=>e.name)).size,I.exercises.length);});
for(const s of ['a@b.com','https://example.com','telefono 616005774','dolor lumbar','lesión rodilla','x'.repeat(41)])check('reject custom '+s,()=>assert(!I.customName(s)));
const C=await import('../../supabase/functions/simple-coach-mock/contract.mjs'),L=await import('../../supabase/functions/simple-coach-mock/contract-v2.mjs');
check('provider omits free text',()=>{const t=valid();t.inventory.custom=['Máquina extra'];const ctx={training:t,health:{diagnosis:'NEVER'},identity:'NEVER'};const body=C.requestBody(ctx,C.DEFAULT_MODEL),j=JSON.stringify(body);assert(!j.includes('Máquina extra'));assert(!j.includes('NEVER'));assert(!Object.hasOwn(JSON.parse(body.input[0].content).training,'preferred'));assert.equal(C.safetyGate(ctx),null);});
check('excluded and equipment gate',()=>{const t=valid();t.excluded=['db_row'];const a=C.allowedExercises(t);assert(!a.some(x=>x.id==='db_row'));assert(!a.some(x=>x.requires.includes('cables')));});
check('legacy request identical',()=>{const ctx={training:{goal:'Fuerza general',experience:'beginner',days:3,minutes:60,equipment:['Gimnasio'],preferred:'',avoided:'',preferences:''}};assert.deepEqual(C.requestBody(ctx,C.DEFAULT_MODEL),L.requestBody(ctx,L.DEFAULT_MODEL));assert.equal(C.safetyGate(ctx),L.safetyGate(ctx));});
fs.mkdirSync(__dirname+'/results',{recursive:true});fs.writeFileSync(__dirname+'/results/unit.json',JSON.stringify({passed:n,total:n}));console.log(n+'/'+n+' unit checks');
})();
