// Exact-ID staging fixtures and real JWT checks. Provider dispatch requires explicit `real TAG`.
// No credentials, identities or JWTs are printed or committed. No production route exists.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const {pathToFileURL}=require('url'),root=path.resolve(__dirname,'../..'),priv=path.join(__dirname,'private'),out=path.join(__dirname,'results');
fs.mkdirSync(priv,{recursive:true});fs.mkdirSync(out,{recursive:true});
const mode=process.argv[2],tag=process.argv[3],get=p=>JSON.parse(fs.readFileSync(p)),file=n=>path.join(priv,n),write=(n,d)=>fs.writeFileSync(file(n),typeof d==='string'?d:JSON.stringify(d,null,2));
const source=path.resolve(root,'../coach-premium-phase2/tests/premium-phase2/private/fixture.json'),credentials=get(source);assert.equal(credentials.ref,'dmqjexigdnfzobarhnib');
const manifest=file('weekly-fixture.json'),sessionFile=file('weekly-sessions.json'),rows=[],equal=(a,b)=>require('util').isDeepStrictEqual(a,b);
const check=(name,v)=>{rows.push({name,pass:!!v});assert(v,name);},q=x=>"'"+String(x).replaceAll("'","''")+"'",j=x=>q(JSON.stringify(x))+'::jsonb';
let fixture=fs.existsSync(manifest)?get(manifest):null,sessions=fs.existsSync(sessionFile)?get(sessionFile):{};
async function req(actor,route,data,method){assert.equal(credentials.ref,'dmqjexigdnfzobarhnib');const r=await fetch('https://'+credentials.ref+'.supabase.co'+route,{method:method||(data===undefined?'GET':'POST'),headers:{apikey:credentials.key,...(sessions[actor]?{Authorization:'Bearer '+sessions[actor].access_token}:{}),'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)}),signal:AbortSignal.timeout(route.includes('/functions/')?120000:25000)});const raw=await r.text();let v;try{v=raw?JSON.parse(raw):null;}catch{v={error:'non_json_response'};}return{ok:r.ok,status:r.status,data:v};}
const rpc=(actor,n,d)=>req(actor,'/rest/v1/rpc/'+n,d),read=(actor,t,where)=>req(actor,'/rest/v1/'+t+'?select=*&'+where),must=async p=>{const r=await p;if(!r.ok)throw Error('Staging request rejected: '+r.status+' '+(r.data?.message||r.data?.error||'unknown'));return r.data;};
const I=require('../../assets/coach-intake.js'),set=(n,lo=8,hi=12,rir=2,rest=180)=>({set_number:n,reps_min:lo,reps_max:hi,rir,rest_seconds:rest});
const good={...I.emptyPremium(),experience:'gt4',pause:false,goal:'balanced',weak_points:['unsure'],days:2,weekdays:['mon','thu'],minutes_by_day:{mon:60,thu:60},effort:'confident',confidence:'high',recovery:'mostly',sleep:'h7_8',stress:'medium',distribution:'coach',activity:{type:'none',weekdays:[],minutes:null,intensity:null},inventory:{equipment:I.equipment.map(e=>e.id),custom:[]}};
const normal=()=>({schema_version:'premium-weekly-checkin-v1',recovery:'normal',sleep:'normal',fatigue:'normal',stress:'moderate',session_perception:'similar',availability:{changed:false,weekdays:[],minutes_by_day:{}},review:{topic:'none',exercise_id:null}});
function answers(c,kind='normal'){const a=normal();if(kind==='good')Object.assign(a,{recovery:'good',sleep:'good',fatigue:'low',stress:'low',session_perception:'easier'});if(kind==='bad')Object.assign(a,{recovery:'bad',sleep:'bad',fatigue:'very_high',stress:'high',session_perception:'much_harder'});if(kind==='availability')a.availability={changed:true,weekdays:['mon','tue','thu','fri'],minutes_by_day:{mon:60,tue:60,thu:60,fri:60}};if(kind==='exercise')a.review={topic:'exercise',exercise_id:c.exercises[2]};return a;}
function save(){write('weekly-fixture.json',fixture);}
async function main(){
 if(mode==='prepare'){
  assert(!fixture,'Do not overwrite the controlled manifest');fixture={ref:credentials.ref,prefix:'SYNTHETIC Premium Weekly '+crypto.randomUUID(),user:credentials.users.mock.id,reviewer:credentials.users.reviewer.id,cases:{},grants:[],started:new Date().toISOString()};
  for(const t of ['longitudinal','decline','discrepancy','missing','availability','exercise']){const n=t==='availability'?5:2;fixture.cases[t]={routine:crypto.randomUUID(),days:Array.from({length:n},()=>crypto.randomUUID()),exercises:Array.from({length:t==='availability'?5:4},()=>crypto.randomUUID()),workouts:[],recommendations:[],catalogue:t==='availability'?['floor_press','db_row','goblet','db_curl','leg_curl']:['hack','db_row','db_curl','floor_press']};const c=fixture.cases[t];c.plans=c.exercises.map((_,i)=>t==='longitudinal'&&i===0?[set(1,6,8,1,240),set(2,8,10,0,240),set(3,10,12,0,240)]:[set(1),set(2),set(3)]);}
  save();let sql='begin;\n';for(const[t,c]of Object.entries(fixture.cases)){sql+=`insert into public.routines(id,owner_id,name) values('${c.routine}','${fixture.user}',${q(fixture.prefix+' '+t)});\n`;c.days.forEach((id,i)=>sql+=`insert into public.routine_days(id,routine_id,name,day_order) values('${id}','${c.routine}','Día ${i+1}',${i});\n`);c.exercises.forEach((id,i)=>{const s=c.plans[i][0],d=t==='availability'?i:Math.floor(i/2);sql+=`insert into public.routine_exercises(id,day_id,name,sets,target,rir,rest_seconds,exercise_order,notes) values('${id}','${c.days[d]}',${q(I.exercises.find(e=>e.id===c.catalogue[i]).name)},${c.plans[i].length},'${s.reps_min}-${s.reps_max}','${s.rir}',${s.rest_seconds},${t==='availability'?0:i%2},'PRIVATE CANARY weekly');\n`;});sql+=`select public.premium_provision('${fixture.user}','${c.routine}',(now() at time zone 'Europe/Madrid')::date,6,now()+interval '2 days');\n`;}
  write('weekly-setup.sql',sql+'commit;');console.log('Prepared six exact-ID fixture routines; no Auth users or provider calls');return;
 }
 assert(fixture&&fixture.ref===credentials.ref);
 if(mode==='refresh'){for(const[actor,s]of Object.entries(sessions)){const r=await req(null,'/auth/v1/token?grant_type=refresh_token',{refresh_token:s.refresh_token});check(actor+' existing controlled JWT refresh',r.ok&&r.data.user.id===credentials.users[actor].id);sessions[actor]=r.data;}write('weekly-sessions.json',sessions);return;}
 if(mode==='login'){for(const[actor,u]of Object.entries(credentials.users)){const r=await req(null,'/auth/v1/token?grant_type=password',{email:u.email,password:u.password});check(actor+' existing controlled JWT',r.ok&&r.data.user.id===u.id);sessions[actor]=r.data;}write('weekly-sessions.json',sessions);return;}
 if(mode==='intake'){let sql='begin;\n';for(const[t,c]of Object.entries(fixture.cases)){const m=await must(read('mock','coach_mesocycles','routine_id=eq.'+c.routine));assert.equal(m.length,1);c.mesocycle=m[0].id;c.revision=m[0].current_revision_id;c.original_revision=c.revision;c.week=1;const training=t==='availability'?{...good,days:5,weekdays:['mon','tue','wed','thu','fri'],minutes_by_day:{mon:30,tue:30,wed:30,thu:30,fri:30}}:good;check(t+' original Premium intake submit',(await rpc('mock','premium_save_intake',{p_mesocycle:c.mesocycle,p_expected:1,p_training:training,p_submit:true})).ok);check(t+' training context permission',(await rpc('mock','premium_permission',{p_mesocycle:c.mesocycle,p_allow:true})).ok);check(t+' weekly explicit permission',(await rpc('mock','premium_weekly_permission',{p_mesocycle:c.mesocycle,p_allow:true})).ok);const by=Object.fromEntries(c.exercises.map((id,i)=>[id,c.plans[i]]));sql+=`update public.routine_revisions r set snapshot=jsonb_set(r.snapshot,'{days}',(select jsonb_agg(d||jsonb_build_object('exercises',(select jsonb_agg(e||jsonb_build_object('planned_sets',${j(by)}->(e->>'id'),'scheme',case when e->>'id'='${c.exercises[0]}' and '${t}'='longitudinal' then 'top_backoff' else 'straight' end) order by (e->>'exercise_order')::int) from jsonb_array_elements(d->'exercises')e)) order by (d->>'day_order')::int) from jsonb_array_elements(r.snapshot->'days')d)) where r.id='${c.revision}' and r.routine_id='${c.routine}';update public.routine_revisions set snapshot_hash=md5(snapshot::text) where id='${c.revision}';\nselect public.premium_bind_catalogue('${c.mesocycle}','${c.revision}',${j(Object.fromEntries(c.exercises.map((id,i)=>[id,c.catalogue[i]])))});select public.premium_assign_reviewer('${c.mesocycle}','${fixture.reviewer}');\n`;}
  const grants=await must(read('mock','context_grants','user_id=eq.'+fixture.user));fixture.grants=grants.filter(x=>['premium_training_history','premium_weekly_checkin'].includes(x.scope)||['premium-tracking-v1','premium-checkin-v1'].includes(x.notice_version)).map(x=>x.id);save();write('weekly-enhance.sql',sql+'commit;');return;
 }
 const c=fixture.cases[tag];
 if(mode==='workouts'){assert(c);const style=process.argv[4]||'stable',n=style==='insufficient'?1:4,anchor=tag==='longitudinal'?(c.week===1?28:c.week===3?8:0):0,stride=tag==='longitudinal'&&c.week>=4?2:7;let sql='begin;\n';for(let k=0;k<n;k++)for(let d=0;d<c.days.length;d++){const id=crypto.randomUUID();c.workouts.push(id);const indexes=c.exercises.map((id,i)=>i).filter(i=>tag==='availability'?i===d:Math.floor(i/2)===d);const data={routine_id:c.routine,routine_day_id:c.days[d],routine_revision_id:c.revision,notes:'PRIVATE CANARY weekly',exercises:indexes.map(i=>({exercise_id:c.exercises[i],name:'PRIVATE CANARY weekly',sets:c.plans[i].map(s=>({set:s.set_number,kg:s.set_number===1?90:82.5,reps:style==='decline'?s.reps_max-k:style==='progress'?s.reps_min+k:s.reps_max,rir:s.rir}))}))};sql+=`insert into public.workouts(id,user_id,variant,day,workout_date,data) values('${id}','${fixture.user}','SYNTHETIC Premium Weekly','Día ${d+1}',(now() at time zone 'Europe/Madrid')::date-${anchor+(n-1-k)*stride},${j(data)});\n`;}
  save();write('weekly-workouts.sql',sql+'commit;');return;
 }
 if(mode==='checkin'){assert(c);const a=answers(c,process.argv[4]);const current=await must(read('mock','coach_weekly_checkins','mesocycle_id=eq.'+c.mesocycle+'&order=created_at.desc'));const existing=current.find(x=>!x.submitted_at);const expected=existing?.row_version??0;const result=await rpc('mock','premium_save_weekly_checkin',{p_mesocycle:c.mesocycle,p_week:c.week,p_revision:c.revision,p_expected:expected,p_answers:a,p_submit:true});check(tag+' submitted immutable checkin',result.ok&&!!result.data.submitted_at);c.checkin=result.data.id;c.answers=a;save();write('weekly-last-checkin.json',result.data);return;}
 if(mode==='context'){assert(c);const ctx=await must(rpc('mock','premium_weekly_provider_context',{p_mesocycle:c.mesocycle}));check(tag+' weekly provider explicit version',ctx.schema_version==='premium-weekly-provider-v1');const txt=JSON.stringify(ctx);check(tag+' provider UUID-free identity-note-private-free',!txt.includes('CANARY')&&!txt.includes('@')&&!/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i.test(txt));check(tag+' recent context bounded',ctx.recent_weeks.length<=4);check(tag+' missing checkin explicit',ctx.checkin_missing===(tag==='missing'));write('weekly-context-'+tag+'-'+c.week+'.json',ctx);return;}
 if(mode==='reserve'){assert(c);const key=crypto.randomUUID(),r=await must(rpc('mock','premium_weekly_reserve_analysis',{p_mesocycle:c.mesocycle,p_key:key}));check(tag+' reserve current week/revision',r.state==='analyzing'&&r.base_revision_id===c.revision);c.rec=r.id;c.key=key;c.recommendations.push(r.id);save();write('weekly-rec.json',r);return;}
 if(mode==='mock-sql'){assert(c);const ctx=get(file('weekly-context-'+tag+'-'+c.week+'.json')),C=await import(pathToFileURL(path.join(root,'supabase/functions/simple-coach-premium/weekly-contract.mjs')));const output={schema_version:'premium-weekly-analysis-v1',kind:'KEEP',confidence:'medium',facts:ctx.routine.exercises.slice(0,4).map(e=>({exercise_ref:e.ref,claim:e.metrics.trend})),checkin_signals:ctx.checkin?[{field:'recovery',value:ctx.checkin.recovery},{field:'fatigue',value:ctx.checkin.fatigue}]:[],interpretation:'Datos de entrenamiento y contexto semanal revisados por separado; no se atribuye una causa.',reason:'Mantener los objetivos mientras se sigue su evolución comparable.',changes:[]};
  if(process.argv[4]==='remove'){output.kind='MODIFY';const e=ctx.routine.exercises[0],s=e.planned_sets.at(-1);output.changes=[{action:'remove_set',exercise_ref:e.ref,set_number:s.set_number,from:C.prescription?C.prescription(s):Object.fromEntries(['reps_min','reps_max','rir','rest_seconds'].map(k=>[k,s[k]]))}];output.reason='Propuesta controlada: retirar solo la última serie; conservar las restantes y revisar la respuesta la próxima semana.';}
  if(process.argv[4]==='schedule'){output.kind='MODIFY';const to=structuredClone(ctx.week_schedule);to[2].weekday='thu';to[3].weekday='fri';to[4].weekday='fri';output.changes=[{action:'change_week_schedule',from:ctx.week_schedule,to}];output.reason='Distribuir las cinco sesiones lógicas en cuatro días disponibles sin cambiar sus ejercicios ni descansos.';}
  const quality=C.semantic(output,ctx);check(tag+' mock closed schema/semantics',quality.ok);write('weekly-output-'+tag+'-'+c.week+'.json',output);const receipt={model:C.MODEL,prompt_version:C.PROMPT_VERSION,response_schema_version:C.SCHEMA_VERSION,input_tokens:0,output_tokens:0,cached_input_tokens:0,cost_usd:0,latency_ms:0};write('weekly-finish.sql',`begin;select public.premium_analysis_claim('${fixture.user}','${c.rec}',1,'mock');select public.premium_analysis_finish('${fixture.user}','${c.rec}',${j(output)},null,${j(receipt)},${j(quality.warnings)});commit;`);return;
 }
 if(mode==='review'){assert(c);const r=await must(read('mock','coach_recommendations','id=eq.'+c.rec));check(tag+' persisted pending human review',r.length===1&&r[0].state==='pending_review');check(tag+' athlete cannot approve own rec',!(await rpc('mock','premium_review_recommendation',{p_id:c.rec,p_approve:true,p_reason:'Unauthorized self approval'})).ok);check(tag+' cannot accept before review',!(await rpc('mock','premium_accept_recommendation',{p_id:c.rec})).ok);if(r[0].kind==='REVIEW')await must(rpc('reviewer','premium_resolve_review',{p_id:c.rec,p_kind:'KEEP',p_patches:[],p_reason:'Controlled staging reviewer keeps without automatic application.'}));else await must(rpc('reviewer','premium_review_recommendation',{p_id:c.rec,p_approve:true,p_reason:'Controlled staging reviewer validation.'}));check(tag+' reviewer assignment can review',(await must(read('reviewer','coach_recommendations','id=eq.'+c.rec)))[0].state==='ready');return;}
 if(mode==='accept'){assert(c);const beforeRev=(await must(read('mock','routine_revisions','id=eq.'+c.revision)))[0],beforeHistory=await must(read('mock','workouts','id=in.('+c.workouts.join(',')+')'));const [a,b]=await Promise.all([rpc('mock','premium_accept_recommendation',{p_id:c.rec}),rpc('mock','premium_accept_recommendation',{p_id:c.rec})]);check(tag+' double accept one result',a.ok&&b.ok&&a.data===b.data);const old=(await must(read('mock','routine_revisions','id=eq.'+c.revision)))[0];check(tag+' prior revision byte-for-byte intact',equal(beforeRev,old));check(tag+' recorded workouts byte-for-byte intact',equal(beforeHistory,await must(read('mock','workouts','id=in.('+c.workouts.join(',')+')'))));const rec=(await must(read('mock','coach_recommendations','id=eq.'+c.rec)))[0];const m=(await must(read('mock','coach_mesocycles','id=eq.'+c.mesocycle)))[0];check(tag+' tracking advances exactly once',m.tracking_week===c.week+1);check(tag+' KEEP creates no revision or MODIFY exactly N+1',m.current_revision_id===a.data&&(rec.kind==='MODIFY'?a.data!==c.revision:a.data===c.revision));if(rec.kind==='MODIFY'){const snapshot=(await must(read('mock','routine_revisions','id=eq.'+a.data)))[0].snapshot;for(const p of rec.patches.filter(p=>p.field==='replace_exercise')){const index=c.exercises.indexOf(p.target_id);assert(index>=0);c.exercises[index]=p.to.id;c.catalogue[index]=p.to.catalogue_id;}c.plans=c.exercises.map(id=>{const e=snapshot.days.flatMap(d=>d.exercises).find(e=>e.id===id);assert(e,'Exact current replacement/preserved UUID');return e.planned_sets;});}
  c.revision=a.data;c.week=m.tracking_week;save();return;
 }
 if(mode==='real'){assert(c);assert(sessions.mock.expires_at>Date.now()/1000+130,'JWT must be fresh before single call');const ledgerFile=path.join(out,'weekly-real.json'),ledger=fs.existsSync(ledgerFile)?get(ledgerFile):[];assert(ledger.length<10&&!ledger.some(r=>r.tag===tag),'No repeat/automatic retry');const key=crypto.randomUUID();ledger.push({tag,week:c.week,key,state:'dispatching'});fs.writeFileSync(ledgerFile,JSON.stringify(ledger,null,2));const r=await req('mock','/functions/v1/simple-coach-premium',{mesocycle_id:c.mesocycle,key,mode:'weekly'});Object.assign(ledger.at(-1),{state:'returned',http_status:r.status,recommendation:r.data?.recommendation||null,error:r.data?.error||null});fs.writeFileSync(ledgerFile,JSON.stringify(ledger,null,2));if(r.data?.recommendation){c.rec=r.data.recommendation.id;c.recommendations.push(c.rec);save();}check(tag+' single real response pending review',r.ok&&r.data?.recommendation?.state==='pending_review');console.log(JSON.stringify({tag,kind:r.data.recommendation.kind,error:r.data.recommendation.analysis_trace?.error,receipt:r.data.recommendation.analysis_trace?.receipt}));return;}
 if(mode==='cleanup-sql'){let sql='begin;\nset constraints premium_revision_rec_fk deferred;\n';for(const[t,c]of Object.entries(fixture.cases)){sql+=`do $$begin if not exists(select 1 from public.routines where id='${c.routine}' and owner_id='${fixture.user}' and name=${q(fixture.prefix+' '+t)}) then raise exception 'weekly_cleanup_identity_mismatch';end if;end $$;\n`;sql+=`delete from public.coach_weekly_checkins where mesocycle_id='${c.mesocycle}' and user_id='${fixture.user}';delete from public.coach_recommendations where mesocycle_id='${c.mesocycle}' and user_id='${fixture.user}';delete from public.coach_mesocycle_weeks where mesocycle_id='${c.mesocycle}' and user_id='${fixture.user}';delete from public.coach_mesocycles where id='${c.mesocycle}' and user_id='${fixture.user}';delete from public.routine_management where routine_id='${c.routine}' and user_id='${fixture.user}';delete from public.routine_revisions where routine_id='${c.routine}' and user_id='${fixture.user}';delete from public.workouts where id in (${c.workouts.map(q).join(',')||'null'}) and user_id='${fixture.user}' and data->>'routine_id'='${c.routine}';delete from public.routine_exercises where id in (${c.exercises.map(q).join(',')}) and day_id in (${c.days.map(q).join(',')});delete from public.routine_days where id in (${c.days.map(q).join(',')}) and routine_id='${c.routine}';delete from public.routines where id='${c.routine}' and owner_id='${fixture.user}';\n`;}
  sql+=`delete from public.context_grants where id in (${fixture.grants.map(q).join(',')||'null'}) and user_id='${fixture.user}' and notice_version in ('premium-tracking-v1','premium-checkin-v1');update coach_private.premium_analysis_budget set enabled=false where id;commit;`;write('weekly-cleanup.sql',sql);return;
 }
 if(mode==='logout'){for(const actor of Object.keys(sessions))check(actor+' test session local signout',(await req(actor,'/auth/v1/logout?scope=local',{},'POST')).ok);fs.unlinkSync(sessionFile);return;}
 throw Error('Unsupported explicit mode');
}
module.exports={fixture,credentials,sessions,rpc,read,must,req,answers,normal,check,rows,write,q,j,equal,save};
if(require.main===module)main().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(()=>{if(rows.length)fs.writeFileSync(path.join(out,'weekly-'+mode+(tag?'-'+tag:'')+'.json'),JSON.stringify({rows,total:rows.length,completed:!process.exitCode},null,2));console.log(rows.filter(r=>r.pass).length+'/'+rows.length+' '+mode+' checks');});
