// Staging replay of the unchanged historical OpenAI F output. Never calls OpenAI.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const root=path.resolve(__dirname,'../..'),priv=path.join(__dirname,'private'),out=path.join(__dirname,'results'),mode=process.argv[2];
fs.mkdirSync(priv,{recursive:true});fs.mkdirSync(out,{recursive:true});
const sourcePath=path.resolve(root,'../coach-premium-phase2/tests/premium-phase2/private/fixture.json');
const oldReal=path.resolve(root,'../coach-premium-phase2/tests/premium-phase2/results/real.json');
const oldContexts=path.resolve(root,'../coach-premium-phase2/tests/premium-phase2/private/contexts.json');
const newReal=path.resolve(root,'../premium-series/tests/premium-series/results/real.json');
const newContexts=path.resolve(root,'../premium-series/tests/premium-series/private/contexts.json');
const get=p=>JSON.parse(fs.readFileSync(p)),write=(n,d)=>fs.writeFileSync(path.join(priv,'phase2-'+n),typeof d==='string'?d:JSON.stringify(d,null,2));
const manifest=path.join(priv,'phase2-fixture.json'),baseline=path.join(priv,'phase2-baseline.json'),rows=[];
const q=x=>"'"+String(x).replaceAll("'","''")+"'",j=x=>q(JSON.stringify(x))+'::jsonb',equal=(a,b)=>require('util').isDeepStrictEqual(a,b);
const check=(name,v)=>{rows.push({name,pass:!!v});assert(v,name);};
let fixture,sessions,credentials;
function env(){fixture=get(manifest);credentials=get(sourcePath);assert.equal(credentials.ref,'dmqjexigdnfzobarhnib');assert.equal(fixture.ref,credentials.ref);sessions=fs.existsSync(path.join(priv,'phase2-sessions.json'))?get(path.join(priv,'phase2-sessions.json')):{};}
async function req(actor,route,data){assert(!route.includes('/functions/'),'No Edge provider route permitted');const r=await fetch('https://'+fixture.ref+'.supabase.co'+route,{method:data===undefined?'GET':'POST',headers:{apikey:credentials.key,...(sessions[actor]?{Authorization:'Bearer '+sessions[actor].access_token}:{}),'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)}),signal:AbortSignal.timeout(25000)});const raw=await r.text();return{ok:r.ok,status:r.status,data:raw?JSON.parse(raw):null};}
const rpc=(actor,n,d)=>req(actor,'/rest/v1/rpc/'+n,d),read=(actor,t,w)=>req(actor,'/rest/v1/'+t+'?select=*&'+w);
const must=async p=>{const r=await p;if(!r.ok)throw Error('staging RPC failed: '+r.status+' '+(r.data?.code||'unknown'));return r.data;};
function outputF(){const ledger=get(oldReal);assert.equal(ledger.length,10);const f=ledger.find(r=>r.tag==='F');assert.equal(f.http_status,200);assert.equal(f.recommendation.kind,'MODIFY');return f.recommendation.analysis_trace.output;}
async function main(){
if(mode==='audit'){
 const V1=await import(pathToFileURL(path.join(root,'supabase/functions/simple-coach-premium/contract.mjs'))),V2=await import(pathToFileURL(path.join(root,'supabase/functions/simple-coach-premium/series-contract.mjs')));
 const all=get(oldReal),more=get(newReal),contexts=get(oldContexts),newCtx=get(newContexts);check('historical dispatch count unchanged',all.length===10&&more.length===4);
 const audit=[...all.map(r=>({r,ctx:contexts[r.tag],contract:V1})),...more.map(r=>({r,ctx:newCtx[r.tag],contract:V2}))].map(({r,ctx,contract})=>{const t=r.recommendation.analysis_trace,v=t.output,quality=contract.semantic(v,ctx);check(r.tag+' '+(r.recommendation.analysis_week||'series')+' saved schema/semantics',r.http_status===200&&t.error===null&&quality.ok);return{tag:r.tag,week:r.recommendation.analysis_week||1,http_status:r.http_status,kind:v.kind,output:v,quality,receipt:t.receipt};});
 const counts={KEEP:0,MODIFY:0,REVIEW:0,invalid:0};audit.forEach(r=>counts[r.kind]++);fs.writeFileSync(path.join(out,'phase2-real-audit.json'),JSON.stringify({source:'Existing fourteen calls only; local validation rerun, no network',counts,audit},null,2));console.log(JSON.stringify(counts));return;
}
if(mode==='prepare'){
 assert(!fs.existsSync(manifest),'Do not overwrite fixture manifest');const b=get(baseline);assert(Object.values(b.counts).every(v=>v===0),'Zero-fixture baseline required');assert.equal(b.budget.enabled,false);assert.equal(b.budget.dispatched,14);assert.equal(b.budget.charged_usd,.194317);assert.equal(b.budget.reserved_usd,0);
 const src=get(sourcePath);assert.equal(src.ref,'dmqjexigdnfzobarhnib');const c={ref:src.ref,user:src.users.mock.id,reviewer:src.users.reviewer.id,routine:crypto.randomUUID(),days:[crypto.randomUUID(),crypto.randomUUID()],exercises:Array.from({length:4},()=>crypto.randomUUID()),workouts:Array.from({length:8},()=>crypto.randomUUID()),prefix:'SYNTHETIC Premium Phase2Closure F '+crypto.randomUUID(),catalogue:['db_curl','floor_press','goblet','db_row'],analysis_key:crypto.randomUUID(),source_output_sha256:crypto.createHash('sha256').update(JSON.stringify(outputF())).digest('hex')};write('fixture.json',c);write('output.json',outputF());
 const I=require(path.join(root,'assets/coach-intake.js'));let sql=`begin;do $$ begin if exists(select 1 from public.coach_mesocycles) or exists(select 1 from public.coach_recommendations) or exists(select 1 from public.context_grants where scope='premium_training_history') or exists(select 1 from public.routines where name like 'SYNTHETIC Premium%') then raise exception 'phase2_nonempty_baseline';end if;end $$;\ninsert into public.routines(id,owner_id,name) values('${c.routine}','${c.user}',${q(c.prefix)});\n`;
 c.days.forEach((id,i)=>sql+=`insert into public.routine_days(id,routine_id,name,day_order) values('${id}','${c.routine}','Día ${i+1}',${i});\n`);
 c.exercises.forEach((id,i)=>sql+=`insert into public.routine_exercises(id,day_id,name,sets,target,rir,rest_seconds,exercise_order) values('${id}','${c.days[Math.floor(i/2)]}',${q(I.exercises.find(e=>e.id===c.catalogue[i]).name)},3,'8-12','2',${i===2?240:180},${i%2});\n`);
 sql+=`select public.premium_provision('${c.user}','${c.routine}',current_date-21,6,now()+interval '1 day');commit;`;
 write('setup.sql',sql);console.log('Prepared one exact-ID staging fixture; no mutation or provider dispatch');return;
}
env();
if(mode==='login'){for(const actor of ['mock','reviewer']){const u=credentials.users[actor],r=await req(null,'/auth/v1/token?grant_type=password',{email:u.email,password:u.password});check(actor+' fresh JWT identity',r.ok&&r.data.user.id===u.id);sessions[actor]=r.data;}write('sessions.json',sessions);return;}
if(mode==='intake'){
 const ms=await must(read('mock','coach_mesocycles','routine_id=eq.'+fixture.routine));assert.equal(ms.length,1);fixture.mesocycle=ms[0].id;fixture.revision=ms[0].current_revision_id;write('fixture.json',fixture);
 const t=get(oldContexts).F.intake;check('unchanged historical F intake submitted',await must(rpc('mock','premium_save_intake',{p_mesocycle:fixture.mesocycle,p_expected:1,p_training:t,p_submit:true})));check('owner explicit context permission',await must(rpc('mock','premium_permission',{p_mesocycle:fixture.mesocycle,p_allow:true})));
 const grants=await must(read('mock','context_grants','user_id=eq.'+fixture.user+'&scope=eq.premium_training_history'));assert.equal(grants.length,1);fixture.grant=grants[0].id;write('fixture.json',fixture);
 let sql=`begin;select public.premium_bind_catalogue('${fixture.mesocycle}','${fixture.revision}',${j(Object.fromEntries(fixture.exercises.map((id,i)=>[id,fixture.catalogue[i]])))});select public.premium_assign_reviewer('${fixture.mesocycle}','${fixture.reviewer}');\n`;
 for(let k=0;k<4;k++)for(let d=0;d<2;d++){const data={routine_id:fixture.routine,routine_day_id:fixture.days[d],routine_revision_id:fixture.revision,exercises:[d*2,d*2+1].map(i=>({exercise_id:fixture.exercises[i],sets:Array.from({length:3},(_,z)=>({set:z+1,kg:20,reps:10,rir:2}))}))};sql+=`insert into public.workouts(id,user_id,variant,day,workout_date,data) values('${fixture.workouts[k*2+d]}','${fixture.user}','SYNTHETIC Premium Phase2Closure','Día ${d+1}',current_date-${(3-k)*7},${j(data)});\n`;}
 sql+=`do $$ begin if not exists(select 1 from coach_private.premium_analysis_budget where id and not enabled and dispatched=14 and charged_usd=.194317 and reserved_usd=0) then raise exception 'phase2_budget_baseline_changed';end if;end $$;update coach_private.premium_analysis_budget set enabled=true,max_calls=14,max_usd=.194317 where id;commit;`;
 write('bind-workouts.sql',sql);return;
}
if(mode==='reserve'){
 const ctx=await must(rpc('mock','premium_provider_context',{p_mesocycle:fixture.mesocycle})),C=await import(pathToFileURL(path.join(root,'supabase/functions/simple-coach-premium/series-contract.mjs')));check('F old output compatible with canonical current context',C.semantic(outputF(),ctx).ok);check('F exact target/exclusion/allowed replacement',ctx.routine.exercises[0].catalogue_id==='db_curl'&&ctx.intake.excluded.includes('db_curl')&&ctx.allowed_replacements.some(e=>e.id==='band_curl'));check('F all four facts match stable server trends',ctx.routine.exercises.every(e=>e.metrics.trend==='stable_comparable'));write('context.json',ctx);
 const r=await must(rpc('mock','premium_reserve_analysis',{p_mesocycle:fixture.mesocycle,p_key:fixture.analysis_key}));check('reserve pending analysis on N',r.state==='analyzing'&&r.base_revision_id===fixture.revision);fixture.recommendation=r.id;write('fixture.json',fixture);
 const before={revision:(await must(read('mock','routine_revisions','id=eq.'+fixture.revision)))[0],exercises:await must(read('mock','routine_exercises','day_id=in.('+fixture.days.join(',')+')')),workouts:await must(read('mock','workouts','id=in.('+fixture.workouts.join(',')+')'))};write('before-accept.json',before);
 const rec={transport:'replay_existing_real_output',source_model:'gpt-5.4-2026-03-05',source_prompt:'premium-analysis-v1',source_schema:'premium-recommendation-v1',source_tag:'F',source_output_sha256:fixture.source_output_sha256,new_openai_calls:0};
 write('finish.sql',`begin;do $$ declare r public.coach_recommendations;c jsonb;begin c:=public.premium_analysis_claim('${fixture.user}','${r.id}',100,'mock');if not (c->>'claimed')::boolean then raise exception 'phase2_mock_claim_failed';end if;r:=public.premium_analysis_finish('${fixture.user}','${r.id}',${j(outputF())},null,${j(rec)},'[]');if r.kind<>'MODIFY' or r.state<>'pending_review' or r.analysis_trace->>'error' is not null then raise exception 'phase2_replay_not_applicable';end if;end $$;commit;select id,kind,state,patches,analysis_trace->'output' as output from public.coach_recommendations where id='${r.id}';`);return;
}
if(mode==='review'){
 const r=(await must(read('mock','coach_recommendations','id=eq.'+fixture.recommendation)))[0];check('stored historical F output exactly unchanged',equal(r.analysis_trace.output,outputF()));check('finish produced one valid replacement',r.kind==='MODIFY'&&r.state==='pending_review'&&r.patches.length===1&&r.patches[0].field==='replace_exercise');check('replay provenance and zero new provider cost',r.analysis_trace.model==='mock'&&r.analysis_trace.receipt.transport==='replay_existing_real_output'&&r.analysis_trace.charged_usd===0);fixture.replacement=r.patches[0].to.id;write('fixture.json',fixture);
 check('athlete cannot accept pending review',!(await rpc('mock','premium_accept_recommendation',{p_id:r.id})).ok);check('athlete cannot approve own proposal',!(await rpc('mock','premium_review_recommendation',{p_id:r.id,p_approve:true,p_reason:'Forbidden'})).ok);
 await must(rpc('reviewer','premium_review_recommendation',{p_id:r.id,p_approve:true,p_reason:'Staging replay: original real F output, exact catalogue exclusion, fresh UUID and preserved baseline inspected.'}));const ready=(await must(read('mock','coach_recommendations','id=eq.'+r.id)))[0];check('assigned reviewer makes recommendation ready',ready.state==='ready'&&ready.reviewed_at&&ready.review_reason);
 write('stale.sql',`begin;select public.premium_mock_recommendation('${fixture.mesocycle}','KEEP','[]','[]','Competing controlled KEEP for stale check only.') as id;commit;`);return;
}
if(mode==='stale-ready'){
 const recs=await must(read('mock','coach_recommendations','routine_id=eq.'+fixture.routine));const stale=recs.find(r=>r.id!==fixture.recommendation);assert(stale);fixture.stale=stale.id;write('fixture.json',fixture);await must(rpc('reviewer','premium_review_recommendation',{p_id:stale.id,p_approve:true,p_reason:'Controlled competing baseline recommendation to verify stale protection.'}));check('competing baseline recommendation ready',(await must(read('mock','coach_recommendations','id=eq.'+stale.id)))[0].state==='ready');return;
}
if(mode==='accept'){
 const before=get(path.join(priv,'phase2-before-accept.json'));const a=await Promise.all([1,2].map(()=>rpc('mock','premium_accept_recommendation',{p_id:fixture.recommendation})));check('two concurrent JWT accepts return same N+1',a.every(r=>r.ok)&&a[0].data===a[1].data&&a[0].data!==fixture.revision);fixture.result_revision=a[0].data;write('fixture.json',fixture);
 const revs=await must(read('mock','routine_revisions','routine_id=eq.'+fixture.routine)),original=revs.find(r=>r.id===fixture.revision),next=revs.find(r=>r.id===fixture.result_revision);check('exactly one N+1 created',revs.length===2&&next.revision_no===2);check('original N byte-for-byte intact',equal(original,before.revision));check('N+1 is replay provenance mock',next.author_kind==='mock'&&next.recommendation_id===fixture.recommendation);
 const exercises=await must(read('mock','routine_exercises','day_id=in.('+fixture.days.join(',')+')'));check('old UUID removed from live/new UUID exact',!exercises.some(e=>e.id===fixture.exercises[0])&&exercises.some(e=>e.id===fixture.replacement));check('replacement UUID differs',fixture.replacement!==fixture.exercises[0]);const repl=exercises.find(e=>e.id===fixture.replacement);check('replacement preserves day/order/3x8-12/RIR2/rest180',repl.day_id===fixture.days[0]&&repl.exercise_order===0&&repl.sets===3&&repl.target==='8-12'&&repl.rir==='2'&&repl.rest_seconds===180);
 for(const id of fixture.exercises.slice(1))check('untouched exercise '+fixture.exercises.indexOf(id),equal(exercises.find(e=>e.id===id),before.exercises.find(e=>e.id===id)));
 const ww=await must(read('mock','workouts','id=in.('+fixture.workouts.join(',')+')'));check('all eight workouts byte-for-byte intact',equal(ww,before.workouts));check('new UUID inherits no workout',ww.every(w=>w.data.exercises.every(e=>e.exercise_id!==fixture.replacement)));check('old UUID remains in four workouts',ww.filter(w=>w.data.exercises.some(e=>e.exercise_id===fixture.exercises[0])).length===4);
 const ctx=await must(rpc('mock','premium_provider_context',{p_mesocycle:fixture.mesocycle}));check('mapping becomes band_curl with no inherited exposure',ctx.routine.exercises[0].catalogue_id==='band_curl'&&ctx.routine.exercises[0].exposures.length===0);
 const m=(await must(read('mock','coach_mesocycles','id=eq.'+fixture.mesocycle)))[0],weeks=await must(read('mock','coach_mesocycle_weeks','mesocycle_id=eq.'+fixture.mesocycle));check('tracking advances once to2',m.tracking_week===2&&m.current_revision_id===fixture.result_revision);check('week1 preserves N',weeks.find(w=>w.week_number===1).revision_id===fixture.revision);check('all future tracking weeks use N+1',weeks.filter(w=>w.week_number>1).every(w=>w.revision_id===fixture.result_revision));
 check('accepted idempotent later call',await must(rpc('mock','premium_accept_recommendation',{p_id:fixture.recommendation}))===fixture.result_revision);check('competing stale cannot apply',!(await rpc('mock','premium_accept_recommendation',{p_id:fixture.stale})).ok);check('competing proposal superseded',(await must(read('mock','coach_recommendations','id=eq.'+fixture.stale)))[0].state==='superseded');write('after-accept.json',{revision:next,exercises,workouts:ww,mesocycle:m,weeks,context:ctx});return;
}
if(mode==='cleanup-sql'){
 const b=get(baseline).budget,c=fixture;write('cleanup.sql',`begin;do $$ begin if not exists(select 1 from public.routines where id='${c.routine}' and owner_id='${c.user}' and name=${q(c.prefix)}) then raise exception 'phase2_cleanup_identity_mismatch';end if;if not exists(select 1 from coach_private.premium_analysis_budget where id and dispatched=14 and charged_usd=.194317 and reserved_usd=0) then raise exception 'phase2_budget_counters_changed';end if;end $$;set constraints premium_revision_rec_fk deferred;delete from public.coach_mesocycle_weeks where mesocycle_id='${c.mesocycle}' and routine_id='${c.routine}' and user_id='${c.user}';delete from public.coach_recommendations where routine_id='${c.routine}' and user_id='${c.user}';delete from public.coach_mesocycles where id='${c.mesocycle}' and routine_id='${c.routine}' and user_id='${c.user}';delete from public.routine_management where routine_id='${c.routine}' and user_id='${c.user}' and plan_kind='premium';delete from public.routine_revisions where routine_id='${c.routine}' and user_id='${c.user}' and origin<>'basic';delete from public.workouts where id in(${c.workouts.map(q).join(',')}) and user_id='${c.user}' and data->>'routine_id'='${c.routine}';delete from public.routine_exercises where day_id in(${c.days.map(q).join(',')});delete from public.routine_days where id in(${c.days.map(q).join(',')}) and routine_id='${c.routine}';delete from public.routines where id='${c.routine}' and owner_id='${c.user}' and name=${q(c.prefix)};delete from public.context_grants where id='${c.grant}' and user_id='${c.user}' and scope='premium_training_history';update coach_private.premium_analysis_budget set enabled=false,max_calls=${b.max_calls},max_usd=${b.max_usd} where id;commit;`);console.log('Generated guarded exact-ID cleanup and original disabled budget restore');return;
}
if(mode==='logout'){for(const actor of ['mock','reviewer'])check(actor+' local test session revoked',(await req(actor,'/auth/v1/logout?scope=local',{})).ok);fs.unlinkSync(path.join(priv,'phase2-sessions.json'));return;}
throw Error('Unknown mode');
}
main().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(()=>{if(rows.length){fs.writeFileSync(path.join(out,'phase2-'+mode+'.json'),JSON.stringify({transport:'replay_existing_real_output',new_openai_calls:0,rows,total:rows.length,completed:!process.exitCode},null,2));console.log(rows.filter(r=>r.pass).length+'/'+rows.length+' '+mode+' checks');}});
