// All provider and Edge transport in this suite is intercepted. No network or credentials.
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const rows=[],clone=x=>structuredClone(x),test=(name,fn)=>{fn();rows.push({name,pass:true});};
async function main(){
const W=await import('../../supabase/functions/simple-coach-premium/weekly-contract.mjs'),S=await import('../../supabase/functions/simple-coach-premium/series-contract.mjs'),D=await import('../../supabase/functions/simple-coach-premium/distribution-contract.mjs');
const ss=[{set_number:1,reps_min:6,reps_max:8,rir:1,rest_seconds:240},{set_number:2,reps_min:8,reps_max:10,rir:0,rest_seconds:240},{set_number:3,reps_min:10,reps_max:12,rir:0,rest_seconds:240}];
const ci={schema_version:'premium-weekly-checkin-v1',recovery:'normal',sleep:'normal',fatigue:'normal',stress:'moderate',session_perception:'similar',availability:{changed:false,weekdays:[],minutes_by_day:{}},review:{topic:'none',exercise_ref:null}};
const ctx={schema_version:W.PROVIDER_VERSION,intake:{experience:'gt4',activity:{type:'none',weekdays:[]}},routine:{days:[{ref:'day_1',order:0}],exercises:[{ref:'exercise_1',day_ref:'day_1',catalogue_id:'hack',prescription:{sets:3,reps:'6-8',rir:'1',rest_seconds:240},planned_sets:ss,prescription_format:'individualized-v5',metrics:{trend:'stable_comparable'},exposures:[{sets:ss.map((s,i)=>({set_number:i+1,kg:i?82.5:90,reps:s.reps_max,rir:s.rir}))}]}]},allowed_replacements:[],checkin_missing:false,checkin:ci,recent_weeks:[],week_schedule:[{day_ref:'day_1',weekday:'mon',minutes:60}],week_schedule_source:'snapshot'};
const edit=(c,f)=>{c=clone(c);f(c);return c;};
function output(c,changes=[],kind=changes.length?'MODIFY':'KEEP'){return{schema_version:W.SCHEMA_VERSION,kind,facts:c.routine.exercises.map(e=>({exercise_ref:e.ref,claim:e.metrics.trend})),checkin_signals:W.checkinSignals(c),interpretation:'Observación del rendimiento registrada; check-in es una declaración adicional.',changes,reason:'Mantener o proponer un ajuste pequeño con revisión humana.',confidence:'medium'};}
function accepts(name,v,c){test(name,()=>assert(W.semantic(v,c).ok,JSON.stringify(W.semantic(v,c))));}
function rejects(name,v,c,failure){test(name,()=>{const r=W.semantic(v,c);assert(!r.ok);if(failure)assert(r.failures.includes(failure),JSON.stringify(r));});}
const good=edit(ctx,c=>{c.checkin.recovery='good';c.checkin.sleep='good';c.checkin.fatigue='low';c.checkin.stress='low';c.routine.exercises[0].metrics.trend='reps_increasing_comparable';});
accepts('scenario 1 progress plus good checkin KEEP',output(good),good);
accepts('scenario 2 stable plus normal KEEP',output(ctx),ctx);
const tired=edit(ctx,c=>c.checkin.fatigue='high');accepts('scenario 3 isolated high fatigue stable KEEP',output(tired),tired);
const declining=edit(ctx,c=>{c.routine.exercises[0].metrics.trend='reps_decreasing_comparable';c.checkin.recovery='worse';c.checkin.sleep='bad';c.checkin.fatigue='high';});
const remove={action:'remove_set',exercise_ref:'exercise_1',set_number:2,from:S.prescription(ss[1])};accepts('scenario 4 repeated decline bad checkin small per-set MODIFY',output(declining,[remove]),declining);accepts('scenario 4 REVIEW also structurally valid',output(declining,[],'REVIEW'),declining);
const discrepancy=edit(good,c=>c.routine.exercises[0].metrics.trend='reps_decreasing_comparable');const discrepancyOutput=output(discrepancy,[],'REVIEW');discrepancyOutput.interpretation='El rendimiento desciende aunque la recuperación declarada es buena; estas observaciones discrepan sin probar una causa.';accepts('scenario 5 decline good checkin recognizes discrepancy',discrepancyOutput,discrepancy);
const scant=edit(tired,c=>c.routine.exercises[0].metrics.trend='insufficient_data');accepts('scenario 6 insufficient history poor perception KEEP',output(scant),scant);rejects('scenario 6 aggressive volume cannot replace missing history',output(scant,[{action:'change_sets',exercise_ref:'exercise_1',from:3,to:8}]),scant);
const five=edit(ctx,c=>{c.routine.days=Array.from({length:5},(_,i)=>({ref:'day_'+(i+1),order:i}));c.routine.exercises=c.routine.days.map((d,i)=>({ref:'exercise_'+(i+1),day_ref:d.ref,catalogue_id:'db_curl',prescription:{sets:3,reps:'8-12',rir:'2',rest_seconds:180},planned_sets:Array.from({length:3},(_,z)=>({set_number:z+1,reps_min:8,reps_max:12,rir:2,rest_seconds:180})),prescription_format:'legacy_uniform_projection',metrics:{trend:'stable_comparable'},exposures:[]}));c.week_schedule=c.routine.days.map((d,i)=>({day_ref:d.ref,weekday:W.WEEKDAYS[i],minutes:30}));c.checkin.availability={changed:true,weekdays:['mon','tue','wed','thu'],minutes_by_day:{mon:60,tue:30,wed:30,thu:30}};});
const schedule={action:'change_week_schedule',from:clone(five.week_schedule),to:five.week_schedule.map(s=>({...s,weekday:s.weekday==='fri'?'mon':s.weekday}))};accepts('scenario 7 five logical days on four weekdays without deleting refs',output(five,[schedule]),five);
rejects('schedule from reordered capture rejected like SQL',output(five,[edit(schedule,c=>c.from.reverse())]),five,'stale_or_unresolved_schedule');
accepts('schedule to reordered with exact logical refs remains valid',output(five,[edit(schedule,c=>c.to.reverse())]),five);
const requested=edit(ctx,c=>c.checkin.review={topic:'exercise',exercise_ref:'exercise_1'});accepts('scenario 8 exercise request supports KEEP no automatic replacement',output(requested),requested);test('exercise request prompt never authorizes automatic substitution',()=>assert(W.PROMPT.includes('no autorización automática')));
const keeps=edit(ctx,c=>c.recent_weeks=Array.from({length:4},(_,i)=>({week:4-i,decision:'KEEP',changes_applied:[],checkin_summary:clone(ci)})));accepts('scenario 9 four consecutive KEEP decisions valid',output(keeps),keeps);
const improved=edit(good,c=>c.recent_weeks=[{week:3,decision:'MODIFY',changes_applied:[remove],checkin_summary:{recovery:'worse'}}]);accepts('scenario 10 prior MODIFY current improvement KEEP',output(improved),improved);
const missing=edit(ctx,c=>{c.checkin_missing=true;c.checkin=null;});accepts('history-only missing checkin explicitly empty signals',output(missing),missing);rejects('missing checkin never fabricates normal',edit(output(missing),v=>v.checkin_signals=[{field:'sleep',value:'normal'}]),missing,'unsupported_checkin_signal');
rejects('wrong field enum pairing not accepted',edit(output(ctx),v=>v.checkin_signals[0]={field:'recovery',value:'very_high'}),ctx,'unsupported_checkin_signal');rejects('duplicate subjective signal rejected',edit(output(ctx),v=>v.checkin_signals.push(v.checkin_signals[0])),ctx);rejects('free health signal rejected',edit(output(ctx),v=>v.checkin_signals[0]={field:'pain',value:'high'}),ctx,'schema_invalid');rejects('objective facts still exact',edit(output(ctx),v=>v.facts[0].claim='reps_decreasing_comparable'),ctx,'unsupported_fact');
rejects('no asserted sleep causality',edit(output(ctx),v=>v.interpretation='El mal sueño ha causado la caída de rendimiento.'),ctx,'unproven_checkin_causality');rejects('health outside weekly contract',edit(output(ctx),v=>v.reason='Hay dolor y una lesión que hay que tratar.'),ctx,'outside_weekly_training_contract');
accepts('hypothesis explicitly uncertain is not asserted causality',edit(output(ctx),v=>v.interpretation='Es posible que el sueño haya influido, pero no está demostrado.'),ctx);accepts('negative causal statement is not asserted causality',edit(output(ctx),v=>v.interpretation='El sueño no ha causado una caída verificable en estos datos.'),ctx);
accepts('not demonstrated cause explicitly remains an uncertainty',edit(output(ctx),v=>v.interpretation='No está demostrado que el sueño ha causado el descenso observado.'),ctx);
rejects('schedule stale from rejected',output(five,[edit(schedule,c=>c.from[0].minutes=45)]),five,'stale_or_unresolved_schedule');rejects('schedule no-op rejected',output(five,[edit(schedule,c=>c.to=clone(c.from))]),five,'empty_schedule_change');rejects('schedule removing logical day rejected',output(five,[edit(schedule,c=>c.to.pop())]),five,'schedule_logical_days_changed');rejects('schedule duplicate ref rejected',output(five,[edit(schedule,c=>c.to[4].day_ref='day_1')]),five,'schedule_logical_days_changed');rejects('schedule unavailable weekday rejected',output(five,[edit(schedule,c=>c.to[4].weekday='sun')]),five,'schedule_weekday_unavailable');rejects('combined sessions must fit aggregate cap',output(five,[edit(schedule,c=>c.to[4].minutes=45)]),five,'schedule_exceeds_available_time');rejects('allocated time cannot conceal existing workload',output(five,[edit(schedule,c=>c.to[4].minutes=15)]),five,'schedule_duration_below_estimate');
const legacyRest={action:'change_rest',exercise_ref:'exercise_5',from:180,to:150};rejects('rest cannot be compressed to cram schedule',output(five,[schedule,legacyRest]),five,'schedule_rest_compression');rejects('schedule unresolved cannot invent original mapping',output(edit(five,c=>{c.week_schedule=[];c.week_schedule_source='unresolved';}),[schedule]),edit(five,c=>{c.week_schedule=[];c.week_schedule_source='unresolved';}),'stale_or_unresolved_schedule');rejects('KEEP must not leave unavailable weekday unresolved',output(five),five,'unresolved_availability_requires_review');accepts('unresolvable availability requires REVIEW with no changes',output(five,[],'REVIEW'),five);
rejects('review target must be current exact ref',output(edit(requested,c=>c.checkin.review.exercise_ref='other')),edit(requested,c=>c.checkin.review.exercise_ref='other'),'weekly_review_target');rejects('provider rejects internal UUID',output(edit(ctx,c=>c.user_id='00000000-0000-4000-8000-000000000001')),edit(ctx,c=>c.user_id='00000000-0000-4000-8000-000000000001'),'weekly_context_not_minimized');rejects('provider rejects free extra checkin field',output(edit(ctx,c=>c.checkin.note='arbitrary')),edit(ctx,c=>c.checkin.note='arbitrary'),'weekly_checkin_shape');
rejects('provider rejects boolean minutes map',output(ctx),edit(ctx,c=>c.checkin.availability.minutes_by_day=true),'weekly_checkin_shape');rejects('provider malformed metrics fail closed without TypeError',output(ctx),edit(ctx,c=>delete c.routine.exercises[0].metrics),'weekly_context_reference_shape');
test('duration estimate same as V5 operating policy',()=>assert.equal(W.estimatedSessionMinutes(five).day_1,19));test('unilateral duration adds bilateral execution and transitions',()=>assert.equal(W.estimatedSessionMinutes(edit(five,c=>c.routine.exercises[0].catalogue_id='db_row')).day_1,22));
const costly=edit(ctx,c=>c.routine.exercises[0].exposures.push(clone(c.routine.exercises[0].exposures[0])));test('repeated high-cost failure is review warning not forced MODIFY',()=>{const r=W.semantic(output(costly),costly);assert(r.ok&&r.warnings.includes('repeated_high_cost_failure:exercise_1'));});
test('request keeps model 1800 tokens low reasoning strict storefalse',()=>{const b=W.requestBody(ctx);assert.equal(b.model,'gpt-5.4-2026-03-05');assert.equal(b.max_output_tokens,1800);assert.equal(b.reasoning.effort,'low');assert.equal(b.store,false);assert.equal(b.text.format.strict,true);assert.equal(b.text.format.schema.properties.schema_version.enum[0],W.SCHEMA_VERSION);});
const response=v=>({status:'completed',usage:{input_tokens:1000,output_tokens:100,input_tokens_details:{cached_tokens:0}},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(v)}]}]});
for(const [name,c,v] of [['KEEP',ctx,output(ctx)],['MODIFY',declining,output(declining,[remove])],['REVIEW',discrepancy,discrepancyOutput],['schedule MODIFY',five,output(five,[schedule])]]){let calls=0;const r=await W.analyze(c,'MOCK',async(url,init)=>{calls++;const body=JSON.parse(init.body);assert.equal(body.text.format.name,'premium_weekly_analysis_v1');return new Response(JSON.stringify(response(v)));});test('mocked transport returns exact '+name,()=>assert(calls===1&&!r.error&&JSON.stringify(r.output)===JSON.stringify(v)&&r.receipt.prompt_version===W.PROMPT_VERSION&&r.receipt.cost_usd===.004));}
for(const status of [400,429,500]){let calls=0;const r=await W.analyze(ctx,'MOCK',async()=>{calls++;return new Response('sensitive provider diagnostics',{status});});test('provider error '+status+' one dispatch sanitized no retry',()=>assert(calls===1&&r.error&&!JSON.stringify(r).includes('sensitive')));}
let badCalls=0;const invalid=await W.analyze(edit(ctx,c=>c.checkin_missing=true),'MOCK',async()=>{badCalls++;throw Error('Must not dispatch');});test('invalid provider context consumes zero calls',()=>assert(invalid.error==='invalid_weekly_context'&&badCalls===0));
const badOutput=await W.analyze(ctx,'MOCK',async()=>new Response(JSON.stringify(response({...output(ctx),extra:'unsafe'}))));test('invalid strict output retains error no applicable proposal',()=>assert.equal(badOutput.error,'invalid_recommendation'));
const edgeSource=fs.readFileSync(path.resolve(__dirname,'../../supabase/functions/simple-coach-premium/index.ts'),'utf8').replace(/^import .*\r?\n/gm,'').replace(/\)!/g,')').replace(/req:Request|body:unknown|name:string|r:any/g,x=>x.split(':')[0]);
async function gateway(body,opts={}){
 let handler,providerCalls=0;const rpcCalls=[];const c=opts.ctx||ctx,v=opts.output||output(c),id='00000000-0000-4000-8000-000000000003';
 const fetchMock=async(url,init={})=>{
  if(url.endsWith('/auth/v1/user'))return new Response(JSON.stringify({id:'00000000-0000-4000-8000-000000000002'}),{status:opts.authDenied?401:200});
  if(url==='https://api.openai.com/v1/responses'){providerCalls++;return new Response(JSON.stringify(response(v)));}
  const name=url.split('/rpc/')[1],p=JSON.parse(init.body);rpcCalls.push({name,p});
  if(name==='premium_reserve_analysis'||name==='premium_weekly_reserve_analysis'){if(opts.reserveError)return new Response(JSON.stringify({message:opts.reserveError}),{status:400});return new Response(JSON.stringify({id,kind:'REVIEW',state:opts.state||'analyzing',analysis_bundle:{provider:c},analysis_trace:{}}));}
  if(name==='premium_analysis_claim')return new Response(JSON.stringify({claimed:opts.claimed!==false,provider:c}));
  if(name==='premium_analysis_finish')return new Response(JSON.stringify({id,kind:p.p_output?.kind||'REVIEW',state:p.p_error?'failed':'pending_review',facts:p.p_output?.facts||[],interpretation:p.p_output?.interpretation||'',patches:[],analysis_trace:{output:p.p_output,receipt:p.p_receipt,error:p.p_error}}));
  throw Error('unexpected intercepted RPC '+name);
 };
 const sandbox={Series:S,Weekly:W,Distribution:D,Deno:{env:{get:k=>({SUPABASE_URL:'https://dmqjexigdnfzobarhnib.supabase.co',SUPABASE_ANON_KEY:'TEST_ANON',SUPABASE_SERVICE_ROLE_KEY:'TEST_SERVICE',OPENAI_API_KEY:'TEST_MODEL'}[k])},serve:f=>handler=f},fetch:fetchMock,Response,Request,TextEncoder,AbortSignal,Error,Set};vm.runInNewContext(edgeSource,sandbox);const r=await handler(new Request('http://127.0.0.1:4241',{method:'POST',headers:{origin:opts.origin||'http://127.0.0.1:4241',authorization:'Bearer TEST_SESSION'},body:JSON.stringify(body)}));return{status:r.status,data:await r.json(),providerCalls,rpcCalls};
}
const body={mesocycle_id:'00000000-0000-4000-8000-000000000004',key:'00000000-0000-4000-8000-000000000005',mode:'weekly'};
const route=await gateway(body);test('weekly Edge opt-in routes correct reserve and output',()=>assert(route.providerCalls===1&&route.rpcCalls[0].name==='premium_weekly_reserve_analysis'&&route.data.recommendation.kind==='KEEP',JSON.stringify(route)));test('weekly token reserve includes full schema bytes and overhead',()=>assert.equal(route.rpcCalls.find(r=>r.name==='premium_analysis_claim').p.p_input_bound,new TextEncoder().encode(JSON.stringify(W.requestBody(ctx))).length+2048));
const legacyCtx={...clone(ctx),schema_version:'premium-provider-v1'};const {mode:ignored,...oldBody}=body;const {checkin_signals:ignoredSignals,...oldOut}=output(legacyCtx);oldOut.schema_version=S.SCHEMA_VERSION;const old=await gateway(oldBody,{ctx:legacyCtx,output:oldOut,origin:'http://127.0.0.1:4233'});test('Phase2 exact old request keeps previous route/contract',()=>assert(old.providerCalls===1&&old.rpcCalls[0].name==='premium_reserve_analysis'&&old.data.recommendation.analysis_trace.output.schema_version===S.SCHEMA_VERSION));
const upgraded=await gateway(oldBody);test('old request selecting captured weekly bundle uses weekly contract safely',()=>assert(upgraded.providerCalls===1&&upgraded.rpcCalls[0].name==='premium_reserve_analysis'&&upgraded.data.recommendation.analysis_trace.output.schema_version===W.SCHEMA_VERSION));const mismatched=await gateway(body,{ctx:legacyCtx,output:oldOut});test('explicit weekly request captured legacy context rejects before provider',()=>assert(mismatched.providerCalls===0&&mismatched.rpcCalls.find(r=>r.name==='premium_analysis_claim').p.p_mode==='mock'&&mismatched.data.recommendation.state==='failed'&&mismatched.data.recommendation.analysis_trace.error==='invalid_weekly_context'));
const stale=await gateway(body,{state:'superseded'});test('scenario 11 stale recommendation no provider dispatch',()=>assert(stale.providerCalls===0&&stale.data.recommendation.state==='superseded'));
for(const [name,error] of [['scenario 12 duplicate checkin conflict','premium_weekly_checkin_conflict'],['scenario 13 other-user checkin denied','premium_not_authorized'],['scenario 14 completed mesocycle denied','premium_weekly_closed_week'],['scenario 15 context grant revoked','premium_history_consent_required']]){const r=await gateway(body,{reserveError:error});test(name,()=>assert(r.providerCalls===0&&r.status===400&&r.data.error===error));}
for(const b of [{...body,mode:'other'},{...body,token:'extra'},{...body,key:null},[]]){const r=await gateway(b);test('Edge malformed closed request '+JSON.stringify(b),()=>assert(r.status===400&&r.providerCalls===0&&r.rpcCalls.length===0));}
const denied=await gateway(body,{authDenied:true});test('Edge auth deny before reserve/provider',()=>assert(denied.status===401&&denied.providerCalls===0&&denied.rpcCalls.length===0));const noOrigin=await gateway(body,{origin:'https://untrusted.invalid'});test('Edge denied origin never reaches provider',()=>assert(noOrigin.status===403&&noOrigin.providerCalls===0));
const noClaim=await gateway(body,{claimed:false});test('duplicate analysis claim returns202 no provider retry',()=>assert(noClaim.status===202&&noClaim.providerCalls===0));const invalidContext=await gateway(body,{ctx:edit(ctx,c=>c.checkin.extra='note')});test('Edge malformed weekly context fails via mock with zero provider cost',()=>assert(invalidContext.providerCalls===0&&invalidContext.rpcCalls.find(r=>r.name==='premium_analysis_claim').p.p_mode==='mock'&&invalidContext.data.recommendation.state==='failed'));
const distributionCtx=edit(ctx,c=>{c.session_distribution_version=D.VERSION;c.distribution_availability={weekdays:['mon'],minutes_by_day:{mon:60}};});
const distributionOutput={...output(distributionCtx),schema_version:D.SCHEMA_VERSION};
const distributionRoute=await gateway(body,{ctx:distributionCtx,output:distributionOutput});
test('captured distribution marker selects the new Edge contract without changing KEEP',()=>assert(distributionRoute.providerCalls===1&&distributionRoute.data.recommendation.analysis_trace.output.schema_version===D.SCHEMA_VERSION));
test('distribution reserve counts its complete strict schema and prompt',()=>assert.equal(distributionRoute.rpcCalls.find(r=>r.name==='premium_analysis_claim').p.p_input_bound,new TextEncoder().encode(JSON.stringify(D.requestBody(distributionCtx))).length+2048));
const badDistribution=await gateway(body,{ctx:edit(distributionCtx,c=>delete c.distribution_availability),output:distributionOutput});
test('distribution marker without availability fails before provider dispatch',()=>assert(badDistribution.providerCalls===0&&badDistribution.data.recommendation.analysis_trace.error==='invalid_weekly_context'));
const dir=path.join(__dirname,'results');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'weekly-unit.json'),JSON.stringify({rows,total:rows.length,completed:true,network:'all intercepted',openai_calls:0},null,2));console.log(rows.length+'/'+rows.length+' weekly contract/Edge mocked checks');
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
