-- Synthetic staging fixtures; every mutation is rolled back.
BEGIN;
CREATE TEMP TABLE client_routine_checks(name text PRIMARY KEY,pass boolean NOT NULL);
DO $$
DECLARE t uuid:='6b47ae02-6574-46db-acdb-f00925efdd74';c uuid:='c7bbe50b-d349-4f7e-8fdc-476f17c22674';
 c2 uuid:='c14a2a6d-9853-431d-856c-4d742002187e';tb uuid:='0b6fb9c1-3a62-4fbb-93d9-b3993a8fffb8';
 rid uuid:=gen_random_uuid();d1 uuid:=gen_random_uuid();d2 uuid:=gen_random_uuid();e1 uuid:=gen_random_uuid();e2 uuid:=gen_random_uuid();e3 uuid:=gen_random_uuid();
 a1 uuid;a2 uuid;code text:=upper('ISO-'||replace(gen_random_uuid()::text,'-',''));
 source jsonb;other jsonb;s jsonb;saved jsonb;stale jsonb;payload jsonb;expanded jsonb;nextdays jsonb;before_history text;h text;total bigint;done bigint;wid uuid;
BEGIN
 INSERT INTO public.routines(id,owner_id,name,description) VALUES(rid,t,'Synthetic shared original',NULL);
 INSERT INTO public.routine_days(id,routine_id,name,day_order) VALUES(d1,rid,'A',5),(d2,rid,'B',9);
 INSERT INTO public.routine_exercises(id,day_id,name,sets,target,rir,rest_seconds,exercise_order,notes) VALUES
 (e1,d1,'Original squat',3,'6-8','2',180,4,NULL),(e2,d1,'Original curl',2,'','0',0,8,''),(e3,d2,'Original row',4,NULL,NULL,150,3,'Keep instruction');
 source:=public.client_routine_template_snapshot(rid);
 INSERT INTO public.routine_share_codes(routine_id,code,max_uses,created_by) VALUES(rid,code,2,t);
 PERFORM set_config('request.jwt.claim.sub',c::text,true);a1:=public.redeem_routine_share_code(code);
 PERFORM set_config('request.jwt.claim.sub',c2::text,true);a2:=public.redeem_routine_share_code(code);
 INSERT INTO client_routine_checks VALUES('real share RPC captures two independent prescriptions',(SELECT count(*)=2 FROM client_routine_customizations WHERE assignment_id IN(a1,a2)));
 INSERT INTO client_routine_checks VALUES('assignment routine UUIDs preserved',NOT EXISTS(SELECT 1 FROM routine_assignments WHERE id IN(a1,a2) AND (trainer_routine_id<>rid OR client_routine_id IS NOT NULL)));
 PERFORM set_config('request.jwt.claim.sub',c::text,true);
 INSERT INTO public.workouts(user_id,variant,day,workout_date,data) VALUES(c,'synthetic','A',current_date-1,jsonb_build_object('routine_id',rid,'routine_day_id',d1,'exercises',jsonb_build_array(jsonb_build_object('exercise_id',e1,'sets',jsonb_build_array(jsonb_build_object('kg',73,'reps',7,'rir',2))))));
 INSERT INTO public.routine_user_notes(user_id,routine_id,exercise_key,note) VALUES(c,rid,'exercise:'||e1,'Keep personal');
 SELECT md5(coalesce(string_agg(j::text,'' ORDER BY j::text),'')) INTO before_history FROM(
 SELECT to_jsonb(w) j FROM workouts w WHERE data->>'routine_id'=rid::text UNION ALL SELECT to_jsonb(n) FROM routine_user_notes n WHERE routine_id=rid) q;
 s:=get_client_routine_structure(c,rid);
 INSERT INTO client_routine_checks VALUES('client reads exact original prescription',s-'assignment_id'-'client_id'-'routine_id'-'version'=source);
 BEGIN PERFORM get_client_routine_structure(c2,rid);RAISE EXCEPTION 'expected denial';EXCEPTION WHEN insufficient_privilege THEN INSERT INTO client_routine_checks VALUES('client cannot read other client',true);END;
 BEGIN PERFORM save_client_routine_structure(c,rid,1,'forbidden',NULL,jsonb_build_object('mode','snapshot_v2','expected',source,'days',source->'days'));RAISE EXCEPTION 'expected denial';EXCEPTION WHEN insufficient_privilege THEN INSERT INTO client_routine_checks VALUES('client cannot edit prescription',true);END;
 PERFORM set_config('request.jwt.claim.sub',tb::text,true);
 BEGIN PERFORM get_client_routine_structure(c,rid);RAISE EXCEPTION 'expected denial';EXCEPTION WHEN insufficient_privilege THEN INSERT INTO client_routine_checks VALUES('unassigned trainer cannot read',true);END;
 BEGIN PERFORM save_client_routine_structure(c,rid,1,'forbidden',NULL,'{}');RAISE EXCEPTION 'expected denial';EXCEPTION WHEN insufficient_privilege THEN INSERT INTO client_routine_checks VALUES('unassigned trainer cannot write',true);END;
 PERFORM set_config('request.jwt.claim.sub',t::text,true);
 other:=get_client_routine_structure(c2,rid);stale:=s;
 payload:=jsonb_build_object('mode','field_patch_v1','changes',jsonb_build_array(jsonb_build_object('entity','exercise','id',e1,'day_id',d1,'expected',jsonb_build_object('target','6-8'),'values',jsonb_build_object('target','17-19'))));
 saved:=save_client_routine_structure(c,rid,1,NULL,NULL,payload);
 INSERT INTO client_routine_checks VALUES('single target persisted in assignment table',(SELECT structure#>>'{days,0,exercises,0,target}'='17-19' FROM client_routine_customizations WHERE assignment_id=a1));
 INSERT INTO client_routine_checks VALUES('returned snapshot agrees with direct storage',saved-'assignment_id'-'client_id'-'routine_id'-'version'=(SELECT structure FROM client_routine_customizations WHERE assignment_id=a1));
 INSERT INTO client_routine_checks VALUES('single-field edit preserves all other fields',saved-'assignment_id'-'client_id'-'routine_id'-'version'=jsonb_set(source,'{days,0,exercises,0,target}','"17-19"'));
 INSERT INTO client_routine_checks VALUES('original template byte exact after client edit',client_routine_template_snapshot(rid)=source);
 INSERT INTO client_routine_checks VALUES('other client byte exact after edit',get_client_routine_structure(c2,rid)=other);
 BEGIN PERFORM save_client_routine_structure(c,rid,1,NULL,NULL,payload);RAISE EXCEPTION 'expected conflict';EXCEPTION WHEN serialization_failure THEN INSERT INTO client_routine_checks VALUES('stale version and duplicate submit rejected',true);END;
 BEGIN PERFORM save_routine_atomic(rid,'forbidden',NULL,payload);RAISE EXCEPTION 'expected scope';EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT LIKE 'routine_scope_required%' THEN RAISE;END IF;INSERT INTO client_routine_checks VALUES('old client editor cannot write shared template',true);END;
 BEGIN PERFORM reorder_my_routine_days_atomic(rid,ARRAY[d2,d1]);RAISE EXCEPTION 'expected scope';EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT LIKE 'routine_scope_required%' THEN RAISE;END IF;INSERT INTO client_routine_checks VALUES('old unscoped day reorder rejected',true);END;
 BEGIN PERFORM reorder_my_routine_exercises_atomic(d1,ARRAY[e2,e1]);RAISE EXCEPTION 'expected scope';EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT LIKE 'routine_scope_required%' THEN RAISE;END IF;INSERT INTO client_routine_checks VALUES('old unscoped exercise reorder rejected',true);END;
 s:=saved;
 payload:=jsonb_build_object('mode','field_patch_v1','changes',jsonb_build_array(jsonb_build_object('entity','exercise','id',e1,'day_id',d1,'expected',jsonb_build_object('sets',3,'target','17-19','rir','2','rest_seconds',180,'notes',NULL),'values',jsonb_build_object('sets',5,'target','','rir','0','rest_seconds',0,'notes',''))));
 saved:=save_client_routine_structure(c,rid,(s->>'version')::bigint,NULL,NULL,payload);
 INSERT INTO client_routine_checks VALUES('multiple fields empty strings and zero persist',saved#>'{days,0,exercises,0}'=jsonb_build_object('id',e1,'day_id',d1,'name','Original squat','sets',5,'target','','rir','0','rest_seconds',0,'exercise_order',4,'notes',''));
 payload:=jsonb_build_object('mode','field_patch_v1','changes',jsonb_build_array(jsonb_build_object('entity','exercise','id',e1,'day_id',d1,'expected',jsonb_build_object('target','','rir','0','notes',''),'values',jsonb_build_object('target',NULL,'rir',NULL,'notes',NULL))));
 saved:=save_client_routine_structure(c,rid,(saved->>'version')::bigint,NULL,NULL,payload);
 INSERT INTO client_routine_checks VALUES('explicit null values preserved',saved#>'{days,0,exercises,0,target}'='null' AND saved#>'{days,0,exercises,0,rir}'='null' AND saved#>'{days,0,exercises,0,notes}'='null');
 s:=saved;
 saved:=reorder_client_routine_structure(c,rid,(s->>'version')::bigint,jsonb_build_object('kind','exercise','day_id',d1,'ids',jsonb_build_array(e2,e1)));
 INSERT INTO client_routine_checks VALUES('client exercise order persisted',saved#>>'{days,0,exercises,0,id}'=e2::text AND saved#>>'{days,0,exercises,1,id}'=e1::text);
 INSERT INTO client_routine_checks VALUES('reorder preserves null empty zero',saved#>'{days,0,exercises,1,target}'='null' AND saved#>'{days,0,exercises,1,rest_seconds}'='0' AND saved#>'{days,0,exercises,0,target}'='""');
 saved:=save_client_routine_structure(c,rid,(saved->>'version')::bigint,NULL,NULL,jsonb_build_object('mode','field_patch_v1','changes',jsonb_build_array(jsonb_build_object('entity','exercise','id',e1,'day_id',d1,'expected',jsonb_build_object('rest_seconds',0),'values',jsonb_build_object('rest_seconds',210)))));
 INSERT INTO client_routine_checks VALUES('editing after reorder targets UUID',saved#>>'{days,0,exercises,1,rest_seconds}'='210' AND saved#>>'{days,0,exercises,0,rest_seconds}'='0');
 saved:=reorder_client_routine_structure(c,rid,(saved->>'version')::bigint,jsonb_build_object('kind','day','ids',jsonb_build_array(d2,d1)));
 INSERT INTO client_routine_checks VALUES('client day order persisted',saved#>>'{days,0,id}'=d2::text AND saved#>>'{days,1,id}'=d1::text);
 s:=saved;nextdays:=saved->'days';
 nextdays:=jsonb_set(nextdays,'{1,exercises}',nextdays#>'{1,exercises}'||jsonb_build_array(jsonb_build_object('id',NULL,'name','Added only for client','sets',2,'target','11-13','rir','1','rest_seconds',90,'notes',NULL)));
 nextdays:=nextdays||jsonb_build_array(jsonb_build_object('id',NULL,'name','Added client day','exercises','[]'::jsonb));
 saved:=save_client_routine_structure(c,rid,(s->>'version')::bigint,s->>'name',s->>'description',jsonb_build_object('mode','snapshot_v2','expected',s-'assignment_id'-'client_id'-'routine_id'-'version','days',nextdays));
 INSERT INTO client_routine_checks VALUES('addition gets new UUID in client snapshot',saved#>>'{days,1,exercises,2,id}' IS NOT NULL AND saved#>>'{days,2,id}' IS NOT NULL);
 INSERT INTO client_routine_checks VALUES('addition never writes physical exercise or day tables',(SELECT count(*)=3 FROM routine_exercises WHERE day_id IN(d1,d2)) AND (SELECT count(*)=2 FROM routine_days WHERE routine_id=rid));
 SELECT total_days,completed_days INTO total,done FROM get_client_custom_routine_cycle_progress(c,rid);
 INSERT INTO client_routine_checks VALUES('cycle uses client-specific days',total=3 AND done=1);
 SELECT total_days,completed_days INTO total,done FROM get_client_custom_routine_cycle_progress(c2,rid);
 INSERT INTO client_routine_checks VALUES('other client cycle keeps original denominator',total=2 AND done=0);
 s:=saved;nextdays:=jsonb_set(saved->'days','{1,exercises}',(saved#>'{days,1,exercises}')-0);
 saved:=save_client_routine_structure(c,rid,(s->>'version')::bigint,'Client-specific name','Client-specific description',jsonb_build_object('mode','snapshot_v2','expected',s-'assignment_id'-'client_id'-'routine_id'-'version','days',nextdays));
 INSERT INTO client_routine_checks VALUES('deletion applies only to client snapshot',jsonb_array_length(saved#>'{days,1,exercises}')=2 AND (SELECT count(*)=2 FROM routine_exercises WHERE day_id=d1));
 INSERT INTO client_routine_checks VALUES('custom name and description independent',saved->>'name'='Client-specific name' AND saved->>'description'='Client-specific description' AND (SELECT name='Synthetic shared original' AND description IS NULL FROM routines WHERE id=rid));
 s:=saved;
 BEGIN PERFORM reorder_client_routine_structure(c,rid,(s->>'version')::bigint,jsonb_build_object('kind','day','ids',jsonb_build_array(d1,d1)));RAISE EXCEPTION 'expected invalid';EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'invalid_order' THEN RAISE;END IF;INSERT INTO client_routine_checks VALUES('invalid permutation rejected',true);END;
 BEGIN PERFORM save_client_routine_structure(c,rid,(s->>'version')::bigint,NULL,NULL,jsonb_build_object('mode','field_patch_v1','changes',jsonb_build_array(jsonb_build_object('entity','exercise','id',e3,'day_id',d1,'expected',jsonb_build_object('sets',4),'values',jsonb_build_object('sets',9)))));RAISE EXCEPTION 'expected identity';EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'foreign_or_deleted_editor_record' THEN RAISE;END IF;INSERT INTO client_routine_checks VALUES('wrong exercise day identity rejected',true);END;
 BEGIN PERFORM save_client_routine_structure(c,rid,(s->>'version')::bigint,NULL,NULL,jsonb_build_object('mode','field_patch_v1','changes',jsonb_build_array(jsonb_build_object('entity','exercise','id',e3,'day_id',d2,'expected',jsonb_build_object('sets',99),'values',jsonb_build_object('sets',9)))));RAISE EXCEPTION 'expected conflict';EXCEPTION WHEN serialization_failure THEN INSERT INTO client_routine_checks VALUES('incorrect field expectation rejected',true);END;
 INSERT INTO client_routine_checks VALUES('rejected requests leave exact snapshot',get_client_routine_structure(c,rid)=s);
 payload:=jsonb_build_object('mode','field_patch_v1','scope','library','changes',jsonb_build_array(jsonb_build_object('entity','exercise','id',e1,'day_id',d1,'expected',jsonb_build_object('target','6-8'),'values',jsonb_build_object('target','Library only 30-35'))));
 PERFORM save_routine_atomic(rid,NULL,NULL,payload);
 INSERT INTO client_routine_checks VALUES('explicit library edit persists only original',(SELECT target='Library only 30-35' FROM routine_exercises WHERE id=e1));
 INSERT INTO client_routine_checks VALUES('library edit cannot update shared client snapshots',get_client_routine_structure(c,rid)=s AND get_client_routine_structure(c2,rid)=other);
 PERFORM reorder_template_routine_structure(rid,jsonb_build_object('kind','day','ids',jsonb_build_array(d2,d1)));
 PERFORM reorder_template_routine_structure(rid,jsonb_build_object('kind','exercise','day_id',d1,'ids',jsonb_build_array(e2,e1)));
 INSERT INTO client_routine_checks VALUES('explicit library reorder changes only original',(SELECT day_order=0 FROM routine_days WHERE id=d2) AND (SELECT exercise_order=0 FROM routine_exercises WHERE id=e2) AND get_client_routine_structure(c,rid)=s AND get_client_routine_structure(c2,rid)=other);
 PERFORM set_config('request.jwt.claim.sub',c::text,true);
 INSERT INTO client_routine_checks VALUES('client fresh read equals trainer confirmed snapshot',get_client_routine_structure(c,rid)=s);
 SELECT md5(coalesce(string_agg(j::text,'' ORDER BY j::text),'')) INTO h FROM(
 SELECT to_jsonb(w) j FROM workouts w WHERE data->>'routine_id'=rid::text UNION ALL SELECT to_jsonb(n) FROM routine_user_notes n WHERE routine_id=rid) q;
 INSERT INTO client_routine_checks VALUES('workouts and personal notes byte exact',h=before_history);
 PERFORM set_config('request.jwt.claim.sub',t::text,true);
 UPDATE routine_assignments SET client_deleted_at=now() WHERE id=a1;
 BEGIN PERFORM get_client_routine_structure(c,rid);RAISE EXCEPTION 'expected inactive';EXCEPTION WHEN insufficient_privilege THEN INSERT INTO client_routine_checks VALUES('withdrawn assignment denied',true);END;
 UPDATE routine_assignments SET client_deleted_at=NULL WHERE id=a1;
 INSERT INTO client_routine_checks VALUES('assignment restore preserves customization',get_client_routine_structure(c,rid)=s);
 BEGIN UPDATE routine_assignments SET client_id='495fa022-d51b-4bdd-a2f8-e031409b69f5' WHERE id=a1;RAISE EXCEPTION 'expected immutable';EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'assignment_identity_immutable' THEN RAISE;END IF;INSERT INTO client_routine_checks VALUES('assignment identity cannot be repointed',true);END;
 -- Exercise real authenticated RLS for a client-only day, without a JWT token.
 PERFORM set_config('request.jwt.claim.sub',c::text,true);
 EXECUTE 'SET LOCAL ROLE authenticated';
 INSERT INTO public.workouts(user_id,variant,day,workout_date,data) VALUES(c,'synthetic','Client-only day',current_date,
  jsonb_build_object('routine_id',rid,'routine_day_id',s#>>'{days,2,id}','exercises','[]'::jsonb)) RETURNING id INTO wid;
 EXECUTE 'RESET ROLE';
 INSERT INTO client_routine_checks VALUES('authenticated athlete can save own client-only day',EXISTS(SELECT 1 FROM workouts WHERE id=wid AND user_id=c AND data->>'routine_day_id'=s#>>'{days,2,id}'));
 EXECUTE 'SET LOCAL ROLE authenticated';
 BEGIN PERFORM structure FROM client_routine_customizations LIMIT 1;RAISE EXCEPTION 'expected direct table denial';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 EXECUTE 'RESET ROLE';
 INSERT INTO client_routine_checks VALUES('actual authenticated role denied direct snapshot access',true);
 PERFORM set_config('request.jwt.claim.sub',c2::text,true);
 EXECUTE 'SET LOCAL ROLE authenticated';
 BEGIN INSERT INTO public.workouts(user_id,variant,day,workout_date,data) VALUES(c2,'synthetic','Other client day',current_date,
  jsonb_build_object('routine_id',rid,'routine_day_id',s#>>'{days,2,id}','exercises','[]'::jsonb));RAISE EXCEPTION 'expected foreign day denial';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'workout_context_not_authorized' THEN RAISE;END IF;END;
 EXECUTE 'RESET ROLE';
 INSERT INTO client_routine_checks VALUES('other athlete cannot save foreign client-only day',true);
 PERFORM set_config('request.jwt.claim.sub',t::text,true);
 saved:=save_client_routine_structure(c,rid,(s->>'version')::bigint,s->>'name',s->>'description',jsonb_build_object('mode','snapshot_v2','expected',s-'assignment_id'-'client_id'-'routine_id'-'version','days',(s->'days')-0));
 PERFORM set_config('request.jwt.claim.sub',c::text,true);
 EXECUTE 'SET LOCAL ROLE authenticated';
 BEGIN INSERT INTO public.workouts(user_id,variant,day,workout_date,data) VALUES(c,'synthetic','Deleted client day',current_date,
  jsonb_build_object('routine_id',rid,'routine_day_id',d2,'exercises','[]'::jsonb));RAISE EXCEPTION 'expected deleted day denial';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'workout_context_not_authorized' THEN RAISE;END IF;END;
 EXECUTE 'RESET ROLE';
 INSERT INTO client_routine_checks VALUES('deleted assigned day cannot fall back to template',true);
 END $$;
INSERT INTO client_routine_checks SELECT 'customization direct table access denied',NOT has_table_privilege('authenticated','public.client_routine_customizations','SELECT,INSERT,UPDATE,DELETE');
INSERT INTO client_routine_checks SELECT 'customization RLS enabled without broad policies',(SELECT relrowsecurity FROM pg_class WHERE oid='public.client_routine_customizations'::regclass) AND NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='client_routine_customizations');
INSERT INTO client_routine_checks SELECT 'anon cannot call read or write',NOT has_function_privilege('anon','public.get_client_routine_structure(uuid,uuid)','EXECUTE') AND NOT has_function_privilege('anon','public.save_client_routine_structure(uuid,uuid,bigint,text,text,jsonb)','EXECUTE');
INSERT INTO client_routine_checks SELECT 'snapshot helper private',NOT has_function_privilege('authenticated','public.client_routine_template_snapshot(uuid)','EXECUTE');
SELECT name,pass FROM client_routine_checks ORDER BY name;
ROLLBACK;
