-- STAGING ONLY. Transactional actor/contract tests. No HTTP, Edge or provider dispatch.
begin;
set local timezone='Europe/Madrid';
create temporary table chat_result(result jsonb) on commit drop;
do $test$
declare
 u uuid:='495fa022-d51b-4bdd-a2f8-e031409b69f5';reviewer uuid:='6b47ae02-6574-46db-acdb-f00925efdd74';other uuid:='c14a2a6d-9853-431d-856c-4d742002187e';
 r uuid:=gen_random_uuid();d uuid:=gen_random_uuid();eid uuid:=gen_random_uuid();m uuid;rev uuid;rev2 uuid;k uuid;t uuid;t2 uuid;rec uuid;
 load jsonb;turn jsonb;again jsonb;claim jsonb;ctx jsonb;v jsonb;candidate jsonb;before jsonb;old_budget jsonb;answers jsonb;ss jsonb;
 denied boolean;message text;mode text;checks jsonb:='{}';co uuid;count_before bigint;chat_dispatched_before integer;chat_charge_before numeric;chat_reserved_before numeric;
 chat_config_before jsonb;chat_max_calls_before integer;chat_max_usd_before numeric;ledger jsonb;charge_before numeric;pending_count bigint;expires_before timestamptz;bound_before integer;fill integer;format_codepoint integer;
begin
 if current_setting('role',true) not in ('none','postgres') then raise exception 'chat_test_admin_context_required';end if;
 if not exists(select 1 from public.profiles where id=u and role='client') or not exists(select 1 from public.profiles where id=reviewer and role='trainer') then raise exception 'chat_test_controlled_actors_missing';end if;
 select jsonb_build_object('dispatched',dispatched,'charged',charged_usd,'reserved',reserved_usd,'enabled',enabled,'max_calls',max_calls,'max_usd',max_usd) into old_budget from coach_private.premium_analysis_budget where id;
 select chat_dispatched,chat_charged_usd,chat_reserved_usd into chat_dispatched_before,chat_charge_before,chat_reserved_before from coach_private.premium_analysis_budget where id;
 select chat_config,chat_max_calls,chat_max_usd into chat_config_before,chat_max_calls_before,chat_max_usd_before from coach_private.premium_analysis_budget where id;
 -- Isolate this controlled actor inside the ROLLBACK transaction, even after live JWT tests.
 -- This changes no Auth rows and restores every existing grant automatically on rollback.
 update public.context_grants set revoked_at=clock_timestamp() where user_id=u and scope in ('premium_training_history','premium_weekly_checkin','premium_chat') and revoked_at is null;
 -- SQL-only dispatch/expiry path needs the current shared admission gate; rolls back.
 update coach_private.premium_analysis_budget set chat_enabled=true,shared_enabled=true where id;
 insert into public.routines(id,owner_id,name)values(r,u,'SYNTHETIC Premium Chat transaction');
 insert into public.routine_days(id,routine_id,name,day_order)values(d,r,'Synthetic training day',0);
 insert into public.routine_exercises(id,day_id,name,sets,target,rir,rest_seconds,exercise_order,notes)values(eid,d,'Synthetic band curl',3,'8-12','2',180,0,'PRIVATE CANARY Chat');
 -- Current admission/entitlement gates apply to controlled fixtures too.
 perform public.premium_set_entitlement(u,true,clock_timestamp()+interval '14 days',array['tracking','weekly','analysis','chat','upgrade'],0,8,8);
 perform set_config('request.jwt.claim.sub',u::text,true);perform public.premium_admission_permission(true,'premium-followup-v1');
 perform set_config('request.jwt.claim.sub','',true);
 m:=public.premium_provision(u,r,current_date,6,now()+interval '1 day');select current_revision_id into rev from public.coach_mesocycles where id=m;
 update public.coach_mesocycles set state='active',intake_submitted_at=now(),reviewer_id=reviewer,intake='{"experience":"gt4","excluded":[],"inventory":{"equipment":["bands"],"custom":[]},"weekdays":["mon"],"minutes_by_day":{"mon":60}}',catalogue_bindings=jsonb_build_object(eid::text,'band_curl') where id=m;
 ss:='[{"set_number":1,"reps_min":8,"reps_max":12,"rir":2,"rest_seconds":180},{"set_number":2,"reps_min":10,"reps_max":12,"rir":1,"rest_seconds":180},{"set_number":3,"reps_min":12,"reps_max":15,"rir":1,"rest_seconds":180}]';
 select jsonb_set(snapshot,'{days,0,exercises,0,planned_sets}',ss) into before from public.routine_revisions where id=rev;
 update public.routine_revisions set snapshot=before,snapshot_hash=md5(before::text) where id=rev;
 perform set_config('request.jwt.claim.sub',u::text,true);
 load:=public.premium_chat_load(m);if load->'permission'<>'false'::jsonb or load->'messages'<>'[]'::jsonb then raise exception 'failed no implicit chat permission';end if;checks:=checks||'{"chat is not implicitly enabled by Premium enrollment":true}';
 denied:=false;begin perform public.premium_chat_permission(m,true);exception when others then denied:=sqlerrm='premium_history_consent_required';end;if not denied then raise exception 'failed history requirement';end if;checks:=checks||'{"chat permission requires separate history consent":true}';
 perform public.premium_permission(m,true);perform public.premium_chat_permission(m,true);
 if exists(select 1 from public.context_grants where user_id=u and scope='premium_weekly_checkin' and revoked_at is null) then raise exception 'failed weekly grant implicit creation';end if;checks:=checks||'{"chat permission does not implicitly grant checkin access":true}';
 foreach message in array array['Tengo dolor de rodilla','I have cancer','Mi correo es test@example.org',u::text,'Tomo medicación','Cuantas calorias debo consumir','Mi peso es 82 kg','peso 82 kg','mido 180 cm','my weight is 82 kg'] loop
  turn:=public.premium_chat_reserve(m,rev,gen_random_uuid(),message);
  if turn->>'state'<>'rejected' or turn->'id'<>'null'::jsonb then raise exception 'failed pre-persistence sensitive input';end if;
  checks:=checks||jsonb_build_object('sensitive input not persisted '||array_position(array['Tengo dolor de rodilla','I have cancer','Mi correo es test@example.org',u::text,'Tomo medicación','Cuantas calorias debo consumir','Mi peso es 82 kg','peso 82 kg','mido 180 cm','my weight is 82 kg'],message),true);
 end loop;
 if exists(select 1 from public.coach_messages where mesocycle_id=m) or exists(select 1 from public.coach_conversations where mesocycle_id=m) then raise exception 'failed sensitive no messages';end if;checks:=checks||'{"rejected sensitive inputs create zero messages and conversations":true}';
 if coach_private.premium_chat_input('Ejercicio con peso corporal')<>'allowed' or not coach_private.premium_chat_safe_output('Ejercicio con peso corporal') then raise exception 'failed bodyweight exercise false positive';end if;checks:=checks||'{"bodyweight exercise without personal measurements remains allowed":true}';
 if coach_private.premium_chat_input('Hack con peso 90 kg')<>'allowed' or not coach_private.premium_chat_safe_output('Hack con peso 90 kg') then raise exception 'failed exercise load false positive';end if;checks:=checks||'{"exercise load is not confused with a standalone personal weight":true}';
 if coach_private.premium_chat_input('Las mediciones de rendimiento registradas son comparables')<>'allowed' or not coach_private.premium_chat_safe_output('Las mediciones de rendimiento registradas son comparables') then raise exception 'failed performance measurement false positive';end if;checks:=checks||'{"performance measurements are not confused with medical terms":true}';
 if coach_private.premium_chat_safe_output('Mi peso es 82 kg') then raise exception 'failed biometric output';end if;checks:=checks||'{"personal measurements are also blocked before answer persistence":true}';
 foreach message in array array['',' ','<script>alert(1)</script>',repeat('a',4001),'Hack'||chr(8238)||'test'] loop
  denied:=false;begin perform public.premium_chat_reserve(m,rev,gen_random_uuid(),message);exception when others then denied:=sqlerrm='premium_chat_invalid_input';end;
  if not denied then raise exception 'failed malformed input';end if;checks:=checks||jsonb_build_object('malformed input rejected '||array_position(array['',' ','<script>alert(1)</script>',repeat('a',4001),'Hack'||chr(8238)||'test'],message),true);
 end loop;
 foreach format_codepoint in array array[173,1536,1541,1564,1757,1807,2192,2193,2274,6158,8203,8207,8234,8238,8288,8292,8294,8303,65279,65529,65531,69821,69837,78896,78911,113824,113827,119155,119162,917505,917536,917631] loop
  if coach_private.premium_chat_input('Hack'||chr(format_codepoint)||'test')<>'invalid' then raise exception 'failed Unicode Cf category';end if;
 end loop;
 denied:=false;begin perform public.premium_chat_reserve(m,rev,gen_random_uuid(),'Hack'||chr(1536)||'test');exception when others then denied:=sqlerrm='premium_chat_invalid_input';end;
 if not denied or exists(select 1 from public.coach_messages where mesocycle_id=m) then raise exception 'failed pre-persistence format control';end if;checks:=checks||'{"all Unicode Cf ranges are rejected and direct RPC cannot persist hidden format controls":true}';
 k:=gen_random_uuid();turn:=public.premium_chat_reserve(m,rev,k,'¿Qué significa RIR 1?');t:=(turn->>'id')::uuid;co:=(turn->>'conversation_id')::uuid;
 if turn->>'state'<>'reserved' or turn->>'revision_id'<>rev::text or turn::text ~ '(context_bundle|chat_grant_id|receipt|reserved_usd)' then raise exception 'failed safe reservation';end if;checks:=checks||'{"reservation captures exact revision and returns no internal bundle":true}';
 again:=public.premium_chat_reserve(m,rev,k,'¿Qué significa RIR 1?');if again->>'id'<>t::text then raise exception 'failed same key';end if;checks:=checks||'{"same key and content returns same turn":true}';
 again:=public.premium_chat_reserve(m,rev,gen_random_uuid(),'¿Qué significa RIR 1?');if again->>'id'<>t::text then raise exception 'failed repeated content';end if;checks:=checks||'{"repeated text with another key cannot dispatch twice":true}';
 denied:=false;begin perform public.premium_chat_reserve(m,rev,k,'¿Qué significa RIR 2?');exception when others then denied:=sqlerrm='premium_chat_key_conflict';end;if not denied then raise exception 'failed key conflict';end if;checks:=checks||'{"same key cannot change content":true}';
 denied:=false;begin perform public.premium_chat_reserve(m,rev,gen_random_uuid(),'¿Cuál es mi siguiente serie?');exception when others then denied:=sqlerrm='premium_chat_message_pending';end;if not denied then raise exception 'failed simultaneous turn';end if;checks:=checks||'{"one in-flight turn blocks another message":true}';
 perform set_config('request.jwt.claim.sub','',true);
 claim:=public.premium_chat_claim(u,t,1,'prepare');ctx:=claim->'provider';
 if claim->>'prepared'<>'true' or (select state from public.coach_messages where id=t)<>'reserved' or (select chat_dispatched from coach_private.premium_analysis_budget where id)<>chat_dispatched_before or (select chat_reserved_usd from coach_private.premium_analysis_budget where id)<>chat_reserved_before then raise exception 'failed prepare quota isolation';end if;checks:=checks||'{"prepare reads captured context without dispatch or cost reservation":true}';
 if ctx->>'schema_version'<>'premium-chat-context-v1' or ctx->'checkin_missing'<>'true'::jsonb or ctx->'checkin'<>'null'::jsonb then raise exception 'failed missing checkin context';end if;checks:=checks||'{"no weekly consent means absent checkin rather than invented values":true}';
 if ctx::text ~* '([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}|@|CANARY|workout_id|exercise_id|day_id|routine_id|user_id)' then raise exception 'failed chat minimization';end if;checks:=checks||'{"provider excludes UUID identities emails notes and canaries":true}';
 if not exists(select 1 from jsonb_array_elements(ctx->'evidence')x where x->>'id'='exercise_1.prescription') or not exists(select 1 from jsonb_array_elements(ctx->'evidence')x where x->>'id'='exercise_1.metric') then raise exception 'failed evidence';end if;checks:=checks||'{"prescription and metric evidence IDs are materialized server-side":true}';
 if not exists(select 1 from jsonb_array_elements(ctx->'evidence')x where x->>'id'='exercise_1.prescription' and x->'value'='{"source":"training.routine.exercises","exercise_ref":"exercise_1","kind":"prescription"}'::jsonb) or not exists(select 1 from jsonb_array_elements(ctx->'evidence')x where x->>'id'='exercise_1.metric' and x->'value'='{"source":"training.routine.exercises","exercise_ref":"exercise_1","kind":"metric"}'::jsonb) or ctx#>'{training,routine,exercises,0,planned_sets}'<>ss or exists(select 1 from jsonb_array_elements(ctx->'evidence')x where x->'value' ? 'metrics' or x->'value' ? 'exposures' or x->'value' ? 'planned_sets') then raise exception 'failed minimized evidence pointers';end if;checks:=checks||'{"evidence registry points to exact training facts without duplicating prescriptions or exposures":true}';
 if not exists(select 1 from jsonb_array_elements(ctx->'evidence')x where x->>'id'='intake' and x->'value'='{"source":"training.intake"}'::jsonb) or not exists(select 1 from jsonb_array_elements(ctx->'evidence')x where x->>'id'='schedule' and x->'value'='{"source":"week_schedule"}'::jsonb) then raise exception 'failed closed source registry';end if;checks:=checks||'{"intake and schedule evidence sources are closed server-defined paths":true}';
 claim:=public.premium_chat_claim(u,t,1,'mock');if claim->>'claimed'<>'true' then raise exception 'failed mock claim';end if;
 if public.premium_chat_claim(u,t,1,'mock')->>'claimed'<>'false' then raise exception 'failed double claim';end if;checks:=checks||'{"only one dispatch claim is possible for a turn":true}';
 v:='{"schema_version":"premium-chat-v1","answer":"RIR 1 indica una repetición estimada en reserva; sigue la prescripción registrada para esa serie.","facts_used":["exercise_1.prescription"],"suggested_action":"none","recommendation_candidate":null}';
 turn:=public.premium_chat_finish(u,t,v,null,'{"input_tokens":0,"output_tokens":0,"cached_input_tokens":0,"status":200}','[]');if turn->>'state'<>'completed' or turn->'recommendation_id'<>'null'::jsonb then raise exception 'failed answer finish';end if;checks:=checks||'{"validated answer completes without creating recommendation":true}';
 again:=public.premium_chat_finish(u,t,v,null,'{}','[]');if again<>turn then raise exception 'failed finish idempotency';end if;checks:=checks||'{"finish replay is byte-idempotent":true}';
 if (select summary->>'version' from public.coach_conversations where id=co)<>'premium-chat-summary-v1' or (select summary::text from public.coach_conversations where id=co) ~ 'RIR 1 indica' then raise exception 'failed summary';end if;checks:=checks||'{"summary stores structured references instead of raw answer or chain of thought":true}';
 perform set_config('request.jwt.claim.sub',u::text,true);turn:=public.premium_chat_reserve(m,rev,gen_random_uuid(),'¿Qué contiene mi programación?');t2:=(turn->>'id')::uuid;perform set_config('request.jwt.claim.sub','',true);
 claim:=public.premium_chat_claim(u,t2,1,'prepare');if jsonb_array_length(claim#>'{provider,last_messages}')<>1 then raise exception 'failed bounded history';end if;checks:=checks||'{"second turn sees its completed same-revision conversation":true}';
 perform public.premium_chat_claim(u,t2,1,'mock');turn:=public.premium_chat_finish(u,t2,jsonb_set(v,'{facts_used}','["made_up_fact"]'),null,'{}','[]');
 if turn->>'state'<>'failed' or (select output from public.coach_messages where id=t2) is not null or (select receipt->>'validation_stage' from public.coach_messages where id=t2)<>'evidence' then raise exception 'failed unsupported evidence';end if;checks:=checks||'{"invented fact ID rejects output without saving raw model output":true}';
 checks:=checks||'{"closed validation diagnostic exposes only the failed stage and no rejected text":true}';
 perform set_config('request.jwt.claim.sub',u::text,true);turn:=public.premium_chat_reserve(m,rev,gen_random_uuid(),'Explicación para probar protección de respuesta');t2:=(turn->>'id')::uuid;perform set_config('request.jwt.claim.sub','',true);
 perform public.premium_chat_claim(u,t2,1,'mock');turn:=public.premium_chat_finish(u,t2,jsonb_set(v,'{answer}','"Mi peso es 82 kg"'),null,'{}','[]');
 if turn->>'state'<>'failed' or turn->'answer'<>'null'::jsonb or (select output from public.coach_messages where id=t2) is not null or (select receipt->>'validation_stage' from public.coach_messages where id=t2)<>'answer_text' then raise exception 'failed protected answer diagnostics';end if;checks:=checks||'{"sensitive answer is discarded and diagnostics identify the stage without retaining content":true}';
 perform set_config('request.jwt.claim.sub',u::text,true);turn:=public.premium_chat_reserve(m,rev,gen_random_uuid(),'¿Podemos ajustar una serie del curl?');t2:=(turn->>'id')::uuid;perform set_config('request.jwt.claim.sub','',true);
 claim:=public.premium_chat_claim(u,t2,1,'mock');ctx:=claim->'provider';
 candidate:=jsonb_build_object('schema_version','premium-recommendation-v2','kind','MODIFY','facts',jsonb_build_array(jsonb_build_object('exercise_ref','exercise_1','claim',ctx#>>'{training,routine,exercises,0,metrics,trend}')),
 'interpretation','Propuesta acotada para revisión humana sobre la programación registrada.','reason','Revisar una serie concreta sin alterar las restantes.','confidence','low','changes',jsonb_build_array(jsonb_build_object('action','remove_set','exercise_ref','exercise_1','set_number',3,'from',(ss->2)-'set_number')));
 v:=jsonb_build_object('schema_version','premium-chat-v1','answer','La propuesta retira solo la tercera serie y queda pendiente de revisión; todavía no se ha aplicado.','facts_used',jsonb_build_array('exercise_1.prescription','exercise_1.metric'),'suggested_action','propose_recommendation','recommendation_candidate',candidate);
 turn:=public.premium_chat_finish(u,t2,v,null,'{}','[]');rec:=(turn->>'recommendation_id')::uuid;
 if turn->>'state'<>'completed' or not exists(select 1 from public.coach_recommendations where id=rec and state='pending_review' and kind='MODIFY' and analysis_week is null and analysis_trace->>'origin'='premium_chat') then raise exception 'failed candidate pipeline';end if;checks:=checks||'{"chat candidate enters existing pending_review pipeline with no weekly advancement marker":true}';
 if (select current_revision_id from public.coach_mesocycles where id=m)<>rev or (select sets from public.routine_exercises where id=eid)<>3 then raise exception 'failed no mutation';end if;checks:=checks||'{"candidate persistence does not alter routine or revision":true}';
 perform set_config('request.jwt.claim.sub',u::text,true);denied:=false;begin perform public.premium_accept_recommendation(rec);exception when others then denied:=sqlerrm='premium_not_ready';end;if not denied then raise exception 'failed pending accept';end if;checks:=checks||'{"athlete cannot accept before reviewer approval":true}';
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform public.premium_review_recommendation(rec,true,'Controlled transactional review of one series.');
 perform set_config('request.jwt.claim.sub',u::text,true);rev2:=public.premium_accept_recommendation(rec);if rev2=rev or (select tracking_week from public.coach_mesocycles where id=m)<>1 then raise exception 'failed chat acceptance tracking';end if;checks:=checks||'{"accepted chat change creates N+1 without completing or advancing the week":true}';
 if (select snapshot from public.routine_revisions where id=rev)<>before or (select snapshot#>'{days,0,exercises,0,planned_sets}' from public.routine_revisions where id=rev2)<>jsonb_build_array(ss->0,ss->1) then raise exception 'failed series preservation';end if;checks:=checks||'{"N is immutable and N+1 preserves surviving individualized series exactly":true}';
 if public.premium_accept_recommendation(rec)<>rev2 then raise exception 'failed duplicate accept';end if;checks:=checks||'{"accepted chat recommendation retains duplicate acceptance idempotency":true}';
 denied:=false;begin perform public.premium_chat_reserve(m,rev,gen_random_uuid(),'Pregunta nueva sobre revisión antigua');exception when others then denied:=sqlerrm='premium_chat_stale_revision';end;if not denied then raise exception 'failed stale turn';end if;checks:=checks||'{"frontend cannot reserve against obsolete revision":true}';
 turn:=public.premium_chat_reserve(m,rev2,gen_random_uuid(),'¿Cuál es mi prescripción actual?');t2:=(turn->>'id')::uuid;perform set_config('request.jwt.claim.sub','',true);claim:=public.premium_chat_claim(u,t2,1,'prepare');
 if claim#>>'{provider,mesocycle,current_revision}'<>'2' or claim#>'{provider,last_messages}'<>'[]'::jsonb then raise exception 'failed refreshed revision';end if;checks:=checks||'{"next message captures N+1 and excludes previous-revision assistant answers":true}';
 perform public.premium_chat_claim(u,t2,1,'mock');
 perform set_config('request.jwt.claim.sub',u::text,true);perform public.premium_chat_permission(m,false);perform set_config('request.jwt.claim.sub','',true);
 turn:=public.premium_chat_finish(u,t2,'{"schema_version":"premium-chat-v1","answer":"Respuesta tardía.","facts_used":[],"suggested_action":"none","recommendation_candidate":null}',null,'{}','[]');
 if turn->>'state'<>'superseded' or turn->'answer'<>'null'::jsonb then raise exception 'failed revocation late response';end if;checks:=checks||'{"revoked chat grant suppresses late answer and candidate":true}';
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform set_config('role','authenticated',true);
 if exists(select 1 from public.coach_recommendations where id=rec) then raise exception 'failed revoked reviewer reading';end if;checks:=checks||'{"revoking chat also removes reviewer access to candidate context":true}';
 perform set_config('role','none',true);
 perform set_config('request.jwt.claim.sub',u::text,true);load:=public.premium_chat_load(m);if load->'permission'<>'false'::jsonb or jsonb_array_length(load->'messages')<1 then raise exception 'failed retained own reading';end if;checks:=checks||'{"revocation blocks processing while owner retains own conversation":true}';
 perform public.premium_chat_permission(m,true);
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform set_config('role','authenticated',true);
 if exists(select 1 from public.coach_recommendations where id=rec) then raise exception 'failed old chat capture regrant revival';end if;checks:=checks||'{"new chat consent does not revive reviewer access to old captured grant":true}';
 perform set_config('role','none',true);perform set_config('request.jwt.claim.sub',u::text,true);
 turn:=public.premium_chat_reserve(m,rev2,gen_random_uuid(),'Pregunta para comprobar expiración');t2:=(turn->>'id')::uuid;perform set_config('request.jwt.claim.sub','',true);
 perform public.premium_chat_claim(u,t2,100,'openai');update public.coach_messages set expires_at=clock_timestamp()-interval '1 second' where id=t2;
 perform coach_private.premium_chat_expire(u);
 if not exists(select 1 from public.coach_messages where id=t2 and state='failed' and error='premium_chat_timeout' and finished_at is not null) or (select chat_reserved_usd from coach_private.premium_analysis_budget where id)<>chat_reserved_before or (select chat_charged_usd from coach_private.premium_analysis_budget where id)<chat_charge_before+.015 then raise exception 'failed expired reservation accounting';end if;checks:=checks||'{"expired dispatch fails and accounts unknown usage conservatively without retry":true}';
 if public.premium_chat_finish(u,t2,'{}',null,'{}','[]')->>'state'<>'failed' then raise exception 'failed expired late finish';end if;checks:=checks||'{"late finish cannot overwrite timed-out state":true}';
 -- Simulate exhausted administrative ceilings; counters are never reset and every write rolls back.
 select jsonb_build_object('dispatched',chat_dispatched,'charged',chat_charged_usd,'reserved',chat_reserved_usd) into ledger from coach_private.premium_analysis_budget where id;
 update coach_private.premium_analysis_budget set chat_max_calls=chat_dispatched where id;
 perform set_config('request.jwt.claim.sub',u::text,true);k:=gen_random_uuid();turn:=public.premium_chat_reserve(m,rev2,k,'Explicación para comprobar límite de llamadas');t2:=(turn->>'id')::uuid;perform set_config('request.jwt.claim.sub','',true);
 claim:=public.premium_chat_claim(u,t2,100,'openai');
 if claim->>'claimed'<>'false' or claim#>>'{message,state}'<>'failed' or claim#>>'{message,error}'<>'premium_chat_budget_exhausted' or (select finished_at from public.coach_messages where id=t2) is null then raise exception 'failed max-call closure';end if;checks:=checks||'{"exhausted call ceiling closes turn without dispatch or pending residue":true}';
 if (select jsonb_build_object('dispatched',chat_dispatched,'charged',chat_charged_usd,'reserved',chat_reserved_usd) from coach_private.premium_analysis_budget where id)<>ledger then raise exception 'failed exhausted claim ledger';end if;checks:=checks||'{"rejected dispatch changes neither calls nor reserved or charged cost":true}';
 perform set_config('request.jwt.claim.sub',u::text,true);again:=public.premium_chat_reserve(m,rev2,k,'Explicación para comprobar límite de llamadas');if again->>'id'<>t2::text or again->>'state'<>'failed' then raise exception 'failed exhausted replay';end if;checks:=checks||'{"failed idempotency key cannot silently retry provider":true}';
 update coach_private.premium_analysis_budget set chat_max_calls=chat_max_calls_before where id;
 turn:=public.premium_chat_reserve(m,rev2,gen_random_uuid(),'Explicación para comprobar límite de llamadas');t:=(turn->>'id')::uuid;
 if t=t2 or turn->>'state'<>'reserved' then raise exception 'failed explicit retry new key';end if;checks:=checks||'{"explicit retry with new key is possible after failed turn without automatic retry":true}';
 perform set_config('request.jwt.claim.sub','',true);perform public.premium_chat_claim(u,t,1,'mock');
 v:='{"schema_version":"premium-chat-v1","answer":"Sigue la prescripción registrada en tu sesión actual.","facts_used":[],"suggested_action":"none","recommendation_candidate":null}';perform public.premium_chat_finish(u,t,v,null,'{}','[]');
 update coach_private.premium_analysis_budget set chat_max_usd=chat_charged_usd+chat_reserved_usd where id;
 perform set_config('request.jwt.claim.sub',u::text,true);turn:=public.premium_chat_reserve(m,rev2,gen_random_uuid(),'Explicación para comprobar límite monetario');t2:=(turn->>'id')::uuid;perform set_config('request.jwt.claim.sub','',true);
 claim:=public.premium_chat_claim(u,t2,100,'openai');
 if claim->>'claimed'<>'false' or claim#>>'{message,error}'<>'premium_chat_budget_exhausted' or (select jsonb_build_object('dispatched',chat_dispatched,'charged',chat_charged_usd,'reserved',chat_reserved_usd) from coach_private.premium_analysis_budget where id)<>ledger then raise exception 'failed monetary cap';end if;checks:=checks||'{"monetary ceiling also rejects before provider with zero cost movement":true}';
 update coach_private.premium_analysis_budget set chat_max_usd=chat_max_usd_before,chat_config=jsonb_set(jsonb_set(chat_config,'{output_tokens}','500'),'{ttl_seconds}','65') where id;
 perform set_config('request.jwt.claim.sub',u::text,true);turn:=public.premium_chat_reserve(m,rev2,gen_random_uuid(),'Pregunta para comprobar límites capturados');t2:=(turn->>'id')::uuid;perform set_config('request.jwt.claim.sub','',true);
 select chat_charged_usd into charge_before from coach_private.premium_analysis_budget where id;
 claim:=public.premium_chat_claim(u,t2,100,'openai');select output_bound,expires_at into bound_before,expires_before from public.coach_messages where id=t2;
 if claim->>'claimed'<>'true' or claim->>'output_tokens'<>'500' or bound_before<>500 or expires_before<clock_timestamp()+interval '60 seconds' or expires_before>clock_timestamp()+interval '70 seconds' then raise exception 'failed captured config claim';end if;checks:=checks||'{"claim captures configured output limit and timeout used for its reservation":true}';
 update coach_private.premium_analysis_budget set chat_config=jsonb_set(jsonb_set(chat_config,'{output_tokens}','100'),'{ttl_seconds}','180') where id;
 if (select output_bound from public.coach_messages where id=t2)<>500 or (select expires_at from public.coach_messages where id=t2)<>expires_before then raise exception 'failed admin mutable config capture';end if;checks:=checks||'{"later administrator limits do not rewrite the in-flight captured bounds":true}';
 turn:=public.premium_chat_finish(u,t2,v,null,'{"input_tokens":100,"output_tokens":400,"cached_input_tokens":50,"status":200}','[]');
 if turn->>'state'<>'completed' or (select receipt->>'usage_known' from public.coach_messages where id=t2)<>'true' or (select chat_charged_usd from coach_private.premium_analysis_budget where id)<>charge_before+.0061375 or (select chat_reserved_usd from coach_private.premium_analysis_budget where id)<>chat_reserved_before then raise exception 'failed captured receipt charge';end if;checks:=checks||'{"receipt uses captured output bound and correctly accounts cached input after config change":true}';
 update coach_private.premium_analysis_budget set chat_config=jsonb_set(chat_config_before,'{input_chars}','10') where id;
 perform set_config('request.jwt.claim.sub',u::text,true);denied:=false;begin perform public.premium_chat_reserve(m,rev2,gen_random_uuid(),'Pregunta que supera el límite operativo');exception when others then denied:=sqlerrm='premium_chat_invalid_input';end;if not denied then raise exception 'failed configured input bound';end if;checks:=checks||'{"server input limit follows private configuration before persistence":true}';
 update coach_private.premium_analysis_budget set chat_config=jsonb_set(chat_config_before,'{history_turns}','1') where id;
 turn:=public.premium_chat_reserve(m,rev2,gen_random_uuid(),'Explicación del contexto reciente');t2:=(turn->>'id')::uuid;perform set_config('request.jwt.claim.sub','',true);claim:=public.premium_chat_claim(u,t2,1,'prepare');
 if jsonb_array_length(claim#>'{provider,last_messages}')<>1 then raise exception 'failed configured context history';end if;checks:=checks||'{"private history limit bounds context independently from retained messages":true}';
 perform public.premium_chat_claim(u,t2,1,'mock');perform public.premium_chat_finish(u,t2,v,null,'{}','[]');
 update coach_private.premium_analysis_budget set chat_config=chat_config_before where id;
 -- Add closed synthetic turns in this transaction up to the default daily boundary.
 select count(*) into count_before from public.coach_messages where user_id=u and created_at::date=current_date;
 if count_before>24 then raise exception 'chat_test_daily_baseline_already_above_boundary';end if;
 fill:=24-count_before::integer;
 insert into public.coach_messages(conversation_id,user_id,routine_id,mesocycle_id,idempotency_key,sequence_no,user_message,message_digest,state,error,revision_id,revision_no,week,context_bundle,expires_at,finished_at)
 select co,u,r,m,gen_random_uuid(),(select next_sequence from public.coach_conversations where id=co)+x,'Synthetic closed quota sample '||x,md5('Synthetic closed quota sample '||x),'failed','premium_chat_provider_failed',rev2,2,1,(select context_bundle from public.coach_messages where id=t2),clock_timestamp(),clock_timestamp() from generate_series(1,fill)x;
 select count(*) into count_before from public.coach_messages where user_id=u and created_at::date=current_date;
 select count(*) into pending_count from public.coach_messages where conversation_id=co and state in ('reserved','dispatched');
 perform set_config('request.jwt.claim.sub',u::text,true);denied:=false;begin perform public.premium_chat_reserve(m,rev2,gen_random_uuid(),'Pregunta por encima de la cuota diaria');exception when others then denied:=sqlerrm='premium_chat_daily_limit';end;
 if not denied or count_before<>24 or (select count(*) from public.coach_messages where user_id=u and created_at::date=current_date)<>24 or pending_count<>0 then raise exception 'failed daily boundary';end if;checks:=checks||'{"twenty-fifth accepted daily turn is rejected without pending messages":true}';
 perform set_config('request.jwt.claim.sub',other::text,true);denied:=false;begin perform public.premium_chat_load(m);exception when others then denied:=sqlerrm='premium_chat_not_authorized';end;if not denied then raise exception 'failed cross owner load';end if;checks:=checks||'{"another client cannot load conversation through privileged RPC":true}';
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform set_config('role','authenticated',true);
 if exists(select 1 from public.coach_messages where user_id=u) then raise exception 'failed reviewer chat access';end if;checks:=checks||'{"assigned reviewer has no raw chat SELECT policy":true}';
 denied:=false;begin perform public.premium_chat_claim(u,t2,1,'mock');exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'failed client service claim';end if;checks:=checks||'{"authenticated reviewer cannot execute service-only dispatch RPC":true}';
 perform set_config('role','none',true);perform set_config('request.jwt.claim.sub','',true);
 if (select jsonb_build_object('dispatched',dispatched,'charged',charged_usd,'reserved',reserved_usd,'enabled',enabled,'max_calls',max_calls,'max_usd',max_usd) from coach_private.premium_analysis_budget where id)<>old_budget then raise exception 'failed independent analysis ledger';end if;checks:=checks||'{"chat never resets or charges the previous analysis ledger":true}';
 insert into pg_temp.chat_result values(jsonb_build_object('checks',checks,'count',(select count(*) from jsonb_object_keys(checks)),'failed',0,'completed',true,'provider_calls',0));
end $test$;
select * from pg_temp.chat_result;
rollback;
