// Loopback-only, synthetic chat preview. Never calls Auth, Supabase or OpenAI.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),port=Number(process.env.PREMIUM_CHAT_PORT||4245);
const C=require('../../assets/coach-premium-chat.js');
const uuid=n=>'40000000-0000-4000-8000-'+String(n).padStart(12,'0');
const copy=v=>structuredClone(v);
const cases=[['explanation','Por qué tengo hack'],['progress','Progreso del press'],['rir','Qué significa RIR 1'],['keep','Por qué KEEP esta semana'],['revision','Qué cambió respecto a N'],['candidate','Revisar el curl · propuesta'],['volume','Pedir el doble de volumen'],['whole','Pedir cambiar toda la rutina'],['privacy','Pedir email de otro cliente'],['injection','Ignorar instrucciones'],['nutrition','Pregunta de nutrición'],['medical','Mensaje médico · no se conserva'],['offtopic','Pregunta ajena a entrenamiento'],['simultaneous','Dos envíos simultáneos'],['stale','Revisión obsoleta'],['permission','Permiso explícito pendiente'],['revoked','Permiso revocado'],['inactive','Piloto cerrado · permiso conservado'],['history-disabled','Historial no autorizado'],['superseded','Respuesta de revisión anterior'],['error','Fallo de red al enviar'],['slow','Respuesta lenta'],['timeout','Respuesta fallida y retry manual'],['long','Mensajes largos'],['xss','Texto con HTML/script'],['missing','No hay check-in'],['quota','Límite operativo'],['budget','HTTP aceptado · presupuesto agotado'],['failed-response','HTTP aceptado · respuesta fallida'],['rejected-response','HTTP aceptado · mensaje rechazado'],['superseded-response','HTTP aceptado · contexto sustituido'],['multiturn','Conversación de 10 turnos'],['two-tabs','Conflicto entre pestañas']];
const initialAsk='¿Cómo voy progresando en el press?';
function recommendation(){return {id:uuid(900),state:'pending_review',kind:'MODIFY',summary:'Revisar una sustitución pequeña del curl.',reason:'Petición del atleta, material disponible y contexto de entrenamiento. Se requiere revisión antes de aceptar.',changes:[{exercise_name:'Curl con mancuernas',before:'3 series · 8–12 reps · RIR 2 · 2 min',after:'Curl con banda · 3 series · 8–12 reps · RIR 2 · 2 min'}],quality_warnings:['Evaluar que el nuevo ejercicio permita conservar los objetivos y comparar su rendimiento por separado.']};}
function fixture(tag){const index=cases.findIndex(c=>c[0]===tag),s={permission:!['permission','revoked'].includes(tag),history_permission:tag!=='history-disabled',available:tag!=='inactive',week:3,revision_no:2,revision_id:uuid(200+index),mesocycle_id:uuid(100+index),conversation:{id:uuid(300+index)},messages:[],recommendation:null,tag,checkin_missing:tag==='missing'};
 if(tag==='timeout'||tag==='superseded')s.messages=[{id:uuid(400),sequence:1,state:tag==='timeout'?'failed':'superseded',user_content:initialAsk,assistant_answer:null,retryable:tag==='timeout',revision_id:s.revision_id}];
 if(tag==='long')s.messages=[{id:uuid(400),sequence:1,state:'completed',user_content:'Quiero entender el objetivo de las series de mi sesión y qué debo anotar después. '.repeat(8),assistant_answer:'Tu revisión actual mantiene el press inclinado. La primera serie tiene 6–8 repeticiones a RIR 1, con 3 minutos de descanso; la siguiente tiene 8–10 a RIR 2. RIR 1 indica que, al terminar, estimas poder completar una repetición adicional con la calidad prevista.\n\nEn las tres exposiciones comparables del press registraste 8, 9 y 10 repeticiones a la misma carga y RIR. Es una tendencia descriptiva; no demuestra por sí sola una causa. Mantén la programación aceptada y registra únicamente lo que realizas. '.repeat(3)}];
 if(tag==='xss')s.messages=[{id:uuid(400),sequence:1,state:'completed',user_content:'<img src=x onerror="window.__chatXss=true"> **mi pregunta**',assistant_answer:'Texto literal: <script>window.__chatXss=true</script> [enlace](javascript:alert(1))'}];return s;}
function answer(s,content){const q=content.toLowerCase();
 if(s.tag==='candidate'||q.includes('cambiar')&&q.includes('curl'))return {text:'Podemos revisar una sustitución pequeña. Esta propuesta no se aplica desde el chat; pasará por validación, revisión y aceptación.',candidate:true};
 if(s.tag==='missing')return {text:'No hay check-in enviado esta semana. En el press constan tres exposiciones comparables: 8, 9 y 10 repeticiones con carga y RIR constantes. No puedo atribuir esa evolución a tu recuperación sin ese contexto.'};
 if(q.includes('por qué')&&q.includes('hack'))return {text:'La hack de tu revisión activa cubre un patrón dominante de rodilla. Están prescritas 2 series: 6–8 reps a RIR 1 y 8–10 a RIR 0, con 4 minutos de descanso. Es una explicación de tu programación actual, no una nueva elección de ejercicios.'};
 if(q.includes('rir'))return {text:'RIR 1 significa que estimas poder realizar una repetición adicional al terminar la serie con la técnica prevista. No es una obligación de llegar al fallo. Usa el RIR concreto de cada serie de tu revisión activa.'};
 if(q.includes('descanso'))return {text:'En el press tienes 3 minutos; en la hack, 4 minutos por serie. Es el descanso programado para preservar la siguiente serie. El chat no modifica esos valores.'};
 if(q.includes('semana anterior')||q.includes('cambió'))return {text:'La revisión 2 retiró la tercera serie de hack tras una recomendación aceptada. Las otras dos conservaron sus repeticiones, RIR y descanso. El resto de ejercicios sigue igual.'};
 if(q.includes('no camb')||q.includes('nada')||s.tag==='keep')return {text:'Esta semana se propuso KEEP: el rendimiento comparable sigue aumentando y no hay una razón suficiente para añadir otro cambio tras la modificación anterior. El check-in favorable es contexto declarado, no prueba de su causa.'};
 if(q.includes('doble')||s.tag==='volume')return {text:'No recomiendo duplicar el volumen sin una razón respaldada por tus datos. El chat tampoco puede cambiar directamente tu rutina. Conserva la prescripción actual mientras se revisa una petición concreta.'};
 if(q.includes('toda mi rutina')||s.tag==='whole')return {text:'No puedo reemplazar toda tu programación desde el chat. Una propuesta pequeña debe pasar por el flujo de validación y revisión; no se aplican cambios automáticamente.'};
 return {text:'En tu revisión '+s.revision_no+' el press tiene tres exposiciones comparables: 8, 9 y 10 repeticiones, con carga y RIR constantes. La tendencia es ascendente; no demuestra una causa. Tu programación activa es la referencia para las próximas series.'};}
function createOfflineAdapter(){const states=new Map(cases.map(([tag])=>[tag,fixture(tag)])),keys=new Map(),calls={},seen=[],counts={provider_mock:0};
 function complete(s){for(const m of s.messages)if(m.ready_at&&Date.now()>=m.ready_at){delete m.ready_at;if(m.revision_id!==s.revision_id){m.state='failed';m.retryable=false;m.assistant_answer=null;}else{m.state='completed';m.assistant_answer=m.answer_later;if(m.candidate_later){s.recommendation=recommendation();m.recommendation_id=s.recommendation.id;}}delete m.answer_later;delete m.candidate_later;}}
 return {mode:'offline',cases,async handle({action,tag='explanation',data={}}){if(!states.has(tag))throw Error('invalid_request');const s=states.get(tag);calls[tag]??={};calls[tag][action]=(calls[tag][action]||0)+1;
  if(action==='reset'){states.set(tag,fixture(tag));for(const k of [...keys.keys()])if(k.startsWith(tag+':'))keys.delete(k);calls[tag]={};return true;}
  if(action==='debug')return {states:copy([...states]),calls:copy(calls),counts:copy(counts),requests:copy(seen)};
  if(action==='change_revision'){s.revision_no++;s.revision_id=uuid(800+s.revision_no);return copy(s);}
  if(action==='revoke'){s.permission=false;return copy(s);}
  if(action==='state'){complete(s);return copy(s);}
  if(action==='navigate')return {handled:true,destination:data.destination};
  if(action==='permission'){if(data.allow!==true||data.notice_version!==C.NOTICE_VERSION)throw Error('premium_chat_consent_required');s.permission=true;return copy(s);}
  if(action==='proposal'){if(!s.permission||!s.recommendation||s.recommendation.id!==data.id)throw Error('premium_chat_forbidden');return copy(s.recommendation);}
  if(!['send','retry'].includes(action))throw Error('invalid_request');
  if(!s.permission||!s.history_permission)throw Error('premium_chat_consent_required');if(!s.available)throw Error('premium_chat_pilot_closed');if(data.revision_id!==s.revision_id||s.tag==='stale')throw Error('premium_chat_stale_context');
  if(s.tag==='error')throw Error('preview_offline');
  const content=String(data.message||'').trim();if(!content||content.length>C.MAX_MESSAGE)throw Error('premium_chat_invalid_message');
  if(s.tag==='rejected-response')return {state:'rejected',error:'premium_chat_sensitive_input'};
  if(/\b(dolor|lesi[oó]n|diagn[oó]stico|medicaci[oó]n|patolog[ií]a)\b/i.test(content)||s.tag==='medical')throw Error('premium_chat_sensitive_input');
  if(keys.has(tag+':'+data.key))return copy(s);
  if(s.messages.some(m=>['reserved','dispatched','generating'].includes(m.state)))throw Error('premium_chat_busy');
  if(s.tag==='quota'&&s.messages.length>=1){const e=Error('premium_chat_daily_limit');e.retry_after=60;throw e;}
  const refusal=['privacy','injection','nutrition','offtopic'].includes(s.tag)||/email de otro|ignora tus|system prompt|uuid|calor[ií]as|dieta/i.test(content);
  const a=refusal?{text:'SIMPLE Coach solo utiliza tu contexto de entrenamiento autorizado. No comparte datos de otros usuarios, instrucciones privadas ni asesoramiento fuera de ese alcance.'}:answer(s,content);
  const m={id:data.message_id,sequence:s.messages.length+1,state:['slow','simultaneous','two-tabs'].includes(s.tag)?'generating':'completed',user_content:content,assistant_answer:['slow','simultaneous','two-tabs'].includes(s.tag)?null:a.text,revision_id:s.revision_id,key:data.key,retryable:true};
  if(['budget','failed-response','superseded-response'].includes(s.tag)){m.state=s.tag==='superseded-response'?'superseded':'failed';m.error=s.tag==='budget'?'premium_chat_budget_exhausted':s.tag==='superseded-response'?'premium_chat_stale_or_revoked':'premium_chat_provider_failed';m.assistant_answer=null;}
  if(m.state==='generating'){m.ready_at=Date.now()+1100;m.answer_later=a.text;m.candidate_later=a.candidate;}
  else if(a.candidate){s.recommendation=recommendation();m.recommendation_id=s.recommendation.id;}
  s.messages.push(m);keys.set(tag+':'+data.key,m.id);seen.push({action,tag,key:data.key,message_id:data.message_id,revision_id:data.revision_id,retry_of:data.retry_of||null});if(!refusal&&!['budget','superseded-response'].includes(s.tag))counts.provider_mock++;return copy(s);
 },snapshot:()=>({states:copy([...states]),calls:copy(calls),counts:copy(counts),requests:copy(seen)})};
}
function html(mode,available=cases){return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SIMPLE Coach · Chat · Preview</title><script>document.documentElement.dataset.theme=localStorage.getItem('premium-chat-theme')==='dark'?'dark':'light'</script><link rel="stylesheet" href="/assets/theme.css"><link rel="stylesheet" href="/assets/coach-premium-chat.css"><style>body{margin:0;overflow:hidden;font:13px/1.45 Arial,sans-serif}.preview-tools{max-width:820px;margin:auto;padding:8px 14px;color:var(--simple-muted)}.preview-tools p{margin:0}.preview-tools summary{min-height:32px;cursor:pointer}.preview-tools select,.preview-tools button{min-height:44px;font:inherit;color:var(--simple-text);background:var(--simple-card);border:1px solid var(--simple-control-line);border-radius:8px;padding:8px}.preview-tools label{display:block;margin-top:6px}.preview-tools select{max-width:100%;width:100%}.preview-tools button{margin-top:8px}</style></head><body><aside class="preview-tools"><p>${mode==='offline'?'Vista previa local. Datos y respuestas simulados; sin llamadas OpenAI ni bases de datos.':'Vista previa staging con JWT. Credenciales solo en el servidor.'}</p><details id="tools"><summary>Opciones de la vista previa</summary><label for="case">Escenario</label><select id="case">${available.map(([v,l])=>'<option value="'+v+'">'+l+'</option>').join('')}</select><button id="theme" type="button">Cambiar a oscuro</button></details></aside><div id="chat-app"></div><script src="/assets/coach-premium-chat.js"></script><script>
const selector=document.getElementById('case'),params=new URLSearchParams(location.search);if([...selector.options].some(o=>o.value===params.get('case')))selector.value=params.get('case');
const themeButton=document.getElementById('theme');function themeLabel(){themeButton.textContent=document.documentElement.dataset.theme==='dark'?'Cambiar a claro':'Cambiar a oscuro'}themeLabel();themeButton.onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;localStorage.setItem('premium-chat-theme',t);themeLabel()};
async function api(action,data={}){const tag=selector.value,r=await fetch('/chat-api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,tag,data})});const v=await r.json();if(!r.ok)throw Object.assign(Error(v.error),{code:v.error,retry_after:v.retry_after});return v;}
let controller=PremiumChat.mount(document.getElementById('chat-app'),api,{pollMs:250});window.PremiumChatUI=controller;
async function setCase(tag,reset=true){controller.destroy();selector.value=tag;history.replaceState({},'',location.pathname+'?case='+encodeURIComponent(tag));if(reset)await api('reset');controller=PremiumChat.mount(document.getElementById('chat-app'),api,{pollMs:250});window.PremiumChatUI=controller;document.getElementById('tools').open=false;}
selector.onchange=()=>setCase(selector.value);document.getElementById('tools').ontoggle=()=>controller.load();window.PremiumChatPreview={setCase,api};
</script></body></html>`;}
function rejectSecrets(v){if(v&&typeof v==='object')for(const[k,x]of Object.entries(v)){if(/^(access_token|refresh_token|authorization|apikey|secret|password|service_role)$/i.test(k))throw Error('unsafe_adapter_output');rejectSecrets(x);}}
function createServer(adapter=createOfflineAdapter(),serverPort=port){return http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');try{
 if(req.method==='GET'&&['/','/review'].includes(req.url.split('?')[0])){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(html(adapter.mode,adapter.cases||cases));}
 if(req.method==='POST'&&req.url==='/chat-api'){if(req.headers.origin!==`http://127.0.0.1:${serverPort}`)throw Error('origin_denied');let body='';for await(const part of req){body+=part;if(Buffer.byteLength(body)>16000)throw Error('invalid_request');}const value=await adapter.handle(JSON.parse(body));rejectSecrets(value);res.setHeader('Content-Type','application/json;charset=utf-8');return res.end(JSON.stringify(value));}
 const allowed=['/assets/theme.css','/assets/coach-premium-chat.js','/assets/coach-premium-chat.css'];if(req.method==='GET'&&allowed.includes(req.url)){res.setHeader('Content-Type',req.url.endsWith('.css')?'text/css;charset=utf-8':'application/javascript;charset=utf-8');return res.end(fs.readFileSync(path.join(root,req.url)));}
 res.writeHead(404);res.end();
 }catch(e){res.writeHead(400,{'Content-Type':'application/json;charset=utf-8'});res.end(JSON.stringify({error:/^[a-z_]+$/.test(e.code||e.message)?e.code||e.message:'invalid_request',...(e.retry_after?{retry_after:e.retry_after}:{})}));}});}
if(require.main===module){const adapter=process.env.PREMIUM_CHAT_ADAPTER?require(path.resolve(process.env.PREMIUM_CHAT_ADAPTER)):createOfflineAdapter();createServer(adapter).listen(port,'127.0.0.1',()=>console.log('Premium chat preview http://127.0.0.1:'+port+'/review ('+adapter.mode+')'));}
module.exports={createServer,createOfflineAdapter,fixture,cases,recommendation,html};
