const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const legacy='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a';
process.env.PLAYWRIGHT_BROWSERS_PATH=legacy+'/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const old=fs.readFileSync(legacy+'/work/test-ux-browser.cjs','utf8'),stub=vm.runInNewContext(old.slice(old.indexOf('const stub='),old.indexOf('const results=[]'))+'stub');
const html=fs.readFileSync('index.html','utf8'),results=[];
(async()=>{for(const engine of ['chromium','webkit']){const b=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});try{
const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true});p.setDefaultTimeout(4000);const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/*',r=>r.request().url()==='https://simple.test/'?r.fulfill({body:html,contentType:'text/html'}):r.request().url().includes('cdn.jsdelivr')?r.fulfill({body:stub,contentType:'application/javascript'}):r.abort());await p.goto('https://simple.test/');
async function test(name,fn){try{await fn();results.push({engine,name,pass:true})}catch(e){results.push({engine,name,pass:false,error:e.message});console.log('FAIL '+engine+' '+name+' '+e.message)}}
async function setup(kind='routine'){await p.evaluate(async kind=>{
 document.querySelectorAll('.modal.show').forEach(e=>closeM(e.id));user={id:'U'};profile={role:'trainer'};window.__simpleStarted=true;$('auth').style.display='none';$('app').style.display='block';window.__editingWorkout=null;window.__savingEditedWorkout=false;window.__routineSaving=false;window.__clientRoutineEdit=null;
 mock.tables.routines=[{id:'R',owner_id:'U',name:'Routine',description:null}];routines=mock.tables.routines;
 mock.tables.routine_days=[{id:'D',routine_id:'R',name:'Day',day_order:0}];mock.tables.routine_exercises=[{id:'E',day_id:'D',name:'Press',sets:2,target:null,rir:'1-2',rest_seconds:120,exercise_order:0,notes:null},{id:'F',day_id:'D',name:'Press',sets:3,target:'',rir:'0',rest_seconds:0,exercise_order:1,notes:''}];
 window.writes=[];window.messages=[];toast=s=>messages.push(s);renderMine=async()=>{};window.testMode='normal';
 if(!window.originalFrom)window.originalFrom=db.from;db.from=originalFrom;
 db.rpc=async(name,args)=>{writes.push({name,args});if(name==='save_routine_atomic'){if(window.testMode!=='noop')for(const ch of args.p_days.changes||[])Object.assign(mock.tables.routine_exercises.find(e=>e.id===ch.id),ch.values);if(window.testMode==='readfail')db.from=()=>{throw Error('read failed')};return {data:'R'}}
 if(name==='update_client_workout_data'){if(window.testMode!=='noop')mock.tables.workouts[0].data=structuredClone(args.p_data.data);return {data:window.testMode==='missing'?{}:{id:'W',data:mock.tables.workouts[0].data}}}
 if(name==='get_client_routine_history')return window.testMode==='readfail'?{error:{message:'read failed'}}:{data:structuredClone(mock.tables.workouts)};return {data:[]};};
 if(kind==='routine'){await openLibraryRoutineEditor('R');openClientRoutineDayEditor(0)}else{
 workoutRoutine={id:'R'};mock.tables.workouts=[{id:'W',user_id:'CLIENT',day:'Day',workout_date:'2026-01-01',data:{routine_id:'R',routine_day_id:'D',duration_seconds:25,custom:{keep:true},exercises:[{exercise_id:'E',notes:null,rest_minutes:null,sets:[{kg:null,reps:0,rir:'',done:true,custom:7}]},{exercise_id:'F',notes:'',rest_minutes:0,sets:[{kg:'0',reps:'',rir:0,done:false}]}]}}];window.workoutHistory=structuredClone(mock.tables.workouts);window.before=structuredClone(workoutHistory[0]);openM('trainModal');await editWorkout('W');}
},kind)}
const rinput=()=>p.locator('#daysEditor input[placeholder="2"]').first();
await test('Focused input is committed without blur',async()=>{await setup();await rinput().fill('3');await p.evaluate(()=>saveClientRoutineEditor());assert.deepEqual(await p.evaluate(()=>writes[0].args.p_days.changes),[{entity:'exercise',id:'E',day_id:'D',expected:{rir:'1-2'},values:{rir:'3'}}])});
await test('Revert field to original sends no write',async()=>{await setup();await rinput().fill('3');await rinput().fill('1-2');await p.evaluate(()=>saveClientRoutineEditor());assert.equal(await p.evaluate(()=>writes.length),0)});
for(const field of ['sets','rest_seconds'])await test('Blank '+field+' is not coerced to zero',async()=>{await setup();await p.locator('#daysEditor input[onchange*="\''+field+'\'"]').first().fill('');await p.evaluate(()=>saveClientRoutineEditor());assert.equal(await p.evaluate(()=>writes.length),0)});
await test('Routine false RPC success never shows success or closes editor',async()=>{await setup();await p.evaluate(()=>window.testMode='noop');await rinput().fill('3');await p.evaluate(()=>saveClientRoutineEditor());assert(await p.locator('#editModal').isVisible());assert(!(await p.evaluate(()=>messages.includes('Rutina guardada'))));assert.equal(await p.evaluate(()=>mock.tables.routine_exercises[0].rir),'1-2')});
await test('Routine failed verification keeps edits and reports uncertainty',async()=>{await setup();await p.evaluate(()=>window.testMode='readfail');await rinput().fill('3');await p.evaluate(()=>saveClientRoutineEditor());assert(await p.locator('#editModal').isVisible());assert(!(await p.evaluate(()=>messages.includes('Rutina guardada'))));assert.equal(await rinput().inputValue(),'3')});
for(const mode of ['missing','noop','readfail'])await test('History '+mode+' never substitutes local data for server',async()=>{await setup('history');await p.evaluate(m=>window.testMode=m,mode);await p.locator('.history-edit-input[data-edit-field="rir"]').first().fill('3');await p.evaluate(()=>saveEditedWorkout('W'));assert.equal(await p.evaluate(()=>__editingWorkout),'W');assert.deepEqual(await p.evaluate(()=>workoutHistory[0]),await p.evaluate(()=>before));assert(!(await p.evaluate(()=>messages.includes('Cambios guardados correctamente'))))});
for(const field of ['kg','reps','rir','rest_minutes'])await test('History invalid '+field+' is rejected',async()=>{await setup('history');await p.locator('[data-edit-field="'+field+'"]').first().fill(field==='rir'?'11':'-1');await p.evaluate(()=>saveEditedWorkout('W'));assert.equal(await p.evaluate(()=>writes.length),0)});
await test('Legacy id is a supported stable identity',async()=>{await setup('history');await p.evaluate(async()=>{const e=workoutHistory[0].data.exercises[0];e.id=e.exercise_id;delete e.exercise_id;mock.tables.workouts=structuredClone(workoutHistory);__editingWorkout=null;await editWorkout('W')});await p.locator('.history-edit-input[data-edit-field="kg"]').first().fill('0');await p.evaluate(()=>saveEditedWorkout('W'));assert.equal(await p.evaluate(()=>mock.tables.workouts[0].data.exercises[0].sets[0].kg),'0');assert(await p.evaluate(()=>messages.includes('Cambios guardados correctamente')))});
for(const mode of ['missing','duplicate'])await test('Identity '+mode+' never falls back to index/name',async()=>{await setup('history');await p.evaluate(async m=>{if(m==='missing')delete workoutHistory[0].data.exercises[0].exercise_id;else workoutHistory[0].data.exercises[1].exercise_id='E';__editingWorkout=null;await editWorkout('W')},mode);await p.locator('.history-edit-input[data-edit-field="kg"]').first().fill('5');await p.evaluate(()=>saveEditedWorkout('W'));assert.equal(await p.evaluate(()=>writes.length),0)});
await test('Zero/blank preserve all untouched values and metadata',async()=>{await setup('history');await p.locator('.history-edit-input[data-edit-field="kg"]').first().fill('0');await p.locator('.history-edit-input[data-edit-field="reps"]').first().fill('');await p.evaluate(()=>saveEditedWorkout('W'));const expected=await p.evaluate(()=>before);expected.data.exercises[0].sets[0].kg='0';expected.data.exercises[0].sets[0].reps='';assert.deepEqual(await p.evaluate(()=>workoutHistory[0]),expected)});
for(const change of ['close','user'])await test('Late history verification after '+change+' cannot replace newer state',async()=>{await setup('history');await p.locator('.history-edit-input[data-edit-field="kg"]').first().fill('15');await p.evaluate(()=>{const originalRpc=db.rpc;db.rpc=(name,args)=>name==='get_client_routine_history'?new Promise(resolve=>window.finishVerification=resolve):originalRpc(name,args);window.pendingSave=saveEditedWorkout('W')});await p.waitForFunction(()=>!!window.finishVerification);assert(await p.evaluate(async change=>{const response=structuredClone(mock.tables.workouts);if(change==='close')closeM('trainModal');else user={id:'NEW'};window.workoutHistory=[{id:'NEW',data:{keep:true}}];$('trainBody').textContent='Nueva vista';const beforeState=JSON.stringify(workoutHistory),beforeUI=$('trainBody').innerHTML;finishVerification({data:response});await pendingSave;window.finishVerification=null;return JSON.stringify(workoutHistory)===beforeState&&$('trainBody').innerHTML===beforeUI},change))});
await test('No JavaScript errors',async()=>assert.deepEqual(errors,[]));
}finally{await b.close()}}
fs.writeFileSync(path.join(__dirname,'results/contracts.json'),JSON.stringify({passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass),results},null,2));console.log(JSON.stringify({passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass)}));if(results.some(x=>!x.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
