const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),extract=require('../integration/function-source.cjs');
const html=fs.readFileSync('index.html','utf8'),prescription=fs.readFileSync('assets/coach-prescription.js','utf8');
const c=vm.createContext({Map,Set,Promise,Intl,console,user:{id:'owner'},simpleCoach:{routineHints:null},esc:v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),SimpleCoachProgrammingV5:{minutes:s=>s/60+' min'}});c.window=c;
for(const name of ['coachV5Prescription','coachV5Line'])vm.runInContext(extract(prescription,name),c);
for(const name of ['sessionOverviewExercises','workoutResetSuffix','workoutDraftKey','workoutNotesKey','persistExerciseNote'])vm.runInContext(extract(html,name),c);
vm.runInContext('const __noteWriteChains=new Map();',c);
let count=0;const check=(label,ok)=>{assert(ok,label);count++;};
(async()=>{
 const e={id:'exercise-uuid',name:'Press <script>',sets:3,target:'8-12',rir:'0',rest_seconds:150,notes:'Line 1\nLine 2'};
 const before=JSON.stringify(e),render=()=>c.sessionOverviewExercises({exercises:[e]},'routine');
 check('exercise identity and text escaped',render().includes('data-exercise-id="exercise-uuid"')&&render().includes('Press &lt;script>'));
 check('zero RIR retained and minutes localized',render().includes('<div>0</div>')&&render().includes('2,5 min'));
 check('rendering does not mutate prescription',JSON.stringify(e)===before);
 check('empty session has useful state',c.sessionOverviewExercises({exercises:[]},'routine').includes('todavía no tiene ejercicios'));
 const planned=[{set_number:1,reps_min:8,reps_max:12,rir:0,rest_seconds:150},{set_number:2,reps_min:10,reps_max:15,rir:1,rest_seconds:180},{set_number:3,reps_min:12,reps_max:15,rir:2,rest_seconds:120}];
 c.simpleCoach.routineHints={owner:'owner',routine:'routine',byId:new Map([[e.id,{version:2,sets:planned,target:e.target,rir:e.rir,rest:e.rest_seconds}]])};
 const p=JSON.stringify(planned),markup=render();
 check('structured per-series prescription remains complete',markup.includes('8–12 reps')&&markup.includes('10–15 reps')&&markup.includes('12–15 reps')&&markup.includes('RIR 0')&&markup.includes('RIR 1')&&markup.includes('RIR 2'));
 check('structured prescription read without mutation',JSON.stringify(planned)===p);
 check('another routine cannot inherit hints',!c.sessionOverviewExercises({exercises:[e]},'another-routine').includes('<ol>'));
 check('new homonym cannot inherit hints',!c.sessionOverviewExercises({exercises:[{...e,id:'new-uuid'}]},'routine').includes('<ol>'));
 const writes=[];c.db={from:()=>({upsert:async(row,options)=>{writes.push({row,options});return {error:null}}})};
 await c.persistExerciseNote('owner',['routine'],'exercise:'+e.id,'note',()=>true);
 check('normal notes keep existing payload',writes.length===1&&!Object.hasOwn(writes[0].row,'statistics_stage_id')&&writes[0].row.exercise_key==='exercise:'+e.id);
 await c.persistExerciseNote('owner',['routine'],'exercise:'+e.id,'new note',()=>true,'reset-uuid');
 check('new notes carry captured reset identity',writes[1].row.statistics_stage_id==='reset-uuid'&&writes[1].row.user_id==='owner'&&writes[1].row.routine_id==='routine');
 await c.persistExerciseNote('owner',['routine'],'exercise:'+e.id,'stale',()=>false,'reset-uuid');
 check('late navigation does not send note',writes.length===2);
 c.workoutRoutine={id:'routine'};c.activeWorkout={day:{id:'day'}};
 check('existing draft and notes keys remain compatible',c.workoutDraftKey()==='simple_workout_draft_v2:owner:routine:day'&&c.workoutNotesKey()==='simple_routine_notes_v3:owner:routine:day');
 c.activeWorkout.statisticsStage={training_reset_id:'reset-uuid'};
 check('cleared notes and drafts have reset namespace',c.workoutDraftKey().endsWith(':reset:reset-uuid')&&c.workoutNotesKey().endsWith(':reset:reset-uuid'));
 console.log(count+'/'+count+' presentation/note/draft checks');
})().catch(e=>{console.error(e);process.exitCode=1});
