const fs=require('fs'),cp=require('child_process'),vm=require('vm'),assert=require('assert/strict');
const read=f=>fs.readFileSync(f,'utf8').replace(/\r\n/g,'\n'),old=f=>cp.execFileSync('git',['show','f0a4cfb:'+f],{encoding:'utf8',maxBuffer:4e6}).replace(/\r\n/g,'\n'),results=[];
function test(name,fn){try{fn();results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:e.message})}}
const html=read('index.html'),before=old('index.html'),scripts=s=>[...s.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).filter(Boolean);
test('All inline behavior identical apart from approved presentation copy, attributes and color token',()=>assert.deepEqual(scripts(html.replace('Sin registro anterior.','Todavía no hay un registro anterior de este ejercicio.').replaceAll('class="previous-session-sets" tabindex="0" role="region" aria-label="Series de la última sesión"','class="previous-session-sets"').replace('style="color:var(--text)">No tienes rutinas todavía.','style="color:#fff">No tienes rutinas todavía.')),scripts(before)));
test('Auth removes only the minimum wait and guards the late initial error snapshot; logout exact',()=>assert.equal(read('assets/auth.js').replace("  // Bootstrap owns an invalid callback. A late initial SDK snapshot must not\n  // replace its expired-link message with the browser's previously stored session.\n  if(event==='INITIAL_SESSION'&&SIMPLE_AUTH_CALLBACK.error)return;\n",''),old('assets/auth.js').replace("    await new Promise(resolve=>setTimeout(resolve,Math.max(0,750-(performance.now()-simpleAuth.startedAt))));\n",'')));
test('OAuth unchanged byte for byte',()=>assert.equal(read('assets/oauth.js'),old('assets/oauth.js')));
test('Same approved Atlas Git blob, no image duplicated',()=>assert.equal(cp.execFileSync('git',['hash-object','--path=assets/atlas.webp','assets/atlas.webp'],{encoding:'utf8'}).trim(),cp.execFileSync('git',['rev-parse','f0a4cfb:assets/atlas.webp'],{encoding:'utf8'}).trim()));
test('Onboarding markup unchanged except accessible no-copy real loader',()=>assert.equal(html.match(/<main id="auth"[\s\S]*?<\/main>/)[0].replace('<div class="auth-loading" id="authLoading" role="status" aria-label="Cargando SIMPLE"></div>','<div class="auth-loading" id="authLoading" role="status" hidden>Comprobando tu sesión…</div>'),before.match(/<main id="auth"[\s\S]*?<\/main>/)[0]));
test('Theme init precedes CSS and SDK; only centralized palette selects dark',()=>{assert(html.indexOf('assets/theme.js')<html.indexOf('<style>'));assert.equal((read('assets/theme.css').match(/data-theme=/g)||[]).length,1);for(const file of ['assets/interior.css','assets/settings.css','assets/auth.css'])assert(!read(file).includes('data-theme='));});
test('New settings/theme scripts compile and contain no remote data API',()=>{for(const file of ['assets/theme.js','assets/settings.js']){const s=read(file);new vm.Script(s);assert(!/fetch\(|db\.|\.from\(|\.rpc\(|signOut\(/.test(s))}});
test('No fictional legal links and settings delegates logout exactly once',()=>{assert(read('assets/auth.js').includes('terms:null,privacy:null'));assert.equal((read('assets/settings.js').match(/\blogout\(\)/g)||[]).length,1);assert(!/onclick=|href=/.test(html.match(/<dialog id="settingsDialog"[\s\S]*?<\/dialog>/)[0]));});
test('Storage unavailable defaults to Light; explicit choice and storage events work without OS coupling',()=>{
 const events={},doc={documentElement:{dataset:{},style:{}}},win={addEventListener(name,fn){events[name]=fn},dispatchEvent(){}};
 vm.runInNewContext(read('assets/theme.js'),{window:win,document:doc,matchMedia(){throw Error('OS preference must not be read')},localStorage:{getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}},CustomEvent:class{}});
 assert.equal(doc.documentElement.dataset.theme,'light');win.simpleTheme.set('dark');assert.equal(doc.documentElement.dataset.theme,'dark');win.simpleTheme.set('system');assert.equal(doc.documentElement.dataset.theme,'dark');events.storage({key:'simple_theme_v1',newValue:'light'});assert.equal(doc.documentElement.dataset.theme,'light');events.storage({key:'simple_theme_v1',newValue:'dark'});assert.equal(doc.documentElement.dataset.theme,'dark');events.storage({key:'simple_theme_v1',newValue:'system'});assert.equal(win.simpleTheme.choice,'light');events.storage({key:'simple_theme_v1',newValue:'invalid'});assert.equal(win.simpleTheme.choice,'light');
});
const report={passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass),results};fs.mkdirSync('tests/polish/results',{recursive:true});fs.writeFileSync('tests/polish/results/contracts.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.failed.length)process.exitCode=1;
