const fs=require('fs'),path=require('path'),assert=require('assert/strict');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='http://127.0.0.1:4182/',out=path.join(__dirname,'results');fs.mkdirSync(out,{recursive:true});
const results=[],shots=[];
(async()=>{for(const engine of ['chromium','webkit']){
const browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});
try{for(const width of [320,360,390,430,768,1280]){
 const p=await browser.newPage({viewport:{width,height:900},hasTouch:width<700});p.setDefaultTimeout(5000);const errors=[],remote=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))remote.push(r.url())});p.on('dialog',d=>d.dismiss());
 const test=async(name,fn)=>{try{await fn();results.push({engine,width,name,pass:true})}catch(e){results.push({engine,width,name,pass:false,error:e.message})}};
 const go=async(role,state='normal')=>{await p.goto(base+'?role='+role+'&state='+state);await p.waitForFunction(()=>window.previewReady);if(state!=='loading'&&role==='trainer')await p.waitForFunction(()=>document.querySelector('#clients .client-overview-card')||document.querySelector('#clients .error')||document.querySelector('#clients .empty'))};
 const shot=async(name)=>{await p.screenshot({path:path.join(out,engine+'-'+width+'-'+name+'.png'),fullPage:true});shots.push(engine+'-'+width+'-'+name+'.png')};
 const fit=async(selector)=>{assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const boxes=await p.locator(selector).evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>{const r=e.getBoundingClientRect();return {x:r.x,right:r.right}}));assert(boxes.every(r=>r.x>=-.5&&r.right<=width+.5),'Content extends outside viewport')};
 const unchanged=async(selector)=>{
 if(!selector.startsWith('#auth')){const colors=await p.locator(selector).evaluate(el=>({bg:getComputedStyle(el).backgroundColor,color:getComputedStyle(el).color}));assert.equal(colors.bg,'rgb(247, 245, 241)');await fit(selector);return;}const data=await p.evaluate(sel=>{
  const props=['color','backgroundColor','backgroundImage','fontFamily','fontSize','fontWeight','padding','borderRadius','borderColor','display','gridTemplateColumns'];
  const nodes=[document.querySelector(sel),...document.querySelector(sel).querySelectorAll('button,input,.card,h2,h3')];
  const snapshot=()=>nodes.map(el=>Object.fromEntries(props.map(k=>[k,getComputedStyle(el)[k]])));
  const enabled=snapshot(),link=document.querySelector('link[href="assets/interior.css"]');link.disabled=true;const baseline=snapshot();link.disabled=false;return {enabled,baseline};
 },selector);assert.deepEqual(data.enabled,data.baseline)};
 await go('client');
 await test('Athlete home: responsive and exact current-cycle count',async()=>{await fit('#shared .card');assert(await p.locator('#shared').innerText().then(t=>t.includes('2/5 del ciclo actual')));assert.equal(await p.locator('#shared [role=progressbar]').getAttribute('aria-valuenow'),'2')});
 await test('Home controls retain touch target and paper palette',async()=>{const v=await p.locator('#app').evaluate(el=>({bg:getComputedStyle(el).backgroundColor,targets:[...el.querySelectorAll('button')].filter(e=>e.getClientRects().length).map(e=>e.getBoundingClientRect().height)}));assert.equal(v.bg,'rgb(247, 245, 241)');assert(v.targets.every(h=>h>=43.5))});
 await shot('athlete');
 await test('Add routine keeps existing code dialog destination',async()=>{await p.locator('#addRoutineButton').click();await p.locator('#redeemModal.show').waitFor();await unchanged('#redeemModal .sheet');await p.locator('#redeemModal').getByRole('button',{name:'Cancelar',exact:true}).click()});
 await test('Open athlete routine: five sessions with original UUID destinations',async()=>{await p.locator('#shared .routine .primary').click();await p.locator('.interior-session-list').waitFor();assert.equal(await p.locator('.interior-session-list button').count(),5);await fit('#trainModal .sheet');assert.match(await p.locator('.interior-session-list button').first().getAttribute('onclick'),/00000000-0000-4000-8000-000000000030/)});
 await shot('athlete-sessions');
 await test('Training destination intact; coherent interior styling',async()=>{await p.locator('.interior-session-list button').first().click();await p.locator('.setrow').first().waitFor();assert.equal(await p.evaluate(()=>activeWorkout.day.id),'00000000-0000-4000-8000-000000000030');assert.equal(await p.locator('.interior-session-list').count(),0);await unchanged('#trainModal .sheet');await shot('workout-or-history')});
 await test('Athlete history destination and coherent styling',async()=>{await p.locator('#trainModalActions').getByRole('button',{name:'Historial',exact:true}).click();await p.locator('.history-session').first().waitFor();await unchanged('#trainModal .sheet');await p.locator('#trainModalActions').getByRole('button',{name:'Cerrar',exact:true}).click()});
 await go('trainer');
 await test('Trainer dashboard uses existing clients and current-cycle values',async()=>{assert.equal(await p.locator('.client-overview-card').count(),3);assert.match(await p.locator('.client-overview-card').first().innerText(),/2\/5 del ciclo actual/);await fit('.client-overview-card')});await shot('trainer-clients');
 await test('Client card opens original profile; profile uses interior styling',async()=>{await p.locator('.client-overview-card').first().click();await p.locator('#clientModal.show').waitFor();assert.match(await p.locator('#clientModalTitle').innerText(),/Alejandra/);await unchanged('#clientModal .sheet');await p.locator('#clientModal').getByRole('button',{name:'Cerrar',exact:true}).click()});
 await test('Routine tab and existing actions remain available',async()=>{await p.locator('#tMine').click();await p.locator('[data-open-routine]').first().waitFor();assert.equal(await p.locator('#mine .routine').count(),2);for(const name of ['Abrir','Progreso','Compartir','Eliminar'])assert.equal(await p.locator('#mine').getByRole('button',{name,exact:true}).count(),2);await fit('#mine .routine')});await shot('trainer-routines');
 await test('Routine open: session list and back navigation retained',async()=>{await p.locator('[data-open-routine]').first().click();await p.locator('#clientSessionList').waitFor();assert.equal(await p.locator('#clientSessionList .routine-editor-day').count(),5);assert(await p.getByRole('button',{name:'← Mis rutinas',exact:true}).isVisible());await fit('#editModal .sheet')});await shot('trainer-sessions');
 await test('Session editor destination and interior styling',async()=>{await p.locator('#clientSessionList').getByRole('button',{name:'Editar sesión',exact:true}).first().click();await p.locator('#daysEditor').waitFor();assert.equal(await p.locator('#clientSessionList').count(),0);await unchanged('#editModal .sheet');await p.getByRole('button',{name:'← Sesiones',exact:true}).click();await p.locator('#clientSessionList').waitFor()});
 await test('Trainer training and return to sessions remain available',async()=>{await p.locator('.routine-day-train').first().click();await p.locator('.setrow').first().waitFor();await unchanged('#trainModal .sheet');await p.locator('#trainModalActions').getByRole('button',{name:'← Sesiones',exact:true}).click();await p.locator('#clientSessionList').waitFor()});
 await test('History action retains day UUID and excluded styling',async()=>{await p.locator('#clientSessionList').getByRole('button',{name:'Historial',exact:true}).first().click();await p.locator('#trainModal.show').waitFor();assert.equal(await p.evaluate(()=>window.__routineHistoryContext.dayId),'00000000-0000-4000-8000-000000000030');await unchanged('#trainModal .sheet');await p.locator('#trainModalActions').getByRole('button',{name:'← Sesiones',exact:true}).click();await p.locator('#clientSessionList').waitFor()});
 await test('Back to routines closes list; progress destination unchanged',async()=>{await p.getByRole('button',{name:'← Mis rutinas',exact:true}).click();assert.equal(await p.locator('#editModal').evaluate(e=>e.classList.contains('show')),false);await p.locator('#mine').getByRole('button',{name:'Progreso',exact:true}).first().click();await p.locator('#clientProgressModal.show').waitFor();await unchanged('#clientProgressModal .sheet');await p.locator('#clientProgressModal').getByRole('button',{name:'Cerrar',exact:true}).click()});
 await test('Share and create routine destinations remain original',async()=>{await p.locator('#mine').getByRole('button',{name:'Compartir',exact:true}).first().click();await p.locator('#shareModal.show').waitFor();await unchanged('#shareModal .sheet');await p.locator('#shareModal').getByRole('button',{name:'Cerrar',exact:true}).click();await p.locator('#tNew').click();await p.locator('#new').waitFor();await unchanged('#app');await fit('#new .card')});
 for(const role of ['client','trainer']){
 await go(role,'long');await test(role+' long names remain in viewport',async()=>{await fit(role==='client'?'#shared .card':'.client-overview-card')});await shot(role+'-long');
 await go(role,'empty');await test(role+' empty view preserves navigation and has no fictional cards',async()=>{assert.equal(await p.locator(role==='client'?'#shared .routine':'.client-overview-card').count(),0);await fit('#app');assert(await p.locator('#tabs').isVisible())});await shot(role+'-empty');
 }
 await go('trainer','loading');await test('Client loading state remains legible',async()=>{assert.match(await p.locator('#clients').innerText(),/Cargando/);await fit('#clients .card')});await shot('loading');
 await go('trainer','error');await test('Client error state remains visible and readable',async()=>{assert.match(await p.locator('#clients .error').innerText(),/No se pudo conectar/);await fit('#clients .error')});await shot('error');
 await go('auth');await p.waitForFunction(()=>simpleAuth.screen==='welcome');await test('Approved onboarding unaffected by interior styles',()=>unchanged('#auth'));await test('No JavaScript errors or remote API traffic',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(remote,[])});
 await p.close();
}}finally{await browser.close()}
}
const report={passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass),results,shots,environment:'Local synthetic data, CSP blocks all API traffic. No remote mutations.'};fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed},null,2));if(report.failed.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
