// Local, isolated, navigable preview. No production SDK or API connection.
const http=require('http'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'../..'),port=Number(process.env.INTERIOR_PORT||4182);
const routes={'/assets/theme.css':['assets/theme.css','text/css'],'/assets/settings.css':['assets/settings.css','text/css'],'/assets/theme.js':['assets/theme.js','application/javascript'],'/assets/settings.js':['assets/settings.js','application/javascript'],'/assets/oauth.js':['assets/oauth.js','application/javascript'],'/assets/auth.css':['assets/auth.css','text/css'],'/assets/auth.js':['assets/auth.js','application/javascript'],'/assets/interior.css':['assets/interior.css','text/css'],'/assets/atlas.webp':['assets/atlas.webp','image/webp'],'/mock-sdk.js':['tests/interior/mock-sdk.js','application/javascript'],'/preview-seed.js':['tests/interior/preview-seed.js','application/javascript']};
const review='<!doctype html><html lang="es"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SIMPLE · Revisión interior</title><style>body{margin:0;font:14px Arial;color:#252929;background:#f7f5f1}header{padding:14px 20px;border-bottom:1px solid #d9d9d4;display:flex;gap:12px;align-items:center;flex-wrap:wrap}select{padding:8px;border:1px solid #d9d9d4;border-radius:6px;background:white}small{color:#656965}iframe{border:0;width:100%;height:calc(100dvh - 88px);display:block}</style><header><b>SIMPLE · Revisión interior</b><a href="/polish-gallery" style="color:inherit">Capturas del pulido</a><label>Vista <select id="role"><option value="client">Atleta</option><option value="trainer">Entrenador</option><option value="auth">Acceso y carga</option></select></label><label>Datos <select id="state"><option value="normal">Ejemplo</option><option value="long">Nombres largos</option><option value="empty">Vacío</option><option value="trash">Papelera llena</option><option value="history">Historial y gráficas</option><option value="auth-loading">Simular carga inicial</option><option value="social">OAuth preparado (en Onboarding)</option><option value="loading">Carga de clientes</option><option value="error">Error de clientes</option></select></label><small>Datos ficticios locales. Sin conexión a Supabase; no guarda cambios.</small></header><iframe title="SIMPLE" src="/?role=client"></iframe><script>for(const s of document.querySelectorAll("select"))s.onchange=()=>document.querySelector("iframe").src="/?role="+document.getElementById("role").value+"&state="+document.getElementById("state").value</script></html>';
http.createServer((req,res)=>{
 const u=new URL(req.url,'http://127.0.0.1');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'none'; form-action 'none'; object-src 'none'; base-uri 'none'");
 if(req.method!=='GET'){res.writeHead(405);return res.end()}
 if(u.pathname==='/polish-gallery'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(require('../polish/gallery.cjs').html())}
 if(u.pathname.startsWith('/polish-screens/')){const data=require('../polish/gallery.cjs').image(u.pathname.slice(16));if(!data){res.writeHead(404);return res.end()}res.setHeader('Content-Type','image/png');return res.end(data)}
 const reports=['browser','screens'].flatMap(name=>{try{return JSON.parse(fs.readFileSync(path.join(__dirname,'results',name+'.json'))).shots||[]}catch(_){return []}});
 const screenshots=[...new Set(['before-create.png','before-trash-client.png','before-trash-trainer.png',...reports])].filter(name=>/^[a-z0-9-]+\.png$/.test(name));
 if(u.pathname==='/gallery'){
  res.setHeader('Content-Type','text/html; charset=utf-8');
  return res.end('<!doctype html><html lang="es"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SIMPLE · Capturas reales</title><style>body{font:15px Arial;background:#f7f5f1;color:#252929;margin:24px}nav{display:flex;gap:16px;flex-wrap:wrap}select{padding:10px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:24px}figure{margin:20px 0}img{width:100%;height:auto;max-height:800px;object-fit:contain;object-position:top;background:white;border:1px solid #d9d9d4}figcaption{padding:12px 0;overflow-wrap:anywhere}a{color:inherit}</style><h1>Capturas reales de SIMPLE</h1><nav><a href="/review">Volver a la preview</a><label>Filtrar <select id="filter"><option value="chromium-390">Móvil 390 · Chromium</option><option value="webkit-320">Móvil 320 · WebKit</option><option value="chromium-1280">Escritorio · Chromium</option><option value="before">Antes del cambio</option><option value="">Todas</option></select></label></nav><p>Datos ficticios locales. Las capturas no acreditan OAuth real ni pruebas físicas en iPhone.</p><main>'+screenshots.map(name=>'<figure data-name="'+name+'"><a href="/screens/'+name+'"><img loading="lazy" src="/screens/'+name+'" alt="'+name+'"></a><figcaption>'+name+'</figcaption></figure>').join('')+'</main><script>const f=document.getElementById("filter");function filter(){document.querySelectorAll("figure").forEach(e=>e.hidden=!e.dataset.name.includes(f.value))}f.onchange=filter;filter()</script></html>');
 }
 if(u.pathname.startsWith('/screens/')){const name=u.pathname.slice(9);if(!screenshots.includes(name)){res.writeHead(404);return res.end()}res.setHeader('Content-Type','image/png');return res.end(fs.readFileSync(path.join(__dirname,'results',name)))}
 if(u.pathname==='/review'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(review)}
 if(u.pathname==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(fs.readFileSync(path.join(root,'index.html'),'utf8').replace('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.115.0','/mock-sdk.js').replace('</body>','<script src="/preview-seed.js"></script></body>'))}
 const route=routes[u.pathname];if(!route){res.writeHead(404);return res.end()}
 res.setHeader('Content-Type',route[1]+'; charset=utf-8');res.end(fs.readFileSync(path.join(root,route[0])));
}).listen(port,'127.0.0.1',()=>console.log('Interior preview: http://127.0.0.1:'+port+'/review — synthetic data, CSP connect-src none'));
