const fs=require('fs'),path=require('path'),assert=require('assert/strict');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.join(__dirname,'results'),results=[],shots=[];
(async()=>{for(const engine of ['chromium','webkit']){
 const b=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});
 try{for(const width of [320,360,390,430,768,1280]){
  const p=await b.newPage({viewport:{width,height:900},hasTouch:width<700});p.setDefaultTimeout(6000);const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.dismiss());
  const test=async(name,fn)=>{try{await fn();results.push({engine,width,name,pass:true})}catch(e){results.push({engine,width,name,pass:false,error:e.message});}};
  const go=async(role,state='normal')=>{await p.goto('http://127.0.0.1:4182/?role='+role+'&state='+state);await p.waitForFunction(()=>window.previewReady);};
  const shot=async(name)=>{const file=engine+'-'+width+'-'+name+'.png';await p.screenshot({path:path.join(out,file),fullPage:!(await p.locator('.modal.show').count())});shots.push(file);};
  const surface=async(selector)=>{const r=await p.locator(selector).evaluate(el=>({w:el.clientWidth,s:el.scrollWidth,bg:getComputedStyle(el).backgroundColor,x:el.getBoundingClientRect().x,right:el.getBoundingClientRect().right}));assert(r.s<=r.w+1,'Surface horizontal overflow: '+JSON.stringify(r));assert(r.x>=0&&r.right<=width+1);assert(['rgb(247, 245, 241)','rgb(255, 255, 255)'].includes(r.bg),'Old theme '+r.bg);};
  await test('Create routine: labels, all fields, focus and short viewport scrolling',async()=>{await go('trainer');await p.locator('#tNew').click();await p.locator('#rn').fill('Rutina de ejemplo con nombre largo y objetivos específicos');await p.locator('#rd').fill('Descripción de ejemplo');await p.getByRole('button',{name:'Añadir día',exact:true}).click();await p.getByRole('button',{name:'Añadir ejercicio',exact:true}).click();await p.locator('#newDays .exercise input').first().fill('Press con mancuernas en banco inclinado — nombre largo');await surface('#new>.card');await surface('#newDays>.card');await shot('create');await p.locator('#newDays .exercise input').first().focus();assert.notEqual(await p.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle),'none');await p.setViewportSize({width,height:430});await p.getByRole('button',{name:'Añadir ejercicio',exact:true}).scrollIntoViewIfNeeded();assert(await p.getByRole('button',{name:'Añadir ejercicio',exact:true}).isVisible());await p.setViewportSize({width,height:900});});
  for(const role of ['client','trainer'])for(const full of [false,true])await test(role+' trash '+(full?'full':'empty')+' state matches icon and readable surface',async()=>{await go(role,full?'trash':'normal');await p.locator(role==='client'?'#tTrashClient':'#tTrash').click();await p.locator(full?'#trash .routine':'#trash .empty').waitFor();assert.equal(await p.locator(role==='client'?'#tTrashClient':'#tTrash').evaluate(e=>e.classList.contains('trash-full')),full);await surface('#app');if(full){await surface('#trash .routine');assert(await p.locator('#trash').getByRole('button',{name:/Restaurar/}).isVisible());if(role==='client')assert.equal(await p.locator('#trash').getByRole('button',{name:'Eliminar',exact:true}).count(),0);}await shot('trash-'+role+'-'+(full?'full':'empty'));});
  await test('Client profile and UUID-separated populated progress chart',async()=>{await go('trainer','history');await p.locator('.client-overview-card').first().click();await p.locator('#clientModal').getByRole('button',{name:'Ver progreso',exact:true}).waitFor();await surface('#clientModal .sheet');await shot('client-profile');await p.locator('#clientModal').getByRole('button',{name:'Ver progreso',exact:true}).click();await p.locator('.progress-point').first().waitFor();await surface('#clientProgressModal .sheet');const opts=await p.locator('#clientProgressExercise option').evaluateAll(es=>es.map(e=>e.value));assert.equal(opts.length,2);assert.notEqual(opts[0],opts[1]);await p.locator('.progress-point').last().focus();await p.keyboard.press('Enter');await p.waitForTimeout(100);const tip=await p.locator('#progressPointTooltip').boundingBox();assert(tip.x>=0&&tip.x+tip.width<=width+1);await shot('progress');});
  await test('Editor and reorder list remain readable; normal scroll outside handle',async()=>{await go('trainer','long');await p.locator('#tMine').click();await p.locator('[data-open-routine]').first().click();await p.locator('#clientSessionList').getByRole('button',{name:'Editar sesión',exact:true}).first().click();await surface('#editModal .sheet');await shot('session-editor');await p.getByRole('button',{name:/Reordenar ejercicios/}).click();assert.equal(await p.locator('.editor-drag-handle').first().evaluate(e=>getComputedStyle(e).touchAction),'none');assert.notEqual(await p.locator('.exercise-reorder-name').first().evaluate(e=>getComputedStyle(e).touchAction),'none');await shot('reorder');});
  await test('Athlete workout, timer, history day, and historical edit share palette',async()=>{await go('client','history');await p.locator('#shared .routine .primary').click();await p.locator('.interior-session-list button').first().click();await p.locator('.tick').first().waitFor();await surface('#trainModal .sheet');await shot('training');await p.locator('.rest-buttons button').first().click();await shot('rest-timer');await p.getByRole('button',{name:'Cerrar temporizador'}).click();await p.locator('#trainModalActions').getByRole('button',{name:'Historial',exact:true}).click();await p.locator('.history-session').first().waitFor();assert.equal(await p.locator('.history-session').count(),14);await p.locator('.history-summary').first().click();await surface('#trainModal .sheet');await shot('history-day');const edit=p.locator('.history-session').first().getByRole('button',{name:/Editar/});await edit.click();await p.locator('.history-edit-input').first().waitFor();await shot('history-editor');});
  await test('OAuth review buttons explicitly disabled, no fake login',async()=>{await go('auth','social');assert.equal(await p.locator('#authOAuth button:disabled').count(),3);assert.match(await p.locator('#authOAuth').innerText(),/sin configurar/);await shot('oauth-preview');});
  await test('No unhandled JavaScript errors in expanded views',()=>assert.deepEqual(errors,[]));
  await p.close();
 }}finally{await b.close();}
}
const report={passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass),results,shots};fs.writeFileSync(path.join(out,'screens.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed},null,2));if(report.failed.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
