const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto'),path=require('path');process.env.PLAYWRIGHT_BROWSERS_PATH=path.resolve('work/pw-browsers');const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const old=fs.readFileSync('work/test-ux-browser.cjs','utf8'),stub=vm.runInNewContext(old.slice(old.indexOf('const stub='),old.indexOf('const results=[]'))+'stub').replace('String(x[k])',"String(k.startsWith('data->>')?x.data?.[k.slice(7)]:x[k])"),html=fs.readFileSync(process.argv[2]||'outputs/index.html','utf8'),results=[];
(async()=>{for(const engine of ['chromium','webkit'])for(const width of [320,360,390,430,1280]){const b=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})}),p=await b.newPage({viewport:{width,height:844}});await p.route('**/*',r=>r.request().url()==='http://simple.test/'?r.fulfill({body:html,contentType:'text/html'}):r.request().url().includes('cdn.jsdelivr')?r.fulfill({body:stub,contentType:'application/javascript'}):r.abort());await p.goto('http://simple.test/');p.setDefaultTimeout(5000);const errors=[];p.on('pageerror',e=>errors.push(e.message));
const test=async(name,fn)=>{try{await fn();results.push({engine,width,name,pass:true})}catch(e){results.push({engine,width,name,pass:false,error:e.message});console.error(name,e.message)}};
async function setup(){await p.evaluate(()=>{closeM('editModal');closeM('clientModal');user={id:'U'};profile={role:'trainer'};window.__simpleStarted=true;document.getElementById('app').style.display='block';document.getElementById('auth').style.display='none';document.getElementById('mine').style.display='block';window.__workoutContextVersion=0;window.__routineSaving=false;window.__clientRoutineEdit=null;mock.tables.routines=[{id:'R',name:'Primera',owner_id:'U'},{id:'S',name:'Segunda',owner_id:'U'}];routines=structuredClone(mock.tables.routines);mock.tables.routine_days=[{id:'D',routine_id:'R',name:'PULL'},{id:'F',routine_id:'S',name:'PUSH'}];mock.tables.routine_exercises=[{id:'E',day_id:'D',name:'Curl',sets:2}];mock.tables.routine_assignments=[{id:'A',trainer_id:'U',client_id:'C',trainer_routine_id:'R'}];window.queue=[];if(window.originalFrom)db.from=originalFrom;else window.originalFrom=db.from;db.rpc=async()=>({data:[]})})}

async function graph(n=14){await setup();await p.evaluate(n=>{closeM('trainModal');closeM('editModal');closeM('clientProgressModal');const key=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');mock.tables.workouts=Array.from({length:n},(_,i)=>{const date=new Date();date.setDate(date.getDate()-i);return{id:'G'+i,user_id:'U',workout_date:key(date),data:{routine_id:'R',routine_day_id:'D',day_name:'PULL',exercises:[{exercise_id:'E',name:'Curl',sets:[{kg:20+i,reps:10,rir:2}]}]}}});},n);await p.evaluate(()=>openRoutineProgress('R'));await p.locator('#clientProgressChart svg').waitFor();await p.evaluate(()=>new Promise(resolve=>{let timer;const root=$('clientProgressChart');const done=()=>{observer.disconnect();resolve()};const observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(done,150)});observer.observe(root,{subtree:true,childList:true,attributes:true});timer=setTimeout(done,150)}));}


await test('Late horizontal scroll keeps selected UUID point visible without changing chart data',async()=>{
 await graph();
 const state=await p.evaluate(async()=>{
  const last=[...document.querySelectorAll('.progress-point')].at(-1),index=Number(last.dataset.progressIndex);
  showProgressPoint(index,last);
  const before=JSON.stringify({points:clientProgressChartState.points,workouts:mock.tables.workouts,calls:mock.rpcCalls});
  const wrap=document.querySelector('.progress-svg-wrap');
  await new Promise(resolve=>{const old=wrap.scrollLeft;wrap.addEventListener('scroll',()=>requestAnimationFrame(resolve),{once:true});wrap.scrollLeft=wrap.scrollWidth;if(wrap.scrollLeft===old)resolve()});
  const rect=wrap.getBoundingClientRect(),tip=document.querySelector('#progressPointTooltip').getBoundingClientRect();
  return {unchanged:before===JSON.stringify({points:clientProgressChartState.points,workouts:mock.tables.workouts,calls:mock.rpcCalls}),selected:[...document.querySelectorAll('.progress-point[aria-pressed="true"]')].map(e=>Number(e.dataset.progressIndex)),index,wrap:{left:rect.left,right:rect.right},tip:{left:tip.left,right:tip.right}};
 });
 assert(state.unchanged);assert.deepEqual(state.selected,[state.index]);assert(state.tip.left>=state.wrap.left-1&&state.tip.right<=state.wrap.right+1,JSON.stringify(state));
});
await b.close();console.log(engine,width,'complete');}
const report={passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass),results};fs.writeFileSync('tests/integration/results/chart-scroll.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.failed.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
