/* OFFLINE PREVIEW ONLY. This is not a security test or server authorization. */
const demoClient=supabase.createClient();
const demoUser='00000000-0000-4000-8000-000000001a01';
const demoRpc=demoClient.rpc;
function demoResult(data,error=null){return {data:structuredClone(data),error};}
demoClient.from=table=>{
 const filters=[],sorts=[];let limit=Infinity,single=false,kind=null,payload;
 const q={select(){return q},eq(k,v){filters.push(x=>String(k.includes('->>')?x[k.split('->>')[0]]?.[k.split('->>')[1]]:x[k])===String(v));return q},is(k,v){filters.push(x=>x[k]==v);return q},in(k,v){filters.push(x=>v.includes(x[k]));return q},not(k,o,v){filters.push(x=>x[k]!==v);return q},order(k,o){sorts.push([k,o?.ascending!==false]);return q},limit(n){limit=n;return q},range(a,b){limit=b-a+1;return q},single(){single=true;return q},maybeSingle(){single=true;return q},insert(v){kind='insert';payload=v;return q},upsert(v){kind='upsert';payload=v;return q},update(v){kind='update';payload=v;return q},delete(){kind='delete';return q},then(resolve,reject){try{const rows=mock.tables[table]??=[];if(kind){if(!['workouts','routine_user_notes'].includes(table))return resolve(demoResult(null,{message:'La estructura queda fija en esta preview.'}));for(const item of Array.isArray(payload)?payload:[payload]){if(!item)continue;const old=kind==='upsert'?rows.find(x=>x.user_id===item.user_id&&x.routine_id===item.routine_id&&x.exercise_key===item.exercise_key):null;if(old)Object.assign(old,item);else rows.push({id:crypto.randomUUID(),created_at:new Date().toISOString(),...item});}}let found=rows.filter(x=>filters.every(f=>f(x)));for(const[k,asc]of sorts)found.sort((a,b)=>(a[k]>b[k]?1:a[k]<b[k]?-1:0)*(asc?1:-1));found=found.slice(0,limit);resolve(demoResult(single?found[0]||null:found));}catch(e){reject(e)}}};return q;
};
demoClient.rpc=async(name,p={})=>{
 const t=mock.tables,now=new Date().toISOString();
 if(name==='get_my_coach_access'){const op=t.coach_operations.find(x=>x.state==='accepted');return demoResult({authorized:true,can_generate:!op,premium:false,routine_id:op?.routine_id});}
 if(name==='save_my_training_intake'){const old=t.training_intakes.find(x=>x.id===p.p_id);let row;if(old?.state==='draft'){row=old;Object.assign(row,{training:p.p_training,state:p.p_submit?'submitted':'draft',row_version:row.row_version+1});}else{row={id:crypto.randomUUID(),user_id:demoUser,revision:t.training_intakes.length+1,row_version:1,state:p.p_submit?'submitted':'draft',training:p.p_training};t.training_intakes.push(row);}t.intake_health=t.intake_health.filter(x=>x.intake_id!==row.id);t.intake_health.push({intake_id:row.id,user_id:demoUser,declarations:p.p_health});for(const o of t.coach_operations)if(o.state==='ready')o.state='stale';return demoResult(row);}
 if(name==='set_my_coach_context_permission'){const g=t.context_grants.find(x=>x.scope===p.p_scope&&!x.revoked_at);if(p.p_allow&&!g)t.context_grants.push({id:crypto.randomUUID(),user_id:demoUser,scope:p.p_scope,revoked_at:null});if(!p.p_allow&&g){g.revoked_at=now;for(const o of t.coach_operations)if(o.state==='ready')o.state='stale';}return demoResult(p.p_allow);}
 if(name==='accept_basic_plan'){const o=t.coach_operations.find(x=>x.id===p.p_operation);if(o?.state==='accepted')return demoResult(o.routine_id);if(o?.state!=='ready')return demoResult(null,{message:'coach_proposal_not_ready'});const r={id:crypto.randomUUID(),owner_id:demoUser,name:o.proposal.name,description:o.proposal.description,routine_order:0,deleted_at:null};t.routines.push(r);o.proposal.days.forEach((d,i)=>{const day={id:crypto.randomUUID(),routine_id:r.id,name:d.name,day_order:i};t.routine_days.push(day);d.exercises.forEach((e,j)=>t.routine_exercises.push({id:crypto.randomUUID(),day_id:day.id,name:e.name,sets:e.sets,target:e.reps_min+'-'+e.reps_max,rir:String(e.rir),rest_seconds:e.rest_seconds,exercise_order:j}));});t.routine_management.push({routine_id:r.id,user_id:demoUser});o.state='accepted';o.routine_id=r.id;return demoResult(r.id);}
 if(name==='get_client_routine_cycle_progress'){const total=t.routine_days.filter(x=>x.routine_id===p.p_routine_id).length;return demoResult([{total_days:total,completed_days:Math.min(total,new Set(t.workouts.filter(x=>x.data.routine_id===p.p_routine_id).map(x=>x.data.routine_day_id)).size)}]);}
 return demoRpc(name,p);
};
demoClient.functions={invoke:async(name,{body})=>{const t=mock.tables,i=t.training_intakes.find(x=>x.id===body.intake_id);if(t.context_grants.filter(x=>!x.revoked_at).length!==2)return demoResult({error:'coach_context_required'});const o={id:crypto.randomUUID(),user_id:demoUser,intake_id:i.id,state:'ready',created_at:new Date().toISOString(),proposal:{schema_version:1,name:'SYNTHETIC · Basic piloto',description:'Ejemplo ficticio local. Sin llamadas a Supabase ni IA.',days:Array.from({length:i.training.days},(_,n)=>({name:'Sesión de prueba '+(n+1),exercises:[{name:'SYNTHETIC · Sentadilla de prueba',sets:2,reps_min:8,reps_max:12,rir:3,rest_seconds:90},{name:'SYNTHETIC · Remo de prueba',sets:2,reps_min:10,reps_max:12,rir:3,rest_seconds:90}]}))}};t.coach_operations.push(o);return demoResult({operation:o});}};
window.supabase.createClient=()=>demoClient;
