// Offline UI verification; security is tested separately with real staging JWTs.
const a=require('./api.cjs'),{fs,path,check,save}=a;
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{for(const engine of ['chromium','webkit']){const b=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});const p=await b.newPage({viewport:{width:390,height:844}});p.setDefaultTimeout(10000);const errors=[];p.on('pageerror',e=>errors.push(e.message));try{
await p.goto('http://127.0.0.1:4192/demo');await p.waitForFunction(()=>window.previewReady);
await p.evaluate(async()=>{$('coachHome').remove();assignments=[{id:'synthetic-assignment'}];await renderCoachHome();});check(engine+' existing assigned athlete unchanged',await p.locator('#coachHome').count()===0);
await p.evaluate(async()=>{assignments=[];await renderCoachHome();});await p.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).click();await p.locator('#coachBegin').click();await p.locator('#coachGoal').fill('Objetivo ficticio para probar el recorrido');
for(const width of [320,360,390,430,1280])for(const theme of ['light','dark']){await p.setViewportSize({width,height:900});await p.evaluate(t=>simpleTheme.set(t),theme);await p.waitForTimeout(300);const info=await p.locator('#coachGoal').evaluate(e=>{const s=getComputedStyle(e),rgb=v=>v.match(/[\d.]+/g).slice(0,3).map(Number),l=v=>rgb(v).map(x=>x/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0),a=l(s.color),b=l(s.backgroundColor);return{contrast:(Math.max(a,b)+.05)/(Math.min(a,b)+.05),font:parseFloat(s.fontSize)};});check(engine+' '+width+' '+theme+' form legible',info.contrast>=4.5&&info.font>=16);check(engine+' '+width+' '+theme+' dialog fits',await p.locator('#coachDialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1));if([320,390,1280].includes(width))await p.screenshot({path:path.join(__dirname,'results','preview-'+engine+'-'+width+'-'+theme+'.png'),fullPage:true});}
await p.locator('#coachGoal').focus();check(engine+' focus visible',await p.locator('#coachGoal').evaluate(e=>parseFloat(getComputedStyle(e).outlineWidth)>=2));check(engine+' comfortable buttons',await p.locator('#coachDialog button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44)));
await p.locator('#coachGrantTraining').check();await p.locator('#coachGrantHealth').check();await p.getByRole('button',{name:'Generar propuesta ficticia',exact:true}).click();await p.locator('#coachAccept').waitFor();await p.screenshot({path:path.join(__dirname,'results','preview-'+engine+'-proposal.png'),fullPage:true});await p.locator('#coachAccept').click();await p.locator('#coachOpen').click();await p.locator('.interior-session-list button').first().click();await p.locator('#saveWorkoutBtn').waitFor();check(engine+' offline complete navigable demo',await p.locator('.workout-exercise').count()===2);
await p.waitForTimeout(300);const col=await p.locator('.setrow input').first().evaluate(e=>({fg:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor}));check(engine+' settled dark training colors',col.fg!==col.bg);await p.screenshot({path:path.join(__dirname,'results','preview-'+engine+'-training-dark.png'),fullPage:true});
check(engine+' no page errors',errors.length===0,errors.join(';'));save('preview-browser');
}finally{await b.close();}}save('preview-browser');})().catch(e=>{save('preview-browser');console.error(e.message);process.exitCode=1});
