const fs=require('fs'),crypto=require('crypto'),assert=require('assert/strict');
const dir=__dirname;fs.mkdirSync(dir+'/private',{recursive:true});fs.mkdirSync(dir+'/results',{recursive:true});
assert(!fs.existsSync(dir+'/private/config.json'),'Resume existing fixture, do not overwrite');
for(const file of ['request.json','response.json','completed.json'])if(fs.existsSync(dir+'/private/'+file))fs.unlinkSync(dir+'/private/'+file);
const c={ref:'dmqjexigdnfzobarhnib',key:'sb_publishable_GAqOb1_W3qiK8ka6EL1G7g_TutTPIVf',users:{},routine:'ba2d0a25-1844-45c1-9777-f0e1aa7aa392',days:['1f9fbb95-9941-4cc4-989c-bfc1d590977b','21a2160e-8822-423a-933f-e0413136983c','950d5458-270f-4f9a-a16a-be4c7d346ca7','7f929817-c4cf-447b-b7f1-0353f73d6659','df0423d6-7e0f-430d-9db2-081cdd9a071e'],old:['05b6c573-abcb-4259-9c0a-93459ddd5a24','879e13f3-9c0d-4020-b10d-d7f753fedb6b','0e4e1c85-3612-481c-9f67-41345b0afa20','041166f2-4306-45c1-b86f-0eb4aca27ed1'],names:['LUNES / PUSH','MARTES / PULL','MIÉRCOLES / LEG','VIERNES / UPPER','SÁBADO / ARMS-LEG'],foreign:crypto.randomUUID(),foreignDay:crypto.randomUUID(),unknown:crypto.randomUUID(),assignments:[crypto.randomUUID(),crypto.randomUUID(),crypto.randomUUID()]};
for(const who of ['trainer','client','otherTrainer','otherClient'])c.users[who]={id:who==='client'?'b7ee910d-bc34-402c-b1a3-5cacceb29519':crypto.randomUUID(),role:who.toLowerCase().includes('trainer')?'trainer':'client',email:'simple-alias-'+crypto.randomUUID()+'@example.invalid',password:crypto.randomBytes(32).toString('base64url')};
const q=s=>"'"+String(s).replaceAll("'","''")+"'";
let sql='BEGIN;\n';
// IDs reproduce the confirmed namespace only in staging, with synthetic accounts.
sql+=`DO $$ BEGIN IF EXISTS(select 1 from auth.users where id=${q(c.users.client.id)}) OR EXISTS(select 1 from routines where id=${q(c.routine)}) OR EXISTS(select 1 from routine_days where id in (${[...c.days,...c.old].map(q).join(',')})) THEN RAISE EXCEPTION 'Fixture namespace occupied; abort'; END IF; END $$;\n`;
for(const u of Object.values(c.users))sql+=`INSERT INTO auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,recovery_token,email_change_token_new,email_change,phone_change,phone_change_token,email_change_token_current,reauthentication_token) VALUES ('00000000-0000-0000-0000-000000000000',${q(u.id)},'authenticated','authenticated',${q(u.email)},extensions.crypt(${q(u.password)},extensions.gen_salt('bf')),now(),'{"provider":"email","providers":["email"]}','{}',now(),now(),'','','','','','','','');
INSERT INTO auth.identities(provider_id,user_id,identity_data,provider,created_at,updated_at) VALUES (${q(u.id)},${q(u.id)},jsonb_build_object('sub',${q(u.id)},'email',${q(u.email)},'email_verified',true),'email',now(),now());
INSERT INTO profiles(id,name,role) VALUES (${q(u.id)},'SYNTHETIC cycle alias validation',${q(u.role)});\n`;
sql+=`INSERT INTO routines(id,owner_id,name) VALUES (${q(c.routine)},${q(c.users.trainer.id)},'SYNTHETIC cycle aliases'),(${q(c.foreign)},${q(c.users.otherTrainer.id)},'SYNTHETIC foreign aliases');\n`;
sql+=`INSERT INTO routine_days(id,routine_id,name,day_order) VALUES ${c.days.map((id,i)=>`(${q(id)},${q(c.routine)},${q(c.names[i])},${i})`).join(',')},(${q(c.foreignDay)},${q(c.foreign)},'FOREIGN',0);\n`;
sql+=`INSERT INTO routine_assignments(id,trainer_id,client_id,trainer_routine_id) VALUES (${q(c.assignments[0])},${q(c.users.trainer.id)},${q(c.users.client.id)},${q(c.routine)}),(${q(c.assignments[1])},${q(c.users.trainer.id)},${q(c.users.otherClient.id)},${q(c.routine)}),(${q(c.assignments[2])},${q(c.users.otherTrainer.id)},${q(c.users.otherClient.id)},${q(c.foreign)});\nCOMMIT;`;
fs.writeFileSync(dir+'/private/config.json',JSON.stringify(c,null,2));fs.writeFileSync(dir+'/private/seed.sql',sql);
const ids=Object.values(c.users).map(u=>q(u.id)).join(',');
const cleanup=`BEGIN;
DO $$ BEGIN IF EXISTS(select 1 from auth.sessions where user_id in (${ids})) THEN RAISE EXCEPTION 'Revoke synthetic sessions first'; END IF; END $$;
DELETE FROM workouts WHERE user_id IN (${ids});
DELETE FROM routine_user_notes WHERE user_id IN (${ids});
DELETE FROM routine_assignments WHERE id IN (${c.assignments.map(q).join(',')});
DELETE FROM routine_days WHERE routine_id IN (${q(c.routine)},${q(c.foreign)});
DELETE FROM routines WHERE id IN (${q(c.routine)},${q(c.foreign)});
DELETE FROM profiles WHERE id IN (${ids});
DELETE FROM auth.users WHERE id IN (${ids});
COMMIT;`;
fs.writeFileSync(dir+'/private/cleanup.sql',cleanup);fs.writeFileSync(dir+'/results/manifest.json',JSON.stringify({...c,key:undefined,users:Object.fromEntries(Object.entries(c.users).map(([k,u])=>[k,{id:u.id,role:u.role}]))},null,2));console.log('Prepared synthetic fixture; no SQL executed.');
