const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict'),{f,j,q,write,rpc,read,check,rows}=require('./live.cjs');
async function prepare(){const P=f.cases.P,O=f.cases.O;const pr=(await read('mock','routine_revisions','routine_id=eq.'+P.routine)).data.find(r=>r.revision_no===2);const a=pr.snapshot.days[0].exercises[0].planned_sets,b=pr.snapshot.days[0].exercises[1].planned_sets;
const patch=(id,ss)=>({target_id:id,field:'planned_sets',from:ss,to:ss.map((s,i)=>i===0?{...s,rest_seconds:s.rest_seconds===240?300:240}:s)});
const replacements=[{target_id:O.exercises[1],field:'replace_exercise',from:O.exercises[1],to:{id:crypto.randomUUID(),catalogue_id:'band_row',sets:3,target:'8-12',rir:'2',rest_seconds:180}},patch(O.exercises[1],O.plans[1])];
write('advanced-setup.sql',`begin;select jsonb_build_object('race1',public.premium_mock_recommendation('${P.mesocycle}','MODIFY',${j([patch(P.exercises[0],a)])},'[]','Synthetic concurrent recommendation 1'),'race2',public.premium_mock_recommendation('${P.mesocycle}','MODIFY',${j([patch(P.exercises[1],b)])},'[]','Synthetic concurrent recommendation 2'),'atomic',public.premium_mock_recommendation('${O.mesocycle}','MODIFY',${j(replacements)},'[]','Synthetic mid-apply failure rollback')) ids;commit;`);
}
async function run(){const ids=require('./private/advanced-ids.json');for(const k of ['race1','race2','atomic'])check('review '+k,(await rpc('reviewer','premium_review_recommendation',{p_id:ids[k],p_approve:true,p_reason:'Synthetic concurrency and atomic safety test.'})).ok);
const r=await Promise.all([ids.race1,ids.race2].map(p_id=>rpc('mock','premium_accept_recommendation',{p_id})));check('different recommendations exactly one winner',r.filter(x=>x.ok).length===1);const loser=ids[r[0].ok?'race2':'race1'];check('stale second cannot overwrite',!(await rpc('mock','premium_accept_recommendation',{p_id:loser})).ok);check('race exactly N+1 count',(await read('mock','routine_revisions','routine_id=eq.'+f.cases.P.routine)).data.length===3);
const before={revs:(await read('mock','routine_revisions','routine_id=eq.'+f.cases.O.routine)).data,ex:(await read('mock','routine_exercises','id=eq.'+f.cases.O.exercises[1])).data};const fail=await rpc('mock','premium_accept_recommendation',{p_id:ids.atomic});check('mid-apply deleted old target rejects',!fail.ok);const after={revs:(await read('mock','routine_revisions','routine_id=eq.'+f.cases.O.routine)).data,ex:(await read('mock','routine_exercises','id=eq.'+f.cases.O.exercises[1])).data};check('failed apply old exercise all fields intact',require('util').isDeepStrictEqual(before.ex,after.ex));check('failed apply no revision',require('util').isDeepStrictEqual(before.revs,after.revs));check('failed apply remains ready',(await read('mock','coach_recommendations','id=eq.'+ids.atomic)).data[0].state==='ready');
}
(process.argv[2]==='prepare'?prepare():run()).catch(e=>{console.error(e.message);process.exitCode=1;}).finally(()=>{if(rows.length)fs.writeFileSync(path.join(__dirname,'results/advanced.json'),JSON.stringify({rows,total:rows.length,completed:!process.exitCode},null,2));console.log(rows.filter(r=>r.pass).length+'/'+rows.length+' advanced checks');});
