const{f,j,q,write}=require('./live.cjs');const K=f.cases.K,M=f.cases.M,O=f.cases.O;const check=(name,expr)=>`if not coalesce((${expr}),false) then raise exception 'failed ${name}';end if;checks:=checks||jsonb_build_object(${q(name)},true);\n`;
let sql=`begin;do $test$ declare r public.coach_recommendations;s public.coach_recommendations;ss jsonb;v jsonb;bad jsonb;pp jsonb;snap jsonb;next_rev uuid;checks jsonb:='{}';denied boolean;begin
perform set_config('request.jwt.claim.sub','${f.users.mock.id}',true);r:=public.premium_reserve_analysis('${K.mesocycle}',gen_random_uuid());ss:=r.analysis_bundle#>'{provider,routine,exercises,0,planned_sets}';
v:=jsonb_build_object('schema_version','premium-recommendation-v2','kind','MODIFY','facts',jsonb_build_array(jsonb_build_object('exercise_ref','exercise_1','claim',r.analysis_bundle#>>'{provider,routine,exercises,0,metrics,trend}')),'interpretation','Synthetic final guard validation.','reason','Explicit rest change on S2.','confidence','low','changes',jsonb_build_array(jsonb_build_object('action','change_set','exercise_ref','exercise_1','set_number',2,'from',(ss->1)-'set_number','to',((ss->1)-'set_number')||'{"rest_seconds":300}'::jsonb)));
pp:=coach_private.premium_output_patches(r,v);
`+check('final SQL exact per-set output valid',`jsonb_array_length(pp)=1 and pp#>>'{0,to,1,rest_seconds}'='300'`)+`
bad:=jsonb_set(v,'{changes,0,to,set_number}','999');denied:=false;begin perform coach_private.premium_output_patches(r,bad);exception when others then denied:=true;end;
`+check('SQL rejects hidden extra ordinal in to','denied')+`
perform set_config('request.jwt.claim.sub','',true);update public.routine_exercises set rest_seconds=90 where id='${K.exercises[0]}';perform set_config('request.jwt.claim.sub','${f.users.mock.id}',true);denied:=false;begin perform coach_private.premium_output_patches(r,v);exception when others then denied:=sqlerrm='premium_stale_live_projection';end;
`+check('live projection inconsistent with revision rejected','denied')+`
perform set_config('request.jwt.claim.sub','',true);update public.routine_exercises set rest_seconds=(ss#>>'{0,rest_seconds}')::int where id='${K.exercises[0]}';perform set_config('request.jwt.claim.sub','${f.users.mock.id}',true);perform public.premium_analysis_claim('${f.users.mock.id}',r.id,100,'mock');s:=public.premium_analysis_finish('${f.users.mock.id}',r.id,v,null,'{}','["controlled_quality_warning"]');
`+check('warning persists before reviewer',`s.state='pending_review' and s.analysis_trace#>>'{quality_warnings,0}'='controlled_quality_warning'`)+`
perform set_config('request.jwt.claim.sub','${f.users.reviewer.id}',true);perform public.premium_review_recommendation(r.id,true,'Final deterministic per-set review.');perform set_config('request.jwt.claim.sub','${f.users.mock.id}',true);next_rev:=public.premium_accept_recommendation(r.id);
`+check('final guard acceptance exact N+1',`coach_private.premium_revision_sets(next_rev,'${K.exercises[0]}')->1=(ss->1)||'{"rest_seconds":300}'::jsonb`)+check('final guard leaves S1 exact',`coach_private.premium_revision_sets(next_rev,'${K.exercises[0]}')->0=ss->0`)+`
select snapshot into snap from public.routine_revisions where id='${M.revision}';update public.routine_revisions set snapshot=(snapshot-'routine')||jsonb_build_object('id','${M.routine}','owner_id','${f.users.mock.id}','name','Synthetic V5 shape') where id='${M.revision}';
`+check('exact Basic V5 root format interpreted',`coach_private.premium_revision_sets('${M.revision}','${M.exercises[0]}')=${j(M.plans[0])}`)+`
update public.routine_revisions set snapshot=jsonb_set(snapshot,'{days,0,exercises,0,planned_sets}','[]') where id='${M.revision}';
`+check('broken individualized plan never flattened',`coach_private.premium_revision_sets('${M.revision}','${M.exercises[0]}') is null`)+check('legacy baseline still uniform interpreted',`coach_private.premium_revision_sets('${O.revision}','${O.exercises[0]}')=${j(O.plans[0])}`)+`
perform set_config('test.series_closure',checks::text,true);end $test$;select current_setting('test.series_closure')::jsonb checks;rollback;`;write('closure.sql',sql);console.log('Generated final closed-schema and revision compatibility tests');
