// Exact-ID synthetic staging fixtures. No Auth users are created/deleted.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const dir=path.join(__dirname,'private'),out=path.join(__dirname,'results'),mode=process.argv[2];fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(out,{recursive:true});
const write=(n,d)=>fs.writeFileSync(path.join(dir,n),typeof d==='string'?d:JSON.stringify(d,null,2)),q=x=>"'"+String(x).replaceAll("'","''")+"'",j=x=>q(JSON.stringify(x))+'::jsonb';
if(mode==='prepare'&&require.main===module){assert(!fs.existsSync(path.join(dir,'fixture.json')));const source=JSON.parse(fs.readFileSync(process.argv[3]));assert.equal(source.ref,'dmqjexigdnfzobarhnib');const f={ref:source.ref,key:source.key,users:source.users,cases:{},grants:[]};for(const tag of 'IJKLMNOP')f.cases[tag]={routine:crypto.randomUUID(),days:[crypto.randomUUID(),crypto.randomUUID()],exercises:Array.from({length:4},()=>crypto.randomUUID()),workouts:[]};write('fixture.json',f);console.log('Created guarded private staging manifest');process.exit(0);}
const f=JSON.parse(fs.readFileSync(path.join(dir,'fixture.json')));assert.equal(f.ref,'dmqjexigdnfzobarhnib');const I=require('../../assets/coach-intake.js'),rows=[];let sessions=fs.existsSync(path.join(dir,'sessions.json'))?JSON.parse(fs.readFileSync(path.join(dir,'sessions.json'))):{};
function check(name,pass){rows.push({name,pass:!!pass});assert(pass,name);}
async function req(w,route,data,method){const r=await fetch('https://'+f.ref+'.supabase.co'+route,{method:method||(data===undefined?'GET':'POST'),headers:{apikey:f.key,...(sessions[w]?{Authorization:'Bearer '+sessions[w].access_token}:{}),'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)}),signal:AbortSignal.timeout(route.includes('/functions/')?120000:20000)});let dataOut;try{dataOut=await r.json();}catch{}return{ok:r.ok,status:r.status,data:dataOut};}
const rpc=(w,n,d)=>req(w,'/rest/v1/rpc/'+n,d),read=(w,t,where)=>req(w,'/rest/v1/'+t+'?select=*&'+where);
const good={...I.emptyPremium(),experience:'gt4',pause:false,goal:'balanced',weak_points:['unsure'],days:2,weekdays:['mon','thu'],minutes_by_day:{mon:60,thu:60},effort:'confident',confidence:'high',recovery:'mostly',sleep:'h7_8',stress:'medium',distribution:'coach',activity:{type:'none',weekdays:[],minutes:null,intensity:null},inventory:{equipment:I.equipment.map(e=>e.id),custom:[]}};
const set=(n,lo,hi,rir,rest)=>({set_number:n,reps_min:lo,reps_max:hi,rir,rest_seconds:rest});
async function main(){
if(mode==='login'){for(const[k,u]of Object.entries(f.users)){const r=await req(null,'/auth/v1/token?grant_type=password',{email:u.email,password:u.password});check('JWT '+k,r.ok&&r.data.user.id===u.id);sessions[k]=r.data;}write('sessions.json',sessions);}
if(mode==='setup'){
let sql='begin;\n';for(const[tag,c]of Object.entries(f.cases)){c.catalogue=['hack','db_row','db_curl','floor_press'];c.plans=c.catalogue.map((_,i)=>i===0?[set(1,6,8,1,tag==='K'?60:240),set(2,8,10,0,tag==='K'?60:240),...(tag==='J'?[]:[set(3,10,12,0,240)])]:[set(1,8,12,2,180),set(2,8,12,2,180),set(3,8,12,2,180)]);if(tag==='O')c.plans[0]=[set(1,8,12,2,180),set(2,8,12,2,180),set(3,8,12,2,180)];
sql+=`insert into public.routines(id,owner_id,name) values('${c.routine}','${f.users.mock.id}','SYNTHETIC Premium Series ${tag}');\n`;
c.days.forEach((id,i)=>sql+=`insert into public.routine_days(id,routine_id,name,day_order) values('${id}','${c.routine}','Día ${i+1}',${i});\n`);
c.exercises.forEach((id,i)=>{const s=c.plans[i][0];sql+=`insert into public.routine_exercises(id,day_id,name,sets,target,rir,rest_seconds,exercise_order,notes) values('${id}','${c.days[Math.floor(i/2)]}',${q(I.exercises.find(e=>e.id===c.catalogue[i]).name)},${c.plans[i].length},'${s.reps_min}-${s.reps_max}','${s.rir}',${s.rest_seconds},${i%2},'PRIVATE CANARY');\n`;});
sql+=`select public.premium_provision('${f.users.mock.id}','${c.routine}',current_date-21,6,now()+interval '1 day');\n`;
}write('setup.sql',sql+'commit;');write('fixture.json',f);}
if(mode==='attach'){const data=JSON.parse(fs.readFileSync(path.join(dir,'attach.json')));for(const c of Object.values(f.cases)){const m=data.find(x=>x.routine_id===c.routine);assert(m);c.mesocycle=m.id;c.revision=m.current_revision_id;}write('fixture.json',f);}
if(mode==='intake'){
let sql='begin;\n';for(const[tag,c]of Object.entries(f.cases)){
check(tag+' submit unchanged Premium intake',(await rpc('mock','premium_save_intake',{p_mesocycle:c.mesocycle,p_expected:1,p_training:good,p_submit:true})).ok);
check(tag+' explicit context grant',(await rpc('mock','premium_permission',{p_mesocycle:c.mesocycle,p_allow:true})).ok);
if(tag!=='O'){const by=Object.fromEntries(c.exercises.map((id,i)=>[id,c.plans[i]]));sql+=`update public.routine_revisions r set snapshot=jsonb_set(r.snapshot,'{days}',(select jsonb_agg(d||jsonb_build_object('exercises',(select jsonb_agg(e||jsonb_build_object('planned_sets',${j(by)}->(e->>'id'),'scheme',case when e->>'id'='${c.exercises[0]}' then 'top_backoff' else 'straight' end) order by (e->>'exercise_order')::int) from jsonb_array_elements(d->'exercises')e)) order by (d->>'day_order')::int) from jsonb_array_elements(r.snapshot->'days')d)) where r.id='${c.revision}' and r.routine_id='${c.routine}';update public.routine_revisions set snapshot_hash=md5(snapshot::text) where id='${c.revision}';\n`;}
sql+=`select public.premium_bind_catalogue('${c.mesocycle}','${c.revision}',${j(Object.fromEntries(c.exercises.map((id,i)=>[id,c.catalogue[i]])))});select public.premium_assign_reviewer('${c.mesocycle}','${f.users.reviewer.id}');\n`;
const n=tag==='L'?1:4;for(let k=0;k<n;k++)for(let d=0;d<2;d++){
const id=crypto.randomUUID();c.workouts.push(id);const data={routine_id:c.routine,routine_day_id:c.days[d],...(tag==='M'?{}:{routine_revision_id:c.revision}),notes:'PRIVATE CANARY',exercises:[d*2,d*2+1].map(i=>({exercise_id:c.exercises[i],name:'PRIVATE CANARY',sets:c.plans[i].map((s,z)=>({set:z+1,kg:z===0?90:82.5,reps:tag==='I'?s.reps_max-k:s.reps_max,rir:s.rir}))}))};
sql+=`insert into public.workouts(id,user_id,variant,day,workout_date,data) values('${id}','${f.users.mock.id}','SYNTHETIC Premium Series','Día ${d+1}',current_date-${(n-1-k)*7},${j(data)});\n`;}
}write('enhance.sql',sql+'commit;');write('fixture.json',f);}
if(mode==='context'){
const contexts={};for(const[tag,c]of Object.entries(f.cases)){const r=await rpc('mock','premium_provider_context',{p_mesocycle:c.mesocycle});if(!r.ok)throw Error(tag+' context '+r.data?.message);check(tag+' provider original contract plus per-set version',r.data.schema_version==='premium-provider-v1'&&r.data.prescription_context_version==='premium-prescription-v2');contexts[tag]=r.data;const e=r.data.routine.exercises[0];check(tag+' exact numeric plan',require('util').isDeepStrictEqual(e.planned_sets,c.plans[0]));const t=JSON.stringify(r.data);check(tag+' UUID-free note-free private-free provider',!t.includes('CANARY')&&!t.includes('@')&&!/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i.test(t));if(tag==='M')check('ambiguous legacy history recognizes unknown plan',e.exposures.every(h=>h.prescription_source==='unknown'&&h.sets.every(s=>s.planned===null)));else check(tag+' per-set history aligned with its revision',e.exposures.every(h=>h.prescription_source==='exact_revision'&&h.sets.every((s,i)=>s.planned.set_number===i+1&&s.rir_delta===0)));
}write('contexts.json',contexts);
for(const w of ['real','trainer','reviewer',null])check((w||'anon')+' owner provider isolation',!(await rpc(w,'premium_provider_context',{p_mesocycle:f.cases.I.mesocycle})).ok);
}
if(mode==='real'){const tag=process.argv[3],c=f.cases[tag];assert(['I','K','L','N'].includes(tag));assert(sessions.mock.expires_at>Date.now()/1000+130);const file=path.join(out,'real.json'),ledger=fs.existsSync(file)?JSON.parse(fs.readFileSync(file)):[];assert(ledger.length<6&&!ledger.some(r=>r.tag===tag),'No retries or duplicates');const key=crypto.randomUUID();ledger.push({tag,key,state:'dispatching'});fs.writeFileSync(file,JSON.stringify(ledger,null,2));const r=await req('mock','/functions/v1/simple-coach-premium',{mesocycle_id:c.mesocycle,key});Object.assign(ledger.at(-1),{state:'returned',http_status:r.status,recommendation:r.data?.recommendation||null,error:r.data?.error||null});fs.writeFileSync(file,JSON.stringify(ledger,null,2));check(tag+' real persisted pending review',r.ok&&r.data?.recommendation?.state==='pending_review');c.real_rec=r.data.recommendation.id;write('fixture.json',f);console.log(JSON.stringify({tag,kind:r.data.recommendation.kind,receipt:r.data.recommendation.analysis_trace?.receipt,error:r.data.recommendation.analysis_trace?.error}));}
}
module.exports={f,req,rpc,read,q,j,write,check,rows};
if(require.main===module)main().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(()=>{if(rows.length)fs.writeFileSync(path.join(out,mode+(process.argv[3]&&mode==='real'?'-'+process.argv[3]:'')+'.json'),JSON.stringify({rows,total:rows.length,completed:!process.exitCode},null,2));console.log(rows.filter(r=>r.pass).length+'/'+rows.length+' '+mode+' checks');});
