// Browser-only mocked transport; no staging writes and no OpenAI calls.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),I=require('../../assets/coach-intake.js'),contexts=require('./private/contexts.json'),ledger=require('./private/preview.json'),out=path.join(__dirname,'results'),rows=[];
const check=(name,v)=>{rows.push({name,pass:!!v});assert(v,name);};
(async()=>{for(const engine of ['chromium','webkit']){const browser=await(engine==='chromium'?chromium:webkit).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});const p=await browser.newPage();let rec=structuredClone(ledger.find(r=>r.tag==='O').recommendation),fail=false,delayA=false;
const state=actor=>({actor,catalogue:I.exercises,context:contexts.O,mesocycle:{number:1,tracking_week:1,planned_weeks:6,revision_no:1},weeks:Array.from({length:6},(_,i)=>({week_number:i+1,revision_no:1})),recommendation:rec,can_analyze:false});
await p.route('**/analysis-api',async route=>{const b=route.request().postDataJSON();if(b.action==='state'){const v=structuredClone(state(b.actor));if(delayA&&b.tag==='I'){v.recommendation.kind='MODIFY';await new Promise(r=>setTimeout(r,300));}else if(delayA)v.recommendation.kind='KEEP';await route.fulfill({json:v});}else if(fail){fail=false;await route.fulfill({status:500,json:{error:'No se pudo completar. Puedes reintentar.'}});}else{if(b.action==='resolve'){rec.kind='KEEP';rec.analysis_trace.manual_resolution='KEEP';}rec.state='ready';await route.fulfill({json:true});}});
try{
 rec.state='pending_review';rec.kind='MODIFY';rec.analysis_trace.output.reason='Explicación extensa de prueba, basada únicamente en observaciones registradas. '.repeat(8);rec.analysis_trace.output.changes=[{action:'change_sets',exercise_ref:'exercise_1',from:3,to:2},{action:'change_rest',exercise_ref:'exercise_2',from:180,to:210},{action:'change_rir',exercise_ref:'exercise_3',from:'2',to:'1'}];
 for(const width of [320,360,390,430,1280])for(const theme of ['light','dark']){await p.setViewportSize({width,height:900});await p.goto('http://127.0.0.1:4240/review');await p.locator('#title').filter({hasText:'Propuesta'}).waitFor();if(await p.locator('html').getAttribute('data-theme')!==theme)await p.locator('#theme').click();check(engine+width+theme+' multiple changes no overflow',await p.locator('body').evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(engine+width+theme+' all three changes and long reason visible',await p.locator('#changes li').count()===3&&(await p.locator('#reason').textContent()).length>500);if(width===390&&engine==='chromium')await p.screenshot({path:path.join(out,'multiple-390-'+theme+'.png'),fullPage:true});}
 rec.kind='REVIEW';rec.analysis_trace.output.kind='REVIEW';rec.analysis_trace.output.changes=[];await p.goto('http://127.0.0.1:4240/review');await p.locator('#title').filter({hasText:'Revisión manual'}).waitFor();check(engine+' REVIEW no athlete acceptance',await p.getByRole('button',{name:/Aceptar/}).count()===0);
 await p.locator('#actor').selectOption('reviewer');const resolve=p.getByRole('button',{name:'Resolver sin cambios'});await resolve.waitFor();await resolve.focus();check(engine+' keyboard visible focus',await resolve.evaluate(b=>document.activeElement===b&&getComputedStyle(b).outlineStyle!=='none'));
 fail=true;await resolve.press('Enter');await p.locator('#message').filter({hasText:'reintentar'}).waitFor();check(engine+' failed action shows accessible error',await p.locator('#message').getAttribute('role')==='alert');check(engine+' failed action allows retry',await resolve.isEnabled());check(engine+' no false success',!(await p.locator('#message').textContent()).includes('completada'));
 await resolve.click();await p.locator('#status').filter({hasText:'Validada'}).waitFor();check(engine+' explicit retry succeeds',true);
 delayA=true;await p.locator('#case').selectOption('I');await p.locator('#case').selectOption('J');await p.locator('#title').filter({hasText:'Mantener'}).waitFor();await p.waitForTimeout(450);check(engine+' stale state response ignored',(await p.locator('#title').textContent())==='Mantener la rutina');
 }finally{await browser.close();}}})().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(()=>{fs.writeFileSync(path.join(out,'ui-edge.json'),JSON.stringify({rows,total:rows.length,completed:!process.exitCode},null,2));console.log(rows.filter(x=>x.pass).length+'/'+rows.length+' UI edge checks');});
