// Offline rendering of outputs persisted in staging; no model calls or DB mutations.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';const{chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.join(__dirname,'results'),rows=[],base='http://127.0.0.1:4240';fs.mkdirSync(out,{recursive:true});function check(name,v){rows.push({name,pass:!!v});assert(v,name);}
(async()=>{for(const engine of ['chromium','webkit']){const browser=await(engine==='chromium'?chromium:webkit).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{
for(const width of [320,360,390,430,1280])for(const theme of ['light','dark']){
await p.setViewportSize({width,height:900});await p.goto(base+'/review');await p.locator('#title').filter({hasText:'Propuesta de cambio'}).waitFor();if(await p.locator('html').getAttribute('data-theme')!==theme)await p.locator('#theme').click();
check(engine+width+theme+' no horizontal overflow',await p.locator('body').evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
check(engine+width+theme+' removal before after explicit',await p.locator('#changes').textContent().then(t=>t.includes('Antes')&&t.includes('Después')&&t.includes('Se elimina la serie 2 original')&&t.includes('S2 · 10–12')));
check(engine+width+theme+' no pending athlete accept',await p.getByRole('button',{name:/Aceptar/}).count()===0);
await p.locator('#actor').selectOption('reviewer');const validate=p.getByRole('button',{name:'Validar propuesta',exact:true});await validate.waitFor();check(engine+width+theme+' tap area',await validate.evaluate(b=>b.getBoundingClientRect().height>=44));await p.keyboard.press('Tab');await validate.focus();check(engine+width+theme+' visible keyboard focus',await validate.evaluate(b=>document.activeElement===b&&getComputedStyle(b).outlineStyle!=='none'));
if(engine==='chromium'&&[390,1280].includes(width))await p.screenshot({path:path.join(out,'remove-'+width+'-'+theme+'.png'),fullPage:true});
}
for(const[tag,text]of [['J','S3 · 10–12 reps · RIR 1 · 4 min'],['K','S2 · 8–10 reps · RIR 0 · 4 min']]){await p.locator('#case').selectOption(tag);await p.locator('#changes').filter({hasText:text}).waitFor();check(engine+tag+' complete prescription and minutes visible',true);if(engine==='chromium')await p.screenshot({path:path.join(out,tag+'-390.png'),fullPage:true});}
await p.locator('#case').selectOption('M');await p.locator('#title').filter({hasText:'Revisión manual'}).waitFor();check(engine+' unsafe output not rendered applicable',await p.locator('#changes-section').isHidden());check(engine+' review problem visible',(await p.locator('#reason').textContent()).includes('no es aplicable con seguridad'));check(engine+' unresolved approve hidden',await p.getByRole('button',{name:'Validar propuesta',exact:true}).count()===0);check(engine+' human resolver present',await p.getByRole('button',{name:'Resolver sin cambios',exact:true}).count()===1);
check(engine+' no browser errors',errors.length===0);
}finally{await browser.close();}}})().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(()=>{fs.writeFileSync(path.join(out,'ui.json'),JSON.stringify({rows,total:rows.length,completed:!process.exitCode},null,2));console.log(rows.filter(r=>r.pass).length+'/'+rows.length+' per-set browser checks');});
