const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const rows=[];function test(name,fn){fn();rows.push({name,pass:true});}
(async()=>{const C=await import('../../supabase/functions/simple-coach-premium/series-contract.mjs');
const ss=[{set_number:1,reps_min:6,reps_max:8,rir:1,rest_seconds:240},{set_number:2,reps_min:8,reps_max:10,rir:0,rest_seconds:240},{set_number:3,reps_min:10,reps_max:12,rir:0,rest_seconds:240}];
const ctx={schema_version:'premium-provider-v1',intake:{experience:'gt4'},routine:{days:[{ref:'day_1'}],exercises:[{ref:'exercise_1',day_ref:'day_1',catalogue_id:'hack',prescription:{sets:3,reps:'6-8',rir:'1',rest_seconds:240},planned_sets:ss,prescription_format:'individualized-v5',metrics:{trend:'stable_comparable'}}]},allowed_replacements:[]};
const keep={schema_version:C.SCHEMA_VERSION,kind:'KEEP',facts:[{exercise_ref:'exercise_1',claim:'stable_comparable'}],interpretation:'Series con objetivos distintos, rendimiento estable.',reason:'Conservar la estructura.',confidence:'medium',changes:[]};
const output=changes=>({...structuredClone(keep),kind:'MODIFY',changes});const change={action:'change_set',exercise_ref:'exercise_1',set_number:2,from:C.prescription(ss[1]),to:{...C.prescription(ss[1]),rir:1}};
const remove={action:'remove_set',exercise_ref:'exercise_1',set_number:2,from:C.prescription(ss[1])};
const add={action:'add_set',exercise_ref:'exercise_1',set_number:3,to:{reps_min:10,reps_max:12,rir:1,rest_seconds:240}};
const mutate=(c,f)=>{c=structuredClone(c);f(c);return c;};
test('numeric individualized KEEP',()=>assert(C.semantic(keep,ctx).ok));
test('one set RIR only',()=>assert(C.semantic(output([change]),ctx).ok));
test('one set reps only',()=>assert(C.semantic(output([mutate(change,c=>{c.set_number=1;c.from=C.prescription(ss[0]);c.to={...c.from,reps_min:5,reps_max:7};})]),ctx).ok));
test('one set rest only',()=>assert(C.semantic(output([mutate(change,c=>c.to={...c.from,rest_seconds:300})]),ctx).ok));
test('remove explicitly middle of 3',()=>assert(C.semantic(output([remove]),ctx).ok));
test('remove retains S1 S3 prescriptions relative order',()=>assert.deepEqual(C.applySetChanges(ss,[remove]),[ss[0],{...ss[2],set_number:2}]));
test('append prescribed S3 to 2',()=>assert(C.semantic(output([add]),mutate(ctx,c=>c.routine.exercises[0].planned_sets=ss.slice(0,2))).ok));
test('append preserves top and back-off',()=>assert.deepEqual(C.applySetChanges(ss.slice(0,2),[add]).slice(0,2),ss.slice(0,2)));
test('RIR change preserves all other sets',()=>assert.deepEqual(C.applySetChanges(ss,[change]).filter(s=>s.set_number!==2),[ss[0],ss[2]]));
for(const [name,c] of [['foreign exercise',mutate(change,c=>c.exercise_ref='other')],['unknown series',mutate(change,c=>c.set_number=9)],['stale from',mutate(change,c=>c.from.rir=2)],['reversed reps',mutate(change,c=>{c.to.reps_min=12;c.to.reps_max=8;})],['partial to',mutate(change,c=>delete c.to.rest_seconds)],['extra field',mutate(change,c=>c.sql='unsafe')],['no-op',mutate(change,c=>c.to=c.from)],['insert instead of append',mutate(add,c=>c.set_number=2)]])test(name,()=>assert(!C.semantic(output([c]),ctx).ok));
test('duplicate ordinal denied',()=>assert(!C.semantic(output([change,change]),ctx).ok));
test('volume mixed with series denied',()=>assert(!C.semantic(output([remove,change]),ctx).ok));
test('uniform flattening denied',()=>assert(!C.semantic(output([{action:'change_sets',exercise_ref:'exercise_1',from:3,to:2}]),ctx).ok));
test('incomplete plan does not fall back to summary',()=>assert.equal(C.sets(mutate(ctx.routine.exercises[0],e=>delete e.planned_sets[0].rir)),null));
test('noncontiguous planned ordinals denied',()=>assert.equal(C.sets(mutate(ctx.routine.exercises[0],e=>e.planned_sets[1].set_number=3)),null));
test('unresolved prescription change denied',()=>assert(!C.semantic(output([change]),mutate(ctx,c=>c.routine.exercises[0].prescription_format='unresolved')).ok));
test('legacy uniform still modifiable',()=>assert(C.semantic(output([{action:'change_sets',exercise_ref:'exercise_1',from:3,to:2}]),mutate(ctx,c=>{delete c.routine.exercises[0].planned_sets;c.routine.exercises[0].prescription_format='legacy_uniform_projection';})).ok));
test('legacy RIR5 rest30 from accepted, safe new to required',()=>{const c=mutate(ctx,c=>{c.routine.exercises[0].planned_sets[0].rir=5;c.routine.exercises[0].planned_sets[0].rest_seconds=30;});const x={action:'change_set',exercise_ref:'exercise_1',set_number:1,from:C.prescription(c.routine.exercises[0].planned_sets[0]),to:{reps_min:6,reps_max:8,rir:4,rest_seconds:240}};assert(C.semantic(output([x]),c).ok);});
test('new to cannot inherit unsafe legacy bounds',()=>assert(!C.semantic(output([mutate(change,c=>{c.to.rir=5;c.to.rest_seconds=30;})]),ctx).ok));
test('beginner close failure denied',()=>assert(!C.semantic(output([change]),{...ctx,intake:{experience:'lt6'}}).ok));
test('REVIEW empty accepted',()=>assert(C.semantic({...keep,kind:'REVIEW'},ctx).ok));
test('REVIEW cannot modify',()=>assert(!C.semantic({...output([change]),kind:'REVIEW'},ctx).ok));
test('facts must exist',()=>assert(!C.semantic({...keep,facts:[{exercise_ref:'exercise_1',claim:'reps_decreasing_comparable'}]},ctx).ok));
test('rest warning retains safe human review',()=>{const c=mutate(change,c=>c.to={...c.from,rest_seconds:60});assert(C.semantic(output([c]),ctx).warnings.some(w=>w.startsWith('rest_below_demand')));});
test('request unchanged model budget storage',()=>{const r=C.requestBody(ctx);assert.equal(r.model,'gpt-5.4-2026-03-05');assert.equal(r.max_output_tokens,1800);assert.equal(r.store,false);assert(r.text.format.strict);});
let calls=0;const result=await C.analyze(ctx,'MOCK',async()=>{calls++;return new Response(JSON.stringify({status:'completed',usage:{input_tokens:1000,output_tokens:100},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(output([change]))}]}]}));});
test('v2 output real transport mocked once',()=>assert(calls===1&&!result.error&&result.output.changes[0].set_number===2));
test('receipt new schema provenance',()=>assert.equal(result.receipt.response_schema_version,C.SCHEMA_VERSION));
const dir=path.join(__dirname,'results');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'unit.json'),JSON.stringify({rows,total:rows.length,completed:true},null,2));console.log(rows.length+'/'+rows.length+' per-set unit checks');
})().catch(e=>{console.error(e.message);process.exitCode=1;});
