const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto'),path=require('path');
const c=JSON.parse(fs.readFileSync(path.join(__dirname,'../cycle-alias/private/config.json')));assert.equal(c.ref,'dmqjexigdnfzobarhnib');
const created={routines:[crypto.randomUUID(),crypto.randomUUID()],exercise:crypto.randomUUID()},results=[];fs.writeFileSync(path.join(__dirname,'private/order-manifest.json'),JSON.stringify(created));
async function request(who,url,method='GET',body){const r=await fetch('https://'+c.ref+'.supabase.co/rest/v1/'+url,{method,headers:{apikey:c.key,Authorization:'Bearer '+c.users[who].token,'Content-Type':'application/json',Prefer:'return=representation'},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();return{status:r.status,data:text?JSON.parse(text):null};}
async function ok(url,method='GET',body){const r=await request('trainer',url,method,body);assert(r.status>=200&&r.status<300,JSON.stringify(r));return r.data;}
async function test(name,fn){try{await fn();results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:e.message});throw e;}}
(async()=>{try{
 for(const [i,id]of created.routines.entries())await ok('routines','POST',{id,owner_id:c.users.trainer.id,name:'SYNTHETIC order '+i,description:'Must stay exact',routine_order:i+1});
 await ok('routine_exercises','POST',{id:created.exercise,day_id:c.days[0],name:'SYNTHETIC fields preserved',sets:3,target:'8–12',rir:'2',rest_seconds:120,exercise_order:0});
 const untouched=await ok('routine_exercises?id=eq.'+created.exercise),history=await ok('workouts?user_id=eq.'+c.users.client.id);
 const ids=[c.routine,...created.routines],reverse=[...ids].reverse();
 await test('Routine order-only RPC persists exact reversed order',async()=>{await ok('rpc/reorder_my_routines_atomic','POST',{p_routine_ids:reverse});assert.deepEqual((await ok('routines?owner_id=eq.'+c.users.trainer.id+'&order=routine_order')).map(r=>r.id),reverse);});
 await test('Day order-only RPC persists forward and reverse; fields and workouts unchanged',async()=>{for(const order of [[...c.days].reverse(),c.days]){await ok('rpc/reorder_my_routine_days_atomic','POST',{p_routine_id:c.routine,p_day_ids:order});assert.deepEqual((await ok('routine_days?routine_id=eq.'+c.routine+'&order=day_order')).map(r=>r.id),order);}assert.deepEqual(await ok('routine_exercises?id=eq.'+created.exercise),untouched);assert.deepEqual(await ok('workouts?user_id=eq.'+c.users.client.id),history);});
 for(const who of ['client','otherTrainer'])await test(who+' cannot reorder trainer structure',async()=>{const r=await request(who,'rpc/reorder_my_routine_days_atomic','POST',{p_routine_id:c.routine,p_day_ids:[...c.days].reverse()});assert(r.status>=400);assert.deepEqual((await ok('routine_days?routine_id=eq.'+c.routine+'&order=day_order')).map(r=>r.id),c.days);});
 await test('Invalid permutation rejected without partial persistence',async()=>{const r=await request('trainer','rpc/reorder_my_routine_days_atomic','POST',{p_routine_id:c.routine,p_day_ids:[c.days[0],c.days[0]]});assert(r.status>=400);assert.deepEqual((await ok('routine_days?routine_id=eq.'+c.routine+'&order=day_order')).map(r=>r.id),c.days);});
}finally{await ok('routine_exercises?id=eq.'+created.exercise,'DELETE');for(const id of created.routines)await ok('routines?id=eq.'+id,'DELETE');await ok('rpc/reorder_my_routines_atomic','POST',{p_routine_ids:[c.routine]});}
})().catch(e=>{console.error(e.message);process.exitCode=1}).finally(()=>{const report={passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass),results};fs.writeFileSync(path.join(__dirname,'results/authenticated-order.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));});
