const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path'),extract=require('../integration/function-source.cjs');
const source=fs.readFileSync('index.html','utf8'),results=[],out=path.join(__dirname,'results');
async function test(name,fn){try{await fn();results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:e.stack})}}
const c=vm.createContext({Set,Map,Date,Intl,console,window:{},localStorage:{getItem(){return null},setItem(){}},matchMedia:()=>({matches:false})});for(const n of ['simpleCycleDateKey','simpleLocalDateKey','readRoutineCycleProgress','loadProgressHistory','renderCycleCompletion'])vm.runInContext(extract(source,n),c);
(async()=>{
for(const [instant,expected]of [['2026-09-25T21:59:59Z','2026-09-25'],['2026-09-25T22:00:00Z','2026-09-26'],['2026-03-28T23:00:00Z','2026-03-29'],['2026-03-29T22:00:00Z','2026-03-30'],['2026-10-25T22:59:59Z','2026-10-25'],['2026-10-25T23:00:00Z','2026-10-26']])await test('Madrid date boundary / DST '+instant,()=>assert.equal(c.simpleCycleDateKey(new Date(instant)),expected));
await test('Explicit historical date formatting remains device-calendar unchanged',()=>{const d=new Date(2026,7,31);assert.equal(c.simpleLocalDateKey(d),'2026-08-31')});
await test('Cycle read crossing Madrid midnight rereads the server; never serves yesterday',async()=>{const date=c.simpleCycleDateKey;let key='2026-09-25',calls=[];c.simpleCycleDateKey=()=>key;c.db={rpc:async(name,args)=>{calls.push({name,args});if(calls.length===1)key='2026-09-26';return{data:[{total_days:5,completed_days:calls.length===1?5:1}]}}};const r=await c.readRoutineCycleProgress('client','routine');assert.equal(r.data[0].completed_days,1);assert.equal(calls.length,2);assert(calls.every(x=>x.args.p_client_id==='client'&&x.args.p_routine_id==='routine'));c.simpleCycleDateKey=date;});
await test('Celebration once per client/routine/calendar date; same day reread keeps text only',()=>{const first=c.renderCycleCompletion(5,5,'client|routine'),next=c.renderCycleCompletion(5,5,'client|routine');assert(first.includes('<img'));assert(!next.includes('<img'));assert(next.includes('Rutina finalizada'));assert(!c.renderCycleCompletion(5,4,'client|routine'));assert(!c.renderCycleCompletion(0,0,'client|empty'));});
await test('Reduced motion does not start the dance',()=>{c.matchMedia=()=>({matches:true});assert(!c.renderCycleCompletion(5,5,'reduced|routine').includes('<img'));});
const rows=Array.from({length:1203},(_,n)=>({id:'w'+n,user_id:'client',workout_date:'2026-09-25',data:{routine_id:'routine'}}));let ranges=[];
function query(list){const q={select(){return q},eq(){return q},order(){return q},range(a,b){ranges.push([a,b]);return Promise.resolve({data:list.slice(a,b+1),error:null})}};return q;}
await test('Own and trainer history paginate beyond default limits without losing or duplicating rows',async()=>{c.db={from:()=>query(rows),rpc:()=>query(rows)};for(const trainer of [false,true]){ranges=[];const data=await c.loadProgressHistory('client','routine',trainer);assert.equal(data.length,1203);assert.deepEqual(ranges,[[0,499],[500,999],[1000,1499]]);}});
await test('Pagination still enforces owner and routine even if response includes foreign rows',async()=>{c.db={rpc:()=>query([...rows.slice(0,10),{id:'foreign',user_id:'other',data:{routine_id:'routine'}},{id:'foreign-routine',user_id:'client',data:{routine_id:'other'}}])};assert.equal((await c.loadProgressHistory('client','routine',true)).length,10)});
await test('History response arriving after owner/modal change is discarded',async()=>{let current=true;c.db={rpc:()=>({order(){return this},async range(){current=false;return{data:rows}}})};assert.equal(await c.loadProgressHistory('client','routine',true,()=>current),null)});
await test('Repeated whole page is rejected rather than looping or silently truncating',async()=>{c.db={rpc:()=>({order(){return this},async range(){return{data:rows.slice(0,500)}}})};await assert.rejects(()=>c.loadProgressHistory('client','routine',true),/no avanza/)});
await test('Remote errors are surfaced, never replaced with cached local results',async()=>{c.db={rpc:()=>({order(){return this},async range(){return{error:Error('blocked')}}})};await assert.rejects(()=>c.loadProgressHistory('client','routine',true),/blocked/)});
const report={passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass),results};fs.writeFileSync(path.join(out,'contracts.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.failed.length)process.exitCode=1;
})();
