const fs=require('fs'),path=require('path'),assert=require('assert/strict');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const results=[],out=path.join(__dirname,'results'),base=process.env.SIMPLE_PUBLIC_URL||'http://127.0.0.1:4184/',publicMode=!!process.env.SIMPLE_PUBLIC_URL;
const write=()=>fs.writeFileSync(path.join(out,(publicMode?'public-':'')+'interactions.json'),JSON.stringify({passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass),results},null,2));
async function page(context){const p=await context.newPage();p.setDefaultTimeout(8000);if(publicMode)await p.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='cdn.jsdelivr.net'&&u.pathname.includes('supabase-js'))return r.fulfill({body:fs.readFileSync('tests/interior/mock-sdk.js'),contentType:'application/javascript'});if(u.origin===new URL(base).origin&&r.request().method()==='GET')return r.continue();return r.abort()});return p;}
async function go(p,role='trainer'){await p.goto(base+'?role='+role+'&state=history');if(publicMode)await p.addScriptTag({content:fs.readFileSync('tests/interior/preview-seed.js','utf8')});await p.waitForFunction(()=>window.previewReady);}
async function extendedOrder(p){await p.evaluate(async()=>{
 const r=mock.tables.routines[0],day=mock.tables.routine_days[0],id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
 mock.tables.routines=Array.from({length:16},(_,i)=>({...r,id:i===0?r.id:id(600+i),name:i===0?'Rutina con nombre largo para comprobar el arrastre entre extremos':'Rutina '+i,routine_order:i}));
 mock.tables.routine_days=Array.from({length:24},(_,i)=>({...day,id:i===0?day.id:id(700+i),name:i===0?'Sesión con nombre largo para comprobar la lectura completa':'Sesión '+i,day_order:i}));
 const original=db.rpc.bind(db);window.orderWrites=[];db.rpc=(name,args)=>{if(!name.startsWith('reorder_'))return original(name,args);orderWrites.push({name,args});const routines=name==='reorder_my_routines_atomic',ids=routines?args.p_routine_ids:args.p_day_ids,key=routines?'routine_order':'day_order';for(const [i,id] of ids.entries())mock.tables[routines?'routines':'routine_days'].find(r=>r.id===id)[key]=i;return Promise.resolve({data:null,error:null})};
 await reload();await renderMine();
});}
async function endToEndDrag(p,kind,reverse=false){
 const root=kind==='routine'?'#mine':'#clientSessionList',rows=p.locator(root+(kind==='routine'?' .routine-sortable':' .routine-editor-day')),count=await rows.count(),row=rows.nth(reverse?count-1:0),handle=row.locator('.drag-handle').first();
 const first=await row.getAttribute(kind==='routine'?'data-routine-id':'data-day-index');await handle.scrollIntoViewIfNeeded();const rect=await handle.boundingBox();await p.mouse.move(rect.x+20,rect.y+20);await p.mouse.down();const y=reverse?5:895;await p.mouse.move(rect.x+20,y,{steps:10});
 await p.waitForFunction(({kind,reverse})=>{const e=kind==='routine'?document.scrollingElement:document.querySelector('#editModal .sheet');return reverse?e.scrollTop<1:e.scrollTop+e.clientHeight>=e.scrollHeight-2;},{kind,reverse},{timeout:8000});
 await p.mouse.up();await p.waitForFunction(()=>!window.__routineReordering&&!__editorOrderSaving);assert.equal(await p.locator('.compact-reorder-ghost').count(),0);return first;
}
(async()=>{for(const engine of ['chromium','webkit']){const browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});
const context=await browser.newContext({viewport:{width:390,height:900},timezoneId:'America/Los_Angeles'}),p=await page(context);
const test=async(name,fn)=>{try{await fn();results.push({engine,name,pass:true})}catch(e){console.error(engine,name,e.message);results.push({engine,name,pass:false,error:e.stack})}write();};
try{
await test('Long routine and day lists: first-last-first, autoscroll and order-only writes',async()=>{await go(p);await extendedOrder(p);await p.locator('#tMine').click();await p.locator('#routineReorderToggle').click();await p.waitForFunction(()=>document.querySelector('#mine.routine-compact-mode'));const id=await p.evaluate(()=>routines[0].id);
 await endToEndDrag(p,'routine');assert.equal(await p.evaluate(()=>routines.at(-1).id),id);await p.waitForTimeout(500);await endToEndDrag(p,'routine',true);assert.equal(await p.evaluate(()=>routines[0].id),id);await p.waitForTimeout(500);
 await p.locator('#routineReorderToggle').click();await p.locator('[data-open-routine]').first().click();await p.getByRole('button',{name:'Reordenar sesiones'}).click();await p.waitForFunction(()=>document.querySelector('#clientSessionList.day-compact-mode'));const first=await p.evaluate(()=>editDays[0].id);
 await endToEndDrag(p,'day');assert.equal(await p.evaluate(()=>editDays.at(-1).id),first);await p.waitForTimeout(500);await endToEndDrag(p,'day',true);assert.equal(await p.evaluate(()=>editDays[0].id),first);assert.equal(await p.evaluate(()=>orderWrites.length),4);
});
await test('Touch pointer cancellation and loss of foreground never save an accidental order',async()=>{await go(p);await extendedOrder(p);await p.locator('#tMine').click();await p.locator('#routineReorderToggle').click();await p.waitForFunction(()=>document.querySelector('#mine.routine-compact-mode'));
 for(const end of ['pointercancel','blur']){const h=p.locator('.routine-drag-handle').first();await h.scrollIntoViewIfNeeded();const r=await h.boundingBox();await h.dispatchEvent('pointerdown',{pointerId:7,pointerType:'touch',isPrimary:true,clientX:r.x+20,clientY:r.y+20,button:0,bubbles:true});await p.evaluate(({x,y})=>document.dispatchEvent(new PointerEvent('pointermove',{pointerId:7,pointerType:'touch',isPrimary:true,clientX:x,clientY:y,bubbles:true})),{x:r.x+20,y:r.y+45});assert.equal(await p.locator('.compact-reorder-ghost').count(),1);await p.evaluate(end=>end==='blur'?window.dispatchEvent(new Event('blur')):document.dispatchEvent(new PointerEvent('pointercancel',{pointerId:7,bubbles:true})),end);assert.equal(await p.locator('.compact-reorder-ghost').count(),0);}
 assert.equal(await p.evaluate(()=>orderWrites.length),0);assert.equal(await p.locator('.routine-sortable').first().evaluate(e=>getComputedStyle(e).touchAction),'pan-y');
});
await test('Cycle UI respects Madrid rollover in another device timezone; stale replies, theme, draft and two tabs',async()=>{
 await p.clock.install({time:new Date('2026-09-25T21:59:50Z')});await go(p,'client');
 await p.evaluate(()=>{window.cycleCount=5;const original=db.rpc.bind(db);db.rpc=(name,args)=>name==='get_client_routine_cycle_progress'?Promise.resolve({data:[{total_days:5,completed_days:cycleCount}],error:null}):original(name,args);localStorage.removeItem('simple_cycle_celebrations_v1');window.__cycleCelebrations=new Set();});
 await p.evaluate(()=>renderShared());assert.match(await p.locator('#shared').innerText(),/5\/5 del ciclo actual/);assert.equal(await p.locator('#shared .weekly-progress-gif').count(),1);
 await p.evaluate(()=>renderShared());assert.equal(await p.locator('#shared .weekly-progress-gif').count(),0);assert.match(await p.locator('#shared').innerText(),/Rutina finalizada/);
 await p.evaluate(()=>{simpleTheme.set('dark');window.dispatchEvent(new Event('focus'))});await p.waitForTimeout(80);assert.match(await p.locator('#shared').innerText(),/5\/5 del ciclo actual/);
 await p.evaluate(()=>{window.cycleCount=0;});await p.clock.runFor(31000);await p.waitForFunction(()=>document.getElementById('shared').textContent.includes('0/5 del ciclo actual'));assert.equal(await p.locator('#shared .weekly-progress-celebration').count(),0);assert.equal(await p.evaluate(()=>simpleLocalDateKey()),'2026-09-26');
 await p.evaluate(()=>{const original=db.rpc.bind(db);window.firstSlow=true;db.rpc=(name,args)=>{if(name==='get_client_routine_cycle_progress'&&firstSlow){firstSlow=false;return new Promise(resolve=>window.releaseOldCycle=()=>resolve({data:[{total_days:5,completed_days:0}],error:null}));}return original(name,args)};window.oldRender=renderShared();});
 await p.waitForFunction(()=>typeof releaseOldCycle==='function');await p.evaluate(async()=>{cycleCount=1;await renderShared();releaseOldCycle();await oldRender});assert.match(await p.locator('#shared').innerText(),/1\/5 del ciclo actual/);
 const p2=await page(context);try{await go(p2,'client');await p2.evaluate(()=>{const old=db.rpc.bind(db);db.rpc=(name,args)=>name==='get_client_routine_cycle_progress'?Promise.resolve({data:[{total_days:5,completed_days:2}],error:null}):old(name,args)});await p.evaluate(()=>announceCycleChange(false));await p2.waitForFunction(()=>document.getElementById('shared').textContent.includes('2/5 del ciclo actual'));}finally{await p2.close();}
 await p.evaluate(()=>{cycleCount=3;});await p.locator('#shared .routine .primary').click();await p.locator('.interior-session-list button').first().click();await p.locator('.workout-exercise').first().waitFor();const before=await p.evaluate(()=>{window.keptWorkout=activeWorkout;activeWorkout.sets[activeWorkout.exercises[0].id][0].kg='42.5';saveWorkoutDraft();return JSON.stringify(activeWorkout)});
 await p.evaluate(()=>{simpleTheme.set('light');window.dispatchEvent(new Event('focus'))});await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>JSON.stringify(activeWorkout)),before);assert(await p.evaluate(()=>activeWorkout===keptWorkout));assert.equal(await p.evaluate(()=>mock.calls.filter(c=>c.write||c.rpc&&!c.rpc.startsWith('get_')).length),0);await p.clock.resume();
});
await test('Late graph responses cannot cross client contexts',async()=>{await go(p);await p.evaluate(()=>{const original=db.rpc.bind(db);let first=true;db.rpc=(name,args)=>{const q=original(name,args);if(name==='get_client_routine_history'&&first){first=false;const range=q.range.bind(q);q.range=(a,b)=>new Promise(resolve=>window.releaseOldGraph=async()=>resolve(await range(a,b)));}return q;};window.oldGraph=openClientRoutineProgress('00000000-0000-4000-8000-000000000002','00000000-0000-4000-8000-000000000010','First client');});await p.waitForFunction(()=>typeof releaseOldGraph==='function');await p.evaluate(()=>openClientRoutineProgress('00000000-0000-4000-8000-000000000003','00000000-0000-4000-8000-000000000011','Second client'));const before=await p.locator('#clientProgressBody').innerHTML();await p.evaluate(async()=>{await releaseOldGraph();await oldGraph});assert.equal(await p.locator('#clientProgressBody').innerHTML(),before);assert.equal(await p.evaluate(()=>clientProgressChartState.identityContext.clientId),'00000000-0000-4000-8000-000000000003');assert.equal(await p.locator('.progress-point').count(),0)});

await test('Trainer dashboard and client profile use the selected client cycle, never trainer own progress',async()=>{
 await go(p);await p.evaluate(async()=>{const old=db.rpc.bind(db);db.rpc=(name,args)=>{if(name!=='get_client_routine_cycle_progress')return old(name,args);const own=args.p_client_id===user.id;return Promise.resolve({data:[{total_days:5,completed_days:own?2:args.p_client_id.endsWith('2')?5:1}],error:null});};await renderClients();});
 await p.locator('#tClients').click();await p.waitForFunction(()=>document.getElementById('clients').textContent.includes('5/5 del ciclo actual'));assert.match(await p.locator('#clients').innerText(),/Rutina finalizada/);
 assert(await p.locator('#clients .weekly-progress-celebration').first().evaluate(e=>{const card=e.closest('.client-overview-card'),a=e.getBoundingClientRect(),b=card.getBoundingClientRect();return a.top>=b.top&&a.bottom<=b.bottom&&a.left>=b.left&&a.right<=b.right;}),'Completion must stay inside the trainer client card');
 await p.evaluate(()=>openClientProfile('00000000-0000-4000-8000-000000000002'));assert.match(await p.locator('#clientModalBody').innerText(),/5\/5 del ciclo actual/);assert.match(await p.locator('#clientModalBody').innerText(),/Rutina finalizada/);
 await p.evaluate(()=>openClientProfile('00000000-0000-4000-8000-000000000003'));assert.match(await p.locator('#clientModalBody').innerText(),/1\/5 del ciclo actual/);assert.doesNotMatch(await p.locator('#clientModalBody').innerText(),/Rutina finalizada/);
 await p.evaluate(()=>{closeM('clientModal');view('mine')});await p.waitForFunction(()=>document.getElementById('mine').textContent.includes('2/5 del ciclo actual'));
});
await test('Chart keeps 601 valid points across two REST pages; old observations return with All',async()=>{
 await go(p);await p.clock.install({time:new Date('2026-09-25T12:00:00Z')});
 await p.evaluate(()=>{const sample=mock.tables.workouts[0];mock.tables.workouts=Array.from({length:601},(_,n)=>{const date=new Date(Date.UTC(2026,8,25)-n*86400000).toISOString().slice(0,10);return{...structuredClone(sample),id:'history-'+n,workout_date:date,created_at:date+'T12:00:00Z'};});});
 await p.evaluate(()=>openClientRoutineProgress('00000000-0000-4000-8000-000000000002','00000000-0000-4000-8000-000000000010','Synthetic long history'));assert.equal(await p.locator('.progress-point').count(),601);
 await p.locator('#clientProgressPeriod').selectOption('month');assert.equal(await p.locator('.progress-point').count(),31);await p.locator('#clientProgressPeriod').selectOption('all');assert.equal(await p.locator('.progress-point').count(),601);
 await p.locator('.progress-point').last().focus();await p.keyboard.press('Enter');assert.equal(await p.locator('.progress-point').last().getAttribute('aria-pressed'),'true');assert(await p.locator('.progress-svg-wrap').evaluate(e=>e.scrollLeft>0));await p.clock.resume();
});

}catch(e){console.error(e)}finally{await context.close();await browser.close();}}
write();console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass)}));if(results.some(r=>!r.pass))process.exitCode=1;})();
