// Builds a sanitized, reviewable report. Never exports fixture identities or JWTs.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),cp=require('child_process');
const dir=__dirname,out=path.join(dir,'results'),fixture=require('./private/fixture.json'),ledger=require('./results/real.json'),contexts=require('./private/contexts.json'),proof=require('./results/proof.json');
assert.equal(ledger.length,10);assert.equal(fixture.ref,'dmqjexigdnfzobarhnib');
const categories=[['unit',28],['login',5],['intake',16],['context',34],['reserve-mock-A',1],['mock-checks',9],['semantic',21],['review-keep-H',3],['ui',106],['ui-edge',54],['functional-resume-security',26],['lifecycle',10],['invariants',15],['tracking',14]];
let total=0;for(const[n,size]of categories){const v=JSON.parse(fs.readFileSync(path.join(out,n+'.json')));assert.equal(v.total,size,n);assert(v.rows.every(x=>x.pass===true),n);total+=size;}
for(const[n,size]of [['coach-intake-v2',50],['coach-quality-v5',35]]){const v=JSON.parse(fs.readFileSync(path.join(dir,'../'+n+'/results/unit.json')));assert.equal(v.total,size);assert.equal(v.passed,size);total+=size;}
const seen=new Set();for(const row of ledger){assert(!seen.has(row.key));seen.add(row.key);assert.equal(row.http_status,200);assert.equal(row.recommendation.analysis_trace.model,'gpt-5.4-2026-03-05');assert(!['invalid','failed'].includes(row.recommendation.state));}total+=ledger.length;
assert.equal(total,437);assert(proof.rollback_exact&&proof.production_functions_exact);assert.deepEqual(proof.stage_before,proof.stage_after);assert.deepEqual(proof.production_before,proof.production_after);
const tagOf=r=>Object.entries(fixture.cases).find(([,f])=>f.routine===r.routine_id)[0];
const assessment={
 A:'Hechos comprobados: 8→9→10→11 reps a 20 kg, 3 series y RIR 2 en los cuatro ejercicios. La interpretación de progreso comparable es razonable; KEEP evita novedades. No inventa causalidad ni cambia prescripción. Confianza alta defendible para esta decisión, no garantía futura.',
 B:'Cuatro exposiciones de 10 reps, 20 kg, 3 series/RIR 2. Estabilidad real; KEEP razonable. La frase «fase válida» está marcada como hipótesis, no atribuye una causa. Sin cambios de catálogo/volumen.',
 C:'12→11→10→9 reps con carga/RIR/series comparables. Cita el descenso real y reconoce que sigue en 8–12. KEEP es una decisión prudente defendible con los datos disponibles, aunque aquí no se obtuvo MODIFY/REVIEW; no reinterpretar este caso como una modificación exitosa. No diagnostica fatiga.',
 D:'Una exposición por ejercicio; insuficiente para tendencia. KEEP evita inferencias o cambios arbitrarios. Confianza high solo se puede leer como confianza en mantener, no evidencia sólida de rendimiento; aclaración recomendable antes de mostrar este indicador.',
 E:'RIR 0→3→1→4 con iguales reps/carga/series. Señala correctamente que no hay comparabilidad suficiente. KEEP es prudente. Confianza high presenta la misma ambigüedad semántica que D; no se usa para aplicar cambios ni se muestra como fuerza de una tendencia.',
 F:'Rendimiento estable, pero el intake excluye explícitamente db_curl. Sustituye exclusivamente db_curl por band_curl, presente en catálogo, compatible con bandas y no excluido. Preserva 3 series, 8–12, RIR 2 y descanso 180 s; los otros tres ejercicios no cambian. Se verificó aceptación real de esta salida en staging, UUID nuevo, revisión 2 y autor model, sin heredar workouts/aliases. No es una equivalencia histórica ni una preferencia inferida por material.',
 G:'Descenso 12→11→10→9, 30 min por sesión y solo 2 ejercicios/6 series por día. El modelo consideró viable la estructura y devolvió KEEP. No se obtuvo un MODIFY real de volumen: la prueba de 3→2 series se realizó con respuesta controlada y aceptación atómica. No forzamos otro gasto para fabricar un resultado; cobertura real de este tipo pendiente de revisión.',
 H:'Mismo historial estable en semanas de seguimiento 1, 2 y 3. Tres KEEP reales sin introducir novedades. Las tres aceptaciones conservaron la revisión 1 y completaron tres semanas, seguimiento 4. Es prueba de continuidad/idempotencia de seguimiento, no de tres semanas nuevas de entrenamiento ni de eficacia longitudinal.'
};
let md='# Premium Fase 2 — evidencia final\n\nFecha: 2026-10-03. Staging únicamente. No publicación.\n\n';
md+='437/437 checks únicos con evidencia final: 352 Premium (incluidos 10 resultados reales), 85 Basic. No se suman repeticiones, las 3 comprobaciones UI de aceptación ya cubiertas por invariantes, ni los contadores históricos de Fase 1. Los controles finales de integridad/rollback se documentan aparte.\n\n';
md+='| Suite | Checks | Naturaleza |\n|---|---:|---|\n';for(const[n,size]of categories)md+=`| ${n} | ${size} | ${['semantic','lifecycle','invariants','tracking'].includes(n)?'SQL en staging; lifecycle/tracking con rollback':n==='ui-edge'?'UI/transport simulado, sin backend':n==='unit'?'Local/mocks, sin red':n==='ui'?'Chromium/WebKit, matriz final de replay; matriz previa con JWT reales':'JWT/datos sintéticos reales en staging'} |\n`;
md+='| OpenAI A–H (H ×3) | 10 | 10 despachos reales, HTTP 200, schema + semántica aceptados |\n| Basic intake v2 | 50 | Local, sin proveedor |\n| Basic V5 | 35 | Local, proveedor simulado |\n\n';
md+='La suite histórica V4 falló en `balanced candidate, direct frequency` tanto en este worktree como en el base limpio 72fc545. Invoca el contrato vigente V5 con la propuesta scalar V4. No se cambió código/tests para ocultarlo ni se contabiliza como prueba superada.\n\n';
md+='Incidencias resueltas durante desarrollo: parser del arnés no aceptaba respuestas HTTP 204; una comprobación esperaba error HTTP para un UPDATE bloqueado por RLS que devolvía cero filas (se verificó el dato, no el status). Un generador SQL tenía una comilla ausente y se corrigió sin commit parcial. La UI no permitía reintentar tras error y se corrigió. El criterio por calendario heredado no alineaba futuras semanas con seguimiento: se corrigió en la ruta nueva y se validó 14/14 con output controlado. El fixture F inicialmente aceptado conservaba las semanas 2–3 según calendario; se documentó el hallazgo, no se reescribió ese fixture para ocultarlo. Todos esos datos se eliminaron después de verificar la corrección con una nueva aceptación transaccional.\n\n';
md+='## Llamadas reales y costes\n\nModelo `gpt-5.4-2026-03-05`; prompt `premium-analysis-v1`; response `premium-recommendation-v1`. Usage registrado y coste calculado con caché; no una factura. Sin reintentos ni errores reales.\n\n| Caso | Semana | Resultado | Input | Cached | Output | USD | Latencia ms |\n|---|---:|---|---:|---:|---:|---:|---:|\n';
let cost=0;for(const row of ledger){const r=row.recommendation,t=r.analysis_trace.receipt;cost+=t.cost_usd;md+=`| ${tagOf(r)} | ${r.analysis_week} | ${r.kind} | ${t.input_tokens} | ${t.cached_input_tokens} | ${t.output_tokens} | ${t.cost_usd.toFixed(7)} | ${t.latency_ms} |\n`;}
assert(Math.abs(cost-.1077695)<1e-10);md+='\nTotal: **10/12 llamadas**, **0,1077695 / 0,50 USD**. 9 KEEP, 1 MODIFY, 0 REVIEW reales. Coste sin cached tokens en H habría sido mayor; se usa el uso real. Contador final conserva el coste, reserva 0 y enabled=false.\n\n';
md+='## Inputs sintéticos\n\nTodos: adulto sintético, experiencia 2–4 años, objetivo equilibrado, dos días lunes/jueves, esfuerzo confiado/RIR con confianza media, recuperación mostly, sueño 7–8h, estrés medio, sin actividad externa ni salud. Equipo: mancuernas, banco y bandas; no equipo inventado. Dos ejercicios por día, 3 series de 8–12, RIR 2, 180 s salvo goblet 240 s. Duración 60 min, excepto G 30 min. F excluye db_curl. Inventario no implica preferencia. Se utilizan db_row/floor_press/goblet/db_curl, reordenados en F para ubicar curl en exercise_1. Ningún UUID/nombre personal/nota canary salió al provider.\n\n';
for(const row of ledger){const r=row.recommendation,tag=tagOf(r);md+=`## ${tag} — semana ${r.analysis_week}\n\n${assessment[tag]}\n\nSalida estructurada **íntegra**, conservada tal como volvió del modelo; no sustituciones de nombres ni correcciones silenciosas:\n\n\`\`\`json\n${JSON.stringify(r.analysis_trace.output,null,2)}\n\`\`\`\n\n`;}
md+='## Hechos frente a interpretación\n\nA: hecho verificable = 8, 9, 10, 11 reps a misma carga/series/RIR. Interpretación = la prescripción parece funcionar. C/G: el descenso está registrado; su causa no está demostrada y no se presenta como fatiga por sueño. E: RIR variable hace menos comparable la serie temporal; no se convierte el menor RIR en progreso. En todas las salidas, facts/ref/claim coinciden con métricas del contexto y SQL reconstruye los números desde exposures. La calidad de la explicación aún requiere juicio humano.\n\n';
md+='## Aceptación, permisos y concurrencia\n\nF real: reviewer asignado → ready → aceptación del atleta en UI; dos clicks enviaron una solicitud; revisión 2 author=model, UUID nuevo de band_curl, antigua conservada y 8 workouts F intactos. H: tres KEEP reales aceptados, sin revisión nueva, seguimiento 4. Volumen G (mock): 3→2 sobre el mismo UUID, otros ejercicios intactos, nueva revisión atómica, semana previa preservada y futuras vinculadas a la nueva. REVIEW controlado: rechazo de aceptación directa/autoaprobación y trainer normal; resolución scoped a KEEP conserva output REVIEW original y no crea revisión vacía.\n\nDos solicitudes del mismo key reservan un ID; dos aceptaciones del mismo ID producen una revisión; dos recomendaciones distintas tienen un ganador. Un fallo a mitad de aplicación no deja revisión/ejercicio parcial. La recomendación real A queda superseded tras aceptar otra basada en la misma revisión. Respuestas tras revocar consentimiento o cambiar seguimiento quedan superseded. Cuotas/coste/cierre bloquean dispatch. Los tests SQL que alteran estado de prueba se deshacen completamente.\n\n';
md+='Reviewer asignado no obtiene workouts globales ni edición directa; otro client, trainer normal y anon no obtienen contexto/reserva/resolución/aceptación ajena. Nadie desde frontend puede bind/claim/finish ni otorgarse acceso. RLS existente y permisos Basic no se amplían.\n\n';
md+='## Integridad final y rollback\n\n| Tabla | Staging count | Staging hash inicial=final | Producción count | Producción hash inicial=final |\n|---|---:|---|---:|---|\n';for(const a of proof.stage_after){const p=proof.production_after.find(x=>x.entity===a.entity);md+=`| ${a.entity} | ${a.count} | ${a.hash} | ${p.count} | ${p.hash} |\n`;}
md+='\nProducción: 52 definiciones de función, hashes, owners, grants y search_path iguales al inicio; ciclo `88c3564c3c49cf9c53fccba89a1e71b5`. No DDL/DML/deploy ni cambios Auth/OAuth/SMTP/usuarios en producción. Patatasimple conserva UUID, role=client, 1 rutina y 1 workout; sus datos están incluidos en las huellas intactas. Main remoto sigue b15968c.\n\n';
md+='Rollback: se eliminaron únicamente los fixtures manifestados, se ejecutó rollback de Fase 2 y se compararon exactamente las 72 funciones de Fase 1. Se detectó una diferencia de hash por CRLF y se normalizó el generador a LF; el segundo control confirmó igualdad exacta. Después se reaplicó el SQL final, 82 funciones: 70 antiguas idénticas, 2 APIs Premium actualizadas y 10 funciones nuevas. Los 12 cuerpos nuevos/reemplazados coinciden con el SQL candidato; Edge v1 verify_jwt=true y cinco archivos coinciden con el candidato. Premium mesocycles/weeks/recommendations/revisions/grants/access=0; contador privado cerrado. No usuarios Auth nuevos; cinco usuarios sintéticos de pruebas preexistentes conservados.\n\n';
md+='## Preview y capturas\n\nhttp://127.0.0.1:4233/review — replay offline de outputs reales, acciones locales simuladas claramente identificadas. Matriz 320/360/390/430/1280, claro/oscuro, Chromium/WebKit. Capturas locales en results/: MODIFY-390-light/dark, MODIFY-1280-light/dark, MODIFY-ready-390, MODIFY-accepted-390, multiple-390-light/dark. No se publican capturas/manifiestos/JWT/resultados crudos.\n\n';
md+='## Decisión para revisión\n\nCandidato de Fase 2 preparado y staging limpio; **no autorizado ni listo para producción sin revisión**. Cobertura pendiente: obtener REVIEW real y un MODIFY real de volumen; no afirmamos que los mocks sean OpenAI. El contrato solo representa prescripción uniforme heredada; cambios individualizados/top set/back-off requieren REVIEW y otra adaptación explícita. La confianza en D/E no es evidencia fuerte. No hay prueba longitudinal de eficacia ni acceso comercial Premium. No continuar Fase 3 automáticamente.\n';
assert(!/sk-proj-|access_token|refresh_token|password\s*[:=]/i.test(md));fs.writeFileSync(path.join(dir,'RESULTS.md'),md);
const example=JSON.stringify(contexts.A,null,2);assert(!/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f-]{23}/i.test(example)&&!example.includes('CANARY')&&!example.includes('@'));fs.writeFileSync(path.join(dir,'provider-example.json'),example);
fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify({checks:total,passed:total,calls:ledger.length,cost_usd:cost,model:'gpt-5.4-2026-03-05',outcomes:{KEEP:9,MODIFY:1,REVIEW:0}},null,2));console.log(total+'/'+total+' unique checks; sanitized full report and provider example generated.');
