// Loopback-only preview. Never serves private files, credentials or production calls.
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'../..'),port=4233,live=process.env.PREMIUM_ANALYSIS_LIVE==='1';
const I=require('../../assets/coach-intake.js'),dir=path.join(__dirname,'private');
const fixture=live?JSON.parse(fs.readFileSync(path.join(dir,'fixture.json'))):null,sessions=live?JSON.parse(fs.readFileSync(path.join(dir,'sessions.json'))):null;
const contexts=JSON.parse(fs.readFileSync(path.join(dir,'contexts.json'))),ledger=JSON.parse(fs.readFileSync(path.join(__dirname,'results/real.json'))),offline={};
for(const tag of 'ABCDEFGH'){const r=structuredClone(ledger.filter(r=>r.tag===tag).at(-1)?.recommendation),m=contexts[tag].mesocycle;if(r)r.state='pending_review';offline[tag]={actor:'athlete',context:contexts[tag],catalogue:I.exercises,mesocycle:{number:m.number,tracking_week:r?.analysis_week||m.week,planned_weeks:m.planned_weeks,revision_no:m.current_revision},weeks:Array.from({length:m.planned_weeks},(_,i)=>({week_number:i+1,revision_no:m.current_revision})),recommendation:r,can_analyze:false};}
async function rest(actor,route,data){if(!fixture||fixture.ref!=='dmqjexigdnfzobarhnib')throw Error('staging_only');const who=actor==='reviewer'?'reviewer':'mock';const r=await fetch('https://'+fixture.ref+'.supabase.co'+route,{method:data===undefined?'GET':'POST',headers:{apikey:fixture.key,Authorization:'Bearer '+sessions[who].access_token,'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)}),signal:AbortSignal.timeout(120000)});const d=await r.json();if(!r.ok)throw Error(/^premium_[a-z_]+$/.test(d.message||d.error||'')?d.message||d.error:'La solicitud fue rechazada.');return d;}
async function state(tag,actor){if(!live)return{...offline[tag],actor};const f=fixture.cases[tag];const[m]=await rest(actor,'/rest/v1/coach_mesocycles?id=eq.'+f.mesocycle+'&select=*');const weeks=await rest(actor,'/rest/v1/coach_mesocycle_weeks?mesocycle_id=eq.'+f.mesocycle+'&select=week_number,revision_id&order=week_number');const revisions=await rest(actor,'/rest/v1/routine_revisions?routine_id=eq.'+f.routine+'&select=id,revision_no');const recs=await rest(actor,'/rest/v1/coach_recommendations?mesocycle_id=eq.'+f.mesocycle+'&select=*&order=created_at.desc');return {actor,catalogue:I.exercises,context:recs[0]?.analysis_bundle?.provider||contexts[tag],mesocycle:{...m,revision_no:revisions.find(r=>r.id===m.current_revision_id)?.revision_no||1},weeks:weeks.map(w=>({...w,revision_no:revisions.find(r=>r.id===w.revision_id)?.revision_no||1})),recommendation:recs[0]||null,can_analyze:actor==='athlete'&&m.state==='active'&&!recs.some(r=>r.analysis_week===m.tracking_week&&['analyzing','pending_review','ready'].includes(r.state))};}
const html=`<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SIMPLE Premium · análisis</title><script>document.documentElement.dataset.theme=localStorage.getItem('premium-preview-theme')==='dark'?'dark':'light'</script><link rel="stylesheet" href="/assets/coach-premium-analysis.css"><header><strong><svg viewBox="0 0 100 70" aria-hidden="true"><path d="M0 25h6v20H0zM13 12h6v46h-6zM26 0h6v70h-6zM68 0h6v70h-6zM81 12h6v46h-6zM94 25h6v20h-6z"/></svg>SIMPLE</strong><button id="theme">Oscuro</button></header><div class="review-tools"><p class="notice">${live?'Fixture sintética conectada a staging.':'Resultados reales de IA sintética; acciones simuladas localmente.'} Premium comercial cerrado.</p><label for="case">Caso</label><select id="case">${[...'ABCDEFGH'].map(t=>'<option>'+t+'</option>').join('')}</select><label for="actor">Vista</label><select id="actor"><option value="athlete">Atleta</option><option value="reviewer">Reviewer asignado</option></select></div><main><p class="breadcrumb" id="breadcrumb"></p><ol class="weeks" id="weeks"></ol><article><p class="status" id="status"></p><h1 id="title">Análisis</h1><section id="observations-section"><h2>Qué hemos observado</h2><ul class="facts" id="facts"></ul><h2>Por qué</h2><p id="interpretation"></p><p id="reason"></p></section><section id="changes-section" hidden><h2>Qué cambiaría</h2><ul class="changes" id="changes"></ul></section><p id="warning"></p><div class="actions" id="actions"></div><p id="message" role="status" aria-live="polite"></p></article></main><script src="/assets/coach-premium-analysis.js"></script></html>`;
http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');try{
 if(req.url==='/analysis-api'&&req.method==='POST'){
  if(req.headers.origin!==`http://127.0.0.1:${port}`)throw Error('origin_denied');let raw='';for await(const s of req){raw+=s;if(raw.length>4000)throw Error('invalid_request');}const {action,tag,actor,data}=JSON.parse(raw);if(!'ABCDEFGH'.includes(tag)||tag.length!==1||!['athlete','reviewer'].includes(actor))throw Error('invalid_request');let value;
  if(action==='state')value=await state(tag,actor);
  else if(live){const f=fixture.cases[tag];if(action==='analyze'){if(actor!=='athlete')throw Error('not_owned');value=await rest(actor,'/functions/v1/simple-coach-premium',{mesocycle_id:f.mesocycle,key:crypto.randomUUID()});}else{const owned=(await rest(actor,'/rest/v1/coach_recommendations?id=eq.'+data.id+'&mesocycle_id=eq.'+f.mesocycle+'&select=id'))[0];if(!owned)throw Error('not_owned');const calls={review:['premium_review_recommendation',{p_id:data.id,p_approve:!!data.approve,p_reason:'Controlled staging UI manual review.'}],resolve:['premium_resolve_review',{p_id:data.id,p_kind:'KEEP',p_patches:[],p_reason:'Controlled staging human resolution: keep without modifications.'}],accept:['premium_accept_recommendation',{p_id:data.id}]};if(!calls[action])throw Error('action_unavailable');value=await rest(actor,'/rest/v1/rpc/'+calls[action][0],calls[action][1]);}}
  else {const v=offline[tag],r=v.recommendation;await new Promise(r=>setTimeout(r,120));if(action==='review'&&actor==='reviewer'&&r.state==='pending_review')r.state=data.approve?'ready':'rejected';else if(action==='resolve'&&actor==='reviewer'&&r.kind==='REVIEW'&&r.state==='pending_review'){r.kind='KEEP';r.state='ready';}else if(action==='accept'&&actor==='athlete'&&r.state==='ready'){r.state='accepted';if(r.kind==='MODIFY'){v.mesocycle.revision_no++;v.weeks.filter(w=>w.week_number>v.mesocycle.tracking_week).forEach(w=>w.revision_no=v.mesocycle.revision_no);}v.mesocycle.tracking_week++;}else throw Error('action_unavailable');value=true;}
  res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(value));
 }
 if(req.method!=='GET'){res.writeHead(405);return res.end();}if(req.url==='/review'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(html);}
 if(!/^\/assets\/coach-premium-analysis\.(js|css)$/.test(req.url)){res.writeHead(404);return res.end();}const f=path.join(root,req.url);res.setHeader('Content-Type',req.url.endsWith('.css')?'text/css':'application/javascript');res.end(fs.readFileSync(f));
 }catch(e){res.writeHead(400,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}));}}).listen(port,'127.0.0.1',()=>console.log('Premium analysis preview http://127.0.0.1:'+port+'/review ('+(live?'staging':'offline')+')'));
