const fs=require('fs'),path=require('path');
const dir=path.join(__dirname,'private'),r=JSON.parse(fs.readFileSync(path.join(dir,'reserved.json'))),ctx=r.analysis_bundle.provider;
const q=x=>"'"+JSON.stringify(x).replaceAll("'","''")+"'::jsonb";
const valid={schema_version:'premium-recommendation-v1',kind:'KEEP',facts:[{exercise_ref:'exercise_1',claim:ctx.routine.exercises[0].metrics.trend}],interpretation:'Progreso comparable.',reason:'Mantener.',confidence:'medium',changes:[]};
const mutate=f=>{const v=structuredClone(valid);f(v);return v;},modify=(action,from,to)=>mutate(v=>{v.kind='MODIFY';v.changes=[{action,exercise_ref:'exercise_1',from,to}];});
const cases=[['KEEP valid',valid,true],['small sets valid',modify('change_sets',3,2),true],['rest valid',modify('change_rest',180,240),true],['RIR valid',modify('change_rir','2','1'),true],['reps valid',modify('change_reps','8-12','10-15'),true],
 ['extra field', {...valid,sql:'update'},false],['null confidence',{...valid,confidence:null},false],['null kind',{...valid,kind:null},false],['unsupported fact',mutate(v=>v.facts[0].claim='stable_comparable'),false],['foreign ref',mutate(v=>v.facts[0].exercise_ref='foreign'),false],['stale from',modify('change_sets',4,3),false],['large volume',modify('change_sets',3,8),false],['zero sets',modify('change_sets',3,0),false],['reversed reps',modify('change_reps','8-12','15-8'),false],['unknown action',modify('exec_sql',3,2),false],['no-op',modify('change_sets',3,3),false],['private email',{...valid,reason:'email@example.invalid'},false],['medical',{...valid,reason:'Diagnóstico médico.'},false],['unsupported REVIEW changes',{...modify('change_sets',3,2),kind:'REVIEW'},false],
 ['bad replacement',mutate(v=>{v.kind='MODIFY';v.changes=[{action:'replace_exercise',exercise_ref:'exercise_1',from_catalogue_id:'db_row',to_catalogue_id:'bar_squat'}];}),false],['valid replacement',mutate(v=>{v.kind='MODIFY';v.changes=[{action:'replace_exercise',exercise_ref:'exercise_1',from_catalogue_id:'db_row',to_catalogue_id:'band_row'}];}),true]];
let sql=`begin;do $test$ declare r public.coach_recommendations;v jsonb;ok boolean;results jsonb:='{}';begin select * into r from public.coach_recommendations where id='${r.id}';\n`;
for(const[name,v,expected]of cases)sql+=`v:=${q(v)};ok:=true;begin perform coach_private.premium_output_patches(r,v);exception when others then ok:=false;end;results:=results||jsonb_build_object('${name}',ok=${expected});if ok<>${expected} then raise exception 'failed ${name}';end if;\n`;
sql+=`perform set_config('test.premium_results',results::text,true);end $test$;select current_setting('test.premium_results')::jsonb checks;rollback;`;fs.writeFileSync(path.join(dir,'semantic.sql'),sql);
