// Screenshots of the explicitly fictitious preview; no Supabase or provider calls.
const path=require('path'),assert=require('assert/strict');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'}),p=await b.newPage({viewport:{width:390,height:844}});let remote=0;p.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4195/'))remote++;});
try{await p.goto('http://127.0.0.1:4195/demo');await p.waitForFunction(()=>window.previewReady);await p.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).click();await p.locator('#coachBegin').click();await p.locator('#coachGoal').fill('Ganar fuerza general');await p.evaluate(()=>{$('coachDialog').scrollTop=0});await p.screenshot({path:path.join(__dirname,'results/final-intake-mobile.png')});
await p.locator('#coachGrantTraining').check();await p.waitForFunction(()=>!simpleCoach.busy);await p.locator('#coachGrantHealth').check();await p.waitForFunction(()=>!simpleCoach.busy);await p.getByRole('button',{name:'Revisar antes de enviar'}).click();await p.locator('#coachConfirmSend').click();await p.getByRole('heading',{name:'Tu rutina está siendo revisada',exact:true}).waitFor();await p.evaluate(()=>{$('coachDialog').scrollTop=0});await p.screenshot({path:path.join(__dirname,'results/final-pending-mobile.png')});
await p.evaluate(()=>{pilotDemoReviewer=true;return openCoachReviewer()});await p.locator('#coachQueue textarea').fill('Ejemplo: revisados días, volumen, frecuencia, duración y contexto.');await p.getByRole('button',{name:'Aprobar propuesta',exact:true}).click();await p.getByRole('heading',{name:'Aprobada',exact:true}).waitFor();await p.setViewportSize({width:1280,height:900});await p.locator('#coachQueue details').first().evaluate(e=>e.open=true);await p.evaluate(()=>{$('coachDialog').scrollTop=0});await p.screenshot({path:path.join(__dirname,'results/final-reviewer-desktop.png')});
await p.evaluate(()=>{pilotDemoReviewer=false;return openSimpleCoach()});await p.locator('#coachBegin').click();await p.locator('#coachAccept').waitFor();await p.setViewportSize({width:390,height:844});await p.evaluate(()=>{simpleTheme.set('dark');$('coachDialog').scrollTop=0});await p.screenshot({path:path.join(__dirname,'results/final-approved-dark.png')});assert.equal(remote,0);assert(await p.getByRole('button',{name:'Cerrar SIMPLE Coach',exact:true}).isEnabled());console.log('Final preview: reviewed, no remote requests; close enabled.');
}finally{await b.close();}})().catch(e=>{console.error(e.message);process.exitCode=1});
