// Local staging preview. Never serves private files or session tokens.
const http=require('http'),fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'../..'),port=Number(process.env.COACH_PORT||4194);
const sdk=path.resolve(root,'../google-auth/tests/onboarding/private/supabase-2.115.0.js');
const types={'.js':'application/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'};
http.createServer((req,res)=>{const u=new URL(req.url,'http://127.0.0.1');res.setHeader('Cache-Control','no-store');if(req.method!=='GET'){res.writeHead(405);return res.end();}
if(u.pathname==='/review'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end('<!doctype html><html lang="es"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SIMPLE Coach · Preview 1C</title><style>body{margin:0;font:14px system-ui;background:#f7f5f1;color:#252929}header{padding:12px 18px}iframe{display:block;border:0;width:100%;height:calc(100dvh - 90px)}a{color:inherit}</style><header><b>SIMPLE Coach · Fase 1C</b><p>Demostración ficticia local. Sin conexión a Supabase ni IA. Los datos se reinician al recargar. <a href="/review">Reiniciar</a></p><div id="demoControls"><button data-mode="demo-athlete">Ver atleta</button> <button data-mode="demo-reviewer">Simular reviewer</button></div><script>document.getElementById("demoControls").onclick=e=>{if(e.target.dataset.mode)document.querySelector("iframe").contentWindow.postMessage(e.target.dataset.mode,location.origin)};</script></header><iframe title="SIMPLE Coach: recorrido de demostración" src="/demo"></iframe></html>');}
if(u.pathname==='/demo-sdk.js'){res.setHeader('Content-Type','application/javascript');return res.end(fs.readFileSync(path.join(root,'tests/interior/mock-sdk.js'),'utf8')+'\n'+fs.readFileSync(path.join(root,'tests/coach/demo-sdk.js'),'utf8')+'\n'+fs.readFileSync(path.join(root,'tests/coach-pilot/preview-sdk.js'),'utf8'));}
if(u.pathname==='/demo-seed.js'){res.setHeader('Content-Type','application/javascript');return res.end(fs.readFileSync(path.join(root,'tests/coach/demo-seed.js')));}
if(u.pathname==='/demo'){res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'none'; form-action 'none'; object-src 'none'; base-uri 'none'");res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(fs.readFileSync(path.join(root,'index.html'),'utf8').replace('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.115.0','/demo-sdk.js').replace('https://yvguatdqncadkwewlepe.supabase.co','https://dmqjexigdnfzobarhnib.supabase.co').replace('</body>','<script src="/demo-seed.js"></script></body>'));}
if(u.pathname==='/sdk.js'){res.setHeader('Content-Type','application/javascript');return res.end(fs.readFileSync(sdk));}
if(u.pathname==='/'){let s=fs.readFileSync(path.join(root,'index.html'),'utf8').replace('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.115.0','/sdk.js').replace(/const SUPABASE_URL\s*=.*?;/,"const SUPABASE_URL='https://dmqjexigdnfzobarhnib.supabase.co';").replace(/const SUPABASE_KEY\s*=.*?;/,"const SUPABASE_KEY='sb_publishable_GAqOb1_W3qiK8ka6EL1G7g_TutTPIVf';");res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(s);}
if(!/^\/assets\/[a-zA-Z0-9._/-]+$/.test(u.pathname)||u.pathname.includes('..')){res.writeHead(404);return res.end();}const file=path.join(root,u.pathname);if(!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));
}).listen(port,'127.0.0.1',()=>console.log('Local preview http://127.0.0.1:'+port+'/review — offline synthetic demo; / requires staging login'));
