const a=require('./api.cjs'),{fs,path,check,save}=a;
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');

(async()=>{await a.login();for(const [engine,who] of [['chromium','browser1'],['webkit','browser2']]){
if(process.env.COACH_ENGINE&&process.env.COACH_ENGINE!==engine)continue;
const b=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});const page=await b.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(20000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{const ui=JSON.parse(fs.readFileSync(path.join(__dirname,'private',who+'-ui.json'))),day=ui.days[0];const ex=(await a.table(who,'routine_exercises','day_id=eq.'+day.id+'&order=exercise_order')).data;
const prior=await a.table(who,'workouts','user_id=eq.'+a.c.users[who].id+'&workout_date=eq.2026-09-20');if(!prior.data.length){const seed=await a.table(who,'workouts','',{user_id:a.c.users[who].id,variant:day.name,day:day.name,workout_date:'2026-09-20',data:{routine_id:ui.routine,routine_day_id:day.id,day_name:day.name,duration_seconds:1234,exercises:ex.map(e=>({exercise_id:e.id,name:e.name,sets:[{kg:20,reps:9,rir:3,done:true}],notes:'SYNTHETIC previous note'}))}},'POST');check(engine+' authenticated prior workout fixture',seed.ok);}
await page.addInitScript(({s,ref})=>localStorage.setItem('sb-'+ref+'-auth-token',JSON.stringify(s)),{s:a.sessions[who],ref:a.c.ref});
await page.goto('http://127.0.0.1:4194');await page.locator('#coachHome .card').filter({has:page.getByRole('button',{name:'Entrenar',exact:true})}).getByRole('button',{name:'Entrenar',exact:true}).click();await page.locator('#trainBody .interior-session-list button').first().click();await page.locator('.workout-exercise').first().waitFor();
check(engine+' existing last-session identity',await page.evaluate(id=>!!getPreviousExerciseSession(id),ex[0].id));
if(!await page.evaluate(()=>activeWorkout.locked)){for(let i=0;i<await page.getByRole('textbox',{name:/^KG ·/}).count();i++){await page.getByRole('textbox',{name:/^KG ·/}).nth(i).fill('31');await page.getByRole('textbox',{name:/^Repeticiones ·/}).nth(i).fill('11');await page.getByRole('textbox',{name:/^RIR ·/}).nth(i).fill('2');}
await page.getByRole('textbox',{name:/^Notas de /}).first().fill('SYNTHETIC personal note');await page.getByRole('button',{name:/^Completar serie/}).first().click();await page.evaluate(()=>saveWorkoutDraft());
const draft=await page.evaluate(()=>({key:workoutDraftKey(),data:localStorage.getItem(workoutDraftKey())}));check(engine+' draft owner routine day UUID',draft.key.includes(a.c.users[who].id)&&draft.key.includes(ui.routine)&&draft.key.includes(day.id)&&!!draft.data);
await page.reload();await page.getByRole('button',{name:'Entrenar',exact:true}).click();await page.locator('#trainBody .interior-session-list button').first().click();await page.locator('#saveWorkoutBtn').waitFor();check(engine+' draft restored',await page.getByRole('textbox',{name:/^KG ·/}).first().inputValue()==='31');
for(const width of [320,360,390,430,1280])for(const theme of ['light','dark']){await page.setViewportSize({width,height:900});await page.evaluate(t=>simpleTheme.set(t),theme);check(engine+' '+width+' '+theme+' session no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if([320,1280].includes(width))await page.screenshot({path:path.join(__dirname,'results',engine+'-training-'+width+'-'+theme+'.png'),fullPage:true});}
await page.locator('#saveWorkoutBtn').click();await page.waitForFunction(()=>!window.__savingWorkout&&(!activeWorkout||activeWorkout.locked===true));}
if(!await page.locator('#trainModal').isVisible()){await page.getByRole('button',{name:'Entrenar',exact:true}).click();await page.locator('#trainBody .interior-session-list button').first().click();await page.waitForFunction(()=>activeWorkout?.locked===true);}
const saved=await a.table(who,'workouts','user_id=eq.'+a.c.users[who].id+'&order=workout_date.desc');check(engine+' real workout persisted',saved.ok&&saved.data.length===2&&saved.data[0].data.exercises[0].sets[0].kg==='31'&&saved.data[0].data.exercises[0].notes==='SYNTHETIC personal note');
const notes=await a.table(who,'routine_user_notes','routine_id=eq.'+ui.routine);check(engine+' personal notes persisted',notes.ok&&notes.data.some(n=>n.note==='SYNTHETIC personal note'));
await page.locator('#trainModalActions').getByRole('button',{name:'Historial',exact:true}).click();await page.locator('.history-session').first().waitFor();check(engine+' history has both workouts',await page.locator('.history-session').count()===2);
await page.evaluate(()=>closeM('trainModal'));await page.getByRole('button',{name:'Progreso',exact:true}).click();await page.locator('#clientProgressExercise').waitFor();check(engine+' charts show only current exercises',await page.locator('#clientProgressExercise option').count()===ex.length);check(engine+' progress exact routine',await page.locator('#clientProgressTitle').getAttribute('data-routine-id')===ui.routine);
await page.evaluate(()=>closeM('clientProgressModal'));await page.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).click();await page.locator('#coachContext').click();await page.locator('#coachGoal').waitFor();
for(const width of [320,390,1280])for(const theme of ['light','dark']){await page.setViewportSize({width,height:900});await page.evaluate(t=>simpleTheme.set(t),theme);check(engine+' '+width+' '+theme+' intake no overflow',await page.locator('#coachDialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await page.screenshot({path:path.join(__dirname,'results',engine+'-intake-'+width+'-'+theme+'.png'),fullPage:true});}
await page.locator('#coachGrantHealth').uncheck();await page.waitForFunction(()=>!simpleCoach.busy);const grant=await a.table(who,'context_grants','scope=eq.declared_health&revoked_at=is.null');check(engine+' revoke after acceptance',grant.ok&&grant.data.length===0);
const old=(await a.table(who,'training_intakes','order=revision.desc&limit=1')).data[0];await page.locator('#coachGoal').fill('SYNTHETIC changed safely');await page.locator('#coachDraft').click();await page.getByText('Borrador guardado.',{exact:true}).waitFor();
const stale=await a.rpc(who,'save_my_training_intake',{p_id:old.id,p_expected:old.row_version,p_training:old.training,p_health:a.health,p_submit:true});check(engine+' stale submitted tab rejected',!stale.ok&&stale.data.message==='coach_intake_conflict');
const nullStale=await a.rpc(who,'save_my_training_intake',{p_id:null,p_expected:null,p_training:old.training,p_health:a.health,p_submit:true});check(engine+' stale blank tab rejected',!nullStale.ok&&nullStale.data.message==='coach_intake_conflict');
const structure=await a.table(who,'routine_exercises','day_id=eq.'+day.id+'&order=exercise_order');check(engine+' intake changes preserve accepted prescription',JSON.stringify(structure.data)===JSON.stringify(ex));
await page.getByRole('button',{name:'Cerrar SIMPLE Coach',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Entrenar',exact:true}).waitFor();check(engine+' session persists with own Coach routine',true);check(engine+' no page errors',errors.length===0,errors.join(';'));
}catch(e){fs.writeFileSync(path.join(__dirname,'results',engine+'-training-failure.txt'),await page.locator('body').innerText());throw e;}finally{await b.close();}save('training-browser');}save('training-browser');})().catch(e=>{save('training-browser');console.error(e.message);process.exitCode=1});
