const a=require('./api.cjs'),{fs,path,check}=a;
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{await a.login();for(const engine of ['chromium','webkit']){
 const b=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});const p=await b.newPage({viewport:{width:390,height:844}});p.setDefaultTimeout(15000);const errors=[];p.on('pageerror',e=>errors.push(e.message));
 try{
 await p.goto('http://127.0.0.1:4194/demo');await p.waitForFunction(()=>window.previewReady);await p.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).click();await p.locator('#coachBegin').click();
 await p.locator('#coachGoal').fill('Fuerza general de prueba');await p.getByRole('button',{name:'Revisar antes de enviar',exact:true}).click();check(engine+' UI requires both consents',await p.locator('#coachError').textContent()==='Autoriza los dos contextos para generar la propuesta.');
 await p.locator('#coachDraft').click();await p.getByText('Borrador guardado.',{exact:true}).waitFor();check(engine+' draft saved before consent',await p.evaluate(()=>mock.tables.training_intakes[0].state==='draft'));
 for(const width of [320,360,390,430,1280])for(const theme of ['light','dark']){await p.setViewportSize({width,height:900});await p.evaluate(t=>simpleTheme.set(t),theme);check(engine+' intake '+width+' '+theme+' accessible size',await p.locator('#coachDialog').evaluate(d=>d.scrollWidth<=d.clientWidth+1&&parseFloat(getComputedStyle(d.querySelector('input')).fontSize)>=16&&d.querySelector('button').getBoundingClientRect().height>=44));if(width===390)await p.screenshot({path:path.join(__dirname,'results',engine+'-consent-'+theme+'.png'),fullPage:true});}
 await p.locator('#coachGrantTraining').check();await p.waitForFunction(()=>!simpleCoach.busy);await p.locator('#coachGrantHealth').check();await p.waitForFunction(()=>!simpleCoach.busy);
 await p.getByRole('button',{name:'Revisar antes de enviar',exact:true}).click();await p.locator('#coachConfirmSend').waitFor();check(engine+' review no send',await p.evaluate(()=>mock.tables.coach_operations.length===0));check(engine+' review shows declared values',await p.locator('#coachProposal').innerText().then(t=>t.includes('Fuerza general de prueba')&&t.includes('Gimnasio')));
 await p.locator('#coachReviewBack').click();check(engine+' back keeps draft values',await p.locator('#coachGoal').inputValue()==='Fuerza general de prueba');await p.getByRole('button',{name:'Revisar antes de enviar',exact:true}).click();
 await p.evaluate(()=>{window.calls=0;const original=db.functions.invoke;db.functions.invoke=async(...args)=>{window.calls++;await new Promise(r=>setTimeout(r,500));return original(...args);};});
 await p.locator('#coachConfirmSend').evaluate(el=>{el.click();el.click();});await p.getByRole('heading',{name:'Pendiente de revisión',exact:true}).waitFor();check(engine+' duplicate sends only once',await p.evaluate(()=>window.calls===1));check(engine+' no immediate acceptance',await p.locator('#coachAccept').count()===0);
 await p.evaluate(()=>{pilotDemoReviewer=true;return openCoachReviewer();});await p.locator('#coachQueue textarea').fill('Revisión de demostración');await p.getByRole('button',{name:'Aprobar propuesta',exact:true}).click();await p.getByRole('heading',{name:'Aprobada',exact:true}).waitFor();check(engine+' preview reviewer flow updated',true);
 await p.evaluate(()=>{pilotDemoReviewer=false;return openSimpleCoach();});await p.locator('#coachBegin').click();await p.locator('#coachAccept').waitFor();await p.locator('#coachDecline').click();await p.locator('#coachComment').fill('Preferiría otra distribución');await p.getByRole('button',{name:'Enviar comentario y rechazar',exact:true}).click();await p.getByRole('heading',{name:'Propuesta no aceptada',exact:true}).waitFor();check(engine+' athlete refusal recorded',await p.evaluate(()=>mock.tables.coach_operations[0].athlete_comment==='Preferiría otra distribución'));
 // REAL JWT: recover the reserved server operation on reload without invoking Edge.
 const ctx=await b.newContext({viewport:{width:390,height:844}});await ctx.addInitScript(({s,ref})=>localStorage.setItem('sb-'+ref+'-auth-token',JSON.stringify(s)),{s:a.sessions.owner,ref:a.c.ref});const q=await ctx.newPage();let invokes=0;q.on('request',r=>{if(r.url().includes('/functions/v1/'))invokes++;});await q.goto('http://127.0.0.1:4194');await q.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).click();await q.locator('#coachBegin').click();await q.getByText('Estamos preparando tu rutina…',{exact:true}).waitFor();await q.reload();await q.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).click();await q.locator('#coachBegin').click();await q.getByText('Estamos preparando tu rutina…',{exact:true}).waitFor();check(engine+' generating reload reuses operation without AI',invokes===0);await q.getByRole('button',{name:'Cerrar SIMPLE Coach',exact:true}).click();check(engine+' can leave generating state',!await q.locator('#coachDialog').isVisible());
 // REAL JWT: reviewer feedback and athlete feedback form, after consent revocation.
 for(const w of ['reviewer','browser1']){const c=await b.newContext({viewport:{width:390,height:844}});await c.addInitScript(({s,ref})=>localStorage.setItem('sb-'+ref+'-auth-token',JSON.stringify(s)),{s:a.sessions[w],ref:a.c.ref});const page=await c.newPage();await page.goto('http://127.0.0.1:4194');if(w==='reviewer'){await page.locator('#coachReviewerEntry button').click();await page.getByText('Feedback del piloto (1)',{exact:true}).waitFor();check(engine+' reviewer reads feedback after intake revoke',true);}else{const prior=(await a.table(w,'coach_pilot_feedback')).data[0];await page.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).click();await page.locator('#coachFeedback').click();await page.locator('#coachRating').waitFor();check(engine+' feedback form loads own existing score',await page.locator('#coachRating').inputValue()===String(prior.rating));const score=prior.rating===4?5:4;await page.locator('#coachRating').selectOption(String(score));await page.getByRole('button',{name:'Guardar valoración',exact:true}).click();await page.getByText('Valoración guardada.',{exact:true}).waitFor();const after=(await a.table(w,'coach_pilot_feedback')).data;check(engine+' feedback success persists one row',after.length===1&&after[0].id===prior.id&&after[0].rating===score);await page.screenshot({path:path.join(__dirname,'results',engine+'-feedback.png'),fullPage:true});}await c.close();}
 check(engine+' no page errors',errors.length===0,errors.join(';'));
 }catch(e){fs.writeFileSync(path.join(__dirname,'results',engine+'-ui-failure.txt'),await p.locator('body').innerText());console.error(await p.evaluate(()=>({busy:simpleCoach.busy,grants:mock.tables.context_grants,valid:$('coachForm')?.checkValidity(),errors:document.getElementById('coachError')?.textContent})));throw e;}finally{await b.close();a.save('ui');}
 }})().catch(e=>{a.save('ui');console.error(e.message);process.exitCode=1});
