const fs=require('fs'),path=require('path'),assert=require('assert/strict');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),results=[];
function check(name,v){assert(v,name);results.push({name,pass:true});}
(async()=>{for(const engine of ['chromium','webkit']){const b=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});try{const p=await b.newPage();await p.goto('http://127.0.0.1:4195/demo');await p.waitForFunction(()=>window.previewReady);check(engine+' authorized sees Coach',await p.locator('#coachHome').count()===1);
await p.evaluate(async()=>{window.visibilityRPC=db.rpc;db.rpc=async(n,a)=>n==='get_my_coach_access'?{data:{authorized:false},error:null}:window.visibilityRPC(n,a);await renderShared();});check(engine+' nonpilot no public Coach entry',await p.locator('#coachHome').count()===0);
await p.evaluate(async()=>{db.rpc=async(n,a)=>n==='get_my_coach_access'?{data:null,error:{message:'offline'}}:window.visibilityRPC(n,a);await renderShared();});check(engine+' access error fails closed',await p.locator('#coachHome').count()===0);
await p.evaluate(async()=>{db.rpc=window.visibilityRPC;await renderShared();});await p.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).click();await p.locator('#coachBegin').click();await p.locator('#coachGoal').fill('Fuerza');await p.locator('#coachGrantTraining').check();await p.waitForFunction(()=>!simpleCoach.busy);await p.locator('#coachGrantHealth').check();await p.waitForFunction(()=>!simpleCoach.busy);await p.getByRole('button',{name:'Revisar antes de enviar'}).click();await p.locator('#coachConfirmSend').click();await p.getByRole('heading',{name:'Tu rutina está siendo revisada',exact:true}).waitFor();await p.evaluate(async()=>{pilotDemoReviewer=true;await openCoachReviewer();});await p.locator('#coachQueue textarea').fill('SYNTHETIC review');await p.getByRole('button',{name:'Aprobar propuesta',exact:true}).click();await p.getByRole('heading',{name:'Aprobada',exact:true}).waitFor();await p.evaluate(async()=>{pilotDemoReviewer=false;await openSimpleCoach()});await p.locator('#coachBegin').click();await p.locator('#coachAccept').click();await p.getByRole('heading',{name:'Rutina creada',exact:true}).waitFor();await p.getByRole('button',{name:'Cerrar SIMPLE Coach',exact:true}).click();
await p.evaluate(async()=>{db.rpc=async(n,a)=>{const r=await window.visibilityRPC(n,a);if(n==='get_my_coach_access')r.data.authorized=false;return r};await renderShared();});check(engine+' accepted routine remains visible after revoke',await p.getByRole('button',{name:'Entrenar',exact:true}).count()===1);
await p.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).click();await p.locator('#coachOpen').waitFor();check(engine+' revoked accepted keeps routine and permissions entry',await p.locator('#coachContext').count()===1);
}finally{await b.close();}}fs.writeFileSync(path.join(__dirname,'results/visibility.json'),JSON.stringify(results,null,2));console.log(results.length+' visibility checks passed');})().catch(e=>{console.error(e.message);process.exitCode=1});
