require('fs').mkdirSync(require('path').join(__dirname,'results'),{recursive:true});
const fs=require('fs'),vm=require('vm'),crypto=require('crypto'),path=require('path');
const legacy='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a';
process.env.PLAYWRIGHT_BROWSERS_PATH=legacy+'/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const html=fs.readFileSync('index.html','utf8'),old=fs.readFileSync(legacy+'/work/test-ux-browser.cjs','utf8');
let stub=vm.runInNewContext(old.slice(old.indexOf('const stub='),old.indexOf('const results=[]'))+'stub');
stub=stub.replace('String(x[k])===String(v)',"String(k.includes('->>')?x[k.split('->>')[0]]?.[k.split('->>')[1]]:x[k])===String(v)");
const results=[];
(async()=>{for(const engine of ['chromium','webkit'])for(const width of [390,1280]){
 const b=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});
 try{const p=await b.newPage({viewport:{width,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/*',r=>r.request().url()==='http://simple.test/'?r.fulfill({body:html,contentType:'text/html'}):r.request().url().includes('cdn.jsdelivr')?r.fulfill({body:stub,contentType:'application/javascript'}):r.abort());
 await p.goto('http://simple.test/');
 const rows=await p.evaluate(async()=>{
  const results=[],test=(name,actual,expected)=>results.push({name,pass:JSON.stringify(actual)===JSON.stringify(expected),actual,expected});
  const uid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
  const U=uid(1),R=uid(2),A=uid(3),B=uid(4),EA=uid(5),EB=uid(6),EC=uid(7),OLD=uid(8),name='Extensión de tríceps';
  const ex=(id,kg,n=name)=>({exercise_id:id,name:n,sets:[{kg,reps:10,rir:2}],notes:''});
  const session=(day,exercises,date='2026-01-01')=>({id:uid(day===A?50:51),user_id:U,workout_date:date,data:{routine_id:R,routine_day_id:day,day_name:day===A?'A':'B',exercises}});
  const days=[{id:A,name:'A',exercises:[{id:EA,name}]},{id:B,name:'B',exercises:[{id:EB,name}]}],map={[EA]:name,[EB]:name};
  const h=[session(A,[ex(EA,20)]),session(B,[ex(EB,50)],'2026-01-02')];
  const pts=(sessions,id,m=map,metric='weight')=>getExercisePoints(sessions,'id:'+id,metric,m,new Set(Object.keys(m))).map(x=>x.value);
  user={id:U};profile={role:'trainer'};workoutRoutine={id:R,name:'Prueba local'};window.workoutHistory=h;
  window.__routineHistoryContext={owner:user,routine:workoutRoutine,dayId:null};
  test('Historial general conserva ambos días',visibleWorkoutHistory().length,2);
  window.__routineHistoryContext.dayId=A;test('Historial A filtra por UUID',visibleWorkoutHistory().map(x=>x.data.routine_day_id),[A]);
  window.__routineHistoryContext.dayId=B;test('Historial B filtra por UUID',visibleWorkoutHistory().map(x=>x.data.routine_day_id),[B]);
  const gd=getProgressDays(h,days);
  test('Días distintos mantienen identidades',[gd[0].key,gd[1].key],[A,B]);
  test('Gráfica A contiene solo A',pts(gd[0].sessions,EA),[20]);
  test('Gráfica B contiene solo B',pts(gd[1].sessions,EB),[50]);
  const same=[session(A,[ex(EA,20),ex(EB,50)])];
  const entries=getProgressExercises(same,map,new Set([EA,EB]));
  test('Homónimos mismo día producen dos opciones UUID',entries.map(e=>e.key),['id:'+EA,'id:'+EB]);
  test('Homónimos tienen etiquetas distinguibles',new Set(entries.map(e=>e.label)).size,2);
  test('No se mezclan pesos A',pts(same,EA),[20]);
  test('No se mezclan pesos B',pts(same,EB),[50]);
  test('Renombrar A conserva gráfica',pts(same,EA,{...map,[EA]:'Otro nombre'}),[20]);
  test('Renombrar A no contamina nombre antiguo B',pts(same,EB,{...map,[EA]:'Otro nombre'}),[50]);
  test('UUID nuevo con nombre reutilizado no hereda puntos',pts(same,EC,{[EC]:name}),[]);
  test('Histórico eliminado conserva opción por su propio UUID',getProgressExercises([h[0]],{[EC]:name},new Set([EC])).map(e=>e.key),['id:'+EC,'id:'+EA]);
  test('Serie eliminada conserva todos sus puntos',pts([h[0]],EA,{[EC]:name}),[20]);
  const noid=[session(A,[ex('',30)])];
  test('Histórico sin UUID tiene opción legacy explícita',getProgressExercises(noid,{},new Set()).map(e=>e.key),['legacy:'+normalizeProgressExerciseName(name)]);
  test('Legacy sin UUID conserva puntos separados',getExercisePoints(noid,'legacy:'+normalizeProgressExerciseName(name),'weight').map(x=>x.value),[30]);
  test('Legacy no se adjudica a un ejercicio UUID',pts(noid,EA),[]);
  test('Legacy homónimo ambiguo en misma sesión no combina sets',getExercisePoints([session(A,[ex('',30),ex('',60)])],'legacy:'+normalizeProgressExerciseName(name),'weight').length,0);
  test('Selector no depende del orden para su identidad',new Set(getProgressExercises(same,map,new Set([EB,EA])).map(e=>e.key)).size,2);
  test('Gráfica mantiene fórmula de repeticiones',pts(same,EA,map,'reps'),[10]);
  test('Gráfica mantiene fórmula 1RM',pts(same,EA,map,'1rm'),[0.0333*20*10+20]);
  const collision=getProgressDays([h[0]],[{...days[0],name:'Renombrado'}, {...days[1],name:'A'}])[0];
  test('UUID día tiene prioridad incluso con nombre histórico reutilizado',[collision.key,collision.id,collision.name],[A,A,'Renombrado']);
  const orphan=structuredClone(h[0]);orphan.data.routine_day_id=OLD;
  test('Día UUID huérfano no se asocia a otro por nombre',getProgressDays([orphan],days).map(x=>[x.key,x.id]),[[OLD,null]]);
  test('Día huérfano mantiene sesiones consultables',getProgressDays([orphan],days)[0].sessions.length,1);
  const noDay=structuredClone(h[0]);delete noDay.data.routine_day_id;
  test('Día sin UUID usa nombre exacto único',getProgressDays([noDay],days)[0].id,A);
  test('Día sin UUID con nombre duplicado no escoge arbitrariamente',getProgressDays([noDay],[days[0],{...days[1],name:'A'}])[0].id,null);
  test('Reordenar días conserva sus UUID',getProgressDays(h,[days[1],days[0]]).map(d=>d.key),[B,A]);
  activeWorkout={day:days[0],exercises:days[0].exercises,historyDays:days,sets:{}};
  test('Última sesión A exacta',getPreviousExerciseSession(EA)?.exercise.sets[0].kg,20);
  const legacy=session(OLD,[ex(OLD,90)],'2026-01-03');legacy.data.day_name='A';window.workoutHistory=[legacy,...h];
  test('UUID exacto anterior gana a fallback legacy más reciente',getPreviousExerciseSession(EA)?.exercise.sets[0].kg,20);
  activeWorkout.exercises=[{id:EC,name}];window.workoutHistory=h;
  test('Nuevo homónimo no hereda Última sesión en día actual',getPreviousExerciseSession(EC),null);
  activeWorkout.exercises=[{id:EA,name:'Renombrado'}];test('Última sesión conserva UUID tras renombrar',getPreviousExerciseSession(EA)?.exercise.sets[0].kg,20);
  activeWorkout.day=days[1];test('Última sesión sigue UUID al mover entre días',getPreviousExerciseSession(EA)?.exercise.sets[0].kg,20);
  window.__routineHistoryContext=null;window.__simpleStarted=true;localStorage.clear();$('auth').style.display='none';$('app').style.display='block';
  mock.tables.routines=[{...workoutRoutine,owner_id:U}];routines=mock.tables.routines;
  mock.tables.routine_days=days.map((d,i)=>({id:d.id,name:d.name,routine_id:R,day_order:i}));
  mock.tables.routine_exercises=[{id:EA,day_id:A,name,sets:1,exercise_order:0},{id:EB,day_id:A,name,sets:1,exercise_order:1}];
  mock.tables.routine_user_notes=[];mock.tables.workouts=[session(A,[ex(EA,20)],simpleLocalDateKey())];
  openM('trainModal');await startWorkoutDay(A);
  test('Reapertura de hoy conserva sets UUID exacto',activeWorkout.sets[EA][0].kg,20);
  test('Reapertura de hoy no copia sets al homónimo',activeWorkout.sets[EB][0].kg,'');
  test('Reapertura mantiene bloqueo',activeWorkout.locked,true);
  closeM('trainModal');mock.tables.workouts=[];await openRoutineProgress(R);
  mock.tables.workouts=same;await openRoutineProgress(R);
  $('clientProgressPeriod').value='all';$('clientProgressPeriod').dispatchEvent(new Event('change'));
  test('UI moderna usa dos valores UUID distintos',[...$('clientProgressExercise').options].map(o=>o.value),['id:'+EA,'id:'+EB]);
  $('clientProgressExercise').value='id:'+EA;renderClientProgressChart();test('UI primera serie un punto',clientProgressChartState.points.map(p=>p.value),[20]);
  $('clientProgressExercise').value='id:'+EB;renderClientProgressChart();test('UI segunda serie un punto',clientProgressChartState.points.map(p=>p.value),[50]);
  closeM('clientProgressModal');localStorage.clear();
  const a={id:EA,name},b={id:EB,name},renamed={id:EA,name:'Renombrado'};
  const personal=new Map([['exercise:'+EA,'Nota A'],['exercise:'+EB,'Nota B']]);
  const resolve=(e,ns=personal,local={},current=[a,b],history=[])=>resolveExerciseNote(e,ns,local,current,history);
  test('Notas modernas A y B independientes',[resolve(a),resolve(b)],['Nota A','Nota B']);
  test('Renombrar UUID conserva nota',resolve(renamed),'Nota A');
  test('Mover UUID conserva nota',resolve({...a,day_id:B}),'Nota A');
  test('Reordenar UUID conserva nota',resolve({...a,exercise_order:9}),'Nota A');
  test('Nuevo UUID con nombre antiguo no hereda nota',resolve({id:EC,name}),'');
  test('Borrar/recrear no hereda nota',resolve({id:EC,name},personal,{},[{id:EC,name}],h),'');
  test('Vacío moderno prevalece sobre plantilla y local',resolve({...a,notes:'Template'},new Map([['exercise:'+EA,'']]),{[EA]:'Old local'}),'');
  test('Local UUID distinto no se usa',resolve({id:EC,name},new Map(),{[EA]:'Local A'}),'');
  test('Local vacío mantiene borrado',resolve(a,new Map(),{[EA]:''}),'');
  test('Local legacy por nombre sin procedencia no se usa',resolve(a,new Map(),{[name]:'Old name'}),'');
  const historic=session(A,[{...ex(EA,30),notes:'Evidence A'}]);
  const legacyNotes=new Map([[simpleNormalizeNoteKey(name),'Evidence A']]);
  test('Legacy único con evidencia UUID puede recuperarse',safeLegacyExerciseNote(a,legacyNotes,[a],[historic]),'Evidence A');
  test('Legacy único hoy sin evidencia no se reasigna',safeLegacyExerciseNote(a,legacyNotes,[a],[]),undefined);
  test('Legacy con homónimos actuales queda sin asignar',safeLegacyExerciseNote(a,legacyNotes,[a,b],[historic]),undefined);
  test('Legacy UUID antiguo y UUID nuevo queda sin asignar',safeLegacyExerciseNote({id:EC,name},legacyNotes,[{id:EC,name}],[historic]),undefined);
  test('Legacy colisión histórica no se asigna',safeLegacyExerciseNote(a,legacyNotes,[a],[historic,session(B,[{...ex(EB,50),notes:'Other'}])]),undefined);
  test('Legacy nota distinta de evidencia no se adjudica',safeLegacyExerciseNote(a,new Map([[simpleNormalizeNoteKey(name),'Unproven']]),[a],[historic]),undefined);
  test('Recuperar nota histórica exacta por UUID',resolve(a,new Map(),{},[a],[historic]),'Evidence A');
  test('Histórico huérfano no da nota a nuevo UUID',resolve({id:EC,name},new Map(),{},[{id:EC,name}],[historic]),'');
  test('Notas históricas vacías no restauran anteriores',resolve(a,new Map(),{},[a],[session(A,[{...ex(EA,40),notes:''}]),historic]),'');
  test('Histórico UUID ambiguo no elige una nota',resolve(a,new Map(),{},[a],[session(A,[{...ex(EA,40),notes:'First'},{...ex(EA,50),notes:'Second'}])]),'');
  activeWorkout={day:days[0],exercises:[{id:EC,name}],historyDays:days,sets:{}};window.workoutHistory=[legacy];
  test('Día huérfano y ejercicio huérfano no dan Última sesión al nuevo UUID',getPreviousExerciseSession(EC),null);
  mock.tables.routine_exercises=[{id:EC,day_id:A,name,sets:1,exercise_order:0}];
  mock.tables.workouts=[session(A,[ex('',99)],simpleLocalDateKey())];
  openM('trainModal');await startWorkoutDay(A);
  test('Reapertura legacy sin UUID no inventa ejecución del nuevo UUID',activeWorkout.sets[EC][0].kg,'');
  closeM('trainModal');localStorage.clear();return results;
 });
 results.push(...rows.map(r=>({engine,width,...r})),{engine,width,name:'Sin excepciones JavaScript',pass:errors.length===0,actual:errors});
 console.log(engine,rows.length+1,'checks',rows.filter(r=>!r.pass));
 }finally{await b.close()}}
 const report={sha256:crypto.createHash('sha256').update(html).digest('hex'),passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass),results};
 fs.writeFileSync('tests/identity/results/browser.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed}));if(report.failed.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
