// Actual index.html entry point, using only its existing offline SDK. No remote requests.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),App=require('../../assets/coach-premium-app.js');
const {seedFixture,base}=require('./premium-training.cjs');
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.join(__dirname,'results'),rows=[];function check(name,v){rows.push({name,pass:!!v});assert(v,name);}
async function hostFixture(){
 const old=db.rpc;window.premiumHostMode='off';window.premiumHostCalls=[];
 db.rpc=async(name,args={})=>{
  if(name==='premium_my_access'){
   premiumHostCalls.push({name});const mode=premiumHostMode;if(mode==='delay')await new Promise(r=>setTimeout(r,600));
   if(mode==='missing')return {data:null,error:{code:'PGRST202',message:'Function missing'}};
   if(mode==='error')return {data:null,error:{code:'network_error',message:'network_error'}};
   const f=premiumTrainingFixture;return {data:{plan:'premium',enabled:mode!=='off',consent:true,notice_version:'premium-followup-v1',capabilities:['tracking','analysis','chat'],allowances:{generation:{remaining:0},analysis:{remaining:1},chat:{remaining:1}},routines:[{routine_id:f.rid,name:'Rutina local Premium N+1',management:'premium',current_revision_id:f.revision,mesocycle_id:f.meso}]},error:null};
  }
  if(name==='premium_chat_load')return {data:{available:true,permission:true,history_permission:true,revision_id:premiumTrainingFixture.revision,revision_no:2,week:2,messages:[]},error:null};
  if(name==='premium_recommendation_view'){if(premiumHostMode==='missing')return {data:null,error:{code:'PGRST202',message:'Function missing'}};const r=mock.tables.coach_recommendations.find(x=>x.id===args.p_id);return {data:r?{...r,quality_warnings:r.analysis_trace.quality_warnings,context_snapshot:undefined}:null,error:null};}
  if(name==='premium_review_recommendation'){const m=mock.tables.coach_mesocycles[0],r=mock.tables.coach_recommendations.find(x=>x.id===args.p_id);if(m.reviewer_id!==user.id||!r)return {data:null,error:{message:'premium_not_authorized'}};r.state=args.p_approve?'ready':'rejected';r.review_reason=args.p_reason;return {data:null,error:null};}
  return old(name,args);
 };
}
async function renderHome(p,mode){await p.evaluate(async mode=>{premiumHostMode=mode;document.getElementById('coachHome')?.remove();await renderCoachHome();},mode);}
async function run(){
 fs.mkdirSync(out,{recursive:true});const words={premium_admission_required:/Autoriza/,premium_admission_stale_or_revoked:/revocado/,premium_basic_baseline_mismatch:/revisión Basic/,premium_basic_operation_pending:/Basic pendiente/,premium_owner_allowance_exhausted:/No quedan solicitudes/,premium_shared_budget_exhausted:/presupuesto/,premium_upgrade_conflict:/otra pestaña/,premium_key_conflict:/otros datos/,premium_notice_required:/aviso/};
 for(const [code,match]of Object.entries(words))check('specific error '+code,match.test(App.errorText({code}))&&App.errorText({code})===App.errorText({message:code}));
 check('unknown error sanitizes provider detail',!App.errorText({message:'sensitive raw provider output'}).includes('sensitive'));
 for(const [engine,type]of [['chromium',chromium],['webkit',webkit]]){
  const browser=await type.launch(engine==='chromium'?{channel:'msedge'}:{});try{
   const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await p.goto(base+'/demo');await p.waitForFunction(()=>qualityReady);await p.evaluate(seedFixture);await p.evaluate(hostFixture);
   for(const mode of ['off','missing','error']){
    await p.evaluate(()=>localStorage.setItem('premium-access',JSON.stringify({enabled:true,plan:'premium'})));await renderHome(p,mode);
    check(engine+' '+mode+' no Premium entry',await p.getByRole('button',{name:'Abrir seguimiento Premium',exact:true}).count()===0);
    check(engine+' '+mode+' Basic unchanged',await p.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).count()===1);
   }
   await renderHome(p,'on');check(engine+' enabled entry once',await p.getByRole('button',{name:'Abrir seguimiento Premium',exact:true}).count()===1);check(engine+' enabled keeps Basic',await p.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).count()===1);
   await p.getByRole('button',{name:'Abrir seguimiento Premium',exact:true}).click();await p.waitForFunction(()=>!!simpleCoachPremium.controller);
   check(engine+' actual session owner',await p.evaluate(()=>simpleCoachPremium.controller.snapshot().view.user_id===user.id));check(engine+' current revision N+1',await p.evaluate(()=>simpleCoachPremium.controller.snapshot().view.mesocycle.revision_id===premiumTrainingFixture.revision));
   check(engine+' partial intake no invented answers',await p.evaluate(()=>simpleCoachPremium.controller.snapshot().intake.activity.type===null&&Object.keys(mock.tables.coach_mesocycles[0].intake).length===1));
   await p.evaluate(()=>simpleCoachPremium.controller.navigate('intake'));check(engine+' partial submitted intake explicit error',(await p.locator('#premiumCoachHost main').innerText()).includes('No se ha podido confirmar la anamnesis guardada'));await p.evaluate(()=>simpleCoachPremium.controller.navigate('home'));
   for(const width of [320,360,390,430,1280])for(const theme of ['light','dark']){
    await p.setViewportSize({width,height:844});await p.evaluate(t=>simpleTheme.set(t),theme);await p.waitForTimeout(50);
    const g=await p.locator('#premiumCoachDialog').evaluate(d=>{const r=d.getBoundingClientRect(),app=d.querySelector('.premium-app');return {horizontal:d.scrollWidth<=d.clientWidth+1,width:r.width,inside:r.left>=0&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight+1,scrolls:[...d.querySelectorAll('*')].filter(x=>x.tagName!=='TEXTAREA'&&x.clientHeight>0&&x.scrollHeight>x.clientHeight+2&&['auto','scroll'].includes(getComputedStyle(x).overflowY)).length,targets:[...app.querySelectorAll('button')].filter(x=>x.getClientRects().length&&x.getBoundingClientRect().height<43.5).length};});
    check(engine+' '+width+' '+theme+' dialog fits',g.inside&&g.horizontal);check(engine+' '+width+' '+theme+' sole vertical scroll',g.scrolls<=1);check(engine+' '+width+' '+theme+' target 44',g.targets===0);
   }
   await p.setViewportSize({width:390,height:430});check(engine+' keyboard viewport simulated fits',await p.locator('#premiumCoachDialog').evaluate(d=>d.getBoundingClientRect().bottom<=innerHeight+1));await p.setViewportSize({width:390,height:844});
   if(engine==='chromium'){await p.evaluate(()=>simpleTheme.set('dark'));await p.screenshot({path:path.join(out,'actual-host-390-dark.png')});}
   await p.locator('#premiumCoachHost [data-action=exit]').click();await p.waitForFunction(()=>!premiumCoachDialog().open&&simpleCoachPremium.controller===null);check(engine+' back closes dialog',await p.evaluate(()=>!document.getElementById('premiumCoachDialog').open&&simpleCoachPremium.controller===null));
   await p.evaluate(()=>premiumHostMode='off');await p.evaluate(()=>openPremiumCoach());check(engine+' direct disabled no mount',await p.locator('#premiumCoachHost.premium-app').count()===0);check(engine+' direct disabled clear notice',(await p.locator('#premiumCoachHost').innerText()).includes('no está disponible'));await p.evaluate(()=>premiumCoachDialog().close());
   await p.evaluate(()=>premiumHostMode='error');await p.evaluate(()=>openPremiumCoach());check(engine+' load error visible no false success',await p.locator('#premiumCoachHost [role=alert]').count()===1&&!(await p.locator('#premiumCoachHost').innerText()).includes('preparado'));check(engine+' load error manual retry',await p.getByRole('button',{name:'Reintentar',exact:true}).count()===1);await p.evaluate(()=>premiumCoachDialog().close());
   await p.evaluate(()=>{premiumHostMode='delay';window.premiumPending=openPremiumCoach();});check(engine+' slow gate loading',await p.locator('#premiumCoachHost [role=status]').innerText()==='Cargando seguimiento…');await p.evaluate(()=>premiumCoachDialog().close());await p.evaluate(()=>premiumPending);check(engine+' late gate cannot reopen',await p.evaluate(()=>!premiumCoachDialog().open&&simpleCoachPremium.controller===null&&premiumCoachDialog().childElementCount===0));
   await p.evaluate(()=>premiumHostMode='on');await p.evaluate(()=>openPremiumCoach());await p.locator('#premiumCoachHost .premium-app-nav [data-action=program]').click();check(engine+' actual host all twelve exercises',await p.locator('#premiumCoachHost .premium-app-exercise').count()===12);await p.locator('#premiumCoachHost [data-action=training]').click();await p.waitForFunction(()=>workoutRoutine?.id===premiumTrainingFixture.rid);check(engine+' train destination exact UUID',await p.evaluate(()=>!premiumCoachDialog().open&&workoutRoutine.id===premiumTrainingFixture.rid&&simpleCoach.routineHints.byId.revisionId===premiumTrainingFixture.revision));
   await p.evaluate(()=>openPremiumCoach());const sub=await p.evaluate(()=>coachDemo.authCallbacks.length-1);await p.evaluate(i=>{const owner=user.id;user={...user,id:crypto.randomUUID()};coachDemo.authCallbacks[i]('SIGNED_IN',{user:{id:user.id}});user={...user,id:owner};},sub);await p.waitForFunction(()=>!premiumCoachDialog().open&&simpleCoachPremium.controller===null);check(engine+' session change removes old owner host',await p.evaluate(()=>!premiumCoachDialog().open&&premiumCoachDialog().childElementCount===0&&simpleCoachPremium.controller===null));
   const ids=await p.evaluate(()=>{closeM('trainModal');const f=premiumTrainingFixture,reviewer=crypto.randomUUID(),other=crypto.randomUUID();mock.tables.coach_mesocycles[0].reviewer_id=reviewer;mock.tables.coach_recommendations=[{id:crypto.randomUUID(),mesocycle_id:f.meso,base_revision_id:f.revision,kind:'KEEP',state:'pending_review',patches:[],facts:[],interpretation:'Conservar la programación con el contexto registrado.',analysis_week:2,analysis_trace:{quality_warnings:['Revisar la comparabilidad antes de decidir.']},context_snapshot:{private_chat:'PRIVATE_CHAT_SENTINEL'}}];window.premiumReviewerFixture={reviewer,other,owner:user.id};return premiumReviewerFixture;});
   await p.evaluate(()=>renderPremiumCoachReviewerEntry(user.id));check(engine+' owner no reviewer entry',await p.locator('#premiumCoachReviewerEntry').count()===0);
   await p.evaluate(async()=>{user={...user,id:premiumReviewerFixture.other};profile={...profile,role:'trainer'};pilotDemoReviewer=true;await renderCoachReviewerEntry();});check(engine+' other trainer no Premium entry',await p.locator('#premiumCoachReviewerEntry').count()===0);check(engine+' other trainer Basic queue unchanged',await p.locator('#coachReviewerEntry').count()===1);
   await p.evaluate(()=>openPremiumCoach({mesocycleId:premiumTrainingFixture.meso}));check(engine+' unassigned direct scope rejected',await p.locator('#premiumCoachHost.premium-app').count()===0&&await p.locator('#premiumCoachHost [role=alert]').count()===1);await p.evaluate(()=>premiumCoachDialog().close());
   await p.evaluate(async()=>{user={...user,id:premiumReviewerFixture.reviewer};premiumHostMode='off';await renderCoachReviewerEntry();});check(engine+' assigned Premium entry once',await p.locator('#premiumCoachReviewerEntry button').count()===1);check(engine+' assigned exact UUID no PII',(await p.locator('#premiumCoachReviewerEntry').innerText()).includes(await p.evaluate(()=>premiumTrainingFixture.meso))&&!(await p.locator('#premiumCoachReviewerEntry').innerText()).includes('@'));check(engine+' assigned Basic queue unchanged',await p.locator('#coachReviewerEntry').count()===1);
   const reads=await p.evaluate(()=>coachDemo.reads.length);await p.locator('#premiumCoachReviewerEntry button').click();await p.waitForFunction(()=>simpleCoachPremium.controller?.snapshot().view.actor==='reviewer');check(engine+' reviewer no owner entitlement required',await p.evaluate(()=>simpleCoachPremium.controller.snapshot().view.access.enabled===false));check(engine+' reviewer no check-in chat nav',await p.locator('#premiumCoachHost [data-action=chat],#premiumCoachHost [data-action=checkin]').count()===0);
   await p.locator('#premiumCoachHost .premium-app-nav [data-action=analysis]').click();await p.getByRole('button',{name:'Ver propuesta',exact:true}).click();check(engine+' reviewer warnings before approve',await p.getByRole('heading',{name:'Avisos de calidad'}).count()===1&&await p.getByRole('button',{name:'Aprobar propuesta',exact:true}).count()===1);check(engine+' reviewer no raw transcript',(await p.locator('#premiumCoachHost').innerText()).includes('PRIVATE_CHAT_SENTINEL')===false);check(engine+' reviewer no owner grants/checkins reads',await p.evaluate(n=>coachDemo.reads.slice(n).every(t=>!['context_grants','coach_weekly_checkins','coach_messages','coach_conversations','routine_user_notes'].includes(t)),reads));
   await p.locator('#premium-review-reason').fill('Revisión local de la propuesta y sus avisos.');await p.getByRole('button',{name:'Aprobar propuesta',exact:true}).click();await p.waitForFunction(()=>mock.tables.coach_recommendations[0].state==='ready'&&!simpleCoachPremium.controller.snapshot().busy);check(engine+' reviewer approval confirmed mock state',await p.evaluate(()=>simpleCoachPremium.controller.snapshot().view.recommendations[0].state==='ready'));await p.locator('#premiumCoachHost [data-action=exit]').click();await p.waitForFunction(()=>!premiumCoachDialog().open&&simpleCoachPremium.controller===null);
   await p.evaluate(()=>premiumHostMode='missing');await p.evaluate(()=>openPremiumCoach({mesocycleId:premiumTrainingFixture.meso}));check(engine+' reviewer missing RPC visible error no mount',await p.locator('#premiumCoachHost.premium-app').count()===0&&await p.locator('#premiumCoachHost [role=alert]').count()===1);await p.evaluate(()=>premiumCoachDialog().close());
   await p.evaluate(async()=>{const real=db.from;db.from=table=>{const q=real(table);if(table==='coach_mesocycles'){const then=q.then;q.then=async(resolve,reject)=>{await new Promise(r=>setTimeout(r,250));return then(resolve,reject);};}return q;};window.premiumReviewerPending=renderPremiumCoachReviewerEntry(user.id);user={...user,id:premiumReviewerFixture.other};await premiumReviewerPending;db.from=real;});check(engine+' reviewer stale session cannot render assignment',await p.locator('#premiumCoachReviewerEntry').count()===0);
   check(engine+' no provider invoke',await p.evaluate(()=>coachDemo.invokeCalls.length===0));check(engine+' no browser errors',errors.length===0);
  }finally{await browser.close();}
 }
 fs.writeFileSync(path.join(out,'host.json'),JSON.stringify({passed:rows.length,total:rows.length,scope:'actual index offline entry gate/session/navigation + Node error translations',rows},null,2));console.log(rows.length+'/'+rows.length+' actual Premium host Chromium/WebKit + specific error contracts');
}
module.exports={hostFixture};if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1;});
