// Critical bridge contracts; no Auth, DB or provider traffic.
const assert=require('assert/strict'),fs=require('fs'),path=require('path');
require('../../assets/coach-intake.js');require('../../assets/coach-programming-v4.js');require('../../assets/coach-programming-v5.js');
const P=require('../../assets/coach-premium-prescription.js'),H=require('./live.cjs'),rows=[];
const check=(n,v)=>{assert(v,n);rows.push({name:n,pass:true});},copy=v=>structuredClone(v),b=H.readJSON(H.file('before-upgrade.json'));
const r=b.revision,owner=r.user_id,routine=r.routine_id,management={routine_id:routine,user_id:owner,operation_id:r.operation_id,current_revision_id:r.id,plan_kind:'premium'};
const bindings=Object.fromEntries(r.snapshot.days.flatMap(d=>d.exercises.map(e=>[e.id,globalThis.SimpleCoachProgrammingV5.byName.get(e.name).id])));
const initial=P.hints(r,management,routine,owner,bindings);check('Inherited accepted Basic V5 exact twelve UUIDs',initial?.size===12);check('Heterogeneous per-series targets preserved',initial.get(r.snapshot.days[0].exercises[0].id).sets[2].rir===0&&initial.get(r.snapshot.days[0].exercises[0].id).sets[0].reps_max===8);
const next=copy(r);next.id='20000000-0000-4000-8000-000000000001';next.origin='premium_recommendation';next.operation_id=null;next.snapshot={routine:{id:routine,owner_id:owner},days:copy(r.snapshot.days)};const ng={...management,current_revision_id:next.id};
const id=next.snapshot.days[0].exercises[0].id;next.snapshot.days[0].exercises[0].planned_sets.pop();next.snapshot.days[0].exercises[0].sets--;
check('Premium N+1 does not require old Basic operation_id',P.hints(next,ng,routine,owner,bindings)?.get(id)?.sets.length===2);
for(const [name,mutate]of [
 ['wrong owner',x=>x.user_id='20000000-0000-4000-8000-000000000009'],['wrong routine',x=>x.routine_id='20000000-0000-4000-8000-000000000009'],['old revision',x=>x.id=r.id],['duplicate exercise',x=>x.snapshot.days[0].exercises.push(copy(x.snapshot.days[0].exercises[0]))],['missing per-series prescription',x=>x.snapshot.days[0].exercises[0].planned_sets=null],['first-set projection mismatch',x=>x.snapshot.days[0].exercises[0].rir=4],['wrong day',x=>x.snapshot.days[0].exercises[0].day_id=x.snapshot.days[1].id],['foreign root',x=>x.snapshot.routine.owner_id='20000000-0000-4000-8000-000000000009'],['unknown origin',x=>x.origin='manual'],['invalid series range',x=>x.snapshot.days[0].exercises[0].planned_sets[0].reps_max=99]
]){const x=copy(next);mutate(x);check(name+' rejected',P.hints(x,ng,routine,owner,bindings)===null);}
{const old=copy(r);old.snapshot.days.forEach(d=>d.exercises.forEach(e=>{delete e.planned_sets;delete e.scheme;e.sets=2;e.reps_min=8;e.reps_max=12;e.rir=3;e.rest_seconds=75;}));const map=P.hints(old,management,routine,owner,bindings);check('Shared legacy Basic v2/v3/v4 numeric format read without rewrite',map?.size===12&&map.get(id)?.sets[0].rest_seconds===75&&map.get(id)?.sets[0].rir===3);}
const a={owner,routine,byId:P.hints(next,ng,routine,owner,bindings)};check('Premium workout carries exact delivered N+1',P.workoutRevision(a,owner,routine)===next.id);check('Other owner cannot stamp a revision',P.workoutRevision(a,'other',routine)===null);check('Basic untouched without Premium marker',P.workoutRevision({owner,routine,byId:new Map()},owner,routine)===null);check('Locked history is not reconstructed by reader',JSON.stringify(b.revision)===JSON.stringify(r));
const many=Array.from({length:12},(_,i)=>({set_number:i+1,reps_min:8,reps_max:12,rir:i===11?0:2,rest_seconds:180}));check('Delivered Premium permits validated up-to-twelve series',P.valid(many));check('Null remains missing rather than RIR0',P.sets({sets:2,reps_min:8,reps_max:12,rir:null,rest_seconds:180})===null);
fs.mkdirSync(path.join(__dirname,'results'),{recursive:true});fs.writeFileSync(path.join(__dirname,'results/prescription.json'),JSON.stringify({rows,total:rows.length,completed:true,provider_calls:0},null,2));console.log(rows.length+'/'+rows.length+' prescription bridge contracts');
