// Unified offline preview. Synthetic training data only; no DB/Auth/provider requests.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
const I=require('../../assets/coach-intake.js'),W=require('../../assets/coach-premium-weekly.js');
const root=path.resolve(__dirname,'../..'),port=Number(process.env.PREMIUM_UPGRADE_PORT||4251),copy=v=>structuredClone(v);
const ids={user:'10000000-0000-4000-8000-000000000001',routine:'10000000-0000-4000-8000-000000000002',revision:'10000000-0000-4000-8000-000000000003',meso:'10000000-0000-4000-8000-000000000004',week:'10000000-0000-4000-8000-000000000005'};
const cases=[['basic','Basic → Premium'],['new','Adopción Premium nueva'],['normal','Semana activa'],['intake','Anamnesis pendiente'],['missing','Sin check-in'],['reviewer','Reviewer asignado'],['denied','Sin autorización'],['expired','Piloto caducado'],['revoked','Historial revocado'],['null','Sin semana / datos incompletos'],['legacy','Prescripción antigua'],['long','Nombres largos'],['conflict','Conflicto de revisión'],['error','Error de red'],['budget','Presupuesto agotado'],['stale','Respuesta tardía'],['xss','Texto con caracteres especiales']];
function training(){return {...I.emptyPremium(),experience:'y1_2',goal:'balanced',days:2,weekdays:['mon','thu'],effort:'learning',pause:false,minutes_by_day:{mon:60,thu:60},confidence:'medium',recovery:'mostly',sleep:'h7_8',stress:'medium',distribution:'coach',inventory:{equipment:I.equipment.map(e=>e.id),custom:[]},activity:{type:'none',weekdays:[],minutes:null,intensity:null}};}
function fixture(tag='normal'){
 const set=(i,rir,seconds)=>({set_number:i,reps_min:8,reps_max:10,rir,rest_seconds:seconds});
 const days=['Lunes / Torso','Jueves / Pierna'].map((name,j)=>({id:'10000000-0000-4000-8000-00000000001'+j,name,day_order:j,exercises:[0,1].map((_,k)=>({id:'10000000-0000-4000-8000-00000000002'+(j*2+k),name:['Press inclinado máquina','Remo pecho apoyado','Prensa 45º','Curl femoral sentado'][j*2+k],exercise_order:k,sets:2,target:'8–10',rir:2,rest_seconds:180,planned_sets:[set(1,2,180),set(2,1,210)]}))}));
 const v={mode:'offline',actor:tag==='reviewer'?'reviewer':'athlete',user_id:ids.user,access:{plan:'premium',enabled:true,expires_at:'2026-12-31T23:59:59Z',consent:true,notice_version:'premium-followup-v1',capabilities:['tracking','analysis','chat'],allowances:{generation:{limit:0,consumed:0,remaining:0},analysis:{limit:3,consumed:0,remaining:3},chat:{limit:10,consumed:0,remaining:10}},routines:[{routine_id:ids.routine,name:'Mi programación',management:'premium',current_revision_id:ids.revision,mesocycle_id:ids.meso,upgradable:false,blocker:null}]},mesocycle:{id:ids.meso,routine_id:ids.routine,number:1,state:'active',planned_weeks:6,revision_id:ids.revision,current_revision_id:ids.revision,revision_no:1,row_version:2,intake:training(),intake_submitted_at:'2026-10-01T12:00:00Z'},week:{id:ids.week,week_number:2,number:2,state:'active'},permission:true,weekly_permission:true,checkin:null,days,recommendations:[]};
 const before=copy(days[0].exercises[0].planned_sets),after=copy(before);after[1].reps_max=12;
 v.recommendations=[{id:'10000000-0000-4000-8000-000000000099',kind:'MODIFY',state:tag==='reviewer'?'pending_review':'ready',revision_id:ids.revision,analysis_week:2,reason:'La carga y el RIR son comparables; aumenta el rango de la última serie manteniendo la calidad técnica.',facts:[{exercise_name:days[0].exercises[0].name,claim:'reps_increasing_comparable',observations:[{date:'2026-09-29',sets:[{kg:40,reps:9,rir:2}]},{date:'2026-10-03',sets:[{kg:40,reps:10,rir:2}]}]}],changes:[{action:'planned_sets',exercise_name:days[0].exercises[0].name,before,after}],quality_warnings:['Confirma que el descanso conserva el rendimiento de la siguiente serie.']}];
 if(['basic','new'].includes(tag)){v.mesocycle=null;v.week=null;v.days=[];v.recommendations=[];v.access.consent=false;v.access.plan=tag==='basic'?'basic':'premium';v.access.routines[0]={...v.access.routines[0],management:tag==='basic'?'basic':'unmanaged',mesocycle_id:null,upgradable:tag==='basic'};}
 if(['denied','expired'].includes(tag)){v.access.enabled=false;v.access.plan='free';v.access.routines=[];v.mesocycle=null;v.week=null;v.days=[];v.recommendations=[];}
 if(tag==='revoked')v.permission=false;
 if(tag==='null'){v.week=null;v.days=[];v.recommendations=[];}
 if(tag==='legacy')days.forEach(d=>d.exercises.forEach(e=>{delete e.planned_sets;delete e.target;e.reps_min=8;e.reps_max=10;}));
 if(tag==='long')days[0].exercises[0].name='Press inclinado en máquina convergente con agarre neutro y un nombre muy largo para comprobar legibilidad';
 if(tag==='xss')days[0].exercises[0].name='<img src=x onerror="window.hostXss=true">';
 if(tag==='missing')v.recommendations=[];
 if(tag==='intake'){v.mesocycle.intake=I.emptyPremium();v.mesocycle.intake_submitted_at=null;v.mesocycle.state='draft';}
 return v;
}
function createOfflineAdapter(){const states=new Map(),messages=new Map(),keys=new Map(),calls=[];let chatCalls=0;
 const get=tag=>{if(!cases.some(c=>c[0]===tag))throw Error('invalid_request');if(!states.has(tag))states.set(tag,fixture(tag));return states.get(tag);};
 async function handle({action,tag='normal',data={}}){const v=get(tag);calls.push({action,tag});if(action==='reset'){states.set(tag,fixture(tag));messages.delete(tag);return copy(states.get(tag));}if(action==='state'){if(tag==='error')throw Error('network_error');if(tag==='stale')await new Promise(r=>setTimeout(r,850));return copy(v);}
  if(!v.access.enabled)throw Error('premium_not_authorized');
  if(action==='admission_permission'){v.access.consent=data.allow===true;return copy(v);}
  if(['upgrade','start'].includes(action)){if(!v.access.consent)throw Error('premium_admission_consent_required');if(data.routine_id!==ids.routine)throw Error('premium_not_authorized');if(!keys.has(data.key)){const n=fixture('intake');n.access=copy(v.access);n.access.plan='premium';n.access.routines[0].management='premium';n.access.routines[0].mesocycle_id=ids.meso;states.set(tag,n);keys.set(data.key,ids.meso);}return copy(states.get(tag));}
  if(action==='history_permission'){v.permission=data.allow===true;return copy(v);}
  if(action==='weekly_permission'){v.weekly_permission=data.allow===true;return copy(v);}
  if(action==='intake_save'){if(tag==='conflict'||data.expected!==v.mesocycle.row_version)throw Error('premium_intake_conflict');if(I.premiumErrors(data.training,data.submit).length)throw Error('premium_invalid_intake');v.mesocycle.intake=copy(data.training);v.mesocycle.row_version++;if(data.submit){v.mesocycle.intake_submitted_at=new Date().toISOString();v.mesocycle.state='active';}return copy(v);}
  if(action==='checkin_save'){if(tag==='conflict'||data.revision_id!==v.mesocycle.revision_id||data.expected!==(v.checkin?.row_version||0))throw Error('premium_weekly_conflict');if(v.checkin?.submitted_at)throw Error('premium_weekly_already_submitted');if(data.submit&&W.validateAnswers(data.answers,v.days.flatMap(d=>d.exercises)))throw Error('premium_weekly_invalid_answers');v.checkin={id:randomUUID(),answers:copy(data.answers),row_version:(v.checkin?.row_version||0)+1,submitted_at:data.submit?new Date().toISOString():null};return copy(v);}
  if(action==='analyze'){if(tag==='budget')throw Error('premium_budget_exhausted');if(!v.permission)throw Error('premium_not_authorized');v.recommendations=fixture().recommendations;v.recommendations[0].kind='KEEP';v.recommendations[0].changes=[];v.recommendations[0].state='pending_review';return copy(v);}
  if(action==='accept'){const r=v.recommendations.find(r=>r.id===data.id);if(!r||r.state!=='ready'||r.revision_id!==v.mesocycle.revision_id)throw Error('premium_stale_revision');v.days[0].exercises[0].planned_sets=copy(r.changes[0]?.after||v.days[0].exercises[0].planned_sets);r.state='accepted';v.mesocycle.revision_no++;v.mesocycle.revision_id=randomUUID();return copy(v);}
  if(['review','reject','resolve'].includes(action)){if(v.actor!=='reviewer')throw Error('premium_not_authorized');v.recommendations.find(r=>r.id===data.id).state=action==='reject'?'rejected':'ready';return copy(v);}
  if(action==='chat_state'||action==='chat_permission'){if(action==='chat_permission')v.chat_permission=data.allow===true;return {mesocycle_id:ids.meso,revision_id:v.mesocycle.revision_id,revision_no:v.mesocycle.revision_no,week:2,planned_weeks:6,conversation_id:ids.week,permission:v.chat_permission!==false,history_permission:v.permission,available:v.permission,messages:copy(messages.get(tag)||[])};}
  if(['chat_send','chat_retry'].includes(action)){if(!v.permission)throw Error('premium_chat_consent_required');if(data.revision_id!==v.mesocycle.revision_id)throw Error('premium_chat_stale_revision');if(tag==='budget')return {message:{state:'failed',error:'premium_chat_budget_exhausted'}};if(!keys.has(data.key)){chatCalls++;const rows=messages.get(tag)||[];rows.push({id:randomUUID(),sequence_no:rows.length+1,state:'completed',user_message:data.message,answer:'Conserva la programación y los descansos indicados. Podemos revisar las últimas exposiciones comparables antes de proponer cambios.',revision_id:v.mesocycle.revision_id,recommendation_id:/propuesta/i.test(data.message)?v.recommendations[0]?.id:null});messages.set(tag,rows);keys.set(data.key,rows.at(-1));}return {message:copy(keys.get(data.key))};}
  throw Error('action_unavailable');
 }
 return {mode:'offline',handle,snapshot:()=>({calls:copy(calls),states:copy([...states]),chatCalls})};
}
function html(){return `<!doctype html><html lang="es" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SIMPLE Coach Premium · vista unificada</title><link rel="stylesheet" href="/assets/theme.css"><link rel="stylesheet" href="/assets/coach-premium-app.css"><link rel="stylesheet" href="/assets/coach-premium-chat.css"><style>body{margin:0}.preview-header{max-width:920px;margin:auto;font:12px Arial,sans-serif;padding:8px 16px;box-sizing:border-box;border-bottom:1px solid var(--simple-line)}.preview-header p{margin:0;line-height:1.4}.preview-header details{margin-top:4px}.preview-header select,.preview-header button{font:inherit;color:var(--simple-text);background:var(--simple-card);border:1px solid var(--simple-control-line);padding:8px;max-width:100%}</style></head><body><aside class="preview-header"><p>Vista local · datos y respuestas simulados · sin OpenAI ni bases de datos</p><details id="preview-tools"><summary>Opciones de la vista previa</summary><label for="case">Escenario </label><select id="case">${cases.map(([v,l])=>'<option value="'+v+'">'+l+'</option>').join('')}</select><button id="theme">Claro / Oscuro</button></details></aside><div id="premium-host"></div><script src="/assets/coach-intake.js"></script><script src="/assets/coach-questionnaire.js"></script><script src="/assets/coach-premium-weekly.js"></script><script src="/assets/coach-premium-chat.js"></script><script src="/assets/coach-premium-adapter.js"></script><script src="/assets/coach-premium-app.js"></script><script>
const selector=document.getElementById('case'),params=new URLSearchParams(location.search);if([...selector.options].some(o=>o.value===params.get('case')))selector.value=params.get('case');
let controller;async function api(action,data={}){const response=await fetch('/premium-host-api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,tag:selector.value,data})});const value=await response.json();if(!response.ok)throw Object.assign(Error(value.error),{code:value.error});return value;}
function start(){controller=PremiumApp.mount(document.getElementById('premium-host'),{adapter:api,onNavigate:()=>controller.navigate('home')});window.PremiumHostUI=controller;}start();
async function setCase(tag,reset=true){controller.destroy();selector.value=tag;localStorage.clear();history.replaceState({},'',location.pathname+'?case='+encodeURIComponent(tag));if(reset)await api('reset');document.getElementById('preview-tools').open=false;start();}
selector.onchange=()=>setCase(selector.value);document.getElementById('theme').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark'};document.getElementById('preview-tools').ontoggle=()=>window.dispatchEvent(new Event('resize'));window.PremiumHostPreview={setCase,api};
</script></body></html>`;}
function rejectPrivate(v){if(!v||typeof v!=='object')return;for(const [k,x]of Object.entries(v)){if(/^(access_token|refresh_token|authorization|apikey|secret|password|service_role|context_bundle|analysis_bundle|context_snapshot)$/i.test(k))throw Error('unsafe_projection');rejectPrivate(x);}}
function createServer(adapter=createOfflineAdapter(),serverPort=port){return http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');try{
 const route=req.url.split('?')[0];if(req.method==='GET'&&['/','/review'].includes(route)){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(html());}
 if(req.method==='POST'&&route==='/premium-host-api'){if(req.headers.origin!=='http://127.0.0.1:'+serverPort)throw Error('origin_denied');let body='';for await(const part of req){body+=part;if(Buffer.byteLength(body)>20000)throw Error('invalid_request');}const value=await adapter.handle(JSON.parse(body));rejectPrivate(value);res.setHeader('Content-Type','application/json;charset=utf-8');return res.end(JSON.stringify(value));}
 const assets=['theme.css','coach-intake.js','coach-questionnaire.js','coach-premium-weekly.js','coach-premium-chat.js','coach-premium-chat.css','coach-premium-app.js','coach-premium-app.css','coach-premium-adapter.js'].map(x=>'/assets/'+x);if(req.method==='GET'&&assets.includes(route)){res.setHeader('Content-Type',route.endsWith('.css')?'text/css;charset=utf-8':'application/javascript;charset=utf-8');return res.end(fs.readFileSync(path.join(root,route)));}res.writeHead(404);res.end();
 }catch(e){res.writeHead(400,{'Content-Type':'application/json;charset=utf-8'});res.end(JSON.stringify({error:/^[a-z_]+$/.test(e.code||e.message)?e.code||e.message:'invalid_request'}));}});}
if(require.main===module)createServer().listen(port,'127.0.0.1',()=>console.log('Unified offline Premium preview http://127.0.0.1:'+port+'/review'));
module.exports={createOfflineAdapter,createServer,fixture,training,cases,ids};
