// Read-only audit of ONE actual provider result captured by Root; never dispatches or retries.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{isDeepStrictEqual:equal}=require('util'),{pathToFileURL}=require('url');
const root=path.resolve(__dirname,'../..'),pfile=n=>path.join(__dirname,'private',n),read=n=>JSON.parse(fs.readFileSync(pfile(n))),rows=[];
const check=(name,ok)=>{rows.push({name,pass:!!ok});assert(ok,name);};
async function main(){
 const W=await import(pathToFileURL(path.join(root,'supabase/functions/simple-coach-premium/weekly-contract.mjs'))),f=read('fixture.json'),r=read('real-weekly-response.json').recommendation,p=read('real-weekly-provider.json'),persisted=read('real-weekly-audit-record.json'),o=r.analysis_trace.output,receipt=r.analysis_trace.receipt;
 check('Actual response and persisted proposal remain identical pending KEEP',r.state==='pending_review'&&persisted.state==='pending_review'&&r.kind==='KEEP'&&persisted.kind==='KEEP'&&persisted.error===null&&equal(o,persisted.output)&&r.analysis_trace.error===null);
 check('Captured real provider preserves inherited Basic and shared history',W.contextQuality(p).ok&&p.baseline_origin==='inherited_basic'&&p.history_origin==='shared_existing_training'&&p.routine.exercises.length===12&&p.routine.days.length===3);
 check('Actual provider binds active N+1 week3',p.mesocycle.current_revision===2&&p.mesocycle.week===3);
 check('Actual current checkin captured rather than inferred',p.checkin_missing===false&&p.checkin.recovery==='good'&&p.checkin.review.topic==='none'&&p.checkin.availability.changed===false&&equal(o.checkin_signals,W.checkinSignals(p)));
 check('Actual output passes final schema and semantic validators',W.validate(o)&&W.semantic(o,p).ok&&receipt.schema_valid===true&&receipt.semantic_valid===true);
 check('Every real factual claim matches exact captured metric',o.facts.every(x=>p.routine.exercises.find(e=>e.ref===x.exercise_ref)?.metrics.trend===x.claim));
 const saved=read('new-workout.json'),recorded=saved.data.exercises.find(x=>x.exercise_id===f.target_exercise),target=p.routine.exercises.find(e=>e.ref==='exercise_1');
 check('Current goblet prescription remains exact two-set Premium revision',target.catalogue_id==='goblet'&&target.planned_sets.length===2&&target.planned_sets[0].reps_min===6&&target.planned_sets[0].reps_max===8&&target.planned_sets[1].reps_min===8&&target.planned_sets[1].reps_max===10&&target.planned_sets.every(s=>s.rir===1&&s.rest_seconds===240));
 check('Actual context contains exact newly saved two-set performance',target.exposures.some(x=>x.date===saved.workout_date&&x.sets.length===2&&x.sets.every((s,i)=>s.kg===recorded.sets[i].kg&&s.reps===recorded.sets[i].reps&&s.rir===recorded.sets[i].rir)));
 check('Actual KEEP has no patches and no automated approval/acceptance',o.kind==='KEEP'&&o.changes.length===0&&r.patches.length===0&&persisted.state==='pending_review');
 check('Actual trace records fixed snapshot and known token cost',receipt.model==='gpt-5.4-2026-03-05'&&receipt.status===200&&receipt.input_tokens===12602&&receipt.output_tokens===527&&receipt.cached_input_tokens===0&&Math.abs(receipt.cost_usd-.039410)<1e-12);
 check('Actual quality warnings remain visible and empty for this output',Array.isArray(r.analysis_trace.quality_warnings)&&r.analysis_trace.quality_warnings.length===0);
 const chat=read('real-chat-response.json').message;check('Additional Chat request blocked before output rather than passed as real',chat.state==='failed'&&chat.error==='premium_chat_budget_exhausted'&&chat.answer===null&&chat.recommendation_id===null);
 const Q=globalThis.SimpleCoachProgrammingV5,table=o.facts.map(x=>{const e=p.routine.exercises.find(e=>e.ref===x.exercise_ref);return`| ${x.exercise_ref} | ${Q.byId.get(e.catalogue_id).name} | ${e.day_ref} | ${x.claim} | ${e.exposures.length} |`;}).join('\n');
 const doc=`# Una nueva llamada real con base Basic heredada\n\nLa única nueva llamada efectiva a GPT terminó con HTTP 200, KEEP pendiente de revisión, error null, esquema y semántica válidos. Se capturó directamente en solo lectura el mismo output persistido y su provider. No se aprobó ni aceptó esa propuesta. El contexto conserva tres días y doce ejercicios, revisión N+1/semana 3, base heredada de Basic, historial compartido y el check-in real enviado para esta prueba. Incluye la nueva sesión de goblet con dos series y sus datos exactos.\n\nModelo: gpt-5.4-2026-03-05. Tokens: 12.602 entrada, 527 salida, 0 caché. Coste: **0,039410 USD**. Sin quality warnings en esta salida concreta.\n\nInterpretación exacta:\n\n> ${o.interpretation}\n\nMotivo exacto:\n\n> ${o.reason}\n\nConfianza: ${o.confidence}. Cambios: ninguno. No se atribuye una decisión original de selección de ejercicios al atleta ni se presenta esa base como generada por Premium. La afirmación de semana parcial es prudente: el contexto semanal tiene registros limitados; no demuestra menor adherencia por sí sola.\n\n| Referencia | Ejercicio | Día lógico | Claim factual exacto | Exposiciones capturadas |\n|---|---|---|---|---:|\n${table}\n\nLos ocho claims coinciden exactamente con metrics.trend. Los cuatro ejercicios no citados siguen presentes en el contexto; el máximo de ocho facts limita la trazabilidad enumerada de una rutina de doce ejercicios, sin justificar datos inventados o cambios sin evidencia. Las señales subjetivas son las siete parejas field/value del check-in, no síntomas ni causalidad clínica.\n\nEl intento posterior de Chat quedó bloqueado **antes del proveedor** con premium_chat_budget_exhausted, sin answer ni candidato. No es una segunda llamada real superada ni un descarte con tokens consumidos. El ledger histórico y la reserva conservadora impedían encajar la petición en el límite vigente; no se ampliaron límites, no se resetearon consumos y no se reintentó. La continuidad Chat sobre esta base nueva sí tiene las pruebas mock/JWT descritas en PIPELINE.md; las siete respuestas Chat reales archivadas se documentan separadamente en telemetry-archive.md.\n\nAuditoría read-only nueva: **${rows.length}/${rows.length} comprobaciones**, sin llamadas remotas a OpenAI, generaciones, aprobación, aceptación o cambio de configuración. La captura de base de datos previa se realizó únicamente contra la fixture exacta de staging.\n`;
 fs.writeFileSync(path.join(__dirname,'REAL-INHERITED.md'),doc);fs.writeFileSync(path.join(__dirname,'results/real-audit.json'),JSON.stringify({rows,total:rows.length,completed:true,new_provider_dispatches:0,actual_source_dispatches:1,cost_usd:receipt.cost_usd},null,2));console.log(rows.length+'/'+rows.length+' actual-source read-only audit checks; no new dispatch');
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
