// Read existing Phase 4 evidence in place. No copies of private bundles, no provider calls.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const root=path.resolve(__dirname,'../..'),archive=process.argv[2]||path.resolve(root,'../premium-chat/tests/premium-chat');
async function main(){
 const C=await import(pathToFileURL(path.join(root,'supabase/functions/simple-coach-chat/chat-contract.mjs'))),S=await import(pathToFileURL(path.join(root,'supabase/functions/simple-coach-premium/series-contract.mjs')));
 const evidence=JSON.parse(fs.readFileSync(path.join(archive,'private/real-evidence.json'),'utf8')),ledger=JSON.parse(fs.readFileSync(path.join(archive,'results/real-dispatches.json'),'utf8'));
 assert.equal(evidence.length,8);assert.equal(ledger.length,9);
 let cost=0;const results=[],types=['Selección del hack','Progresión del press','Significado de RIR 1','Descansos y top/backoff','Sesiones y check-in de la semana','Petición de cambiar el curl','Intento de prompt injection/datos ajenos','Resumen de evolución y decisiones'];
 let doc='# Premium Phase 4 — revisión de las llamadas ya archivadas\n\nBase revisada: `1b8cf72`. Lectura de las evidencias originales de `premium-chat`, sin copiar bundles privados y sin nuevas llamadas.\n\nHay **ocho dispatches reales: siete respuestas aceptadas y una descartada**. Una novena solicitud fue bloqueada antes del proveedor. Ninguna de las siete respuestas válidas propuso cambios: `suggested_action=none`, `recommendation_candidate=null`. El pipeline de recomendación se probó separadamente con JWT y candidatos declarados mock.\n\n';
 for(let i=0;i<evidence.length;i++){
  const e=evidence[i],l=ledger[i];assert.equal(l.index,i+1);assert.equal(e.user_message,l.question);assert.equal(e.context.message,e.user_message);cost+=e.receipt.charged_usd;
  const contextValid=C.contextQuality(e.context).ok;assert(contextValid,'Archived captured context invalid');
  const facts=e.output?.facts_used||[],grounding=facts.map(id=>{const match=/^(exercise_\d+)\.(prescription|metric)$/.exec(id);if(!match)return{id,source:id==='checkin'?'Declaración semanal capturada':id==='schedule'?'Calendario de sesiones':'Registro cerrado de contexto'};const x=e.context.training.routine.exercises.find(x=>x.ref===match[1]);assert(x);return{id,exercise:S.CATALOGUE.find(c=>c.id===x.catalogue_id)?.name||x.catalogue_id,source:match[2]==='metric'?'Métricas/exposiciones registradas: trend `'+x.metrics.trend+'`, '+x.metrics.exposures+' exposiciones, '+x.metrics.recorded_sets+' series registradas':'Prescripción exacta: '+x.planned_sets.map(s=>'S'+s.set_number+' '+s.reps_min+'–'+s.reps_max+' reps / RIR '+s.rir+' / '+String(s.rest_seconds/60).replace('.',',')+' min').join('; ')};});
  if(!e.output){assert.equal(i,0);assert.equal(e.state,'failed');assert.equal(e.error,'premium_chat_invalid_output');results.push({index:1,classification:'discarded',schema:'not_reconstructable',semantic:'not_reconstructable',scope:'not_reconstructable',charged_usd:e.receipt.charged_usd});
   doc+='## 1 — Selección del hack: descartada\n\nPregunta: '+e.user_message+'\n\nEl proveedor respondió HTTP '+e.receipt.status+'; el servidor finalizó con `premium_chat_invalid_output`. El output literal no se conservó. Por ello **no se puede reconstruir su schema, semántica, scope ni la causa literal de rechazo**. Tampoco se atribuye retrospectivamente una categoría concreta: se detectaron y corrigieron falsos positivos de cargas/«mediciones», pero no demuestran cuál causó esta respuesta. Modelo `'+e.receipt.model+'`; coste '+e.receipt.charged_usd.toFixed(7)+' USD. La nueva telemetría es futura y no rellena ese dato histórico ausente.\n\n';continue;
  }
  const schema=C.validate(e.output),quality=C.semantic(e.output,e.context);assert(schema&&quality.ok,'Accepted archive no longer validates');assert.equal(e.state,'completed');assert.equal(e.error,null);assert.equal(e.output.suggested_action,'none');assert.equal(e.output.recommendation_candidate,null);assert.equal(e.answer,e.output.answer);
  const texts=[e.user_message,e.answer];assert(texts.every(t=>!/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|PRIVATE CANARY/i.test(t)),'Do not publish identity/private note text');
  results.push({index:i+1,classification:'accepted',schema,semantic:quality.ok,scope_safety:quality.failures.length===0,facts,suggested_action:e.output.suggested_action,recommendation_candidate:false,charged_usd:e.receipt.charged_usd});
  doc+='## '+(i+1)+' — '+types[i]+'\n\nPregunta: '+e.user_message+'\n\nContexto: revisión '+e.context.mesocycle.current_revision+', semana '+e.context.mesocycle.week+'; '+e.context.training.routine.exercises.length+' ejercicios con prescripción por serie; '+e.context.last_messages.length+' mensajes previos de esa revisión; check-in '+(e.context.checkin_missing?'ausente':'capturado y explícito')+'; '+e.context.recent_decisions.length+' decisiones estructuradas previas.\n\nFacts utilizados:\n\n'+grounding.map(f=>'- `'+f.id+'`: '+(f.exercise?f.exercise+' — ':'')+f.source+'.').join('\n')+'\n\nRespuesta exacta conservada:\n\n'+e.answer.split('\n').map(line=>'> '+line).join('\n')+'\n\nResultado: schema válido; semántica válida; filtros de scope/seguridad válidos; facts vinculados al contexto capturado. `suggested_action=none`; `recommendation_candidate=null`. HTTP '+e.receipt.status+'; coste '+e.receipt.charged_usd.toFixed(7)+' USD.\n\n';
 }
 const blocked=ledger[8];assert.equal(blocked.index,9);assert.equal(blocked.result.message?.state,'failed');assert.equal(blocked.result.message?.error,'premium_chat_budget_exhausted');assert(Math.abs(cost-.1948175)<1e-10);
 doc+='## 9 — Bloqueada antes del proveedor\n\nLa solicitud posterior de explicar el hack quedó `failed / premium_chat_budget_exhausted` durante claim. No constituye un noveno dispatch ni una respuesta de IA. La reserva conservadora de input/output no cabía en el saldo restante; no se reintentó.\n\n## Evaluación\n\nLas siete respuestas válidas están ancladas a la misma revisión vigente y al contexto real capturado. La petición de cambiar el curl no forzó una modificación y la inyección no devolvió instrucciones internas ni datos ajenos. El resumen no inventó decisiones aceptadas. Los checks automáticos son filtros acotados; no se presentan como una prueba matemática de veracidad o seguridad universal.\n\nMejoras de presentación observadas, sin reescribir las respuestas: casos 2/3 muestran `exercise_2`; casos 3/4 usan Markdown y segundos. El prompt del candidato ya pide nombres legibles, texto plano y minutos, pero esos siete outputs históricos no se regeneran ni se declaran modificados. En el caso 6, «estancamiento» es menos preciso que «rendimiento estable» cuando no hay regresión demostrada. En el caso 8, el calendario/check-in narrados existen en el contexto, pero `facts_used` ya contiene ocho IDs de ejercicios y no cita schedule/checkin; es una limitación de trazabilidad de referencias, no datos inventados. No cambia el schema ni fuerza recomendaciones.\n\nCoste de los ocho dispatches archivados: **'+cost.toFixed(7)+' USD**. Coste anterior de análisis: 0,3549945 USD; acumulado archivado: **0,549812 USD / 28 llamadas**. No hay nuevas llamadas en esta revisión.\n\nLa respuesta 1 sigue sin reconstrucción literal. Esa limitación histórica permanece documentada; no se encubre con mocks ni con telemetría añadida después.\n';
 fs.writeFileSync(path.join(__dirname,'telemetry-archive.md'),doc);fs.mkdirSync(path.join(__dirname,'results'),{recursive:true});fs.writeFileSync(path.join(__dirname,'results/telemetry-archive.json'),JSON.stringify({dispatches:8,accepted:7,discarded:1,preprovider_blocked:1,new_provider_calls:0,cost_usd:cost,results},null,2));
 console.log(JSON.stringify({dispatches:8,accepted_schema_semantic_scope:7,discarded_unreconstructable:1,preprovider_blocked:1,cost_usd:cost,new_calls:0}));
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
