// Offline affected-host regression. No Supabase, OAuth, users or provider calls.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const P=require('./preview.cjs'),A=require('../../assets/coach-premium-adapter.js'),I=require('../../assets/coach-intake.js'),App=require('../../assets/coach-premium-app.js');
const out=path.join(__dirname,'results'),port=4254,base='http://127.0.0.1:'+port,rows=[],screenshots=[],adapter=P.createOfflineAdapter();fs.mkdirSync(out,{recursive:true});
function check(name,value){rows.push({name,pass:!!value});assert(value,name);}
function luminance(rgb){const x=rgb.match(/[\d.]+/g).slice(0,3).map(n=>{const v=Number(n)/255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return x[0]*.2126+x[1]*.7152+x[2]*.0722;}
function contrast(a,b){const l=[luminance(a),luminance(b)].sort((x,y)=>y-x);return (l[0]+.05)/(l[1]+.05);}
const snapshot=p=>p.evaluate(()=>window.PremiumHostUI.snapshot());
async function ready(p){await p.waitForFunction(()=>window.PremiumHostUI?.snapshot().view&&!window.PremiumHostUI.snapshot().busy);}
async function reset(p,tag){await p.evaluate(tag=>window.PremiumHostPreview.setCase(tag),tag);await ready(p);}
async function nav(p,to){await p.evaluate(to=>window.PremiumHostUI.navigate(to),to);}
async function geometry(p,label){const v=await p.evaluate(()=>{const r=document.querySelector('.premium-app'),m=r.querySelector('main'),b=r.getBoundingClientRect(),styles=getComputedStyle(r);return {width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,viewport:innerWidth,viewportHeight:innerHeight,bottom:b.bottom,overflow:getComputedStyle(m).overflowY,bg:styles.backgroundColor,ink:styles.color,short:[...r.querySelectorAll('button:not(:disabled)')].filter(x=>x.getClientRects().length&&x.getBoundingClientRect().height<43.5).map(x=>x.textContent),vertical:[...r.querySelectorAll('*')].filter(x=>x.tagName!=='TEXTAREA'&&x.clientHeight>0&&x.scrollHeight>x.clientHeight+2&&['auto','scroll'].includes(getComputedStyle(x).overflowY)).length};});check(label+' no horizontal scroll',v.width<=v.viewport+1);check(label+' viewport fits',v.bottom<=v.viewportHeight+1&&v.height<=v.viewportHeight+1);check(label+' targets 44px',v.short.length===0);check(label+' one vertical scroller',v.vertical<=1);check(label+' distinct foreground/background',v.bg!==v.ink);return v;}
async function adapterChecks(){
 const calls=[],v=P.fixture();const tables={coach_mesocycles:[{...v.mesocycle,user_id:P.ids.user,tracking_week:2,current_revision_id:P.ids.revision}],coach_mesocycle_weeks:[v.week],routine_revisions:[{id:P.ids.revision,revision_no:1,snapshot:{days:v.days}}],coach_recommendations:[],context_grants:[{scope:'premium_training_history',notice_version:'premium-tracking-v1'}],coach_weekly_checkins:[]};
 const db={auth:{getSession:async()=>({data:{session:{user:{id:P.ids.user},access_token:'NOT_EXPOSED'}}})},from(table){const q={select(columns){calls.push({table,columns});return q;},eq(){return q;},is(){return q;},order(){return q;},then(resolve){return Promise.resolve({data:tables[table]||[],error:null}).then(resolve);}};return q;},rpc:async(name,args)=>{calls.push({rpc:name,args});return {data:name==='premium_my_access'?v.access:name==='premium_chat_load'?{messages:[],permission:true}:true,error:null};},functions:{invoke:async(name,{body})=>{calls.push({edge:name,body});return {data:{message:{state:'completed',answer:'Respuesta'}},error:null};}}};
 const live=A.create(db),s=await live.load();check('SDK current session same user',s.user_id===P.ids.user);check('SDK current revision scoped',s.mesocycle.revision_id===P.ids.revision);check('SDK no session/token projection',!JSON.stringify(s).includes('NOT_EXPOSED'));check('SDK no raw bundles/chat list',calls.filter(c=>c.columns).every(c=>!/(analysis_bundle|context_snapshot|context_bundle|coach_messages)/.test(c.columns)));
 await live.handle('chat_send',{revision_id:P.ids.revision,key:P.ids.week,message:'Descansos',message_id:'STRIP',conversation_id:'STRIP',retry_of:'STRIP'});const edge=calls.find(c=>c.edge);check('SDK Edge existing endpoint',edge.edge==='simple-coach-chat');check('SDK exact Edge request',Object.keys(edge.body).sort().join(',')==='key,mesocycle_id,message,revision_id');
 v.access.enabled=false;const gated=await A.create(db).load();check('SDK disabled gate no workspace',gated.mesocycle===null);const denied=A.create({...db,auth:{getSession:async()=>({data:{session:null}})}});await assert.rejects(denied.load(),/not_authenticated/);check('SDK no session rejected',true);
 const warning=A.recommendation({id:P.ids.week,kind:'MODIFY',base_revision_id:P.ids.revision,patches:[{target_id:v.days[0].exercises[0].id,field:'planned_sets',from:[{rir:0}],to:[{rir:1}]}],quality_warnings:['Preserve'],facts:[]},v.days);check('SDK warnings retained',warning.quality_warnings[0]==='Preserve');check('SDK patch exact exercise UUID',warning.changes[0].exercise_name===v.days[0].exercises[0].name);
 check('JSONB object order accepted',App.equal({a:1,b:{c:2,d:3}},{b:{d:3,c:2},a:1}));check('JSONB array order preserved',!App.equal([1,2],[2,1]));
}
async function run(){await adapterChecks();const server=P.createServer(adapter,port);await new Promise(r=>server.listen(port,'127.0.0.1',r));let browser;
 try{for(const [engine,type]of [['chromium',chromium],['webkit',webkit]]){browser=await type.launch(engine==='chromium'?{channel:'msedge'}:{});for(const width of [320,360,390,430,1280])for(const theme of ['light','dark']){const ctx=await browser.newContext({viewport:{width,height:width===1280?900:812}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await p.goto(base+'/review?case=normal');await ready(p);await reset(p,'normal');await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);const label=engine+' '+width+' '+theme;
  check(label+' labelled offline',await p.locator('.preview-header').innerText().then(t=>t.includes('simulados')));check(label+' home correct week',(await snapshot(p)).view.week.week_number===2);const colors=await geometry(p,label+' home');check(label+' body text contrast AA',contrast(colors.bg,colors.ink)>=4.5);const muted=await p.locator('.premium-app-context').evaluate(e=>getComputedStyle(e).color);check(label+' secondary text contrast AA',contrast(colors.bg,muted)>=4.5);
  await nav(p,'program');check(label+' program four exercises',await p.locator('.premium-app-exercise').count()===4);check(label+' heterogeneous rests visible',(await p.locator('main').innerText()).includes('3,5 min'));await geometry(p,label+' program');
  await nav(p,'analysis');await p.getByRole('button',{name:'Ver propuesta',exact:true}).click();check(label+' before/after',(await p.locator('main').innerText()).includes('Antes')&&(await p.locator('main').innerText()).includes('Después'));check(label+' quality warning before accept',await p.getByRole('heading',{name:'Avisos de calidad'}).count()===1);check(label+' one accept action',await p.getByRole('button',{name:'Aceptar propuesta',exact:true}).count()===1);await geometry(p,label+' proposal');
  await nav(p,'checkin');check(label+' actual weekly question',(await p.locator('main').innerText()).includes('¿Cómo te has recuperado esta semana'));await p.getByRole('button',{name:'Continuar',exact:true}).click();check(label+' unfilled validates',await p.locator('[role=alert]').innerText().then(t=>t.includes('Elige')));await p.getByRole('radio',{name:'Bien',exact:true}).check();await p.getByRole('button',{name:'Continuar',exact:true}).click();await p.getByRole('button',{name:'← Atrás',exact:true}).click();check(label+' back retains answer',await p.getByRole('radio',{name:'Bien',exact:true}).isChecked());await geometry(p,label+' checkin');
  await nav(p,'chat');await p.waitForSelector('#premium-chat-input');await p.waitForFunction(()=>!document.querySelector('#premium-chat-input').disabled);await p.locator('#premium-chat-input').fill('¿Cómo conservar los descansos?');await p.getByRole('button',{name:'Enviar',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.chat-assistant'));check(label+' chat answer plain',(await p.locator('.chat-assistant').innerText()).includes('programación'));await geometry(p,label+' chat');await p.setViewportSize({width,height:430});await p.waitForFunction(()=>document.querySelector('.premium-app').getBoundingClientRect().bottom<=innerHeight+1);await geometry(p,label+' keyboard viewport simulation');await p.setViewportSize({width,height:width===1280?900:812});await p.waitForFunction(()=>Math.abs(document.querySelector('.premium-app').getBoundingClientRect().bottom-innerHeight)<2);
  await nav(p,'home');check(label+' common navigation preserved',(await snapshot(p)).screen==='home');await p.keyboard.press('Tab');check(label+' keyboard focus',await p.evaluate(()=>document.activeElement.tagName==='BUTTON'));check(label+' focus visible',await p.evaluate(()=>parseFloat(getComputedStyle(document.activeElement).outlineWidth)>=2));
  if(engine==='chromium'&&((width===390&&theme==='light')||(width===430&&theme==='dark')||(width===1280&&theme==='light'))){await nav(p,'program');const file=path.join(out,'program-'+width+'-'+theme+'.png');await p.screenshot({path:file});screenshots.push(file);await nav(p,'home');const home=path.join(out,'home-'+width+'-'+theme+'.png');await p.screenshot({path:home});screenshots.push(home);}
  check(label+' no JS errors',errors.length===0);await ctx.close();}
  const ctx=await browser.newContext({viewport:{width:390,height:812}}),p=await ctx.newPage();await p.goto(base+'/review');await ready(p);
  for(const tag of ['basic','new']){await reset(p,tag);check(engine+' '+tag+' admission visible',await p.getByRole('button',{name:tag==='basic'?'Continuar con Premium':'Empezar seguimiento Premium',exact:true}).count()===1);await p.getByRole('button',{name:tag==='basic'?'Continuar con Premium':'Empezar seguimiento Premium',exact:true}).click();check(engine+' '+tag+' consent not inferred',(await snapshot(p)).view.access.consent===false);await p.locator('#premium-admission-allow').check();await p.getByRole('button',{name:tag==='basic'?'Continuar con Premium':'Empezar seguimiento Premium',exact:true}).click();await ready(p);await p.waitForFunction(()=>window.PremiumHostUI.snapshot().view.mesocycle!==null);check(engine+' '+tag+' same routine adoption',(await snapshot(p)).view.mesocycle.routine_id===P.ids.routine);}
  for(const tag of ['denied','expired']){await reset(p,tag);check(engine+' '+tag+' gate closed',await p.getByRole('button',{name:'Completar check-in'}).count()===0&&await p.getByRole('button',{name:'Hablar con SIMPLE Coach'}).count()===0);}
  await reset(p,'null');await nav(p,'checkin');check(engine+' no week honest',await p.locator('main').innerText().then(t=>t.includes('No hay una semana activa')));
  await reset(p,'legacy');await nav(p,'program');check(engine+' legacy scalar preserved',await p.locator('main').innerText().then(t=>t.includes('2 series')&&t.includes('RIR 2')));
  await reset(p,'long');await nav(p,'program');await geometry(p,engine+' long names');
  await reset(p,'revoked');await nav(p,'chat');await p.waitForFunction(()=>document.querySelector('#premium-chat-input')?.disabled);check(engine+' revoked chat no composer',await p.locator('#premium-chat-input').isDisabled());
  await reset(p,'reviewer');await nav(p,'proposal');check(engine+' reviewer no chat nav',await p.getByRole('button',{name:'Chat',exact:true}).count()===0);await nav(p,'analysis');await p.getByRole('button',{name:'Ver propuesta'}).click();check(engine+' reviewer has approve',await p.getByRole('button',{name:'Aprobar propuesta'}).count()===1);check(engine+' reviewer no athlete accept',await p.getByRole('button',{name:'Aceptar propuesta'}).count()===0);
  await reset(p,'missing');await nav(p,'analysis');check(engine+' missing checkin explicit',await p.locator('main').innerText().then(t=>t.includes('No hay check-in enviado')));
  await reset(p,'budget');await nav(p,'analysis');await p.getByRole('button',{name:'Solicitar análisis'}).click();await p.waitForSelector('[role=alert]');check(engine+' budget no false success',await p.locator('[role=alert]').innerText().then(t=>t.includes('agotado')));
  await reset(p,'normal');await nav(p,'chat');await p.waitForFunction(()=>!document.querySelector('#premium-chat-input')?.disabled);for(let turn=0;turn<10;turn++){await p.locator('#premium-chat-input').fill('Pregunta de entrenamiento '+turn);await p.getByRole('button',{name:'Enviar',exact:true}).click();await p.waitForFunction(n=>document.querySelectorAll('.chat-assistant').length===n,turn+1);}check(engine+' ten-turn common chat',await p.locator('.chat-assistant').count()===10);
  await reset(p,'normal');await nav(p,'analysis');await p.getByRole('button',{name:'Ver propuesta'}).click();await p.getByRole('button',{name:'Aceptar propuesta',exact:true}).click();check(engine+' acceptance explicit confirmation',await p.getByRole('button',{name:'Confirmar aceptación'}).count()===1);await p.getByRole('button',{name:'Confirmar aceptación'}).click();await ready(p);check(engine+' acceptance refresh revision',(await snapshot(p)).view.mesocycle.revision_no===2);await nav(p,'chat');await p.waitForFunction(()=>document.querySelector('.chat-context')?.textContent.includes('2'));check(engine+' chat follows accepted revision',await p.locator('.chat-context').innerText().then(t=>t.includes('2')));
  await reset(p,'intake');await nav(p,'intake');const intakeChoices={experience:'1–2 años',pause:'No',goal:I.premiumGoals.find(x=>x.id==='balanced').label,days:'2 días',activity:'No',effort:I.effort.find(x=>x.id==='learning').label,confidence:'Media',recovery:I.recovery.find(x=>x.id==='mostly').label,sleep:'7–8 horas',stress:'Media',distribution:I.distribution.find(x=>x.id==='coach').label};
  let steps=0;while(steps++<20){const current=await snapshot(p),keys=await p.evaluate(()=>[...SimpleCoachIntake.premiumSteps(PremiumHostUI.snapshot().intake),'inventory']),key=keys[current.intakeStep];if(!key)break;
   if(intakeChoices[key])await p.getByRole('radio',{name:intakeChoices[key],exact:true}).check();
   if(key==='weekdays'){await p.getByRole('checkbox',{name:'Lunes',exact:true}).check();await p.getByRole('checkbox',{name:'Jueves',exact:true}).check();}
   if(key==='minutes_by_day'){await p.getByLabel('Lunes',{exact:true}).selectOption('60');await p.getByLabel('Jueves',{exact:true}).selectOption('60');}
   if(key==='sleep')await p.getByLabel('¿El horario es estable?',{exact:true}).selectOption('yes');
   if(key==='inventory'){await p.getByRole('checkbox',{name:'Tenemos todo el equipamiento',exact:true}).check();check(engine+' all equipment catalog once',(await snapshot(p)).intake.inventory.equipment.length===I.equipment.length);}
   await p.getByRole('button',{name:'Continuar',exact:true}).click();check(engine+' intake step '+key+' advances',(await snapshot(p)).intakeStep===current.intakeStep+1);
  }
  check(engine+' intake full schema valid',await p.evaluate(()=>SimpleCoachIntake.premiumErrors(PremiumHostUI.snapshot().intake,true).length===0));await p.getByRole('button',{name:'Enviar anamnesis'}).click();await ready(p);check(engine+' intake server confirmed',(await snapshot(p)).view.mesocycle.intake_submitted_at!==null);await p.reload();await ready(p);check(engine+' intake after reload',(await snapshot(p)).view.mesocycle.intake_submitted_at!==null);
  await reset(p,'normal');await nav(p,'checkin');for(const name of ['Bien','Normal','Normal','Moderado','Similar','No','Un ejercicio']){await p.getByRole('radio',{name,exact:true}).check();if(name==='Un ejercicio')await p.getByLabel('Ejercicio de la rutina actual').selectOption(P.fixture().days[0].exercises[0].id);await p.getByRole('button',{name:'Continuar',exact:true}).click();}await p.getByRole('button',{name:'Enviar check-in'}).click();await ready(p);check(engine+' full weekly server confirmed',(await snapshot(p)).view.checkin.submitted_at!==null);check(engine+' exact exercise checkin',(await snapshot(p)).view.checkin.answers.review.exercise_id===P.fixture().days[0].exercises[0].id);
  await reset(p,'conflict');await nav(p,'checkin');await p.getByRole('radio',{name:'Bien',exact:true}).check();await p.getByRole('button',{name:'Guardar borrador'}).click();await p.waitForSelector('[role=alert]');check(engine+' conflict prevents overwrite',(await snapshot(p)).conflict===true&&(await snapshot(p)).view.checkin===null);check(engine+' conflict retains answers',(await snapshot(p)).answers.recovery==='good');
  await reset(p,'normal');await nav(p,'checkin');const second=await ctx.newPage();await second.goto(base+'/review?case=normal');await ready(second);await nav(second,'checkin');await second.getByRole('radio',{name:'Bien',exact:true}).check();await p.waitForFunction(()=>PremiumHostUI.snapshot().conflict);check(engine+' two tabs stop stale draft',(await snapshot(p)).conflict);await second.close();
  await reset(p,'stale');const waiting=p.evaluate(()=>PremiumHostUI.load());await nav(p,'program');await waiting;check(engine+' late state retains current navigation',(await snapshot(p)).screen==='program');
  await reset(p,'xss');await nav(p,'program');check(engine+' exercise names plaintext',await p.locator('.premium-app-exercise img').count()===0&&await p.evaluate(()=>!window.hostXss));
  await reset(p,'normal');await nav(p,'chat');await p.waitForFunction(()=>!document.querySelector('#premium-chat-input')?.disabled);const countBefore=adapter.snapshot().chatCalls;await p.locator('#premium-chat-input').fill('Comprobar descansos tras doble pulsación');await p.evaluate(()=>{const button=document.querySelector('.chat-send');button.click();button.click();});await p.waitForSelector('.chat-assistant');check(engine+' double click one request',adapter.snapshot().chatCalls===countBefore+1);
  await p.evaluate(()=>PremiumHostPreview.setCase('error'));await p.waitForSelector('[role=alert]');check(engine+' load error no fake data',(await snapshot(p)).view===null);check(engine+' load error retry visible',await p.getByRole('button',{name:'Actualizar estado',exact:true}).count()===1);
  await ctx.close();await browser.close();browser=null;
 }
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
 const result={passed:rows.filter(r=>r.pass).length,total:rows.length,rows,screenshots,scope:'Offline only. Keyboard height is simulated; not physical iPhone. No model/database calls.'};fs.writeFileSync(path.join(out,'ui.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,total:result.total,screenshots},null,2));
}
run().catch(e=>{fs.writeFileSync(path.join(out,'ui-failure.json'),JSON.stringify({rows,error:e.message},null,2));console.error(e.stack);process.exitCode=1;});
