// Local browser behavior and layout. Every backend response is explicitly synthetic.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,'results');fs.mkdirSync(out,{recursive:true});
const rows=[];function check(name,value,detail=''){rows.push({name,pass:!!value,detail});assert(value,name+(detail?': '+detail:''));}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 for(const engine of ['chromium','webkit']){
 const browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})}),context=await browser.newContext({viewport:{width:390,height:844}}),p=await context.newPage();p.setDefaultTimeout(12000);const errors=[],remote=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4196/'))remote.push(r.url());});
 const snapshot=async name=>{await p.evaluate(()=>{$('coachDialog').scrollTop=0;});await p.screenshot({path:path.join(out,engine+'-'+name+'.png')});};
 const start=async()=>{await p.goto('http://127.0.0.1:4196/demo');await p.waitForFunction(()=>window.previewReady);await p.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).click();await p.locator('#coachBegin').click();};
 const layout=async name=>{
  for(const width of [320,360,390,430,1280])for(const theme of ['light','dark']){
   await p.setViewportSize({width,height:900});await p.evaluate(t=>simpleTheme.set(t),theme);
   // Check settled colors after the existing SIMPLE theme transitions, not an intermediate frame.
   await p.locator('#coachDialog').evaluate(async d=>{await Promise.all(d.getAnimations({subtree:true}).filter(a=>a.effect.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));});
   const result=await p.locator('#coachDialog').evaluate(d=>{const lum=c=>{const v=c.match(/[\d.]+/g).slice(0,3).map(Number).map(n=>n/255).map(n=>n<=.04045?n/12.92:((n+.055)/1.055)**2.4);return v[0]*.2126+v[1]*.7152+v[2]*.0722;};const contrast=e=>{const s=getComputedStyle(e),a=lum(s.color),b=lum(s.backgroundColor);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);};return {overflow:d.scrollWidth>d.clientWidth+1,buttons:[...d.querySelectorAll('button')].filter(x=>x.getClientRects().length).every(x=>x.getBoundingClientRect().height>=43.9),inputs:[...d.querySelectorAll('textarea,select,input:not([type=checkbox])')].filter(x=>x.getClientRects().length).every(x=>parseFloat(getComputedStyle(x).fontSize)>=16),contrast:[...d.querySelectorAll('button')].filter(x=>x.getClientRects().length&&!x.disabled).every(x=>contrast(x)>=4.5),nativePaint:[...d.querySelectorAll('button,textarea')].every(x=>getComputedStyle(x).appearance==='none')};});
   check(engine+' '+name+' '+width+' '+theme+' fit/touch/contrast',!result.overflow&&result.buttons&&result.inputs&&result.contrast&&result.nativePaint,JSON.stringify(result));
   if(width===390&&(name==='consent'||name==='intake'||name==='pending'||name==='approved'||name==='reviewer'||name==='feedback'||name==='generating')){await snapshot(name+'-'+theme);if(name==='consent'){await p.locator('#coachGrantTraining').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,engine+'-consent-action-'+theme+'.png')});}}
  }
  await p.setViewportSize({width:390,height:844});
 };
 try{
  // Historical screenshot is useful evidence, not a re-run of legacy tests.
  if(fs.existsSync(path.join(out,'coach-before.js'))){await p.goto('http://127.0.0.1:4196/before');await p.waitForFunction(()=>window.previewReady);await p.getByRole('button',{name:'Entrenar con SIMPLE Coach',exact:true}).click();await p.locator('#coachBegin').click();await p.locator('#coachGoal').waitFor();for(const theme of ['light','dark']){await p.evaluate(t=>simpleTheme.set(t),theme);await snapshot('before-intake-'+theme);}await p.evaluate(()=>sessionStorage.clear());}
  await start();await p.locator('#coachGrantTraining').waitFor();
  check(engine+' information and sole v2 consent precede questions',await p.locator('#coachForm').count()===0&&await p.locator('#coachGrantHealth').count()===0&&(await p.locator('#coachDialog').innerText()).includes('pilot-supervised-v2'));
  await layout('consent');await p.getByRole('button',{name:'Continuar',exact:true}).click();check(engine+' A required without fake B',await p.locator('#coachError').innerText()==='Acepta el permiso de entrenamiento para continuar.');
  await p.locator('#coachGrantTraining').check();await p.waitForFunction(()=>!simpleCoach.busy);check(engine+' consent server call only A',await p.evaluate(()=>coachDemo.rpcCalls.filter(c=>c.name==='set_my_coach_context_permission').every(c=>c.args.p_scope==='training_intake')));
  await p.getByRole('button',{name:'Continuar',exact:true}).click();await p.locator('#coachGoal').selectOption('Ganar masa muscular');
  await p.locator('#coachPreferredDetails summary').click();await p.locator('#coachPreferred input[value="Peso muerto rumano con mancuernas"]').check();
  await p.locator('#coachAvoided').locator('..').locator('summary').click();await p.locator('#coachAvoided input[value="Press de pecho en máquina"]').check();
  check(engine+' no health read and no free intake text',await p.evaluate(()=>!coachDemo.reads.includes('intake_health')&&!$('coachForm').querySelector('textarea,input[type=text]')));
  await layout('intake');
  await p.locator('#coachDays').focus();await p.keyboard.press('Tab');check(engine+' logical keyboard focus',await p.locator('#coachMinutes').evaluate(x=>x===document.activeElement));
  check(engine+' visible focus',await p.locator('#coachMinutes').evaluate(x=>getComputedStyle(x).outlineStyle!=='none'));
  await p.locator('#coachDraft').click();await p.getByText('Borrador guardado.',{exact:true}).waitFor();
  check(engine+' draft never includes health payload',await p.evaluate(()=>{const c=coachDemo.rpcCalls.filter(c=>c.name==='save_my_training_intake').at(-1);return !Object.hasOwn(c.args,'p_health')&&c.args.p_training.preferences===''&&mock.tables.intake_health.length===0;}));
  await p.locator('#coachDeleteDraft').click();check(engine+' deletion requires explicit confirmation',await p.locator('#coachConfirmDelete').isVisible()&&await p.evaluate(()=>mock.tables.training_intakes.length===1));await p.locator('#coachCancelDelete').click();check(engine+' deletion cancel keeps draft',await p.evaluate(()=>mock.tables.training_intakes.length===1));
  await p.locator('#coachDeleteDraft').click();await p.locator('#coachConfirmDelete').click();await p.getByText('Borrador borrado.',{exact:true}).waitFor();check(engine+' own unsubmitted draft deletion clears UI',await p.evaluate(()=>mock.tables.training_intakes.length===0)&&await p.locator('#coachGoal').inputValue()==='');
  await p.locator('#coachGoal').selectOption('Fuerza general');
  await p.evaluate(()=>coachDemo.errors.save_my_training_intake='coach_intake_conflict');await p.locator('#coachDraft').click();await p.getByText('El formulario cambió en otra pestaña. Vuelve a abrirlo para cargar la versión actual.',{exact:true}).waitFor();check(engine+' errors preserve choice and unlock',await p.locator('#coachGoal').inputValue()==='Fuerza general'&&await p.locator('#coachDraft').isEnabled());await p.evaluate(()=>delete coachDemo.errors.save_my_training_intake);
  await p.getByRole('button',{name:'Revisar antes de enviar',exact:true}).click();await layout('review');check(engine+' review sends nothing before confirmation',await p.evaluate(()=>coachDemo.invokeCalls.length===0)&&await p.getByText('No se enviará información de salud.',{exact:false}).isVisible());
  await p.locator('#coachReviewBack').click();check(engine+' back preserves values',await p.locator('#coachGoal').inputValue()==='Fuerza general');await p.getByRole('button',{name:'Revisar antes de enviar',exact:true}).click();
  await p.evaluate(()=>coachDemo.delays.invoke=1000);await p.locator('#coachConfirmSend').evaluate(x=>{x.click();x.click();});await p.getByText('Estamos preparando tu rutina…',{exact:true}).waitFor();check(engine+' duplicate action disabled during generation',await p.locator('#coachConfirmSend').isDisabled());await p.getByRole('heading',{name:'Tu rutina está siendo revisada',exact:true}).waitFor();
  check(engine+' exactly one invoke with only identifier/key',await p.evaluate(()=>coachDemo.invokeCalls.length===1&&Object.keys(coachDemo.invokeCalls[0].body).sort().join(',')==='intake_id,key'));check(engine+' cannot accept pending review',await p.locator('#coachAccept').count()===0);await layout('pending');
  await start();await p.getByRole('heading',{name:'Tu rutina está siendo revisada',exact:true}).waitFor();check(engine+' reload preserves backend state without another invocation',await p.evaluate(()=>coachDemo.invokeCalls.length===0&&mock.tables.coach_operations.length===1));
  await p.evaluate(()=>{pilotDemoReviewer=true;return openCoachReviewer();});await p.locator('#coachQueue').waitFor();check(engine+' reviewer has no health and full prescription',!(await p.locator('#coachQueue').innerText()).includes('SHOULD_NEVER_RENDER')&&await p.locator('#coachQueue h4').count()===3&&(await p.locator('#coachQueue').innerText()).includes('90 s de descanso'));check(engine+' expiry quiet above 7 days',await p.locator('.coach-expiry').count()===0);
  await p.evaluate(()=>{coachDemo.expires=new Date(Date.now()+6*86400000).toISOString();return openCoachReviewer();});check(engine+' expiry warning in 7 day window',await p.locator('.coach-expiry').innerText().then(x=>/^Tu permiso de reviewer caduca el \d{2}\/\d{2}\/\d{4}\.$/.test(x)));await layout('reviewer');
  await p.getByRole('button',{name:'Rechazar propuesta',exact:true}).click();check(engine+' reject empty reason makes no mutation',await p.evaluate(()=>!coachDemo.rpcCalls.some(x=>x.name==='review_coach_proposal')));
  await p.locator('#coachQueue textarea').fill('Distribución sintética pendiente de revisión.');await p.getByRole('button',{name:'Rechazar propuesta',exact:true}).click();await p.getByRole('heading',{name:'Rechazada',exact:true}).waitFor();
  await p.evaluate(()=>{pilotDemoReviewer=false;return openSimpleCoach();});await p.locator('#coachBegin').click();await p.getByRole('heading',{name:'Propuesta no disponible',exact:true}).waitFor();check(engine+' rejection cannot accept and gives reason',await p.locator('#coachAccept').count()===0&&(await p.locator('#coachProposal').innerText()).includes('Distribución sintética'));
  await p.evaluate(()=>{const o=mock.tables.coach_operations[0];o.state='pending_review';pilotDemoReviewer=true;return openCoachReviewer();});await p.locator('#coachQueue textarea').fill('Revisados días, material, volumen, series, reps, RIR y descansos.');await p.getByRole('button',{name:'Aprobar propuesta',exact:true}).click();await p.getByRole('heading',{name:'Aprobada',exact:true}).waitFor();
  await p.evaluate(()=>{pilotDemoReviewer=false;return openSimpleCoach();});await p.locator('#coachBegin').click();await p.getByRole('heading',{name:'Tu rutina está lista',exact:true}).waitFor();check(engine+' proposal review does not create real structure',await p.evaluate(()=>mock.tables.routines.length===0));await layout('approved');
  await p.locator('#coachAccept').evaluate(x=>{x.click();x.click();});await p.getByRole('heading',{name:'Rutina creada',exact:true}).waitFor();check(engine+' acceptance one UI call one structure',await p.evaluate(()=>coachDemo.rpcCalls.filter(c=>c.name==='accept_basic_plan').length===1&&mock.tables.routines.length===1));
  await p.evaluate(()=>openSimpleCoach());check(engine+' no feedback before workout',await p.locator('#coachFeedback').count()===0);
  await p.evaluate(()=>{mock.tables.workouts.push({id:crypto.randomUUID(),user_id:demoUser,data:{routine_id:mock.tables.routines[0].id}});return openSimpleCoach();});await p.locator('#coachFeedback').click();await p.locator('#coachRating').waitFor();await layout('feedback');
  await p.setViewportSize({width:320,height:400});await p.locator('#coachFeedbackComment').fill('Una valoración sintética larga para verificar que el comentario se conserva al ajustar el área visible como cuando aparece el teclado. '.repeat(4));await p.locator('#coachFeedbackComment').focus();check(engine+' reduced viewport keyboard approximation usable',await p.locator('#coachDialog').evaluate(d=>d.scrollWidth<=d.clientWidth+1)&&await p.locator('#coachFeedbackComment').evaluate(x=>x===document.activeElement));await snapshot('feedback-keyboard-simulation');await p.setViewportSize({width:390,height:844});
  await p.locator('#coachRating').selectOption('4');await p.getByRole('button',{name:'Guardar valoración',exact:true}).click();await p.getByText('Valoración guardada.',{exact:true}).waitFor();await p.evaluate(()=>openSimpleCoach());check(engine+' existing feedback invites update only on demand',await p.locator('#coachFeedback').innerText()==='Ver o actualizar valoración');await p.locator('#coachFeedback').click();await p.locator('#coachRating').selectOption('5');await p.getByRole('button',{name:'Guardar valoración',exact:true}).click();await p.getByText('Valoración guardada.',{exact:true}).waitFor();check(engine+' feedback update remains single row',await p.evaluate(()=>mock.tables.coach_pilot_feedback.length===1&&mock.tables.coach_pilot_feedback[0].rating===5));
  // Old text is never prefilled or silently reused, and health is never read.
  await p.evaluate(()=>{simpleCoach.accepted=false;mock.tables.coach_operations=[];mock.tables.training_intakes=[{id:crypto.randomUUID(),revision:1,row_version:1,state:'draft',training:{goal:'PRIVATE_OLD_TEXT',experience:'beginner',days:3,minutes:45,equipment:['Gimnasio'],preferred:'',avoided:'',preferences:'PRIVATE_OLD_TEXT'}}];return coachLoadIntake(true);});await p.getByRole('button',{name:'Continuar',exact:true}).click();check(engine+' old arbitrary draft text not reused',await p.locator('#coachGoal').inputValue()===''&&!(await p.locator('#coachDialog').innerText()).includes('PRIVATE_OLD_TEXT'));
  // Close while save response is pending: there must be no subsequent provider dispatch.
  await p.locator('#coachGoal').selectOption('Fuerza general');await p.getByRole('button',{name:'Revisar antes de enviar',exact:true}).click();await p.evaluate(()=>{coachDemo.delays.save_my_training_intake=600;coachDemo.invokeCalls=[];});await p.locator('#coachConfirmSend').click();await p.getByRole('button',{name:'Cerrar SIMPLE Coach',exact:true}).click();await wait(750);check(engine+' close during save prevents provider invocation',await p.evaluate(()=>coachDemo.invokeCalls.length===0&&!$('coachDialog').open));
  await p.evaluate(()=>{delete coachDemo.delays.save_my_training_intake;coachDemo.delays.get_my_coach_access=500;openSimpleCoach();});await p.getByRole('button',{name:'Cerrar SIMPLE Coach',exact:true}).click();await wait(650);check(engine+' late access response cannot reopen modal',await p.evaluate(()=>!$('coachDialog').open));
  await p.evaluate(()=>{delete coachDemo.delays.get_my_coach_access;const i=mock.tables.training_intakes.at(-1);mock.tables.coach_operations=[{id:crypto.randomUUID(),intake_id:i.id,user_id:demoUser,state:'reserved',created_at:new Date().toISOString(),expires_at:new Date(Date.now()+300000).toISOString()}];demoPersist();void coachLoadIntake();});await p.getByRole('heading',{name:'Estamos preparando tu rutina',exact:true}).waitFor();await layout('generating');check(engine+' resumed generation has no accept or send',await p.locator('#coachAccept').count()===0&&await p.locator('#coachConfirmSend').count()===0);await p.getByRole('button',{name:'Cerrar SIMPLE Coach',exact:true}).click();
  await start();await p.getByRole('heading',{name:'Estamos preparando tu rutina',exact:true}).waitFor();check(engine+' reserved refresh polls same operation without invoke',await p.evaluate(()=>coachDemo.invokeCalls.length===0&&mock.tables.coach_operations.length===1));await p.getByRole('button',{name:'Cerrar SIMPLE Coach',exact:true}).click();
  await p.evaluate(()=>{mock.tables.coach_operations[0].state='rejected';mock.tables.coach_operations[0].retry_authorized_at=new Date().toISOString();return coachLoadIntake();});await p.locator('#coachRetry').click();check(engine+' authorized retry still requires consent/form review',await p.locator('#coachGrantTraining').isVisible()&&await p.evaluate(()=>coachDemo.invokeCalls.length===0));
  await p.evaluate(()=>{for(const g of mock.tables.context_grants)g.notice_version='pilot-supervised-v1';return coachLoadIntake(true);});check(engine+' old v1 consent is not converted',!await p.locator('#coachGrantTraining').isChecked());await p.locator('#coachGrantTraining').check();await p.waitForFunction(()=>!simpleCoach.busy);
  await p.getByRole('button',{name:'Continuar',exact:true}).click();await p.locator('#coachGoal').selectOption('Fuerza general');await p.getByRole('button',{name:'Revisar antes de enviar',exact:true}).click();await p.evaluate(()=>{mock.tables.coach_operations=[];coachDemo.delays.invoke=500;});await p.locator('#coachConfirmSend').click();await p.waitForFunction(()=>coachDemo.invokeCalls.length===1);await p.getByRole('button',{name:'Cerrar SIMPLE Coach',exact:true}).click();await wait(650);check(engine+' late provider callback cannot reopen closed screen',await p.evaluate(()=>!$('coachDialog').open&&mock.tables.coach_operations.length===1));
  await p.evaluate(()=>{mock.tables.coach_operations[0].state='pending_review';return coachLoadIntake();});await p.getByRole('heading',{name:'Tu rutina está siendo revisada',exact:true}).waitFor();check(engine+' return after closing generation reuses operation',await p.evaluate(()=>coachDemo.invokeCalls.length===1));
  await p.evaluate(()=>{pilotDemoReviewer=false;return openCoachReviewer();});await p.getByText('No tienes permiso para revisar propuestas.',{exact:true}).waitFor();check(engine+' unauthorized reviewer reveals no queue',await p.locator('#coachQueue').count()===0);
  await p.evaluate(()=>{delete coachDemo.delays.get_my_coach_access;mock.tables.coach_operations=[];return openSimpleCoach();});await p.locator('#coachBegin').click();await p.getByRole('button',{name:'Continuar',exact:true}).click();await p.locator('#coachGoal').selectOption('Fuerza general');await p.getByRole('button',{name:'Revisar antes de enviar',exact:true}).click();await p.evaluate(()=>{coachDemo.delays.save_my_training_intake=500;coachDemo.invokeCalls=[];});await p.locator('#coachConfirmSend').click();await p.evaluate(()=>{for(const cb of coachDemo.authCallbacks)cb('SIGNED_OUT');user=null;});await wait(650);check(engine+' logout suppresses pending callback and clears modal',await p.evaluate(()=>coachDemo.invokeCalls.length===0&&!$('coachDialog').open&&$('coachDialog').children.length===0));
  check(engine+' no unexpected runtime errors',errors.length===0,errors.join(';'));check(engine+' no remote API or provider traffic',remote.length===0,remote.join(';'));
 }catch(e){await p.screenshot({path:path.join(out,engine+'-failure.png')});fs.writeFileSync(path.join(out,engine+'-failure.txt'),await p.locator('body').innerText());throw e;}finally{await browser.close();fs.writeFileSync(path.join(out,'ui.json'),JSON.stringify({kind:'synthetic-browser',checks:rows.length,passed:rows.filter(x=>x.pass).length,rows},null,2));}
 }
 console.log('Coach v2 UI: '+rows.length+'/'+rows.length+' checks, Chromium + WebKit, mocked responses only.');
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
