begin;
create temporary table stage_checks(name text primary key,pass boolean);
do $$
declare t uuid:='6b47ae02-6574-46db-acdb-f00925efdd74';c uuid:='c7bbe50b-d349-4f7e-8fdc-476f17c22674';other uuid:='c14a2a6d-9853-431d-856c-4d742002187e';tb uuid:='0b6fb9c1-3a62-4fbb-93d9-b3993a8fffb8';rid uuid:=gen_random_uuid();d1 uuid:=gen_random_uuid();d2 uuid:=gen_random_uuid();eid uuid:=gen_random_uuid();wid uuid:=gen_random_uuid();req uuid:=gen_random_uuid();stage jsonb;again jsonb;n bigint;done bigint;oldhash text;h text;baseline text;noop boolean;
begin
 select md5(pg_get_functiondef('public.get_client_routine_cycle_progress(uuid,uuid)'::regprocedure)) into oldhash;
 insert into public.routines(id,owner_id,name)values(rid,t,'Synthetic statistical stages');
 insert into public.routine_days(id,routine_id,name,day_order)values(d1,rid,'A',0),(d2,rid,'B',1);
 insert into public.routine_exercises(id,day_id,name,sets,target,rir,rest_seconds,exercise_order,notes)values(eid,d1,'Synthetic exercise',2,'8-12','2',120,0,'preserved');
 insert into public.routine_assignments(trainer_id,client_id,trainer_routine_id)values(t,c,rid),(t,other,rid);
 insert into public.workouts(id,user_id,variant,day,workout_date,created_at,data)values(wid,c,'synthetic','A',current_date-2,clock_timestamp()-interval '2 days',jsonb_build_object('routine_id',rid,'routine_day_id',d1,'exercises',jsonb_build_array(jsonb_build_object('exercise_id',eid,'sets',jsonb_build_array(jsonb_build_object('kg',20,'reps',10,'rir',2)),'notes','preserved'))));
 select md5(string_agg(to_jsonb(w)::text,'' order by w.id)) into baseline from public.workouts w where user_id=c and data->>'routine_id'=rid::text;
 perform set_config('request.jwt.claim.sub',t::text,true);
 stage:=public.get_client_routine_statistics_stage(c,rid);
 insert into stage_checks values('no previous stage',stage-'training_reset_id'=jsonb_build_object('id',null,'started_at',null));
 select total_days,completed_days into n,done from public.get_client_routine_stage_cycle_progress(c,rid);
 insert into stage_checks values('no stage original cycle',n=2 and done=1);
 stage:=public.reset_client_routine_statistics(c,rid,null,req);
 insert into stage_checks values('trainer reset returns server timestamp',stage->>'id' is not null and (stage->>'started_at')::timestamptz<=clock_timestamp());
 again:=public.reset_client_routine_statistics(c,rid,null,req);
 insert into stage_checks values('same request idempotent',again=stage);
 select count(*) into n from public.client_routine_statistics_stages where client_id=c and routine_id=rid;
 insert into stage_checks values('one stage',n=1);
 begin perform public.reset_client_routine_statistics(c,rid,null,gen_random_uuid());raise exception 'test expected stale';exception when serialization_failure then insert into stage_checks values('stale second tab rejected',true);end;
 select total_days,completed_days into n,done from public.get_client_routine_stage_cycle_progress(c,rid);
 insert into stage_checks values('cycle zero after reset',n=2 and done=0);
 select md5(string_agg(to_jsonb(w)::text,'' order by w.id)) into h from public.workouts w where user_id=c and data->>'routine_id'=rid::text;
 insert into stage_checks values('historical workout exact',h=baseline);
 insert into stage_checks values('exercise prescription and notes exact',exists(select 1 from public.routine_exercises where id=eid and sets=2 and target='8-12' and rir='2' and rest_seconds=120 and notes='preserved'));
 insert into stage_checks values('other client no stage',public.get_client_routine_statistics_stage(other,rid)-'training_reset_id'=jsonb_build_object('id',null,'started_at',null));
 perform set_config('request.jwt.claim.sub',c::text,true);
 insert into stage_checks values('athlete sees same stage',public.get_client_routine_statistics_stage(c,rid)-'training_reset_id'=stage);
 begin perform public.reset_client_routine_statistics(c,rid,(stage->>'id')::uuid,gen_random_uuid());raise exception 'test expected athlete denial';exception when insufficient_privilege then insert into stage_checks values('athlete cannot reset',true);end;
 perform set_config('request.jwt.claim.sub',other::text,true);
 begin perform public.get_client_routine_statistics_stage(c,rid);raise exception 'test expected other denial';exception when insufficient_privilege then insert into stage_checks values('other client cannot read',true);end;
 perform set_config('request.jwt.claim.sub',tb::text,true);
 begin perform public.reset_client_routine_statistics(c,rid,(stage->>'id')::uuid,gen_random_uuid());raise exception 'test expected trainer denial';exception when insufficient_privilege then insert into stage_checks values('unassigned trainer cannot reset',true);end;
 begin perform public.get_client_routine_statistics_stage(c,rid);raise exception 'test expected trainer denial';exception when insufficient_privilege then insert into stage_checks values('unassigned trainer cannot read',true);end;
 perform set_config('request.jwt.claim.sub','',true);
 begin perform public.get_client_routine_statistics_stage(c,rid);raise exception 'test expected anon denial';exception when insufficient_privilege then insert into stage_checks values('anon denied',true);end;
 perform set_config('request.jwt.claim.sub',c::text,true);
 insert into public.workouts(user_id,variant,day,workout_date,created_at,data)values(c,'synthetic','B',current_date,clock_timestamp(),jsonb_build_object('routine_id',rid,'routine_day_id',d2,'exercises','[]'::jsonb));
 select total_days,completed_days into n,done from public.get_client_routine_stage_cycle_progress(c,rid);
 insert into stage_checks values('new workout counts',n=2 and done=1);
 insert into public.workouts(user_id,variant,day,workout_date,created_at,data)values(c,'synthetic','A',current_date,clock_timestamp(),jsonb_build_object('routine_id',rid,'routine_day_id',d1,'exercises','[]'::jsonb));
 select total_days,completed_days into n,done from public.get_client_routine_stage_cycle_progress(c,rid);
 insert into stage_checks values('new stage full cycle',n=2 and done=2);
 insert into stage_checks values('original cycle function hash exact',oldhash=md5(pg_get_functiondef('public.get_client_routine_cycle_progress(uuid,uuid)'::regprocedure)));
 insert into stage_checks values('no direct table privileges',not has_table_privilege('authenticated','public.client_routine_statistics_stages','select') and not has_table_privilege('authenticated','public.client_routine_statistics_stages','insert'));
 insert into stage_checks values('table RLS enabled',(select relrowsecurity from pg_class where oid='public.client_routine_statistics_stages'::regclass));
 insert into stage_checks values('anon cannot execute',not has_function_privilege('anon','public.reset_client_routine_statistics(uuid,uuid,uuid,uuid)','execute'));
 insert into stage_checks values('compatible deletion foreign keys',(select count(*)=3 and bool_and(case conname when 'client_routine_statistics_stages_created_by_fkey' then confdeltype='n' else confdeltype='c' end) from pg_constraint where conrelid='public.client_routine_statistics_stages'::regclass and contype='f'));
 if exists(select 1 from stage_checks where not coalesce(pass,false))then raise exception 'statistics test failed';end if;
end $$;
select jsonb_agg(to_jsonb(t) order by name) checks from stage_checks t;
rollback;
