// Public assets can be checked with SIMPLE_PUBLIC_URL; all data stays in this browser's mock SDK.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),cp=require('child_process');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.join(__dirname,'results'),results=[],shots=[],base=process.env.SIMPLE_PUBLIC_URL||process.env.SIMPLE_PREVIEW_URL||'http://127.0.0.1:4183/';fs.mkdirSync(out,{recursive:true});
const publicMode=!!process.env.SIMPLE_PUBLIC_URL,prefix=publicMode?'public-':'';
const baselineCss=cp.execFileSync('git',['show','a5d97e8:assets/interior.css'],{encoding:'utf8',maxBuffer:2e6});
const write=()=>fs.writeFileSync(path.join(out,prefix+'browser.json'),JSON.stringify({kind:publicMode?'Public product assets with isolated mock SDK; no real authentication or remote writes':'Local browser fixtures; no remote writes',passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass),results,shots},null,2));
async function isolated(page){if(!publicMode)return;await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='cdn.jsdelivr.net'&&u.pathname.includes('supabase-js'))return r.fulfill({body:fs.readFileSync('tests/interior/mock-sdk.js'),contentType:'application/javascript'});if(u.origin===new URL(base).origin&&r.request().method()==='GET')return r.continue();return r.abort()});}
async function go(p,role='client'){await p.goto(base+'?role='+role+'&state=history');if(publicMode)await p.addScriptTag({content:fs.readFileSync('tests/interior/preview-seed.js','utf8')});await p.waitForFunction(()=>window.previewReady);}
async function shot(p,name){const f=prefix+name+'.png';await p.screenshot({path:path.join(out,f)});shots.push(f);}
async function contrast(locator){const ratio=await locator.evaluate(e=>{const rgb=s=>s.match(/[\d.]+/g).slice(0,3).map(Number),lum=a=>a.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);let p=e,bg;while(p){bg=getComputedStyle(p).backgroundColor;if(!bg.includes('rgba')&&!bg.includes('transparent'))break;p=p.parentElement;}const a=lum(rgb(getComputedStyle(e).color)),b=lum(rgb(bg));return (Math.max(a,b)+.05)/(Math.min(a,b)+.05)});assert(ratio>=4.5,'Contrast '+ratio);}
(async()=>{for(const engine of ['chromium','webkit']){
 const browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});try{for(const width of (process.env.COMPACT_WIDTHS||'320,360,390,430,1280').split(',').map(Number)){
 const test=async(name,fn)=>{try{await fn();results.push({engine,width,name,pass:true})}catch(e){results.push({engine,width,name,pass:false,error:e.message});console.error(engine,width,name,e.message)}write();};
 for(const saved of [null,'system','light','dark','invalid'])await test('First paint and persistence from '+String(saved),async()=>{
  // A transparent HTML canvas uses BODY's background; WebKit may report that during its first style update.
  const context=await browser.newContext({viewport:{width,height:900},colorScheme:'dark',reducedMotion:'reduce'}),p=await context.newPage();try{await isolated(p);await p.addInitScript(saved=>{if(!sessionStorage.getItem('compact-seeded')){if(saved!==null)localStorage.setItem('simple_theme_v1',saved);sessionStorage.setItem('compact-seeded','1')}window.paintThemes=[];let frames=0;function paint(){if(document.body){const rootBg=getComputedStyle(document.documentElement).backgroundColor;paintThemes.push({choice:document.documentElement.dataset.theme,bg:rootBg==='rgba(0, 0, 0, 0)'?getComputedStyle(document.body).backgroundColor:rootBg});}if(++frames<30)requestAnimationFrame(paint)}requestAnimationFrame(paint)},saved);
   await go(p);await p.waitForFunction(()=>paintThemes.length>0);const expected=saved==='dark'?'dark':'light',frames=await p.evaluate(()=>paintThemes);assert(frames.every(f=>f.choice===expected&&f.bg===(expected==='dark'?'rgb(32, 36, 35)':'rgb(247, 245, 241)')));assert.equal(await p.evaluate(()=>simpleTheme.choice),expected);if(saved==='system')assert.equal(await p.evaluate(()=>localStorage.getItem('simple_theme_v1')),'light');
   await p.locator('#app .settings-trigger').click();assert.deepEqual(await p.locator('#settingsDialog input').evaluateAll(es=>es.map(e=>e.value)),['light','dark']);assert.equal(await p.locator('#settingsDialog input:checked').inputValue(),expected);
   await p.locator('input[value=light]').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>simpleTheme.choice),'dark');await p.keyboard.press('ArrowLeft');assert.equal(await p.evaluate(()=>simpleTheme.choice),'light');assert.equal(await p.locator('input[value=light]').evaluate(e=>getComputedStyle(e.parentElement).outlineStyle),'solid');
   for(const tone of ['dark','light']){await p.locator('#settingsDialog label').filter({hasText:tone==='dark'?'Oscuro':'Claro'}).click();await p.keyboard.press('Escape');await p.reload();if(publicMode)await p.addScriptTag({content:fs.readFileSync('tests/interior/preview-seed.js','utf8')});await p.waitForFunction(()=>window.previewReady);assert.equal(await p.evaluate(()=>simpleTheme.choice),tone);await p.locator('#app .settings-trigger').click();}
  }finally{await context.close()}
 });
 for(const role of ['client','trainer']){
  const context=await browser.newContext({viewport:{width,height:900},colorScheme:'dark',reducedMotion:'reduce'}),p=await context.newPage(),errors=[];p.setDefaultTimeout(6000);p.on('pageerror',e=>errors.push(e.message));await isolated(p);await go(p,role);
  await p.evaluate(()=>{for(const row of mock.tables.workouts){row.user_id=user.id;row.data.exercises[0].sets=[{kg:80,reps:8,rir:2},{kg:0,reps:0,rir:0},{kg:null,reps:'',rir:null},...Array.from({length:5},(_,i)=>({kg:82.5+i,reps:9+i,rir:1}))];row.data.exercises[0].notes='Nota larga intacta. '.repeat(200)}window.fixtureBefore=JSON.stringify(mock.tables);});
  if(role==='client'){await p.locator('#shared .routine .primary').click();await p.locator('.interior-session-list button').first().click();}else{await p.locator('#tMine').click();await p.locator('[data-open-routine]').first().click();await p.locator('.routine-day-train').first().click();}
  await p.locator('.previous-set').first().waitFor();
  for(const tone of ['light','dark'])await test(role+' '+tone+' compact complete sets, notes, keyboard and unchanged workout',async()=>{
   const snapshot=await p.evaluate(()=>{window.keptActive=activeWorkout;return JSON.stringify({activeWorkout,history:window.workoutHistory})});await p.locator('#trainModal .settings-trigger').click();await p.locator('#settingsDialog label').filter({hasText:tone==='dark'?'Oscuro':'Claro'}).click();assert.equal(await p.locator('#settingsRole').innerText(),role==='trainer'?'Entrenador':'Atleta');assert.equal(await p.locator('#settingsDialog label').first().evaluate(e=>e.getBoundingClientRect().height)>=44,true);if(width===390)await shot(p,engine+'-'+width+'-'+role+'-settings-'+tone);await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>JSON.stringify({activeWorkout,history:window.workoutHistory})),snapshot);assert(await p.evaluate(()=>keptActive===activeWorkout));
   const block=p.locator('.previous-session').first(),sets=block.locator('.previous-session-sets');assert.equal(await sets.locator('.previous-set').count(),8);assert.equal(await sets.locator('.previous-set').nth(0).innerText(),'1. 80 kg × 8 · RIR 2');assert.equal(await sets.locator('.previous-set').nth(1).innerText(),'2. 0 kg × 0 · RIR 0');assert.equal(await sets.locator('.previous-set').nth(2).innerText(),'3. — kg × — · RIR —');assert.equal(await block.locator('.previous-session-date').innerText(),'23/9/2026');
   // The revised contract requires every set to be readable without an inner scroll area.
   const geometry=await sets.evaluate(e=>{const r=e.getBoundingClientRect();return {width:e.clientWidth,scroll:e.scrollWidth,height:e.clientHeight,scrollHeight:e.scrollHeight,items:[...e.children].map(c=>{const b=c.getBoundingClientRect();return {inside:b.left>=r.left-1&&b.right<=r.right+1&&b.top>=r.top-1&&b.bottom<=r.bottom+1,top:b.top}})}});
   assert(geometry.scroll<=geometry.width+1,'Previous sets overflow horizontally');assert(geometry.scrollHeight<=geometry.height+1,'Previous sets are vertically clipped');assert(geometry.items.every(x=>x.inside),'Every set must fit inside the visible reference');assert(new Set(geometry.items.map(x=>x.top)).size>1,'Eight sets must wrap into readable rows');assert.equal(await sets.getAttribute('tabindex'),null,'Static reference should not add a keyboard stop');await contrast(sets.locator('.previous-set').first());assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
   assert.equal(await p.evaluate(()=>JSON.stringify(mock.tables)),await p.evaluate(()=>fixtureBefore));assert.equal(await p.locator('#saveWorkoutBtn').count(),1);assert.equal(await p.locator('#saveWorkoutBtn').evaluate(e=>getComputedStyle(e).position),'static');assert.equal(await p.evaluate(()=>mock.calls.filter(x=>x.write||x.rpc&&!x.rpc.startsWith('get_')).length),0);assert.deepEqual(errors,[]);
   if([390,1280].includes(width)){await shot(p,engine+'-'+width+'-'+role+'-after-'+tone);if(!publicMode){await p.route('**/assets/interior.css*',r=>r.fulfill({body:baselineCss,contentType:'text/css'}));const sheet=p.locator('link[href^="assets/interior.css"]');await sheet.evaluate(e=>{e.href='assets/interior.css?before=1'});await p.waitForFunction(()=>getComputedStyle(document.querySelector('.previous-session-sets')).flexWrap==='nowrap');await shot(p,engine+'-'+width+'-'+role+'-before-'+tone);await p.unroute('**/assets/interior.css*');await sheet.evaluate(e=>{e.href='assets/interior.css'});await p.waitForFunction(()=>getComputedStyle(document.querySelector('.previous-session-sets')).flexWrap==='wrap');}}
  });
  await test(role+' no history remains compact and is not invented',async()=>{await p.evaluate(()=>{window.workoutHistory=[];document.querySelector('.previous-session').outerHTML=renderPreviousSession(activeWorkout.exercises[0].id)});assert.equal(await p.locator('.previous-session').first().locator('.previous-set').count(),0);assert.match(await p.locator('.previous-session').first().innerText(),/Sin registro anterior/);assert((await p.locator('.previous-session').first().boundingBox()).height<=44);});await context.close();
 }
 }}finally{await browser.close()}}
write();console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass),shots:shots.length}));if(results.some(r=>!r.pass))process.exitCode=1;
})().catch(e=>{write();console.error(e);process.exitCode=1});
