const fs=require('fs'),assert=require('assert/strict'),cp=require('child_process'),I=require('../../assets/coach-intake.js'),Q=require('../../assets/coach-programming-v4.js'),cases=require('../coach-quality-v4/cases.cjs');
const rows=[];async function test(name,f){await f();rows.push(name);}
const ex=(id,sets=2)=>({name:Q.byId.get(id).name,sets,reps_min:8,reps_max:10,rir:3,rest_seconds:60});
const t=cases.A.training;
const good={schema_version:1,name:'Basic · rutina inicial',description:Q.instruction(t),days:['Lunes','Miércoles','Viernes'].map((name,i)=>({name,exercises:['goblet','db_rdl','floor_press','band_row',...(i===2?['dead_bug']:[])].map(id=>ex(id))}))};
(async()=>{const C=await import('../../supabase/functions/simple-coach-mock/contract.mjs'),P=await import('../../supabase/functions/simple-coach-mock/provider.mjs');
await test('54 unique metadata records, unchanged identity/material',()=>{assert.equal(Q.catalogue.length,54);for(const e of I.exercises){const m=Q.byId.get(e.id);assert.equal(m.name,e.name);assert.deepEqual(m.requires,e.requires);assert(!m.primary.some(g=>m.secondary.includes(g)));}});
await test('hip thrust/bridge are not hamstrings',()=>{for(const id of ['hip_thrust','glute_bridge'])assert(!Q.byId.get(id).primary.includes('hamstrings'));for(const id of ['db_rdl','bar_rdl','leg_curl','seated_curl'])assert(Q.byId.get(id).primary.includes('hamstrings'));});
await test('press triceps are secondary only',()=>{assert(!Q.byId.get('chest_press').primary.includes('triceps'));assert(Q.byId.get('chest_press').secondary.includes('triceps'));});
await test('frozen v3 source equals candidate de6cc79',()=>assert.equal(fs.readFileSync('supabase/functions/simple-coach-mock/contract-v3.mjs','utf8').replaceAll('\r\n','\n'),cp.execFileSync('git',['show','de6cc79:supabase/functions/simple-coach-mock/contract.mjs']).toString().replaceAll('\r\n','\n')));
await test('questionnaire vocabulary and Premium schema unchanged',()=>{for(const f of ['assets/coach-intake.js','tests/coach-intake-v2/basic-intake-v2.schema.json','tests/coach-intake-v2/premium-intake-v1.schema.json'])assert.equal(fs.readFileSync(f,'utf8').replaceAll('\r\n','\n'),cp.execFileSync('git',['show','de6cc79:'+f]).toString().replaceAll('\r\n','\n'));});
await test('balanced candidate, direct frequency',()=>{const r=C.reviewProposal(good,{prompt_version:'basic-initial-v4',training:t});assert(r.ok);assert.equal(r.muscles.hamstrings.direct,6);assert.equal(r.muscles.hamstrings.frequency,3);assert.equal(r.muscles.triceps.direct,0);assert.equal(r.muscles.triceps.secondary,6);});
for(const [name,change,code] of [
 ['unauthorized weekday',p=>p.days[0].name='Domingo','unauthorized_day'],
 ['duplicated exercise',p=>p.days[0].exercises.push(p.days[0].exercises[0]),'duplicate_exercise'],
 ['missing femorals despite hip',p=>p.days.forEach(d=>d.exercises[1]=ex('hip_thrust')),'major_absent_hamstrings'],
 ['systematic failure',p=>p.days[0].exercises[0].rir=0,'prescription_bounds'],
 ['beginner RIR 2',p=>p.days[0].exercises[0].rir=2,'prescription_bounds'],
 ['core overlong rest',p=>p.days[2].exercises.at(-1).rest_seconds=180,'prescription_bounds'],
 ['schema extra key',p=>p.secret='synthetic','schema_invalid']])await test(name,()=>{const p=structuredClone(good);change(p);assert(C.reviewProposal(p,{prompt_version:'basic-initial-v4',training:t}).failures.includes(code));});
await test('unavailable/excluded rejects exact ID only',()=>{assert(C.reviewProposal(good,{prompt_version:'basic-initial-v4',training:{...t,excluded:['db_rdl']}}).failures.includes('equipment_or_avoidance'));assert(I.allowedExercises({...t,excluded:['db_rdl']}).some(e=>e.id==='bar_rdl'));assert(!I.allowedExercises(cases.B.training).some(e=>e.id==='bench_press'));});
await test('unilateral duration includes both sides and transition',()=>{const e=ex('db_row');assert.equal(Q.seconds(e),120+2*(10*4*2+60+15));assert.equal(Q.byId.get('reverse_lunge').unilateral,true);assert.equal(Q.byId.get('dead_bug').unilateral,true);});
await test('80/90% thresholds inclusive and independent of rounding',()=>{const p={...good,days:[{name:'Lunes',exercises:[ex('goblet')]}]},seconds=300+Q.seconds(ex('goblet'));for(const [ratio,warning,fail] of [[.8,false,false],[.80001,true,false],[.9,true,false],[.90001,false,true]]){const r=Q.evaluate(p,{...t,days:1,weekdays:['mon'],minutes:seconds/60/ratio});assert.equal(r.warnings.some(w=>w.code==='duration_80_90'),warning);assert.equal(r.failures.includes('duration_over_90'),fail);}});
await test('femoral sparse warning differs from hip coverage',()=>{const p=structuredClone(good);p.days[1].exercises[1]=ex('glute_bridge');p.days[2].exercises[1]=ex('hip_thrust');const r=C.reviewProposal(p,{prompt_version:'basic-initial-v4',training:t});assert(r.ok);assert(r.warnings.some(w=>w.code==='hamstrings_sparse'));assert(r.warnings.some(w=>w.code==='low_muscle_frequency'&&w.muscle==='hamstrings'));});
await test('novice variety ceiling versus experienced warnings',()=>{const names=Q.catalogue.slice(0,13).map(e=>e.id),p={...good,days:good.days.map((d,i)=>({...d,exercises:names.slice(i*5,i*5+5).map(id=>ex(id))}))};assert(Q.evaluate(p,t).failures.includes('beginner_variety_ceiling'));assert(!Q.evaluate(p,{...t,experience:'gt4'}).failures.includes('beginner_variety_ceiling'));});
await test('sport on next weekday including Sunday to Monday',()=>{const p={...good,days:[{name:'Sábado',exercises:[ex('goblet')]},{name:'Domingo',exercises:[ex('goblet',3),ex('db_rdl',3)]}]};const r=Q.evaluate(p,{...t,days:2,weekdays:['sat','sun'],activity:{type:'football',weekdays:['mon']}});assert(r.warnings.some(w=>w.code==='sport_before_heaviest'&&w.alternative_days.includes('Sábado')));});
await test('small muscles omitted without compulsory random isolation',()=>{const r=Q.evaluate(good,t);assert.equal(r.smallMuscles.biceps.direct,0);assert(r.smallMuscles.biceps.secondary>0);assert(r.ok);});
for(const [name,{training}]of Object.entries(cases))await test('closed feasible context '+name,()=>{assert.equal(I.basicErrors(training).length,0);assert.equal(C.safetyGate({prompt_version:'basic-initial-v4',training}),null);const b=C.requestBody({prompt_version:'basic-initial-v4',training},C.DEFAULT_MODEL),s=JSON.stringify(b);assert(!s.includes('example.invalid'));assert.equal(b.model,'gpt-5.4-2026-03-05');assert.equal(b.store,false);assert.equal(b.text.format.schema.properties.days.minItems,training.days);});
await test('legacy v3 routing retains request and validation',async()=>{const V=await import('../../supabase/functions/simple-coach-mock/contract-v3.mjs');const ctx={prompt_version:'basic-initial-v4',training:t,prompt_version:'basic-initial-v3'};assert.deepEqual(C.requestBody(ctx,C.DEFAULT_MODEL),V.requestBody(ctx,C.DEFAULT_MODEL));const p={...good,description:I.effortInstruction(t)};assert.deepEqual(C.reviewProposal(p,ctx),V.reviewProposal(p,ctx));});
const wire={days:good.days.map((d,i)=>({day:t.weekdays[i],exercises:d.exercises.map(e=>({id:Q.byName.get(e.name).id,s:e.sets,lo:e.reps_min,hi:e.reps_max,r:e.rir,rest:e.rest_seconds}))}))};
await test('compact model output decodes unchanged persisted schema 1',()=>assert.deepEqual(C.decodeOutput(wire,{prompt_version:'basic-initial-v4',training:t}),good));
await test('one provider attempt actual transport with mocked output',async()=>{let calls=0;const r=await P.generate({prompt_version:'basic-initial-v4',training:t},{key:'TEST_ONLY',model:C.DEFAULT_MODEL,fetcher:async()=>{calls++;return new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(wire)}]}],usage:{input_tokens:100,output_tokens:200}}));}});assert.equal(calls,1);assert.equal(r.error_code,null);assert.deepEqual(r.proposal,good);});
for(const status of [429,500])await test('no retry or raw error leak '+status,async()=>{let calls=0;const r=await P.generate({prompt_version:'basic-initial-v4',training:t},{key:'TEST_ONLY',model:C.DEFAULT_MODEL,fetcher:async()=>{calls++;return new Response('{"error":{"message":"SECRET_ECHO","code":"rate_limit_exceeded"}}',{status});}});assert.equal(calls,1);assert(!JSON.stringify(r).includes('SECRET_ECHO'));assert.equal(r.proposal,null);});
await test('Premium and malformed inputs never dispatch',async()=>{for(const training of [I.emptyPremium(),{...t,weak_points:['biceps']}]){let calls=0;const r=await P.generate({prompt_version:'basic-initial-v4',training},{key:'TEST_ONLY',model:C.DEFAULT_MODEL,fetcher:async()=>{calls++;}});assert.equal(calls,0);assert.equal(r.error_code,'safety_review_required');}});
await test('rejected wire preserved for restricted staging diagnostic, not approvable',async()=>{const bad=structuredClone(wire);bad.days.forEach(d=>d.exercises=d.exercises.filter(e=>e.id!=='db_rdl'));const r=await P.generate({prompt_version:'basic-initial-v4',training:t},{key:'TEST_ONLY',model:C.DEFAULT_MODEL,fetcher:async()=>new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(bad)}]}],usage:{input_tokens:100,output_tokens:200}}))});assert.equal(r.proposal,null);assert.equal(r.error_code,'quality_rejected');assert(r.quality.failures.includes('major_absent_hamstrings'));assert(r.rejected_proposal.days.length===3);});
await test('reviewer mutation handlers exactly preserved',()=>{const f='assets/coach-reviewer.js',old=cp.execFileSync('git',['show','de6cc79:'+f]).toString(),now=fs.readFileSync(f,'utf8'),part=s=>s.slice(s.indexOf("if(o.state==='pending_review'||"),s.indexOf('queue.append(section);')).replaceAll('\r\n','\n');assert.equal(part(now),part(old));});
await test('type bounds explicitly support 180 seconds and 20 isolation reps',()=>{assert.equal(Q.bounds(Q.byId.get('bar_squat')).rest[1],180);assert.equal(Q.bounds(Q.byId.get('leg_curl')).reps[1],20);assert.equal(Q.bounds(Q.byId.get('dead_bug')).reps[1],15);});
fs.mkdirSync(__dirname+'/results',{recursive:true});fs.writeFileSync(__dirname+'/results/legacy-v4.json',JSON.stringify({passed:rows.length,rows},null,2));console.log(rows.length+'/'+rows.length+' v4 unit/provider checks');})().catch(e=>{console.error(e);process.exitCode=1;});
