const fs=require('fs'),path=require('path'),cases=require('./cases.cjs'),Q=globalThis.SimpleCoachProgrammingV5,I=globalThis.SimpleCoachIntakeV5;
const dir=__dirname+'/results',v4dir=path.resolve(__dirname,'../../../coach-quality-v4/tests/coach-quality-v4/results');
const read=k=>JSON.parse(fs.readFileSync(dir+'/real-quality-'+k+'.json')),round=n=>Number(n.toFixed(3));
const sets=p=>p.days.flatMap(d=>d.exercises.flatMap(e=>Q.planned(e))),counts=p=>{const ss=sets(p);return {rir:round(ss.reduce((n,s)=>n+s.rir,0)/ss.length),zero:ss.filter(s=>s.rir===0).length,one:ss.filter(s=>s.rir===1).length,total:ss.length,rests:[...new Set(ss.map(s=>s.rest_seconds))].sort((a,b)=>a-b).map(Q.minutes).join(' / '),reps:[...new Set(ss.map(s=>s.reps_min+'–'+s.reps_max))].join(' / '),core:[...new Set(p.days.flatMap(d=>d.exercises.filter(e=>Q.byName.get(e.name)?.primary.includes('core')).map(e=>e.name)))].join('; '),variable:p.days.flatMap(d=>d.exercises).filter(Q.heterogeneous).length}};
const table=(headers,rows)=>'| '+headers.join(' | ')+' |\n| '+headers.map(()=>'---').join(' | ')+' |\n'+rows.map(r=>'| '+r.join(' | ')+' |').join('\n')+'\n\n';
let doc='# Propuestas reales Basic v5 — 6 realizadas / 2 pendientes\n\nSolo GPT-5.4 en staging; cada salida se conserva completa, sin cambiar nombres ni objetivos. No aprobadas ni aceptadas. G/H no se generaron: presupuesto máximo reservado. Estas rutinas son propuestas para revisión, no una garantía de idoneidad individual.\n\n';
let comparison='# Comparativa v4 / v5\n\nUna salida por caso y versión; comparación descriptiva, no ensayo ni prueba de superioridad. Se reutilizan recibos v4 archivados, sin nuevas llamadas. Solo A↔A, B↔B y F↔G tienen perfiles comparables; en gimnasio completo v5 añade disponibilidad explícita de máquina abdominal y rueda. B mantiene inventario idéntico. C/D/E no tienen un control v4 de entrada equivalente; G/H v5 pendientes.\n\n';
const summary=[];
for(const k of 'ABCDEFGH'){
 const r=read(k),t=cases[k].training,p=r.proposal;doc+='## '+k+' — '+cases[k].label+'\n\n';
 doc+='Experiencia: '+I.experience.find(e=>e.id===t.experience).label+'. Objetivo: '+I.goals.find(e=>e.id===t.goal).label+'. Días: '+t.days+' ('+I.weekdays.filter(d=>t.weekdays.includes(d.id)).map(d=>d.label).join(', ')+'). '+t.minutes+' min por sesión. Estimación RIR: '+t.effort+'.\n\n';
 doc+='Material disponible (no preferencia): '+t.inventory.equipment.map(id=>I.equipment.find(e=>e.id===id).label).join('; ')+'.\n\nExclusiones: '+(t.excluded.map(id=>I.exercises.find(e=>e.id===id).name).join('; ')||'ninguna')+'. Actividad externa: '+t.activity.type+' ('+(t.activity.weekdays.join(', ')||'sin días')+'). Sin puntos débiles ni selección de ejercicios incluidos.\n\n';
 if(!p){doc+='**No generado.** El gasto confirmado es 0,223705 USD; el siguiente envío exige reservar hasta 0,0934775 USD y superaría el límite de 0,30 USD. No se llamó al proveedor para este caso ni se sustituyó con mocks.\n\n';continue;}
 const q=Q.evaluate(p,t),m=counts(p);summary.push({case:k,...m,unique:q.unique,durations:q.days.map(d=>d.minutes),warnings:q.warnings.length,cost:r.estimated_cost_usd});
 doc+='Modelo: '+r.model+'. Prompt: '+r.prompt_version+'. Coste: '+r.estimated_cost_usd+' USD. Estado antes de limpieza: '+r.state+'.\n\n'+p.name+'\n\n'+p.description+'\n\n';
 for(const d of p.days){const dm=q.days.find(x=>x.name===d.name);doc+='### '+d.name+'\n\n'+dm.exercises+' ejercicios · '+dm.sets+' series · ≈'+dm.minutes+' min estimados (no medidos).\n\n';
 doc+=table(['Ejercicio exacto','Esquema','Serie','Reps','RIR','Descanso'],d.exercises.flatMap(e=>e.planned_sets.map(s=>[e.name,e.scheme,s.set_number,s.reps_min+'–'+s.reps_max+(Q.byName.get(e.name)?.unilateral?' por lado':''),s.rir,Q.minutes(s.rest_seconds)])));
 }
 doc+='### Evaluación descriptiva\n\n'+table(['Grupo','Directas','Frecuencia directa','Participación secundaria','Frecuencia secundaria'],Object.entries(q.muscles).map(([g,m])=>[Q.labels[g],m.direct,m.frequency,m.secondary,m.secondary_frequency]));
 doc+='No sumar las filas musculares como series totales: un ejercicio puede involucrar varios grupos. Espalda alta es un subconjunto de espalda; secundarias no equivalen automáticamente a directas.\n\n';
 doc+='Patrones (series): '+Object.entries(q.patterns).map(([g,n])=>g+' '+n).join('; ')+'.\n\n';
 doc+='Total '+q.totalSets+' series, '+q.unique+' ejercicios distintos, RIR medio '+m.rir+'. RIR 0: '+m.zero+'; RIR 1: '+m.one+'. Ejercicios con objetivos variables: '+m.variable+'. Rangos: '+m.reps+'. Descansos: '+m.rests+'. Abdomen: '+m.core+'.\n\n';
 doc+='Sesiones tren inferior: '+q.days.map(d=>d.name+' '+d.legSets+'/'+d.sets+' series de movimientos de pierna').join('; ')+'. La clasificación no suma abdomen ni trabajo indirecto como pierna.\n\n';
 doc+='Cobertura/material/exclusiones: todos los ejercicios pertenecen al catálogo permitido; los grandes grupos tienen cobertura directa. No hay duplicados dentro del mismo día. Las repeticiones de un ejercicio entre días son exposiciones de entrenamiento, no identidades históricas fusionadas. No hay actividad externa declarada; no se infiere tolerancia ni ausencia de fatiga.\n\n';
 doc+='Avisos (heurísticas, no todos implican un problema):\n\n'+(q.warnings.length?q.warnings.map(w=>'- '+w.code+': '+w.message+' '+[w.day,w.exercise,w.set?'serie '+w.set:'',w.muscle?Q.labels[w.muscle]:''].filter(Boolean).join(' · ')).join('\n'):'- Ninguno.')+'\n\n';
 const previous={A:'A',B:'B',F:'G'}[k];if(previous){const old=JSON.parse(fs.readFileSync(v4dir+'/real-quality-'+previous+'.json')),op=old.proposal,oq=Q.evaluate(op,old.training),om=counts(op);
 comparison+='## v5 '+k+' / v4 '+previous+'\n\n';
 comparison+=table(['Métrica','v4 archivada','v5 real'],[['RIR medio',om.rir,m.rir],['Series RIR 0',om.zero,m.zero],['Series RIR 1',om.one,m.one],['Series totales',om.total,m.total],['Ejercicios distintos',oq.unique,q.unique],['Ejercicios con variación por serie',om.variable,m.variable],['Reps',om.reps,m.reps],['Descansos',om.rests,m.rests],['Abdomen',om.core,m.core],['Minutos por sesión',oq.days.map(d=>d.minutes).join('/'),q.days.map(d=>d.minutes).join('/')]]);
 comparison+=table(['Grupo','Directas v4','Directas v5','Frecuencia v4→v5'],Object.entries(q.muscles).map(([g,v])=>[Q.labels[g],oq.muscles[g].direct,v.direct,oq.muscles[g].frequency+'→'+v.frequency]));
 const names=[...new Set([...op.days.flatMap(d=>d.exercises.map(e=>e.name)),...p.days.flatMap(d=>d.exercises.map(e=>e.name))])],exercise=(p,n)=>p.days.flatMap(d=>d.exercises.filter(e=>e.name===n).map(e=>d.name+': '+Q.planned(e).map(s=>s.reps_min+'–'+s.reps_max+' RIR'+s.rir+' '+Q.minutes(s.rest_seconds)).join(' + '))).join('; ')||'—';
 comparison+=table(['Ejercicio','v4: cada serie','v5: cada serie'],names.map(n=>[n,exercise(op,n),exercise(p,n)]));
 }
}
const clean=s=>s.split('\n').map(x=>x.trimEnd()).join('\n').trimEnd()+'\n';fs.writeFileSync(__dirname+'/GENERACIONES.md',clean(doc));fs.writeFileSync(__dirname+'/COMPARATIVA.md',clean(comparison));fs.writeFileSync(dir+'/summary.json',JSON.stringify(summary,null,2));console.log(JSON.stringify(summary));
