// Archived real receipts only: no network, no provider call, no mutation of outputs.
const fs=require('fs'),crypto=require('crypto'),cases=require('./cases.cjs'),Q=globalThis.SimpleCoachProgrammingV5,I=globalThis.SimpleCoachIntakeV5;
const dir=__dirname+'/results',table=(h,rs)=>'| '+h.join(' | ')+' |\n| '+h.map(()=>'---').join(' | ')+' |\n'+rs.map(r=>'| '+r.join(' | ')+' |').join('\n')+'\n\n';
const data=Object.fromEntries([...'ABCDEFGH'].map(k=>[k,JSON.parse(fs.readFileSync(dir+'/real-quality-'+k+'.json'))]));
const expected=JSON.parse(fs.readFileSync(__dirname+'/private/af-hashes.json'));
for(const k of 'ABCDEF')if(crypto.createHash('sha256').update(fs.readFileSync(dir+'/real-quality-'+k+'.json')).digest('hex')!==expected[k])throw Error('Archived output changed: '+k);
let doc='# Ajuste final de descansos V5 — revisión desde 1b96f61\n\nNo publicado. A–F se conservan byte a byte y no se han regenerado. G/H son propuestas reales de staging, pendientes de revisión antes de limpiar sus fixtures; no aprobadas ni aceptadas. La evaluación de avisos siguiente usa el candidato final, sin retocar ninguna prescripción del modelo.\n\n';
const summaries=[];for(const [k,r]of Object.entries(data)){const q=Q.evaluate(r.proposal,r.training),hist={},zeros=[];for(const d of r.proposal.days)for(const e of d.exercises)for(const s of e.planned_sets){hist[s.rest_seconds]=(hist[s.rest_seconds]||0)+1;if(s.rir===0){const m=Q.byName.get(e.name);zeros.push({day:d.name,exercise:e.name,set:s.set_number,rest:s.rest_seconds,type:m.type,stable:m.stable,costly:Q.costly(m)});}}
 summaries.push({case:k,rests:hist,total:q.totalSets,zero:zeros.length,zeros,isolations:zeros.filter(z=>z.type==='isolation').length,calves:zeros.filter(z=>z.type==='calf').length,stable:zeros.filter(z=>z.stable).length,costly:zeros.filter(z=>z.costly).length,warnings:q.warnings,failures:q.failures,durations:q.days.map(d=>d.minutes)});
}
doc+='## Descansos reales A–H\n\nCada celda cuenta series; no se han normalizado los descansos históricos.\n\n';
const rests=[...new Set(summaries.flatMap(s=>Object.keys(s.rests).map(Number)))].sort((a,b)=>a-b);
doc+=table(['Caso',...rests.map(Q.minutes),'Series','Minutos estimados por sesión'],summaries.map(s=>[s.case,...rests.map(n=>s.rests[n]||'—'),s.total,s.durations.join(' / ')]));
doc+='## Todas las ubicaciones RIR 0 — E/F/G/H\n\nAislamiento y máquina estable son dimensiones que se solapan: no sumar columnas. Gemelos se detalla como accesorio. La clasificación de alta demanda incluye banca además de fatigue_cost=high, sin cambiar el catálogo.\n\n';
doc+=table(['Caso','RIR 0','Aislamientos','Gemelos','Estables','Alta demanda'],summaries.filter(s=>'EFGH'.includes(s.case)).map(s=>[s.case,s.zero,s.isolations,s.calves,s.stable,s.costly]));
for(const s of summaries.filter(s=>'EFGH'.includes(s.case))){doc+='### '+s.case+'\n\n';doc+=table(['Día','Ejercicio exacto','Serie','Descanso','Tipo','Alta demanda'],s.zeros.map(z=>[z.day,z.exercise,z.set,Q.minutes(z.rest),z.type,z.costly?'Sí':'No']));}
doc+='## Avisos de calidad\n\nOrientaciones prácticas, no diagnósticos ni umbrales fisiológicos. Una opción válida de 2 min para aislamiento a RIR 0 no se marca como problema por preferir a veces 2,5 min. La revisión por fallo repetido de alto coste requiere más de una exposición y evidencia adicional: solapamiento muscular entre ejercicios, todas las series de un ejercicio al fallo o recuperación inferior a la preferencia contextual. Dos exposiciones solo define repetición; no afirma que dos sean excesivas por sí mismas. El aviso pide justificar, no rechaza la propuesta. Los avisos preexistentes de densidad global (>4 o >50% por sesión) se conservan como cribado V5, no como prohibición.\n\n';
doc+=table(['Caso','short_rest','rest_performance_review','demanding_failure','Otros','Fallos duros'],summaries.map(s=>[s.case,...['short_rest','rest_performance_review','demanding_failure'].map(c=>s.warnings.filter(w=>w.code===c).length),s.warnings.filter(w=>!['short_rest','rest_performance_review','demanding_failure'].includes(w.code)).map(w=>w.code).join(', ')||'—',s.failures.join(', ')||'Ninguno']));
for(const s of summaries.filter(s=>'EFGH'.includes(s.case))){doc+='### Avisos '+s.case+'\n\n'+s.warnings.map(w=>'- '+w.code+': '+[w.day,w.exercise,w.set?'serie '+w.set:''].filter(Boolean).join(' · ')+'. '+w.message+(w.reference_seconds?' Referencia: '+Q.minutes(w.reference_seconds)+'.':'')).join('\n')+'\n\n';}
doc+='## G/H completas — entradas y propuestas originales\n\n';
for(const k of 'GH'){const r=data[k],t=r.training,q=Q.evaluate(r.proposal,t);doc+='### '+k+' — '+cases[k].label+'\n\nExperiencia: '+I.experience.find(x=>x.id===t.experience).label+'. Objetivo: '+I.goals.find(x=>x.id===t.goal).label+'. Días: '+t.days+'. Disponibilidad: '+I.weekdays.filter(x=>t.weekdays.includes(x.id)).map(x=>x.label).join(', ')+'. Duración: '+t.minutes+' min/día. RIR: estimación habitual. Exclusiones: ninguna. Actividad externa: ninguna.\n\nMaterial disponible (no preferencia): '+t.inventory.equipment.map(id=>I.equipment.find(x=>x.id===id).label).join('; ')+'.\n\n'+r.proposal.name+'\n\n'+r.proposal.description+'\n\n';
 for(const d of r.proposal.days){doc+='#### '+d.name+'\n\n';doc+=table(['Ejercicio exacto','Esquema','Serie','Reps','RIR','Descanso'],d.exercises.flatMap(e=>e.planned_sets.map(s=>[e.name,e.scheme,s.set_number,s.reps_min+'–'+s.reps_max,s.rir,Q.minutes(s.rest_seconds)])));}
 doc+='Series: '+q.totalSets+'. RIR 0: '+q.rirZero+'. RIR 1: '+q.rirOne+'. Minutos estimados: '+q.days.map(d=>d.name+' '+d.minutes).join('; ')+'. No son tiempos medidos.\n\n';
}
const ledger=JSON.parse(fs.readFileSync(__dirname+'/private/openai-budget.json')),extra=ledger.calls.filter(x=>'GH'.includes(x.case));
doc+='## Coste y llamadas\n\n'+table(['Caso/intento','Resultado','Tokens entrada/salida','USD'],extra.map(x=>{const r=JSON.parse(fs.readFileSync(dir+'/real-quality-'+x.case+(x.case==='G'&&(x.attempt||1)===1?'-attempt1':'')+'.json'));return [x.case+' / '+(x.attempt||1),x.operation_state,r.input_tokens+' / '+r.output_tokens,x.confirmed_cost_usd];}));
doc+='Adicional real: '+extra.reduce((n,x)=>n+x.confirmed_cost_usd,0).toFixed(7)+' USD. Total fase: '+ledger.calls.reduce((n,x)=>n+x.confirmed_cost_usd,0).toFixed(7)+' USD / 0,45 USD autorizados. Nueve llamadas en toda la fase: seis A–F anteriores, G fallida, H y un único reintento G autorizado explícitamente. No hubo bucles. El techo de salida V5 se amplió de 3200 a 5120 tras el fallo; la reserva previa para ese reintento fue 0,1253075 USD (acumulado con reserva 0,44131).\n';
fs.writeFileSync(__dirname+'/FINAL-REST.md',doc);fs.writeFileSync(dir+'/rest-summary.json',JSON.stringify(summaries,null,2));console.log(JSON.stringify(summaries.map(({zeros,warnings,...s})=>({...s,warnings:warnings.length}))));
