const fs=require('fs'),assert=require('assert/strict'),cp=require('child_process'),vm=require('vm'),cases=require('./cases.cjs'),I=globalThis.SimpleCoachIntakeV5,Q=globalThis.SimpleCoachProgrammingV5;
const rows=[];async function test(n,f){await f();rows.push(n);}
const ex=(id,ss)=>{const sets=(ss||[[8,10,3,120],[8,10,3,120]]).map(([reps_min,reps_max,rir,rest_seconds],i)=>({set_number:i+1,reps_min,reps_max,rir,rest_seconds}));return {name:Q.byId.get(id).name,sets:sets.length,...Object.fromEntries(Object.entries(sets[0]).filter(([k])=>k!=='set_number')),scheme:new Set(sets.map(s=>JSON.stringify({...s,set_number:0}))).size===1?'straight':'varied',planned_sets:sets};};
const make=t=>({schema_version:2,name:'Basic · rutina inicial',description:Q.instruction(t),days:I.weekdays.filter(d=>t.weekdays.includes(d.id)).map(d=>({name:d.label,exercises:['goblet','db_rdl','floor_press','band_row'].map(id=>ex(id))}))});
const t=cases.A.training,good=make(t);
(async()=>{const C=await import('../../supabase/functions/simple-coach-mock/contract.mjs'),V4=await import('../../supabase/functions/simple-coach-mock/contract-v4.mjs'),P=await import('../../supabase/functions/simple-coach-mock/provider.mjs');
await test('v4 contract/metadata and original questionnaire byte-equivalent to base',()=>{for(const f of ['supabase/functions/simple-coach-mock/contract-v4.mjs','assets/coach-programming-v4.js','assets/coach-intake.js','tests/coach-intake-v2/premium-intake-v1.schema.json'])assert.equal(fs.readFileSync(f,'utf8').replaceAll('\r\n','\n'),cp.execFileSync('git',['show','2a8bfc0:'+f]).toString().replaceAll('\r\n','\n'));});
await test('schema2 valid with exact first-set legacy projection',()=>{assert(C.validate(good));assert(C.reviewProposal(good,{training:t}).ok);assert.equal(good.description.length<500,true);});
for(const [name,mutate,code]of [
 ['count mismatch',p=>p.days[0].exercises[0].sets++,'set_count'],
 ['projection mismatch',p=>p.days[0].exercises[0].rir=2,'projection_mismatch'],
 ['extra key',p=>p.days[0].exercises[0].secret=1,'schema_invalid'],
 ['bad numbering',p=>p.days[0].exercises[0].planned_sets[1].set_number=1,'prescription_bounds'],
 ['bad min/max',p=>p.days[0].exercises[0].planned_sets[1].reps_min=11,'prescription_bounds'],
 ['novice zero',p=>{p.days[0].exercises[0]=ex('goblet',[[8,10,0,120]]);},'beginner_failure'],
 ['missing hamstrings',p=>p.days.forEach(d=>d.exercises[1]=ex('hip_thrust')),'major_absent_hamstrings'],
 ['duplicate exercise',p=>p.days[0].exercises.push(p.days[0].exercises[0]),'duplicate_exercise'],
 ['unauthorized weekday',p=>p.days[0].name='Domingo','unauthorized_day'],
 ['straight is not heterogeneous',p=>p.days[0].exercises[0].planned_sets[1].rir=2,'scheme_mismatch'],
 ['invalid backoff',p=>p.days[0].exercises[0].scheme='top_backoff','backoff_mismatch']
])await test(name,()=>{const p=structuredClone(good);mutate(p);assert(C.reviewProposal(p,{training:t}).failures.includes(code));});
for(const [k,{training}]of Object.entries(cases))await test('case '+k+' feasible and closed model input',()=>{assert.deepEqual(I.basicErrors(training),[]);assert.equal(C.safetyGate({training}),null);const b=C.requestBody({training},C.DEFAULT_MODEL);assert.equal(b.model,'gpt-5.4-2026-03-05');assert.equal(b.store,false);assert(!JSON.stringify(b).includes('weak_points'));assert(!JSON.stringify(b).includes('health'));assert.equal(JSON.parse(b.input[0].content).catalogue.every(x=>!training.excluded.includes(x[0])),true);});
await test('new equipment not invented; exact exclusions',()=>{const b=I.allowedExercises(cases.B.training).map(x=>x.id);assert(b.includes('weighted_crunch'));assert(!b.includes('cable_crunch'));assert(!b.includes('machine_crunch'));assert(!b.includes('ab_wheel'));assert(I.allowedExercises({...t,excluded:['floor_crunch']}).some(e=>e.id==='reverse_crunch'));assert(!I.allowedExercises({...t,excluded:['floor_crunch']}).some(e=>e.id==='floor_crunch'));});
await test('new machine/wheel vocabulary valid but unknown remains denied',()=>{assert.deepEqual(I.basicErrors({...t,excluded:['ab_wheel'],inventory:{equipment:['ab_wheel','ab_machine','dumbbells','bands'],custom:[]}}),[]);assert(I.basicErrors({...t,inventory:{equipment:['invented'],custom:[]}}).length);assert(I.basicErrors({...t,weak_points:['arms']}).length);});
await test('dynamic core priority and metadata conservative',()=>{assert.equal(Q.byId.get('dead_bug').hypertrophy_priority,'context_only');assert.equal(Q.byId.get('bird_dog').hypertrophy_priority,'context_only');assert.equal(Q.byId.get('ab_wheel').failure_suitable,false);assert(Q.byId.get('hack').failure_suitable);assert(!Q.byId.get('bar_rdl').failure_suitable);assert(!Q.byId.get('hip_thrust').primary.includes('hamstrings'));});
const advanced=cases.E.training,p=make(advanced);p.days.forEach(d=>d.exercises.forEach(e=>{e.rir=2;e.planned_sets.forEach(s=>s.rir=2);}));
p.days[0].exercises[0]=ex('hack',[[5,7,1,180],[7,9,0,210]]);p.days[0].exercises[0].scheme='top_backoff';
await test('advanced legitimate top/backoff and RIR0/1/2 accepted',()=>{const r=C.reviewProposal(p,{training:advanced});assert(r.ok,JSON.stringify(r.failures));assert(r.rirZero>0&&r.rirOne>0&&r.variableExercises>0);assert(!r.warnings.some(w=>w.code==='technical_failure'));});
await test('fatigue warnings are not deterministic failures',()=>{const z=structuredClone(p);z.days[0].exercises=['hack','leg_press','bar_rdl','chest_press','leg_curl'].map(id=>ex(id,[[8,10,0,90],[8,10,0,90],[8,10,0,90]]));const r=Q.evaluate(z,advanced);for(const code of ['session_failure_density','demanding_failure','failure_volume','technical_failure','short_rest'])assert(r.warnings.some(w=>w.code===code),code);assert(!r.failures.includes('technical_failure'));});
await test('novice complexity and unsafe effort are visible warnings',()=>{const x=structuredClone(good);x.days[0].exercises[0]=ex('goblet',[[8,10,3,120],[10,12,2,120]]);const r=C.reviewProposal(x,{training:t});assert(r.ok);for(const code of ['beginner_complexity','beginner_effort','effort_uncertain'])assert(r.warnings.some(w=>w.code===code));});
await test('unilateral actual time and per-set differences preserved',()=>{const e=ex('db_row',[[7,9,1,120],[10,12,0,150]]);assert.equal(Q.seconds(e),120+9*8+120+15+12*8+150+15);});
await test('rest presentation minutes only no data mutation',()=>{for(const [s,x]of [[60,'1 min'],[75,'1,25 min'],[90,'1,5 min'],[120,'2 min'],[150,'2,5 min'],[180,'3 min']])assert.equal(Q.minutes(s),x);});
await test('schema1 and explicit v4 context unchanged',()=>{const ctx={training:{...t,inventory:{equipment:globalThis.SimpleCoachIntake.equipment.map(e=>e.id),custom:[]}},prompt_version:'basic-initial-v4'};assert.deepEqual(C.requestBody(ctx,C.DEFAULT_MODEL),V4.requestBody(ctx,C.DEFAULT_MODEL));const old={...good,schema_version:1,days:good.days.map(d=>({...d,exercises:d.exercises.map(({scheme,planned_sets,...e})=>e)}))};assert(C.validate(old));assert.deepEqual(C.reviewProposal(old,ctx),V4.reviewProposal(old,ctx));});
const wire={days:good.days.map((d,i)=>({day:t.weekdays[i],exercises:d.exercises.map(e=>({id:Q.byName.get(e.name).id,k:0,b:[{s:2,lo:8,hi:10,r:3,rest:120}]}))}))};
await test('wire blocks expanded exactly',()=>assert.deepEqual(C.decodeOutput(wire,{training:t}),good));
await test('provider accepts schema2 mocked transport once',async()=>{let calls=0;const r=await P.generate({training:t},{key:'LOCAL_TEST',model:C.DEFAULT_MODEL,fetcher:async()=>{calls++;return new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(wire)}]}],usage:{input_tokens:100,output_tokens:200}}));}});assert.equal(calls,1);assert.equal(r.error_code,null);assert.deepEqual(r.proposal,good);});
for(const status of [429,500])await test('provider no retry '+status,async()=>{let n=0;const r=await P.generate({training:t},{key:'LOCAL_TEST',model:C.DEFAULT_MODEL,fetcher:async()=>{n++;return new Response('{"error":{"message":"DO_NOT_LEAK","code":"rate_limit_exceeded"}}',{status});}});assert.equal(n,1);assert.equal(r.proposal,null);assert(!JSON.stringify(r).includes('DO_NOT_LEAK'));});
await test('Premium and invalid input no provider call',async()=>{for(const training of [I.emptyPremium(),{...t,weak_points:['biceps']}]){let n=0;const r=await P.generate({training},{key:'LOCAL_TEST',model:C.DEFAULT_MODEL,fetcher:async()=>{n++;}});assert.equal(n,0);assert.equal(r.error_code,'safety_review_required');}});
fs.mkdirSync(__dirname+'/results',{recursive:true});fs.writeFileSync(__dirname+'/results/unit.json',JSON.stringify({passed:rows.length,total:rows.length,rows},null,2));
fs.writeFileSync(__dirname+'/results/mock-proposal.json',JSON.stringify({proposal:p,training:advanced,synthetic:true,mocked:true},null,2));
console.log(rows.length+'/'+rows.length+' v5 unit/provider LOCAL checks');
})().catch(e=>{console.error(e);process.exitCode=1;});
