// Navigable offline safe-projection preview, not an OAuth/AI production test.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
process.env.PLAYWRIGHT_BROWSERS_PATH='C:/Users/raulc/Documents/Codex/2026-09-07/quiero-que-realices-una-auditor-a/work/pw-browsers';
const {chromium,webkit}=require('C:/Users/raulc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const P=require('../premium-upgrade/preview.cjs'),port=4258,rows=[],out=path.join(__dirname,'results');
const exerciseNames=['Prensa 45º','Press de pecho','Jalón al pecho','Curl con mancuernas','Peso muerto rumano','Sentadilla goblet','Remo en polea','Press de hombro','Curl femoral sentado','Remo con mancuerna','Press de suelo','Elevaciones laterales'];
function fixture(role='athlete'){
 const v=P.fixture(role==='reviewer'?'reviewer':'normal'),names=exerciseNames;
 const sets=[1,2].map(set_number=>({set_number,reps_min:8,reps_max:12,rir:2,rest_seconds:180}));
 const make=n=>({sessions:Array.from({length:n},(_,i)=>({name:'Sesión '+(i+1),weekday:['mon','tue','thu','fri'][i],minutes:75,estimated_minutes:38,exercises:names.filter((_,k)=>k%n===i).map(name=>({name,planned_sets:sets}))}))});
 v.recommendations[0]={...v.recommendations[0],kind:'MODIFY',reason:'Se redistribuyen las mismas 24 series en cuatro sesiones.',facts:[{exercise_name:'Prensa 45º',claim:'insufficient_data',observations:[]}],changes:[{action:'session_distribution',exercise_name:'Distribución de sesiones',before:make(3),after:{...make(4),quality:{sets_before:24,sets_after:24,muscle_sets_after:{quads:4,chest:4,back:6},frequency_after:{quads:2,chest:2,back:3},volume_reason:null},removed_exercises:[]}}],quality_warnings:['whole_program_distribution_requires_review']};return v;
}
const adapter={async handle({action,tag}){if(['state','reset'].includes(action))return fixture(tag==='reviewer'?'reviewer':'athlete');throw Error('action_unavailable');}};
const check=(name,ok)=>{assert(ok,name);rows.push(name);};
async function run(){fs.mkdirSync(out,{recursive:true});const server=P.createServer(adapter,port);await new Promise(r=>server.listen(port,'127.0.0.1',r));
try{for(const [engine,type]of [['Chromium',chromium],['WebKit',webkit]]){const browser=await type.launch({headless:true,...(engine==='Chromium'?{channel:'msedge'}:{})});try{for(const role of ['athlete','reviewer'])for(const [width,theme]of [[320,'light'],[390,'dark'],[1280,'light']]){const page=await browser.newPage({viewport:{width,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+port+'/review?case='+(role==='reviewer'?'reviewer':'normal'));await page.waitForFunction(()=>window.PremiumHostUI?.snapshot().view&&!window.PremiumHostUI.snapshot().busy);await page.evaluate(theme=>{document.documentElement.dataset.theme=theme;window.PremiumHostUI.navigate('analysis');},theme);await page.locator('[data-action=proposal]').click();
 const key=[engine,role,width,theme].join(' ');const text=await page.locator('main').innerText();check(key+' full before/after prescriptions',text.includes('Antes')&&text.includes('Después')&&text.includes('24 → 24')&&text.includes('Serie 2: 8–12 reps, RIR 2, 3 min'));check(key+' all twelve exercises visible',namesPresent(text));check(key+' no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));check(key+' review and acceptance remain separate',role==='reviewer'?await page.locator('[data-action=review]').count()===1&&await page.locator('[data-action=confirm_accept]').count()===0:await page.locator('[data-action=confirm_accept]').count()===1&&await page.locator('[data-action=review]').count()===0);check(key+' warnings persist before action',text.includes('Avisos de calidad'));check(key+' no script errors',errors.length===0);
 if(engine==='Chromium'&&role==='reviewer'&&width!==320)await page.screenshot({path:path.join(out,'review-'+width+'-'+theme+'.png'),fullPage:true});await page.close();}}finally{await browser.close();}}}finally{await new Promise(r=>server.close(r));}
console.log(JSON.stringify({suite:'distribution safe projection UI',passed:rows.length,checks:rows,network:'local preview only',openai_calls:0}));}
function namesPresent(text){return exerciseNames.every(x=>text.split(x).length>=3);}
run().catch(e=>{console.error(e);process.exitCode=1;});
