// Pure contract validation: no credentials, Edge requests or OpenAI calls.
const assert=require('node:assert/strict');
(async()=>{
 const D=await import('../../supabase/functions/simple-coach-premium/distribution-contract.mjs');
 const S=await import('../../supabase/functions/simple-coach-premium/series-contract.mjs');
 const W=await import('../../supabase/functions/simple-coach-premium/weekly-contract.mjs');
 const clone=x=>structuredClone(x),rows=[];
 const check=(name,value)=>{assert(value,name);rows.push(name);};
 const cats=['leg_press','chest_press','pulldown','db_curl','db_rdl','goblet','cable_row','db_shoulder','seated_curl','db_row','floor_press','db_lateral'];
 const ss=[1,2].map(set_number=>({set_number,reps_min:8,reps_max:12,rir:2,rest_seconds:180}));
 const ctx={schema_version:W.PROVIDER_VERSION,session_distribution_version:D.VERSION,distribution_availability:{weekdays:['mon','tue','thu','fri'],minutes_by_day:{mon:75,tue:75,thu:75,fri:75}},intake:{experience:'gt4',activity:{type:'none',weekdays:[]},excluded:[]},routine:{days:[1,2,3].map(n=>({ref:'day_'+n,order:n-1})),exercises:cats.map((catalogue_id,n)=>({ref:'exercise_'+(n+1),day_ref:'day_'+(Math.floor(n/4)+1),catalogue_id,planned_sets:clone(ss),prescription:{sets:2,reps:'8-12',rir:'2',rest_seconds:180},metrics:{trend:'insufficient_data'},exposures:[]}))},allowed_replacements:D.CATALOGUE,checkin_missing:true,checkin:null,recent_weeks:[],week_schedule:[],week_schedule_source:'unresolved'};
 function layout(n,c=ctx){return {action:'change_session_distribution',sessions:Array.from({length:n},(_,i)=>({action:i<c.routine.days.length?'move_session':'add_session',session_ref:i<c.routine.days.length?'day_'+(i+1):'new_day_'+(i+1-c.routine.days.length),weekday:['mon','tue','thu','fri'][i],minutes:75,exercises:c.routine.exercises.filter((e,k)=>k%n===i).map(e=>({exercise_ref:e.ref,catalogue_id:e.catalogue_id,planned_sets:clone(e.planned_sets)}))})),removed_sessions:c.routine.days.slice(n).map(d=>d.ref),removed_exercises:[],volume_reason:null};}
 function output(ch,c=ctx){return {schema_version:D.SCHEMA_VERSION,kind:'MODIFY',facts:[{exercise_ref:'exercise_1',claim:'insufficient_data'}],checkin_signals:[],interpretation:'Solo una exposición: no demuestra una tendencia.',changes:[ch],reason:'Redistribuir el volumen sin ampliarlo.',confidence:'low'};}
 const ch=layout(4),v=output(ch),valid=D.semantic(v,ctx);assert(valid.ok,JSON.stringify(valid));check('3→4 accepted with every set explicit',valid.ok);check('3→4 keeps 24 weekly sets',valid.before===24&&valid.after===24);check('four session durations fit availability',Object.values(valid.durations).every(n=>n<=75));check('muscle volume unchanged',JSON.stringify(valid.groupsBefore)===JSON.stringify(Object.fromEntries(Object.keys(valid.groupsBefore).map(k=>[k,valid.groupsAfter[k]]))));check('distribution review warning preserved',valid.warnings.includes('whole_program_distribution_requires_review'));
 const c4=clone(ctx);c4.routine.days.push({ref:'day_4',order:3});check('4→3 with explicit removed session',D.semantic(output(layout(3,c4),c4),c4).ok);check('same count redistribution',D.semantic(output(layout(3)),ctx).ok);
 function rejects(name,edit,c=ctx){const x=clone(ch);edit(x);check(name,!D.semantic(output(x,c),c).ok);}
 rejects('unavailable Wednesday rejected',x=>x.sessions[3].weekday='wed');rejects('duplicate weekdays rejected',x=>x.sessions[3].weekday='mon');rejects('duplicate existing session rejected',x=>x.sessions[3].session_ref='day_1');rejects('unknown existing session rejected',x=>{x.sessions[3].action='move_session';x.sessions[3].session_ref='day_9';});rejects('missing exercise cannot disappear silently',x=>x.sessions[0].exercises.pop());rejects('duplicate exercise cannot inflate volume',x=>x.sessions[1].exercises[0]=clone(x.sessions[0].exercises[0]));rejects('baseline UUID reference cannot change catalogue identity',x=>x.sessions[0].exercises[0].catalogue_id='horizontal_press');rejects('excluded exercise rejected',()=>{}, {...clone(ctx),intake:{...ctx.intake,excluded:['db_curl']}});rejects('unavailable material rejected',()=>{}, {...clone(ctx),allowed_replacements:ctx.allowed_replacements.filter(e=>e.id!=='db_rdl')});rejects('time cap enforced',x=>x.sessions[0].minutes=15);rejects('null prescription rejected',x=>x.sessions[0].exercises[0].planned_sets=null);rejects('empty session rejected',x=>x.sessions[0].exercises=[]);rejects('invalid RIR rejected',x=>x.sessions[0].exercises[0].planned_sets[0].rir=6);rejects('series order preserved',x=>x.sessions[0].exercises[0].planned_sets[1].set_number=1);rejects('no compressed rest to fit extra volume',x=>x.sessions[0].exercises[0].planned_sets[0].rest_seconds=90);rejects('volume increase needs separate justification',x=>x.sessions[0].exercises[0].planned_sets.push({...ss[0],set_number:3}));
 const larger=clone(ch);larger.sessions[0].exercises[0].planned_sets.push({...ss[0],set_number:3});larger.volume_reason='Se propone una serie adicional explícita para revisión, separada de añadir un día.';check('explicit volume increase remains reviewer warning',D.semantic(output(larger),ctx).warnings.includes('weekly_volume_changed:24->25'));
 const remove=clone(ch),old=remove.sessions[0].exercises.pop();remove.removed_exercises.push({exercise_ref:old.exercise_ref,reason:'Retirada explícita de una redundancia.'});check('explicit removal retains declared accounting',D.semantic(output(remove),ctx).ok);
 const fresh=clone(ch);fresh.sessions[0].exercises.push({exercise_ref:'new_exercise_1',catalogue_id:'band_curl',planned_sets:clone(ss)});fresh.volume_reason='Adición explícita de cuatro series semanales, no implícita en el día.';check('new exercise requires complete allowed prescription',D.semantic(output(fresh),ctx).ok);
 check('cannot mix topology and unrelated changes',!D.semantic({...v,changes:[ch,{action:'change_rir',exercise_ref:'exercise_1',from:'2',to:'3'}]},ctx).ok);check('cannot invent progress from one observation',!D.semantic({...v,facts:[{exercise_ref:'exercise_1',claim:'reps_increasing_comparable'}]},ctx).ok);check('missing checkin has no invented normal signals',!D.semantic({...v,checkin_signals:[{field:'fatigue',value:'normal'}]},ctx).ok);
 const keep={...v,kind:'KEEP',changes:[]};check('four available days do not force MODIFY',D.semantic(keep,ctx).ok);check('legacy weekly contract still accepted independently',W.semantic({...keep,schema_version:W.SCHEMA_VERSION},ctx).ok);check('strict schema includes structured session operations',D.requestBody(ctx).text.format.schema===D.SCHEMA);check('no UUID references in provider request',!/[0-9a-f]{8}-[0-9a-f]{4}/.test(JSON.stringify(D.requestBody(ctx))));check('prescriptions remain the existing series architecture',S.sets(ctx.routine.exercises[0]).length===2);
 const avoided=clone(ctx);avoided.intake.excluded=['db_curl'];check('KEEP preserves an excluded historical baseline',D.semantic({...keep},avoided).ok);check('normal MODIFY cannot increase an excluded current exercise',!D.semantic({...keep,kind:'MODIFY',changes:[{action:'change_sets',exercise_ref:'exercise_4',from:2,to:3}]},avoided).ok);
 let dispatches=0;const realShape={status:'completed',usage:{input_tokens:100,output_tokens:100,input_tokens_details:{cached_tokens:0}},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(v)}]}]};const response=await D.analyze(ctx,'MOCK',async(_url,init)=>{dispatches++;assert.equal(JSON.parse(init.body).text.format.name,'premium_weekly_distribution_v1');return new Response(JSON.stringify(realShape));});check('mock transport preserves the new strict contract',dispatches===1&&!response.error&&response.output.changes[0].sessions.length===4);check('receipt records the distribution schema',response.receipt.response_schema_version===D.SCHEMA_VERSION);
 console.log(JSON.stringify({suite:'distribution pure contract',passed:rows.length,checks:rows,openai_calls:0}));
})().catch(e=>{console.error(e);process.exitCode=1;});
